- .gitignore
- CMakeLists.txt
This enables out-of-tree builds, and the use of other build tools.
This will not overwrite Makefile if you are building in the
source tree.  To use makefiles generated from CMake, you must
build out of the source tree.
Usage: If SPIRV-Cross source is in $SPIRV_CROSS_ROOT, then to
build with ninja in a different directory:
cmake -G Ninja $SPIRV_CROSS_ROOT
ninja
ctest
Tests will be enabled if you have python3.
> Add a CMakeLists.txt file for use by cmake, ctest

- Makefile
- README.md
- reference/shaders/asm/comp/bitcast_iadd.asm.comp
- reference/shaders/asm/comp/bitcast_iequal.asm.comp
- reference/shaders/asm/comp/bitcast_sar.asm.comp
- reference/shaders/asm/comp/bitcast_sdiv.asm.comp
- reference/shaders/asm/comp/bitcast_slr.asm.comp
- reference/shaders/asm/comp/bitcast_udiv.asm.comp
- reference/shaders/comp/casts.comp
- shaders/asm/comp/bitcast_iadd.asm.comp
- shaders/asm/comp/bitcast_iequal.asm.comp
- shaders/asm/comp/bitcast_sar.asm.comp
- shaders/asm/comp/bitcast_sdiv.asm.comp
- shaders/asm/comp/bitcast_slr.asm.comp
- shaders/asm/comp/bitcast_udiv.asm.comp
- shaders/comp/casts.comp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
Implement more correct integer op handling.
In some cases we need to bitcast when dealing with int vs. uint.
SPIR-V allows inputs to be of different integer signedness, so we need
to deal with this somehow.
Add testing system to test SPIR-V assembly.
For now, test all possible combination for all major cases.
- IAdd (which doesn't care about input type as long as they're equal)
- SDiv/UDiv operations which care about input type.
- Arith/Logical right shifts.
- IEqual to test outputs to bvec, which shouldn't get output cast. Also
tests casting in function-like calls.
> Better handling of bitcasts within integer operations

- spirv_cpp.cpp
- spirv_cpp.hpp
> CompilerCPP now properly initializes arrays with constant expressions

- spirv_cross.cpp
When the SPIR-V includes metadata for debugging
(aka OpLine instructions) the CompilerError at
line 1588 was eventually triggered.
> Do not try to pump OpLine instructions into a block

- spirv_glsl.cpp
- spirv_glsl.hpp
Using old-school GLSL as input containing code ala
"gl_FragColor = whatever" resulted in illegal
declarations ala "out vec4 gl_FragColor;".
> Change variable names beginning with gl_ in GLSL

- spirv_msl.cpp
This caused a null pointer being used when called with p_vtx_attrs = nullptr and p_res_bindings != nullptr
> Correct vector's size begin checked

- spirv_msl.cpp
Useful for adding defines or additional includes, chose to add this _before_ the standard includes
> Emit header_lines for MSL also

- main.cpp
- reference/shaders/vulkan/frag/spec-constant.vk.frag
- reference/shaders/vulkan/frag/spec-constant.vk.frag.vk
- shaders/vulkan/frag/spec-constant.vk.frag
- spirv_common.hpp
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
This PR adds "full" support for specialization constants.
- Basic reflection API
- Vulkan GLSL backend emits spec constants and not plain constants
- OpSpecConstantOp implemented for every known testable opcode 
- Arrays can have spec constant size
> Add more complete specialization constant support

- spirv_glsl.cpp
I am converting HLSL shaders to spirv with gslang and converting spirv to GLSL with SPIRV-Cross. I'm running into an issue where I have shaders which define variables named `input` or `output` which are reserved keywords in GLSL (as defined in https://www.opengl.org/registry/doc/GLSLangSpec.4.20.6.pdf under 3.6: Keywords). SPIRV-Cross does modify names starting with `gl_` but not any other keywords.
SPIRV-Cross outputs `input` & `output` (as defined in HLSL) as valid variable names however the driver rejects this code. I modified the function `CompilerGLSL::replace_illegal_names` to check that either `m.alias` starts with `gl_` or equals one of the reserved keywords.
The list of keywords is quite large (201 elements), but it also contains a lot of keywords that are not very likely to ever …
> Added all glsl reserved keywords to replace_illegal_names

- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Updated approach to MSL-specific functions to override emit_instruction() and emit_glsl_op() functions with MSL-specific behaviour. Removed emit_msl_defines() function.
> Support MSL-specific functions

- CMakeLists.txt
Issue #70: Windows Python 3.x installations do not include a python3.exe; this
caused the old test to fail and issue a spurious warning.
> Fixed python3 detection for spirv-cross-test.

- CMakeLists.txt
- main.cpp
- msvc/SPIRV-Cross.vcxproj
- msvc/SPIRV-Cross.vcxproj.filters
- reference/shaders/comp/cfg.comp
- reference/shaders/comp/generate_height.comp
- reference/shaders/comp/loop.comp
- reference/shaders/comp/return.comp
- reference/shaders/comp/torture-loop.comp
- reference/shaders/frag/mix.frag
- reference/shaders/tesc/water_tess.tesc
- reference/shaders/vert/ground.vert
- reference/shaders/vert/ocean.vert
- shaders/comp/cfg.comp
- spirv_cfg.cpp
- spirv_cfg.hpp
- spirv_common.hpp
- spirv_cpp.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.hpp
A currently uglyness in SPIRV-Cross output is that variables are always declared in the entry block if they aren't accessed there to avoid problems where multiple scopes potentially access a variable. This PR implement CFG traversal and dominance analysis to figure out where to optimally place variable declarations to improve readability of generated code.
This is also the first step to properly fix https://github.com/KhronosGroup/SPIRV-Cross/issues/55
> WIP: Add control flow graph analysis for variable scoping

- spirv_glsl.cpp
Enables [GL_ARB_shader_texture_lod](https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/specs/ARB/shader_texture_lod.txt) extension if textureLod() is used on version < 130.
> Legacy GL_ARB_shader_texture_lod support.

- jni/Android.mk
- spirv_msl.hpp
Added spirv_cfg.cpp and spirv_msl.cpp to makefile
UINT32_MAX was giving me a compile error being undefined, neither including `<cstdint>` nor `<stdint.h>` fixed that. It could be done with `<limits>` and `std::numeric_limits<T>::max()`, but as this is a `const static` I fear there could be a problem because of static initialization order, so this seems to be the safest way to me.
> Updated Android build

- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
CompilerMSL fix func_call_arg() cast error when not passed SPIRVariable type.
CompilerGLSL allow retrieval of partial source if an error occurs.
CompilerMSL supports promoting unnamed global vars to function args. 
CompilerMSL use correct MSL type name for 3D textures.
> CompilerMSL fix cast error & add minor feature to CompilerGLSL

- main.cpp
- reference/shaders/comp/struct-packing.comp
- shaders/comp/struct-packing.comp
- spirv_cross.cpp
The array size was dropped from consideration during recursion.
> Fix get_declared_struct_size for nested arrays of structs.

- spirv_common.hpp
- spirv_msl.cpp
- spirv_msl.hpp
MSL support OpFMod as fmod() function.
Remove SPIRType::is_packed member.
> MSL sort interface struct members by offset instead of location.

- .clang-format
- .travis.yml
- reference/shaders/comp/cfg.comp
- reference/shaders/comp/dowhile.comp
- reference/shaders/comp/inout-struct.invalid.comp
- reference/shaders/comp/loop.comp
- reference/shaders/comp/return.comp
- reference/shaders/comp/torture-loop.comp
- reference/shaders/desktop-only/comp/fp64.desktop.comp
- reference/shaders/desktop-only/comp/int64.desktop.comp
- reference/shaders/frag/for-loop-init.frag
- reference/shaders/frag/ground.frag
- reference/shaders/tese/water_tess.tese
- reference/shaders/vert/ground.vert
- reference/shaders/vert/ocean.vert
- shaders/frag/for-loop-init.frag
- spirv_cfg.hpp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
This is one of the most complicated fixes in SPIRV-Cross so far, but fixes a long-standing bug with for loops in ESSL, which have a very particular restriction. https://github.com/KhronosGroup/SPIRV-Cross/issues/55
```
for (int i = 0; i < 4; i++)
```
via SPIR-V and back again generated this kind of code
```
int i = 0;
for (; i < 4; i = i + 1)
```
While this is perfectly legal GLSL it looks ugly, and also breaks a GLES 2.0 restriction saying that for loops must have a strict form of
```
for (int i = initializer; condition only using i; i++, i-- or i += const-expr)
```
In order to acheive this, we need a control flow graph implementation which analyzes the scope of variables. With the CFG, we can move the initializer into the for loop header if we can prove that the loop header is directly …
> Fix for loops for legacy ESSL.

- main.cpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
glslang now handles NoWrite/NoRead correctly for images so the ugly workaround for ESSL 3.10 is no longer needed. Do not modify decoration flags until compile time to avoid breaking reflection.
> Fix handling of NoWrite/NoRead decoration for images.

- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Refactor emit_texture_op() function to simplify subclass overrides.
CompilerMSL refactored to simplify handling of vertex attributes.
> Refactor emit_texture_op() function.

- spirv_common.hpp
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_msl.cpp
When used in a locale-sensitive setting, eg. GUI application, the float to string conversions will necessarily use the current locale. This may result in floating point numbers with eg. commas as a decimal mark.
This patch attempts to avoid these locale specific conversions by temporarily overriding the current locale with a classic locale (C locale).
I am not sure if this is the best way.
> Use the classic locale when converting floats to string

- main.cpp
- reference/shaders/legacy/vert/transpose.legacy.vert
- shaders/legacy/vert/transpose.legacy.vert
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
This improves handling of transpose in targets which do not support row_major layouts natively. The common use-case of row_major_matrix * vector will now be written as vector * matrix instead to avoid the transpose().
UBOs are now emitted as uniform structs by default.
> Legacy GLSL improvements

- main.cpp
- reference/shaders/flatten/array.flatten.vert
- reference/shaders/flatten/basic.flatten.vert
- reference/shaders/flatten/copy.flatten.vert
- reference/shaders/flatten/dynamic.flatten.vert
- reference/shaders/flatten/multiindex.flatten.vert
- reference/shaders/flatten/rowmajor.flatten.vert
- reference/shaders/flatten/struct.flatten.vert
- reference/shaders/flatten/swizzle.flatten.vert
- shaders/flatten/array.flatten.vert
- shaders/flatten/basic.flatten.vert
- shaders/flatten/copy.flatten.vert
- shaders/flatten/dynamic.flatten.vert
- shaders/flatten/multiindex.flatten.vert
- shaders/flatten/rowmajor.flatten.vert
- shaders/flatten/struct.flatten.vert
- shaders/flatten/swizzle.flatten.vert
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
Legacy GLSL targets do not support uniform buffers, and as such require
some sort of emulation. There are two alternatives - one is to represent
a uniform buffer as a uniform struct, and another one is to flatten it
into an array of primitive vector types (vec4).
Uniform struct have two disadvantages that make using them prohibitive
in some applications:
- The location assignment for struct members is arbitrary which means
the application has to set each struct member one by one
- Some Android drivers fail to link shader programs if both vertex and
fragment shader use the same uniform struct
Because of this, we need to support flattening uniform buffers into an
array. This is not just important for legacy GLSL but also is sometimes
useful for ESSL 3.0 where some Android drivers do not …
> Implement buffer block flattening

- spirv_glsl.cpp
Hey all, this is another fix for compiling spirv_cross with the old C++11 stdlib used by Chrome.
> Fix compilation on some old C++11 standard libraries.

- spirv_msl.cpp
Hey all, this fixes writable SSBOs being put in the "constant" address spaces causing compile errors when their are written to. This is a quick-fix and I would understand it if more work is required. If that's the case please kindly provide guidance on what should be done.
> spirv_msl: Put writable SSBOs in the 'device' address space

- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
This PR really only affects spirv_msl. Changes to spirv_glsl are a side effect of running the style formatter (on source code from a previous commit).
> Remove emission of function prototypes in MSL.

- .travis.yml
- CMakeLists.txt
- README.md
- reference/shaders-msl/vert/basic.vert
- shaders-msl/vert/basic.vert
- test_shaders.py
This PR sets up the basic system for how we can have regression tests for Metal as well.
While shaders we test specifically are found in shaders-msl, we would ideally reuse the same shaders to test Metal as well.
> Add basic setup for regression testing Metal output.

- reference/shaders/flatten/matrixindex.flatten.vert
- shaders/flatten/matrixindex.flatten.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
To extract a column from row-major matrix, we need to do a strided load one
component at a time. In this case flattened_access_chain_offset still returns
the offset to the first element, but the stride is equal to matrix stride
instead of vector stride.
For this to work, we need to pass matrix stride (and transpose flag) through,
similar to how matrix flattening works.
Additionally slightly clean up recursive flattened_access_chain structure -
specifically, instead of deciding mid-traversal that we need matrix stride
information, we can just pass the matrix stride through - for access chains
that end in matrix/vector this gets us what we need, and for access chains
that end in structs the flattened_access_chain_struct code will recompute
correct stride/transposition data to pass through …
> Implement flattening of row major matrix indexing

- reference/shaders-msl/vert/basic.vert
- shaders-msl/vert/basic.vert
- test_shaders.py
If we run on a system with Xcode installed to a default path, run Xcode
Metal shader compiler to validate the generated MSL shader.
This uncovers an issue in the existing MSL test - MSL backend currently
does not auto-assign attribute locations, which means that translating
GLSL shader without location layout produces an invalid MSL which
generates "error: 'attribute' index '0' is used more than once".
> Validate Metal shaders on OSX with Metal compiler

- spirv_cross.cpp
- spirv_hlsl.cpp
There is still some `throw` syntax, thus failed to compile when `SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=On`.
This simple patch fixes it.
> Fix build when SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=On.

- main.cpp
- reference/shaders-msl/frag/for-loop-init.frag
- reference/shaders-msl/vert/copy.flatten.vert
- reference/shaders-msl/vert/dynamic.flatten.vert
- shaders-msl/frag/for-loop-init.frag
- shaders-msl/vert/copy.flatten.vert
- shaders-msl/vert/dynamic.flatten.vert
- spirv_cross.cpp
- spirv_glsl.cpp
- test_shaders.py
Addresses https://github.com/KhronosGroup/SPIRV-Cross/issues/112.
Problem was that the statement which emits a function was evaluated out-of-order (which is legal for compiler to do) and the condition statement was wrongly invalidated.
> For loop evaluation order fix.

- reference/shaders-msl/comp/global-invocation-id-writable-ssbo-in-function.comp
- reference/shaders-msl/comp/global-invocation-id.comp
- reference/shaders-msl/comp/local-invocation-id.comp
- reference/shaders-msl/comp/local-invocation-index.comp
- reference/shaders-msl/comp/writable-ssbo.comp
- shaders-msl/comp/global-invocation-id-writable-ssbo-in-function.comp
- shaders-msl/comp/global-invocation-id.comp
- shaders-msl/comp/local-invocation-id.comp
- shaders-msl/comp/local-invocation-index.comp
- shaders-msl/comp/writable-ssbo.comp
- spirv_msl.cpp
- spirv_msl.hpp
Hey all,
As the name implies this adds support for gl_GlobalInvocationID to the MSL output so that non-trivial compute shaders work. Unfortunately this commit is in the MSL backend that doesn't have tests but locally we have verified this works correctly and using gl_GlobalInvocationID works as expected.
> spirv_msl: Add support for gl_GlobalInvocationId

- reference/shaders-msl/frag/basic.frag
- reference/shaders-msl/frag/composite-extract-forced-temporary.frag
- reference/shaders-msl/frag/mix.frag
- reference/shaders-msl/frag/sampler-ms.frag
- reference/shaders-msl/frag/sampler.frag
- reference/shaders-msl/frag/swizzle.frag
- spirv_msl.cpp
Compiler MSL support DimBuffer as image dimension.
CompilerMSL check texture coordinate result type dimension before adding swizzles.
Update MSL reference shaders affected by this update.
> CompilerMSL add support for texel buffers.

- .travis.yml
We need recent Xcode to support ios-metal1.2
> Update to Xcode 8.2 on Travis and reenable Metal validation

- README.md
- reference/shaders/legacy/fragment/io-blocks.legacy.frag
- reference/shaders/legacy/vert/io-block.legacy.vert
- shaders/legacy/fragment/io-blocks.legacy.frag
- shaders/legacy/vert/io-block.legacy.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
Fix issue where layout() qualifiers are emitted for members in legacy
targets.
> Add support for flattening I/O blocks.

- spirv_glsl.cpp
The variable i was used as a uint32_t in multiple places, like type_member_for_offset, so changed its type.
I build SPIRV-Cross as part of my project so I see these quite a bit.
> Just fix a few minor warnings.

- README.md
- main.cpp
- reference/shaders-msl/flatten/swizzle.flatten.vert
- reference/shaders-msl/vert/ubo.alignment.vert
- shaders-msl/vert/ubo.alignment.vert
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
MSL and SPIR-V (std140) have slightly different structure member size and alignment rules.
This PR pads and packs MSL struct members to align them with the SPIR-V offsets.
> CompilerMSL aligns MSL struct members with SPIR-V offsets

- reference/shaders-hlsl/frag/basic.frag
- reference/shaders-hlsl/frag/builtins.frag
- reference/shaders-hlsl/frag/io-block.frag
- reference/shaders-hlsl/frag/mrt.frag
- reference/shaders-hlsl/frag/no-return.frag
- reference/shaders-hlsl/frag/no-return2.frag
- reference/shaders-hlsl/vert/basic.vert
- reference/shaders-hlsl/vert/instancing.vert
- reference/shaders-hlsl/vert/locations.vert
- reference/shaders-hlsl/vert/no-input.vert
- reference/shaders-hlsl/vert/qualifiers.vert
- shaders-hlsl/frag/builtins.frag
- shaders-hlsl/frag/io-block.frag
- shaders-hlsl/frag/mrt.frag
- shaders-hlsl/frag/no-return.frag
- shaders-hlsl/frag/no-return2.frag
- shaders-hlsl/vert/instancing.vert
- shaders-hlsl/vert/locations.vert
- shaders-hlsl/vert/no-input.vert
- shaders-hlsl/vert/qualifiers.vert
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Rewrote the implementation of HLSL inputs and outputs to be more robust and support more stuff.
- A traversal is done to find all statically accessed builtin variables in the shader. This is common to all APIs, so Metal might benefit from this as well.
- Separate out logic for builtins from the handling of user-defined inputs and outputs.
- Add support for the more common builtins like frag-coord, frag-depth, vertex-id, instance-id and MRT.
- Location decorations are now used always if the shader uses it. For varyings and attributes which are not using these, the locations (TEXCOORD[N]) are assigned based on their name, and failing that, their ID. All sensible SPIR-V shaders really should use locations, so these serve as crude fallbacks.
- I/O blocks are now supported by having extra …
> Rewrite HLSL backend handling of inputs and outputs

- spirv_msl.hpp
Using new deprecation option to formally mark existing deprecated compile() function overload as deprecated.
> CompilerMSL mark the legacy compile() function as deprecated

- spirv_cross.cpp
- spirv_cross.hpp
This avoids the need to construct a temporary std::vector on the application side just to create a Compiler instance if application itself doesn't use STL containers.
> Added a Compiler ctor that takes IR as raw array and count

- reference/shaders-hlsl/vert/matrix-attribute.vert
- shaders-hlsl/vert/matrix-attribute.vert
- spirv_hlsl.cpp
HLSL doesn't support matrix attributes so we pack them into vectors. Fixed a little bug in the generated unpacking code and added a test.
> Fix HLSL matrix unrolling

- reference/shaders-hlsl/frag/basic.frag
- reference/shaders-hlsl/frag/tex-sampling.frag
- shaders-hlsl/frag/tex-sampling.frag
- spirv_hlsl.cpp
- spirv_hlsl.hpp
For #125 aka no more need for D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY.
Also improves texture calls for shader model 2/3.
> Shader model 4/5 style texture sampling

- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
CompilerMSL round floating point tex coords for read() and tex array index, to avoid toggling arbitrarily between two tex array layers due to rounding errors.
CompilerMSL remove option to flip fragment coordinates.
> CompilerMSL round floating point tex coords for read() and tex array index.

- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
Facilitates easy SPIR-V patching when needed.
> Add support for querying binary offsets of decorations in SPIR-V.

- reference/shaders-msl/flatten/basic.flatten.vert
- reference/shaders-msl/flatten/multiindex.flatten.vert
- reference/shaders-msl/flatten/push-constant.flatten.vert
- reference/shaders-msl/flatten/struct.flatten.vert
- reference/shaders-msl/flatten/swizzle.flatten.vert
- reference/shaders-msl/legacy/vert/transpose.legacy.vert
- reference/shaders-msl/vert/basic.vert
- reference/shaders-msl/vert/copy.flatten.vert
- reference/shaders-msl/vert/dynamic.flatten.vert
- reference/shaders-msl/vert/pointsize.vert
- reference/shaders-msl/vert/ubo.alignment.vert
- reference/shaders-msl/vert/ubo.vert
- reference/shaders-msl/vulkan/vert/vulkan-vertex.vk.vert
- shaders-msl/vert/pointsize.vert
- spirv_msl.hpp
This is a convenience fix for Issue #169. More sophisticated fix to that issue may come later.
> CompilerMSL output [[point_size]] attribute for BuiltInPointSize member by default.

- spirv_cross.cpp
It's the default with recent spirv-as, so be more friendly.
> Support SPIR-V 1.2.

- reference/shaders-msl/flatten/basic.flatten.vert
- reference/shaders-msl/flatten/multiindex.flatten.vert
- reference/shaders-msl/flatten/push-constant.flatten.vert
- reference/shaders-msl/flatten/struct.flatten.vert
- reference/shaders-msl/flatten/swizzle.flatten.vert
- reference/shaders-msl/legacy/vert/transpose.legacy.vert
- reference/shaders-msl/vert/basic.vert
- reference/shaders-msl/vert/copy.flatten.vert
- reference/shaders-msl/vert/dynamic.flatten.vert
- reference/shaders-msl/vert/ubo.alignment.vert
- reference/shaders-msl/vert/ubo.vert
- reference/shaders-msl/vulkan/vert/vulkan-vertex.vk.vert
- spirv_msl.cpp
- spirv_msl.hpp
This enables the point_size builtin based on the existing active_input/output_builtins variable.
Renames is_rendering_points to enable_point_size_builtin to be able to forcefully disable point_size when not using Point topology as before, but make the intention clearer.
> Implement more sophisticated check for point_size.

- main.cpp
- reference/shaders-msl/comp/atomic.comp
- reference/shaders-msl/comp/global-invocation-id-writable-ssbo-in-function.comp
- reference/shaders-msl/comp/global-invocation-id.comp
- reference/shaders-msl/comp/local-invocation-id.comp
- reference/shaders-msl/comp/local-invocation-index.comp
- reference/shaders-msl/comp/writable-ssbo.comp
- reference/shaders-msl/desktop-only/frag/image-ms.desktop.frag
- reference/shaders-msl/desktop-only/frag/query-levels.desktop.frag
- reference/shaders-msl/desktop-only/frag/sampler-ms-query.desktop.frag
- reference/shaders-msl/frag/bitcasting.frag
- reference/shaders-msl/vert/functions.vert
- reference/shaders-msl/vert/out_block.vert
- reference/shaders-msl/vert/texture_buffer.vert
- shaders-msl/comp/atomic.comp
- shaders-msl/desktop-only/frag/image-ms.desktop.frag
- shaders-msl/desktop-only/frag/query-levels.desktop.frag
- shaders-msl/desktop-only/frag/sampler-ms-query.desktop.frag
- shaders-msl/frag/bitcasting.frag
- shaders-msl/vert/functions.vert
- shaders-msl/vert/out_block.vert
- shaders-msl/vert/texture_buffer.vert
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
This started as a fix for #171, but extended to map a large number of GLSL functions to their Metal counterparts. 
See the commit note for details about the added functionality.
> CompilerMSL map many GLSL functions to MSL functions

- main.cpp
write_string_to_file would try to write the error message that it failed to open a file stream to the very same file stream it just tried to open.
Fix this by writing to stderr instead.
> Fix null pointer dereference

- main.cpp
- reference/shaders/desktop-only/geom/basic.desktop.sso.geom
- reference/shaders/desktop-only/tesc/basic.desktop.sso.tesc
- reference/shaders/desktop-only/tese/triangle.desktop.sso.tese
- reference/shaders/desktop-only/vert/basic.desktop.sso.vert
- shaders/desktop-only/geom/basic.desktop.sso.geom
- shaders/desktop-only/tesc/basic.desktop.sso.tesc
- shaders/desktop-only/tese/triangle.desktop.sso.tese
- shaders/desktop-only/vert/basic.desktop.sso.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
SSO shaders need explicit declaration of gl_PerVertex between stages.
This PR adds support for SSO between vertex, geometry and tessellation shaders.
A CLI option for --separate-shader-objects and an API option will force gl_PerVertex to be redeclared with the builtin block inside the shader.
Only desktop is supported. ES is a bit weird here since SSO support does not imply block support.
gl_PerFragment is only for compatibility context, so it is not relevant for SPIR-V.
> Add support for Separate Shader Objects

- main.cpp
- reference/shaders/flatten/multi-dimensional.desktop.flatten_dim.frag
- shaders/flatten/multi-dimensional.desktop.flatten_dim.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
In older targets, multiple array dimensions are not supported.
This PR adds support to flatten `float[2][3][4]` to `float[2 * 3 * 4]` and access chains are modified to do this flattening.
The support is a bit limited. Constructors of multiple dimensions and partially accessing a multidimensional array is not supported.
> Add support for flattening multidimensional arrays into single dimension

- spirv_hlsl.cpp
This just broke. There are no tests for shader model 2/3 and I don't think we can easily test that on Travis. We could setup an appveyor script.
> Fix shader model 2/3 texture sampling

- reference/shaders-msl/flatten/basic.flatten.vert
- reference/shaders-msl/flatten/multiindex.flatten.vert
- reference/shaders-msl/flatten/push-constant.flatten.vert
- reference/shaders-msl/flatten/struct.flatten.vert
- reference/shaders-msl/flatten/swizzle.flatten.vert
- reference/shaders-msl/legacy/vert/transpose.legacy.vert
- reference/shaders-msl/vert/basic.vert
- reference/shaders-msl/vert/copy.flatten.vert
- reference/shaders-msl/vert/dynamic.flatten.vert
- reference/shaders-msl/vert/functions.vert
- reference/shaders-msl/vert/out_block.vert
- reference/shaders-msl/vert/pointsize.vert
- reference/shaders-msl/vert/texture_buffer.vert
- reference/shaders-msl/vert/ubo.alignment.vert
- reference/shaders-msl/vert/ubo.vert
- reference/shaders-msl/vulkan/vert/vulkan-vertex.vk.vert
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Per extended discussion in issue #186, add support for emitting SPIR-V type declarations tuned for specified SPIR-V objects, as well as SPIR-V `OpTypeImage` access qualifiers. CompilerMSL uses this to output appropriate MSL image access qualifiers.
Also includes several MSL builtin enhancements, including eliding unused builtin inputs and outputs, and support for gl_ClipDistance in Metal.
> Emit type declarations tuned for specified SPIR-V objects + MSL builtin enhancements.

- include/spirv_cross/image.hpp
imageLoad takes a const-ref to image and calls load on it, make the load method const to prevent compile error.
> Make image2dBase::load const

- spirv_glsl.cpp
According to https://www.khronos.org/opengl/wiki/History_of_OpenGL#OpenGL_3.2_.282009.29
I am getting errors on OS X when output GLSL version is set to 150 and the unnecessary 
`#extension GL_ARB_geometry_shader4 : require`
string is still generated
> Geometry shader core since GLSL 150

- spirv_msl.cpp
> Fix fallthrough warning.

- reference/shaders-hlsl/frag/basic.frag
- reference/shaders-hlsl/frag/combined-texture-sampler-parameter.frag
- reference/shaders-hlsl/frag/combined-texture-sampler-shadow.frag
- reference/shaders-hlsl/frag/resources.frag
- shaders-hlsl/frag/resources.frag
- spirv_hlsl.cpp
- spirv_hlsl.hpp
A bit incomplete as the HLSL backend does not support the more exotic types yet, but cbuffers, textures and samplers should be covered.
> Add basic support for : register() declaration in HLSL.

- reference/shaders/asm/frag/hlsl-sample-cmp-level-zero.asm.frag
- reference/shaders/asm/frag/invalidation.asm.frag
- shaders/asm/frag/hlsl-sample-cmp-level-zero.asm.frag
- shaders/asm/frag/invalidation.asm.frag
- spirv_glsl.cpp
- test_shaders.py
Needed for SPIR-V generated by HLSL.
> Workaround textureLod on sampler2DArrayShadow

- reference/shaders/frag/sampler-proj.frag
- shaders/frag/sampler-proj.frag
- spirv_glsl.cpp
The modified object might not be mutable (e.g. shader input).
Added a test for the case when this happens.
> Always make a copy when handling OpCompositeInsert

- spirv_cross.cpp
It may be used with OpLine or OpSource to specify filename.
> Ignore debug instruction OpString

- spirv_cfg.hpp
- spirv_cross.cpp
- spirv_glsl.cpp
Old implementation would explode runtime for long shaders with many blocks.
Fixes https://github.com/KhronosGroup/SPIRV-Cross/issues/226.
> Optimize CFG walking

- reference/shaders/asm/comp/bitcast_iadd.asm.comp
- reference/shaders/asm/comp/bitcast_iequal.asm.comp
- reference/shaders/asm/comp/bitcast_sar.asm.comp
- reference/shaders/asm/comp/bitcast_sdiv.asm.comp
- reference/shaders/asm/comp/bitcast_slr.asm.comp
- reference/shaders/asm/comp/bitcast_udiv.asm.comp
- reference/shaders/asm/comp/multiple-entry.asm.comp
- reference/shaders/asm/frag/default-member-names.asm.frag
- shaders/asm/frag/default-member-names.asm.frag
- spirv_glsl.cpp
Use a unique prefix for member since they can easily conflict with types.
> Fix default member name implementation.

- README.md
- spirv_glsl.cpp
ESSL 300 and GLSL <410 do not support this along with legacy targets.
Fixes #222
> Do not emit layout(location) qualifiers for older GLSL targets.

- README.md
- main.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
The different options were scattered around in different backends and
didn't really work right with CLI at all.
This slightly changes the API, so @billhollings, @RobDangerous, please see if this will break anything. Also unifies the interface so Y-flip / clipspace fixup works as expected for all targets now.
Fixes #241.
> Unify vertex clip-coord fixups.

- reference/shaders-hlsl/comp/access-chains.comp
- reference/shaders-hlsl/comp/address-buffers.comp
- reference/shaders-hlsl/comp/builtins.comp
- reference/shaders-hlsl/comp/ssbo-array.comp
- shaders-hlsl/comp/access-chains.comp
- shaders-hlsl/comp/address-buffers.comp
- shaders-hlsl/comp/builtins.comp
- shaders-hlsl/comp/ssbo-array.comp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Built upon https://github.com/KhronosGroup/SPIRV-Cross/pull/220.
Fixes #249.
Lots of stuff is certainly missing, but it should be usable now for basic compute shaders.
> Basic HLSL compute shader support

- spirv_glsl.cpp
"x = x && y" was converted to "x &= y", which is invalid.
> Fix assignment optimization for logical and/or.

- spirv_hlsl.cpp
I'm using SPIRV-Cross to port an OpenGL application to Direct3D 11. It's working fairly well, but explicit UBO bindings fail with the following error:
```
D3DCompile failed: Unspecified error (0x80004005)
C:\msys64\home\rossy\mpv\Shader@0x000000000742B570(21,24-25): error X3530: invalid register specification, expected 'b' binding
```
This change fixes the error for me. I think b# bindings should be used for cbuffers on shader model 4.0-5.0 as well as 5.1.
Reference: https://msdn.microsoft.com/en-us/library/windows/desktop/bb509581.aspx
> Use the correct cbuffer binding for HLSL SM 4.0-5.0

- reference/shaders-hlsl/frag/tex-sampling.frag
- shaders-hlsl/frag/tex-sampling.frag
- spirv_hlsl.cpp
In GLSL, it seems like the component is selected with an integer constant argument, but in HLSL, it's selected by calling a different method on the texture itself.
EDIT: I noticed the Travis build didn't start again. I've contacted Travis support in case this is something to do with my account. 😕 The tests pass locally (including with fxc.exe.)
> Fix texture GatherRed/Green/etc. methods for HLSL SM 5.0

- spirv_hlsl.cpp
It seems like HLSL uses the same atan2(y, x) argument order as GLSL. Fixing this corrected an error in one of our cross-compiled shaders.
I also used a small test shader to verify that this was correct. Left is a GLSL shader that graphs the range of atan(y, x), cross-compiled to HLSL with glslang and SPIRV-Cross (with this fix.) Right is the same shader running natively in OpenGL.
References:
http://docs.gl/sl4/atan
https://msdn.microsoft.com/en-us/library/windows/desktop/bb509575.aspx
> Fix HLSL atan2() argument order

- CMakeLists.txt
Hi,
Project doesn't compile on my machine (clang 5.0.0, linux), spirv-cross doesn't have the correct compile options set. It was working on gcc since c++11 is enabled by default. 
The commit adds compile options & defines.
> Fix compilation with clang

- reference/shaders-hlsl/frag/matrix-input.frag
- reference/shaders-hlsl/vert/matrix-output.vert
- shaders-hlsl/frag/matrix-input.frag
- shaders-hlsl/vert/matrix-output.vert
- spirv_hlsl.cpp
Bandaid, might have to revisit this later.
Fixes #264
> HLSL: Only unroll matrices for vertex input.

- reference/shaders-hlsl/asm/vert/empty-struct-composite.asm.vert
- reference/shaders-msl/asm/vert/empty-struct-composite.asm.vert
- reference/shaders/asm/vert/empty-struct-composite.asm.vert
- shaders-hlsl/asm/vert/empty-struct-composite.asm.vert
- shaders-msl/asm/vert/empty-struct-composite.asm.vert
- shaders/asm/vert/empty-struct-composite.asm.vert
- spirv_glsl.cpp
This "feature" is a bit icky as we have no useful representation of it,
so never emit code which has anything to do with empty structs.
Fixes #292 .
> Handle empty struct declarations with best effort.

- spirv_glsl.cpp
The early_fragment_tests layout qualifier requires either OpenGL 4.2 or use of the GL_ARB_shader_image_load_store extension.
> Require GL_ARB_shader_image_load_store extension.

- reference/shaders-hlsl/asm/comp/specialization-constant-workgroup.asm.comp
- reference/shaders-hlsl/asm/comp/storage-buffer-basic.asm.comp
- reference/shaders-hlsl/comp/builtins.comp
- reference/shaders-hlsl/frag/spec-constant.frag
- spirv_hlsl.cpp
At least, I think this is correct. I don't know if HLSL has an equivalent for specialization constants in SPIR-V where the work group size can be specified after the shader is compiled. Without this change, the HLSL compiler ignores the initializers for the constants and expects them to be provided by a cbuffer.
> Use 'static const' for spec constants in HLSL

- spirv_common.hpp
Reuses an enum name as a struct type, creates friction for API wrappers.
Closes #313
> Rename nested Image struct type.

- reference/shaders-hlsl/comp/rwbuffer-matrix.comp
- shaders-hlsl/comp/rwbuffer-matrix.comp
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
This is rather painful as we have to deal with manually poking out data, but should allow full support for dynamically accessed row-major matrices and other complicated scenarios.
> HLSL RWByteAddressBuffer support for row/column matrices

- spirv_hlsl.cpp
Fix to_plain_buffer_length cast.
> Just minor warning fix when compiling under x64

- reference/shaders-msl/asm/frag/default-member-names.asm.frag
- reference/shaders-msl/asm/frag/op-constant-null.asm.frag
- reference/shaders-msl/asm/frag/phi-loop-variable.asm.frag
- reference/shaders-msl/asm/frag/undef-variable-store.asm.frag
- shaders-msl/asm/frag/default-member-names.asm.frag
- shaders-msl/asm/frag/op-constant-null.asm.frag
- shaders-msl/asm/frag/phi-loop-variable.asm.frag
- shaders-msl/asm/frag/undef-variable-store.asm.frag
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Changes outside `spirv_msl.hpp/cpp` are result of running `format_all.sh`.
> CompilerMSL support and tests for OpUndef.

- reference/shaders/asm/frag/struct-composite-extract-swizzle.asm.frag
- shaders/asm/frag/struct-composite-extract-swizzle.asm.frag
- spirv_glsl.cpp
> Do not allow base expressions when extracting struct members.

- reference/shaders/asm/frag/temporary-phi-hoisting.asm.frag
- shaders/asm/frag/temporary-phi-hoisting.asm.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
A continue block might have used a temporary which existed only in the
loop body.
Fixes #330.
> Fix complicated Phi case.

- reference/shaders-hlsl/frag/early-fragment-test.frag
- shaders-hlsl/frag/early-fragment-test.frag
- spirv_hlsl.cpp
Other backends seem to support it already, but HLSL is missing it.
> HLSL: Support early_fragment_tests attribute

- reference/opt/shaders/asm/comp/name-alias.asm.invalid.comp
- reference/opt/shaders/desktop-only/frag/hlsl-uav-block-alias.asm.frag
- reference/shaders/asm/comp/name-alias.asm.invalid.comp
- reference/shaders/desktop-only/frag/hlsl-uav-block-alias.asm.frag
- shaders/desktop-only/frag/hlsl-uav-block-alias.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
HLSL UAVs are a bit annoying because they can share block types,
so reflection becomes rather awkward. Sometimes we will need to make
some nasty fallbacks, so add a reflection interface which lets you query
post-shader compile which names was actually declared in the shader.
Fixes #345.
> Improve handling of block name declaration in GLSL.

- reference/opt/shaders-hlsl/comp/rwbuffer-matrix.comp
- reference/opt/shaders-hlsl/frag/combined-texture-sampler-parameter.frag
- reference/opt/shaders-hlsl/frag/combined-texture-sampler-shadow.frag
- reference/opt/shaders-hlsl/frag/mrt.frag
- reference/opt/shaders-hlsl/frag/swizzle-scalar.frag
- reference/opt/shaders-hlsl/frag/various-glsl-ops.frag
- reference/opt/shaders-hlsl/vert/locations.vert
- reference/opt/shaders-hlsl/vert/matrix-output.vert
- reference/opt/shaders-hlsl/vert/no-input.vert
- reference/opt/shaders-hlsl/vert/point-size-compat.vert
- reference/opt/shaders-hlsl/vert/qualifiers.vert
- reference/shaders-hlsl/comp/rwbuffer-matrix.comp
- reference/shaders-hlsl/frag/combined-texture-sampler-parameter.frag
- reference/shaders-hlsl/frag/combined-texture-sampler-shadow.frag
- reference/shaders-hlsl/frag/mrt.frag
- reference/shaders-hlsl/frag/partial-write-preserve.frag
- reference/shaders-hlsl/frag/swizzle-scalar.frag
- reference/shaders-hlsl/frag/various-glsl-ops.frag
- reference/shaders-hlsl/vert/locations.vert
- reference/shaders-hlsl/vert/matrix-output.vert
- reference/shaders-hlsl/vert/no-input.vert
- reference/shaders-hlsl/vert/point-size-compat.vert
- reference/shaders-hlsl/vert/qualifiers.vert
- shaders-hlsl/frag/swizzle-scalar.frag
- spirv_glsl.cpp
- spirv_hlsl.cpp
Add scalar swizzling to constant composites as well.
Fixes #371.
> Fix swizzling of scalar integers in HLSL.

- reference/opt/shaders/asm/tesc/tess-fixed-input-array-builtin-array.asm.tesc
- reference/opt/shaders/tesc/water_tess.tesc
- reference/shaders/asm/tesc/tess-fixed-input-array-builtin-array.asm.tesc
- reference/shaders/tesc/water_tess.tesc
- shaders/asm/tesc/tess-fixed-input-array-builtin-array.asm.tesc
- spirv_glsl.cpp
Need to take into account that gl_Position[i] needs to be rewritten as
gl_out[i].gl_Position instead.
Input array sizes in tesc needs to be unsized or gl_MaxPatchVertices as well.
Fixes #375.
> Fix tessellation control shaders from HLSL.

- reference/opt/shaders-msl/desktop-only/vert/basic.desktop.sso.vert
- reference/opt/shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- reference/shaders-msl/desktop-only/vert/basic.desktop.sso.vert
- reference/shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- shaders-msl/desktop-only/vert/basic.desktop.sso.vert
- shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
The recent change to auto-generate GLSL gl_in/gl_out structs, for HLSL-originated SPIR-V, broke certain MSL use-cases. This PR fixes that.
> Revert to not forcing gl_in/gl_out block for MSL.

- reference/opt/shaders-msl/asm/frag/inliner-dominator-inside-loop.asm.frag
- reference/opt/shaders/asm/frag/inliner-dominator-inside-loop.asm.frag
- reference/shaders-msl/asm/frag/inliner-dominator-inside-loop.asm.frag
- reference/shaders/asm/frag/inliner-dominator-inside-loop.asm.frag
- shaders-msl/asm/frag/inliner-dominator-inside-loop.asm.frag
- shaders/asm/frag/inliner-dominator-inside-loop.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
Normally, temporary declaration must dominate any use of it,
so we generally did not need to analyze the CFG for these variables,
but there is an edge case where you have an inliner doing:
```
do {
create_temporary;
break;
} while(0);
use_temporary;
```
The inside of the loop dominates the outer scope, but we cannot emit
code like this, so make sure we hoist these temporaries outside
the "loop".
Fixes #384.
> Analyze the CFG for temporaries as well.

- reference/opt/shaders-hlsl/frag/constant-composites.frag
- reference/opt/shaders-msl/frag/constant-composites.frag
- reference/opt/shaders/frag/constant-composites.frag
- reference/shaders-hlsl/frag/constant-composites.frag
- reference/shaders-hlsl/frag/partial-write-preserve.frag
- reference/shaders-msl/frag/constant-composites.frag
- reference/shaders/frag/constant-composites.frag
- shaders-hlsl/frag/constant-composites.frag
- shaders-msl/frag/constant-composites.frag
- shaders/frag/constant-composites.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Move arrays and structs out to their own global static constants.
Also, replace illegal names in HLSL as well.
Fix #425.
> Do not declare constant composites inline in HLSL.

- spirv_glsl.cpp
- spirv_hlsl.cpp
This allows me to compile SPIRV-Cross for Griffin-esque environments (i.e. including all the code compilation files inside one file).
> Uniquely name these static functions (spirv_hlsl/spirv_glsl)

- spirv_glsl.cpp
Fixes the following warning:
> C4146: unary minus operator applied to unsigned type, result still unsigned
> Fix MSVC 2017 warning

- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
That's a feature we use for our dx12 backend in gfx-rs. Due to the definition of push constants in Vulkan, we need to split push constant blocks if they are (partially) used in multiple shader stages. We divide them into multiple constant buffers and define the root signature layout accordingly. Therefore, we need to be able to mirror this splitting on the shader side.
It's purely optional and shouldn't affect other applications.
> hlsl: Support custom root constant layout

- reference/opt/shaders-hlsl/frag/input-attachment-ms.frag
- reference/opt/shaders-hlsl/frag/input-attachment.frag
- reference/opt/shaders-msl/frag/input-attachment-ms.frag
- reference/opt/shaders-msl/frag/input-attachment.frag
- reference/opt/shaders-msl/frag/sample-depth-separate-image-sampler.frag
- reference/shaders-hlsl/frag/input-attachment-ms.frag
- reference/shaders-hlsl/frag/input-attachment.frag
- reference/shaders-msl/frag/input-attachment-ms.frag
- reference/shaders-msl/frag/input-attachment.frag
- reference/shaders-msl/frag/sample-depth-separate-image-sampler.frag
- shaders-hlsl/frag/input-attachment-ms.frag
- shaders-hlsl/frag/input-attachment.frag
- shaders-msl/frag/input-attachment-ms.frag
- shaders-msl/frag/input-attachment.frag
- shaders-msl/frag/sample-depth-separate-image-sampler.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Fix #435.
Fix #439.
There might be a way to exploit on-tile storage in Metal, but I have no idea how that would map into subpasses in SPIR-V.
> Implement subpassLoad in HLSL and MSL.

- reference/opt/shaders-msl/frag/sample-mask.frag
- reference/shaders-msl/frag/sample-mask.frag
- shaders-msl/frag/sample-mask.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
This is a partial fix for Issue #443. It fixes the original issue reported in the use of `gl_SampleMask.
Issue #443 still requires work that is independent of this PR...and this PR can be added now.
> CompilerMSL support gl_SampleMask and convert it to scalar uint from array.

- spirv_cross.cpp
I found a crash in OpCopyMemory where it assumed that var wasn't null. This looked like a small oversight as the lines directly above and below do the null check.
I attached a dissassembly file that caused this crash.
[TestDissassembly.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1725213/TestDissassembly.txt)
> Null crash fix in OpCopyMemory.

- reference/opt/shaders-msl/comp/struct-nested.comp
- reference/shaders-msl/comp/struct-nested.comp
- shaders-msl/comp/struct-nested.comp
- spirv_msl.cpp
> CompilerMSL remove incorrect packing of non-interface type-aliased structs.

- reference/opt/shaders-hlsl/asm/frag/function-overload-alias.asm.frag
- reference/opt/shaders-msl/asm/frag/function-overload-alias.asm.frag
- reference/opt/shaders/asm/frag/function-overload-alias.asm.frag
- reference/shaders-hlsl/asm/frag/function-overload-alias.asm.frag
- reference/shaders-msl/asm/frag/function-overload-alias.asm.frag
- reference/shaders/asm/frag/function-overload-alias.asm.frag
- shaders-hlsl/asm/frag/function-overload-alias.asm.frag
- shaders-msl/asm/frag/function-overload-alias.asm.frag
- shaders/asm/frag/function-overload-alias.asm.frag
- spirv_common.hpp
- spirv_cpp.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
Awkward, but legal SPIR-V.
Fix #454.
> Handle overloaded functions which share the same OpName.

- reference/opt/shaders-hlsl/frag/spec-constant-block-size.frag
- reference/opt/shaders-msl/frag/spec-constant-block-size.frag
- reference/opt/shaders/vulkan/frag/spec-constant-block-size.vk.frag
- reference/opt/shaders/vulkan/frag/spec-constant-block-size.vk.frag.vk
- reference/shaders-hlsl/frag/spec-constant-block-size.frag
- reference/shaders-msl/frag/spec-constant-block-size.frag
- reference/shaders/vulkan/frag/spec-constant-block-size.vk.frag
- reference/shaders/vulkan/frag/spec-constant-block-size.vk.frag.vk
- shaders-hlsl/frag/spec-constant-block-size.frag
- shaders-msl/frag/spec-constant-block-size.frag
- shaders/vulkan/frag/spec-constant-block-size.vk.frag
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_msl.cpp
Won't really be correct if the spec constant is changed outside
SPIRV-Cross, but nothing we can do about that, really.
Fix #459.
> Support spec constant array size in blocks.

- main.cpp
- shaders-other/README.md
- shaders-other/aliased-entry-point-names.asm
- spirv_cross.cpp
- spirv_cross.hpp
SPIR-V allows names to alias if they implement different stages.
Deprecate the old interface and replace it with a new one which takes
execution modes into account.
Fix #476.
> Take execution model into account for entry point methods.

- CMakeLists.txt
- jni/Android.mk
- main.cpp
- msvc/SPIRV-Cross.vcxproj
- msvc/SPIRV-Cross.vcxproj.filters
- spirv_cross_util.cpp
- spirv_cross_util.hpp
Fixes #467.
I noticed that in #210 the choice was made to explicitly move this method into `main.cpp`, but it would be useful to expose as part of the reflection API if possible (I'd prefer not to re-implement it myself).
Let me know if it's still too specific or belongs on another class. Thanks!
> Move `rename_interface_variable` to util

- reference/opt/shaders-hlsl/frag/array-lut-no-loop-variable.frag
- reference/opt/shaders-msl/frag/array-lut-no-loop-variable.frag
- reference/opt/shaders/frag/array-lut-no-loop-variable.frag
- reference/shaders-hlsl/frag/array-lut-no-loop-variable.frag
- reference/shaders-msl/frag/array-lut-no-loop-variable.frag
- reference/shaders/frag/array-lut-no-loop-variable.frag
- shaders-hlsl/frag/array-lut-no-loop-variable.frag
- shaders-msl/frag/array-lut-no-loop-variable.frag
- shaders/frag/array-lut-no-loop-variable.frag
- spirv_cross.cpp
- spirv_glsl.cpp
Fixes awkward code-gen issue.
Fix #488.
> Disallow arrays and structs from becoming loop variables.

- main.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
The old interface had some awkward issue when set_options was used in a base class, where overloading would not work right.
This splits out the interface into separate calls which is more direct and cleaner.
Fix #489.
> Deprecate old set_options()/get_options() interface in favor of explicit names.

- spirv_glsl.cpp
Nothing super exciting, but I ran into this issue and I figured I would try and upstream my fix. Basically it adds support for emitting the textureXYZGrad() GLSL instruction for legacy GLSL generation.
I'm not sure if this is the proper way to go about creating a pull request, so apologies if I screwed something up.
> Added generation of the textureXYZGrad() legacy GLSL instruction

- reference/opt/shaders-msl/frag/mrt-array.frag
- reference/shaders-msl/frag/mrt-array.frag
- shaders-msl/frag/mrt-array.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_msl.cpp
> Flatten MSL MRT outputs when used as an array.

- reference/opt/shaders-msl/frag/shadow-compare-global-alias.frag
- reference/shaders-msl/frag/shadow-compare-global-alias.frag
- shaders-msl/frag/shadow-compare-global-alias.frag
- spirv_msl.cpp
> Fix depth-compare sampling in MSL when used as global alias argument.

- spirv_glsl.cpp
- spirv_hlsl.cpp
There is no sensible way to map this that would work in all scenarios.
Closes #535.
> Unsigned integers are disallowed on legacy targets.

- reference/opt/shaders/vulkan/frag/separate-combined-fake-overload.vk.frag
- reference/opt/shaders/vulkan/frag/separate-combined-fake-overload.vk.frag.vk
- reference/shaders/vulkan/frag/separate-combined-fake-overload.vk.frag
- reference/shaders/vulkan/frag/separate-combined-fake-overload.vk.frag.vk
- shaders/vulkan/frag/separate-combined-fake-overload.vk.frag
- spirv_glsl.cpp
> Deal with fake overloads when using combined image samplers.

- main.cpp
- spirv_cross_util.cpp
- spirv_cross_util.hpp
> Add support for inheriting bindings for combined image samplers.

- spirv_glsl.cpp
textureGrad isn't part of core GL2 or GLES2. In desktop GL, it's
provided by GL_ARB_shader_texture_lod and is called texture2DGradARB; in
ES, it's provided by GL_EXT_shader_texture_lod and is called
texture2DGradEXT.
This change rewrites textureGrad similarly to textureProj as per above.
> Fix textureGrad compilation for legacy targets

- main.cpp
- reference/opt/shaders-msl/comp/basic.comp
- reference/opt/shaders-msl/comp/culling.comp
- reference/opt/shaders-msl/comp/dowhile.comp
- reference/opt/shaders-msl/comp/inverse.comp
- reference/opt/shaders-msl/comp/mod.comp
- reference/opt/shaders-msl/comp/modf.comp
- reference/opt/shaders-msl/comp/read-write-only.comp
- reference/opt/shaders-msl/comp/shared.comp
- reference/opt/shaders-msl/comp/struct-layout.comp
- reference/opt/shaders-msl/comp/torture-loop.comp
- reference/opt/shaders-msl/frag/readonly-ssbo.frag
- reference/shaders-msl-no-opt/comp/loop.comp
- reference/shaders-msl/comp/basic.comp
- reference/shaders-msl/comp/culling.comp
- reference/shaders-msl/comp/dowhile.comp
- reference/shaders-msl/comp/inverse.comp
- reference/shaders-msl/comp/mod.comp
- reference/shaders-msl/comp/modf.comp
- reference/shaders-msl/comp/read-write-only.comp
- reference/shaders-msl/comp/shared.comp
- reference/shaders-msl/comp/struct-layout.comp
- reference/shaders-msl/comp/torture-loop.comp
- reference/shaders-msl/frag/readonly-ssbo.frag
- shaders-msl/frag/readonly-ssbo.frag
- spirv_cross_util.hpp
- spirv_msl.cpp
> Use const device address space for readonly SSBOs in MSL.

- reference/opt/shaders-hlsl/frag/row-major-layout-in-struct.frag
- reference/shaders-hlsl/frag/row-major-layout-in-struct.frag
- shaders-hlsl/frag/row-major-layout-in-struct.frag
- spirv_hlsl.cpp
Unlike GLSL, child structs do not inherit matrix layouts.
Fix #295.
> Emit matrix layouts in structs directly.

- reference/opt/shaders-msl/frag/binary-func-unpack-pack-arguments.frag
- reference/shaders-msl/frag/binary-func-unpack-pack-arguments.frag
- shaders-msl/frag/binary-func-unpack-pack-arguments.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
OSX 10.14 broke (?) how overload resolution works,
so overloading e.g. dot(float3, packed_float3) no longer works.
Fix this by unpacking expressions before various func ops.
This fix might need to be applied elsewhere, but do so later if needed.
Fix #603.
> Unpack expressions when used in functions on MSL.

- spirv_glsl.cpp
Basically what the title says. If you have a shadow sampler up until now SPIRV-Cross would emit a `texture[XY]()` instruction, which works fine on modern GLSL backends but not on legacy backends. 
This adds the emission of  `shadowXY()` instructions. It's not 100% complete but should cover the most used cases, at least to implement CSM. And it's a starting point for others to pile on more variants if necessary.
> Added support for shadowXY() sample instructions in legacy GLSL

- reference/opt/shaders-msl/vert/set_builtin_in_func.vert
- reference/shaders-msl/vert/set_builtin_in_func.vert
- shaders-msl/vert/set_builtin_in_func.vert
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
Add and use Compiler::get_non_pointer_type() convenience functions.
Fixes issue #610.
> CompilerMSL pass builtin struct members into functions.

- reference/opt/shaders-msl/vert/texture_buffer.vert
- reference/shaders-msl-no-opt/vert/functions_nested.vert
- reference/shaders-msl/vert/texture_buffer.vert
- spirv_msl.cpp
- spirv_msl.hpp
Add CompilerMSL::Options::texture_width_max.
Emit and use spvTexelBufferCoord() function to convert 1D
texel buffer coordinates to 2D Metal texture coordinates.
> CompilerMSL support larger texel buffers by using 2D Metal textures.

- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Some projects build SPIRV-Cross as a single translation unit
and this causes a lot of warnings because the same macro is redeclared
multiple times in the different backends. This make sure that each
backend has its own namespace for internal macros.
> Add basic namespace to internal macros

- reference/opt/shaders-hlsl/asm/frag/unknown-depth-state.asm.frag
- reference/opt/shaders-msl/asm/frag/unknown-depth-state.asm.frag
- reference/opt/shaders/asm/frag/unknown-depth-state.asm.vk.frag
- reference/opt/shaders/asm/frag/unknown-depth-state.asm.vk.frag.vk
- reference/shaders-hlsl/asm/frag/unknown-depth-state.asm.frag
- reference/shaders-msl/asm/frag/unknown-depth-state.asm.frag
- reference/shaders/asm/frag/unknown-depth-state.asm.vk.frag
- reference/shaders/asm/frag/unknown-depth-state.asm.vk.frag.vk
- shaders-hlsl/asm/frag/unknown-depth-state.asm.frag
- shaders-msl/asm/frag/unknown-depth-state.asm.frag
- shaders/asm/frag/unknown-depth-state.asm.vk.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
Track which OpSampledImages are ever used with Dref opcodes.
Fix #631.
> Support OpTypeImage with depth == 2 (unknown) properly.

- reference/opt/shaders-msl/vert/no_stage_out.vert
- reference/opt/shaders-msl/vert/no_stage_out.write_tex.vert
- reference/shaders-msl/vert/no_stage_out.vert
- reference/shaders-msl/vert/no_stage_out.write_tex.vert
- shaders-msl/vert/no_stage_out.vert
- shaders-msl/vert/no_stage_out.write_tex.vert
- spirv_msl.cpp
- spirv_msl.hpp
Add CompilerMSL::Options::disable_rasterization input/output API flag.
Disable rasterization via API flag or when writing to textures.
Disable rasterization when shader declares no output.
Add test shaders for vertex no output and write texture forcing void output.
Metal has an IFF relationship between pipeline rasterization and vertex shader void return.
Metal requires that vertex shaders have a void return on any of:
- rasterization is disabled on the pipeline
- writing to textures
- writing to buffers
- no output variables are declared
Furthermore...when a void return is declared by the shader for any of the above reasons, the runtime pipeline must disable rasterization...requiring feedback through the API of the void return.
> CompilerMSL vertex entry point return void when rasterization disabled.

- spirv_msl.cpp
- spirv_msl.hpp
Simplification refactor of PR #644.
> Add CompilerMSL::get_is_rasterization_disabled() to manage rasterization status.

- reference/opt/shaders-msl/vert/no_stage_out.write_buff.vert
- reference/opt/shaders-msl/vert/no_stage_out.write_buff_atomic.vert
- reference/shaders-msl/vert/no_stage_out.write_buff.vert
- reference/shaders-msl/vert/no_stage_out.write_buff_atomic.vert
- shaders-msl/vert/no_stage_out.write_buff.vert
- shaders-msl/vert/no_stage_out.write_buff_atomic.vert
- spirv_msl.cpp
- spirv_msl.hpp
Continues from PRs #644 & #646 to include writes and atomic writes to buffers from vertex shaders.
> CompilerMSL disable rasterization on buffer writes in vertex shader.

- reference/opt/shaders/asm/frag/for-loop-phi-only-continue.asm.frag
- reference/shaders/asm/frag/for-loop-phi-only-continue.asm.frag
- shaders/asm/frag/for-loop-phi-only-continue.asm.frag
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
Need to promote while loops for for-loops in this case.
Also, deal with potential loop variables for other loop types.
Fix #651.
> Deal with continue blocks which only flush phi variables.

- reference/opt/shaders-hlsl/asm/frag/pass-by-value.asm.frag
- reference/opt/shaders-msl/asm/frag/pass-by-value.asm.frag
- reference/opt/shaders/asm/frag/pass-by-value.asm.frag
- reference/shaders-hlsl/asm/frag/pass-by-value.asm.frag
- reference/shaders-msl/asm/frag/empty-struct.asm.frag
- reference/shaders-msl/asm/frag/pass-by-value.asm.frag
- reference/shaders/asm/frag/pass-by-value.asm.frag
- shaders-hlsl/asm/frag/pass-by-value.asm.frag
- shaders-msl/asm/frag/pass-by-value.asm.frag
- shaders/asm/frag/pass-by-value.asm.frag
- spirv_msl.cpp
MSL would force thread const& which would not work if the input argument
came from a different storage class.
Emit proper non-reference arguments for such values.
Fix #643.
> MSL: Properly support passing parameters by value.

- spirv_msl.cpp
> MSL: Fix segfault when trying to store to an array inside struct.

- reference/opt/shaders-hlsl/asm/comp/global-parameter-name-alias.asm.comp
- reference/opt/shaders-msl/asm/comp/global-parameter-name-alias.asm.comp
- reference/opt/shaders/asm/comp/global-parameter-name-alias.asm.comp
- reference/shaders-hlsl/asm/comp/global-parameter-name-alias.asm.comp
- reference/shaders-msl/asm/comp/global-parameter-name-alias.asm.comp
- reference/shaders/asm/comp/global-parameter-name-alias.asm.comp
- shaders-hlsl/asm/comp/global-parameter-name-alias.asm.comp
- shaders-msl/asm/comp/global-parameter-name-alias.asm.comp
- shaders/asm/comp/global-parameter-name-alias.asm.comp
- spirv_glsl.cpp
- spirv_msl.cpp
When the name of an alias global variable collides with a global
declaration, MSL would emit inconsistent names, sometimes with the
naming fix, sometimes without, because names were being tracked in two
separate meta blocks. Fix this by always redirecting parameter naming to
the original base variable as necessary.
Fix #665.
> MSL: Fix naming issue of aliased global variables.

- reference/shaders-msl/desktop-only/vert/shader-draw-parameters.desktop.vert
- reference/shaders/desktop-only/vert/shader-draw-parameters-450.desktop.vert
- reference/shaders/desktop-only/vert/shader-draw-parameters.desktop.vert
- shaders-msl/desktop-only/vert/shader-draw-parameters.desktop.vert
- shaders/desktop-only/vert/shader-draw-parameters-450.desktop.vert
- shaders/desktop-only/vert/shader-draw-parameters.desktop.vert
- spirv_glsl.cpp
- spirv_msl.cpp
This adds the builtin uniforms from the `SPV_KHR_shader_draw_parameters` extension, and emits them to GLSL (with `GL_ARB_shader_draw_parameters`) and MSL. Metal doesn't support repeated draws the way Vulkan does, so the `DrawIndex` builtin isn't implemented here.
HLSL isn't added in this PR. I don't know what the corresponding builtin variables are in HLSL.
> Support the shader_draw_parameters extension.

- reference/shaders-msl/asm/frag/unord-relational-op.asm.frag
- shaders-msl/asm/frag/unord-relational-op.asm.frag
- spirv_msl.cpp
- spirv_msl.hpp
The SPIR-V spec says that these check if the operands either are
unordered or satisfy the given condition. So that's just what we'll do,
using Metal's `isunordered()` stdlib function. Apple's optimizers ought
to be able to collapse that to a single unordered compare.
> MSL: Support unordered relational operators.

- reference/opt/shaders-msl/asm/frag/vector-shuffle-oom.asm.frag
- reference/opt/shaders-msl/flatten/struct.flatten.vert
- reference/opt/shaders-msl/vert/copy.flatten.vert
- reference/opt/shaders-msl/vert/dynamic.flatten.vert
- reference/shaders-msl-no-opt/asm/frag/inliner-dominator-inside-loop.asm.frag
- reference/shaders-msl/asm/frag/min-max-clamp.asm.frag
- reference/shaders-msl/asm/frag/vector-shuffle-oom.asm.frag
- reference/shaders-msl/flatten/struct.flatten.vert
- reference/shaders-msl/vert/copy.flatten.vert
- reference/shaders-msl/vert/dynamic.flatten.vert
- shaders-msl/asm/frag/min-max-clamp.asm.frag
- spirv_msl.cpp
This roughly matches their semantics in SPIR-V and MSL. For `FMin`,
`FMax`, and `FClamp`, and the Metal functions `fast::min()`,
`fast::max()`, and `fast::clamp()`, the result is undefined if any
operand is NaN. For the 'N' operations and their corresponding MSL
`precise::` functions, the result is consistent with IEEE 754 (first
non-NaN wins; result is NaN if all operands are NaN).
We can only do this with 32-bit floats, though, because Metal only
provides these variants for `float`. `half` only has one variant of
these functions that is presumably consistent with IEEE 754. I guess
that's OK; the SPIR-V spec only says that `F{Min,Max,Clamp}` are
undefined for NaNs. Performance might suffer, though.
> MSL: Emit F{Min,Max,Clamp} as fast:: and N{Min,Max,Clamp} as precise::.

- reference/opt/shaders-msl/asm/comp/buffer-write-relative-addr.asm.comp
- reference/shaders-msl/asm/comp/buffer-write-relative-addr.asm.comp
- shaders-msl/asm/comp/buffer-write-relative-addr.asm.comp
- spirv_msl.cpp
The length field in `Instruction` doesn't include the initial
opcode/length word. We only need to skip three words instead of four.
> MSL: Correct number of words to skip in OpImageWrite.

- reference/opt/shaders-msl/asm/frag/locations-components.asm.frag
- reference/shaders-msl/asm/frag/locations-components.asm.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Two varyings (vertex outputs/fragment inputs) might have the same
location but be in different components--e.g. the compiler may have
packed what were two different varyings into a single varying vector.
Giving both varyings the same `[[user]]` attribute won't work--it may
yield unexpected results, or flat out fail to link. We could eventually
pack such varyings into a single vector, but that would require us to
handle the case where the varyings are different types--e.g. a `float`
and a `uint` packed into the same vector. For now, it seems most
prudent to give them unique `[[user]]` locations and let Apple's
compiler work out the best way to pack them.
> MSL: Account for components when assigning locations to varyings.

- reference/opt/shaders-hlsl/comp/composite-array-initialization.comp
- reference/opt/shaders-msl/asm/frag/lut-promotion-initializer.asm.frag
- reference/opt/shaders-msl/comp/composite-array-initialization.comp
- reference/opt/shaders-msl/frag/array-lut-no-loop-variable.frag
- reference/opt/shaders-msl/frag/constant-array.frag
- reference/opt/shaders-msl/frag/constant-composites.frag
- reference/opt/shaders-msl/frag/lut-promotion.frag
- reference/opt/shaders/comp/composite-array-initialization.comp
- reference/shaders-hlsl/comp/composite-array-initialization.comp
- reference/shaders-msl/asm/frag/lut-promotion-initializer.asm.frag
- reference/shaders-msl/asm/frag/op-constant-null.asm.frag
- reference/shaders-msl/comp/composite-array-initialization.comp
- reference/shaders-msl/comp/composite-construct.comp
- reference/shaders-msl/frag/array-lut-no-loop-variable.frag
- reference/shaders-msl/frag/constant-array.frag
- reference/shaders-msl/frag/constant-composites.frag
- reference/shaders-msl/frag/lut-promotion.frag
- reference/shaders-msl/vert/return-array.vert
- reference/shaders/comp/composite-array-initialization.comp
- shaders-hlsl/comp/composite-array-initialization.comp
- shaders-msl/comp/composite-array-initialization.comp
- shaders/comp/composite-array-initialization.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Fix #685.
Removes the virtual override for constant_expression in MSL. It is no longer needed since the GLSL implementation deals with backend special cases already.
Also fixes a bug in HLSL where chained AccessChains did not work on SSBOs.
> Fix composite array declarations in MSL.

- .gitignore
- reference/shaders-hlsl/frag/basic-color-3comp.sm30.frag
- reference/shaders-hlsl/frag/basic-color-3comp.sm50.frag
- shaders-hlsl/frag/basic-color-3comp.sm30.frag
- shaders-hlsl/frag/basic-color-3comp.sm50.frag
- spirv_hlsl.cpp
- test_shaders.py
The HLSL compiler throws the following error when targeting shader model 3 and an output with the "COLOR" semantic is not a four-component vector:
``` 
error X4529: COLOR0 must be a four-component vector
```
This fixes that by forcing fragment shader outputs to a four-component vector and padding any outputs with less components with zeroes.
Also added some user-specific Visual Studio files to the gitignore for convenience and tests to do future regression checking on the above.
> Fix invalid code generation for HLSL SM 3 when fragment shader output is not a vec4

- spirv_msl.cpp
Don't bother with hacky workaround unless required.
Fix #694.
> MSL: textureQueryLod() is not supported.

- reference/opt/shaders-msl/asm/comp/atomic-decrement.asm.comp
- reference/opt/shaders-msl/asm/comp/atomic-increment.asm.comp
- reference/shaders-msl/asm/comp/atomic-decrement.asm.comp
- reference/shaders-msl/asm/comp/atomic-increment.asm.comp
- shaders-msl/asm/comp/atomic-decrement.asm.comp
- shaders-msl/asm/comp/atomic-increment.asm.comp
- spirv_msl.cpp
- spirv_msl.hpp
We were passing a constant '1' to `emit_atomic_func_op()`--which caused
us to refer to SPIR-V value `%1`, which is almost certainly not what we
want! What we really want is to add/subtract the literal constant '1'
to/from the memory location.
> MSL: Fix OpAtomicIIncrement and OpAtomicIDecrement.

- reference/opt/shaders-msl/asm/frag/interpolation-qualifiers-struct.asm.frag
- reference/opt/shaders-msl/asm/frag/vector-shuffle-oom.asm.frag
- reference/opt/shaders-msl/frag/in_block.frag
- reference/opt/shaders-msl/frag/interpolation-qualifiers-block.frag
- reference/opt/shaders-msl/vert/interpolation-qualifiers-block.vert
- reference/opt/shaders-msl/vert/out_block.vert
- reference/shaders-msl-no-opt/asm/frag/inliner-dominator-inside-loop.asm.frag
- reference/shaders-msl-no-opt/frag/in_block_assign.frag
- reference/shaders-msl/asm/frag/interpolation-qualifiers-struct.asm.frag
- reference/shaders-msl/asm/frag/vector-shuffle-oom.asm.frag
- reference/shaders-msl/frag/in_block.frag
- reference/shaders-msl/frag/interpolation-qualifiers-block.frag
- reference/shaders-msl/vert/interpolation-qualifiers-block.vert
- reference/shaders-msl/vert/out_block.vert
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Implement this by flattening outputs and unflattening inputs explicitly.
This allows us to pass down a single struct instead of dealing with the
insanity that would be passing down each flattened member separately.
Remove stage_uniforms_var_id.
Seems to be dead code. Naked uniforms do not exist in SPIR-V for Vulkan,
which this seems to have been intended for. It was also unused elsewhere.
Fix: #695.
> MSL: Support global I/O block and struct Input/Output usage.

- reference/opt/shaders-msl/vert/layer.msl11.invalid.vert
- reference/opt/shaders-msl/vert/viewport-index.msl2.invalid.vert
- reference/shaders-msl/vert/layer.msl11.invalid.vert
- reference/shaders-msl/vert/viewport-index.msl2.invalid.vert
- shaders-msl/vert/layer.msl11.invalid.vert
- shaders-msl/vert/viewport-index.msl2.invalid.vert
- spirv_msl.cpp
This requires MSL 2.0+.
Also, force `ViewportIndex` and `Layer` to be defined as the correct
type, which is always `uint` in MSL.
Since Metal doesn't yet have geometry shaders, the vertex shader (or
tessellation evaluation shader == "post-tessellation vertex shader" in
Metal jargon) is the only kind of shader that can set this output. This
currently requires an extension to Vulkan, which causes validation of
the SPIR-V binaries for the test cases to fail. Therefore, the test
cases are marked "invalid", even though they're actually perfectly valid
SPIR-V--they just won't work without the
`SPV_EXT_shader_viewport_index_layer` extension.
> MSL: Handle the ViewportIndex builtin.

- main.cpp
- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- shaders-msl-no-opt/frag/texture-access.swizzle.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
It's intended to be used with MoltenVK to support arbitrary
`VkComponentMapping` settings. The idea is that MoltenVK will pass a
buffer (which it set to some buffer index that isn't being used)
containing packed versions of the `VkComponentMapping` struct, one for
each sampled image.
Yes, this is horribly ugly. It is unfortunately necessary. Much of the
ugliness is to support swizzling gather operations, where we need to
alter the component that the gather operates on--something complicated
by the `gather()` method requiring the passed-in component to be a
constant expression. It doesn't even support swizzling gathers on depth
textures, though I could add that if it turns out we need it.
> MSL: Add an option to insert texture swizzles into generated shaders.

- spirv_common.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
Avoids special "meta" data to express this type.
Makes MSL implementation in line with HLSL.
Fix #720.
> Refactor MSL to use SPIRCombinedImageSampler.

- CMakeLists.txt
- main.cpp
- msvc/SPIRV-Cross.vcxproj
- msvc/SPIRV-Cross.vcxproj.filters
- spirv_common.hpp
- spirv_cpp.cpp
- spirv_cpp.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_parsed_ir.cpp
- spirv_cross_parsed_ir.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- spirv_parser.cpp
- spirv_parser.hpp
- spirv_reflect.cpp
- spirv_reflect.hpp
This is a large refactor which splits out the SPIR-V parser from Compiler and moves it into its more appropriately named `Parser` module.
The `Parser` is responsible for building a `ParsedIR` structure which is then consumed by one or more compilers.
`Compiler` can take a `ParsedIR` by value or move reference. This should allow for optimal case for both multiple compilations and single compilation scenarios.
Fix #712.
> Hoist out parsing module from spirv_cross::Compiler

- reference/opt/shaders-hlsl/asm/frag/cbuffer-stripped.asm.frag
- reference/opt/shaders-hlsl/asm/frag/pass-by-value.asm.frag
- reference/opt/shaders-hlsl/comp/num-workgroups-alone.comp
- reference/opt/shaders-hlsl/comp/num-workgroups-with-builtins.comp
- reference/opt/shaders-hlsl/comp/rwbuffer-matrix.comp
- reference/opt/shaders-hlsl/frag/constant-buffer-array.invalid.sm51.frag
- reference/opt/shaders-hlsl/frag/resources.frag
- reference/opt/shaders-hlsl/frag/row-major-layout-in-struct.frag
- reference/opt/shaders-hlsl/frag/spec-constant-block-size.frag
- reference/opt/shaders-hlsl/vert/basic.vert
- reference/opt/shaders-hlsl/vert/read-from-row-major-array.vert
- reference/shaders-hlsl/asm/frag/cbuffer-stripped.asm.frag
- reference/shaders-hlsl/asm/frag/pass-by-value.asm.frag
- reference/shaders-hlsl/comp/num-workgroups-alone.comp
- reference/shaders-hlsl/comp/num-workgroups-with-builtins.comp
- reference/shaders-hlsl/comp/rwbuffer-matrix.comp
- reference/shaders-hlsl/frag/constant-buffer-array.invalid.sm51.frag
- reference/shaders-hlsl/frag/partial-write-preserve.frag
- reference/shaders-hlsl/frag/resources.frag
- reference/shaders-hlsl/frag/row-major-layout-in-struct.frag
- reference/shaders-hlsl/frag/spec-constant-block-size.frag
- reference/shaders-hlsl/vert/basic.vert
- reference/shaders-hlsl/vert/read-from-row-major-array.vert
- spirv_cross.hpp
- spirv_hlsl.cpp
HLSL just picked the variable name which did not work as expected for
some users. Use the same logic as GLSL and set up declared_block_names,
so the actual name can be queried later.
Fix #728.
> HLSL: Use same logic as GLSL for picking cbuffer block name.

- reference/opt/shaders/asm/comp/specialization-constant-workgroup.asm.comp
- reference/opt/shaders/asm/comp/storage-buffer-basic.invalid.asm.comp
- reference/opt/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert
- reference/opt/shaders/comp/composite-array-initialization.comp
- reference/opt/shaders/vulkan/frag/spec-constant-block-size.vk.frag
- reference/opt/shaders/vulkan/frag/spec-constant-ternary.vk.frag
- reference/shaders-no-opt/vulkan/frag/spec-constant.vk.frag
- reference/shaders/asm/comp/specialization-constant-workgroup.asm.comp
- reference/shaders/asm/comp/storage-buffer-basic.invalid.asm.comp
- reference/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert
- reference/shaders/comp/composite-array-initialization.comp
- reference/shaders/vulkan/frag/spec-constant-block-size.vk.frag
- reference/shaders/vulkan/frag/spec-constant-ternary.vk.frag
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
Previously, when generating non-Vulkan GLSL, each use of a spec constant
would be subsituted for its default value and the declaration of the constant
itself would be omitted completely.
This change slightly alters this behavior. The uses of the constant are kept,
as well as the declaration, although the latter is stripped of the layout
qualifier. The declaration is also prepended with the following code:
#ifndef <constant name>_value
#define <constant name> <default constant value>
#endif
and the constant itself now looks like
const <constant type> <constant name> = <constant name>_value;
The rationale for this change is that it gives the user a way to provide
custom values for specialization constants even when the target does not
support them.
> Alter the handling of spec consts in non-Vulkan GLSL

- spirv_msl.cpp
The compiler in 10.14 reports an error that the attribute cannot be applied to types if the specifier is printed before the fragment specifier.
I can't see anywhere in the spec that suggests where the specifier must be inserted, but the examples place it at the beginning.
> MSL: Print early_fragment_tests specifier before fragment

- reference/opt/shaders-msl/asm/comp/relaxed-block-layout.asm.comp
- reference/shaders-msl/asm/comp/relaxed-block-layout.asm.comp
- shaders-msl/asm/comp/relaxed-block-layout.asm.comp
- spirv_msl.cpp
This is necessary to support `VK_KHR_relaxed_block_layout`.
> MSL: Also pack members at unaligned offsets.

- reference/opt/shaders-msl/vert/sign-int-types.vert
- reference/shaders-msl/vert/sign-int-types.vert
- shaders-msl/vert/sign-int-types.vert
- spirv_msl.cpp
- spirv_msl.hpp
Metal does not define the sign() function for integer types, only floating-point types. GLSL defines sign() for genType, genDType, and genIType (Section 8.3 - Common Functions).
This PR generates a wrapper function which uses select() to return -1, 0, or 1 depending on the input, using the select() function. Not sure if this is the optimal method of implementing these semantics, but it seems cleaner to me than a series of ternaries, and uses templates like the surrounding wrappers.
Please let me know if I'm going about this the wrong way. If it is acceptable, should I also add a test shader for this function overload?
> MSL: Emit wrapper for SSign (sign() for int types)

- main.cpp
- spirv_hlsl.cpp
When compiling a fragment shader to a HLSL shader model 30, an exception "Separate image and samplers not supported in legacy HLSL." fired from CompilerHLSL::emit_legacy_uniform.
This change combines image and sampler and skip the separated one, if shader model <= 30.
> HLSL: Combine image and sampler on shader model <= 30

- reference/opt/shaders-hlsl/frag/depth-greater-than.frag
- reference/opt/shaders-hlsl/frag/depth-less-than.frag
- reference/opt/shaders-msl/frag/depth-greater-than.frag
- reference/opt/shaders-msl/frag/depth-less-than.frag
- reference/opt/shaders/desktop-only/frag/depth-greater-than.desktop.frag
- reference/opt/shaders/desktop-only/frag/depth-less-than.desktop.frag
- reference/shaders-hlsl/frag/depth-greater-than.frag
- reference/shaders-hlsl/frag/depth-less-than.frag
- reference/shaders-msl/frag/depth-greater-than.frag
- reference/shaders-msl/frag/depth-less-than.frag
- reference/shaders/desktop-only/frag/depth-greater-than.desktop.frag
- reference/shaders/desktop-only/frag/depth-less-than.desktop.frag
- shaders-hlsl/frag/depth-greater-than.frag
- shaders-hlsl/frag/depth-less-than.frag
- shaders-msl/frag/depth-greater-than.frag
- shaders-msl/frag/depth-less-than.frag
- shaders/desktop-only/frag/depth-greater-than.desktop.frag
- shaders/desktop-only/frag/depth-less-than.desktop.frag
- spirv_glsl.cpp
- spirv_hlsl.cpp
Adds support on HLSL SM 5.0, and fixes bug on GLSL.
Makes sure early fragment tests is tested on MSL as well.
Fix #747.
> Deal with depth_greater/depth_less qualifiers.

- reference/opt/shaders/desktop-only/comp/extended-arithmetic.desktop.comp
- reference/shaders/desktop-only/comp/extended-arithmetic.desktop.comp
- shaders/desktop-only/comp/extended-arithmetic.desktop.comp
- spirv_glsl.cpp
- uaddCarry
- usubBorrow
- umulExtended
- imulExtended
Fix #740.
Fix #745.
> GLSL: Support extended arithmetic opcodes.

- reference/opt/shaders-msl/asm/comp/relaxed-block-layout.asm.comp
- reference/shaders-msl/asm/comp/relaxed-block-layout.asm.comp
- shaders-msl/asm/comp/relaxed-block-layout.asm.comp
- spirv_msl.cpp
This is also needed for `VK_KHR_relaxed_block_layout` support.
> MSL: Also pack 2- and 4- element vectors when necessary.

- spirv_parser.cpp
SPEC:
Continue specifying the Source text from the previous instruction. This has no semantic impact and can safely be removed from a module.
> Handle opcode OpSourceContinued.

- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross_parsed_ir.cpp
> Remove old hack for dealing with HLSL counter buffers.

- reference/opt/shaders/vert/invariant.vert
- reference/shaders/asm/vert/invariant.asm.vert
- reference/shaders/asm/vert/invariant.sso.asm.vert
- reference/shaders/vert/invariant.vert
- shaders/vert/invariant.vert
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
Avoids certain cases of variance between translation units by forcing
every dependent expression of a store to be temporary.
Should avoid the major failure cases where invariance matters.
Fix #761.
> Handle invariant decoration more robustly.

- spirv_common.hpp
- spirv_glsl.cpp
- spirv_parser.cpp
Defer failure of pointer-to-pointer to compilation time, so we can still
reflect VK_KHR_variable_pointer shaders.
Fix #770.
> Keep track of pointer-to-pointer depth in parser.

- spirv_msl.cpp
- spirv_msl.hpp
Based on a patch by Stefan Dösinger.
Metal cannot do signedness conversion on vertex attributes, and for good
reason. Putting a `uint4` into an `int4`, or a `char4` into a `uint4`,
would lose those values that are outside the range of the target type.
But putting a `uchar4` into a `short4` or an `int4`, or a `ushort4` into
an `int4`, should work. In that case, force the signedness in the shader
to match the declared type of the host.
Unfortunately, I don't really know how to automatically test this. This
remapping is done based on input parameters normally supplied by
MoltenVK. I'm not sure how we'd set this up for the command-line
`spirv-cross` tool.
> MSL: Force signedness of shader vertex attributes to match the host.

- spirv_msl.cpp
- spirv_msl.hpp
> MSL: Use an enum instead of two mutually exclusive booleans.

- spirv_msl.cpp
Apple unexpectedly removed `memory_scope` in MSL 2.1.
> MSL don't emit memory_scope after MSL 2.0.

- reference/opt/shaders-hlsl/frag/complex-expression-in-access-chain.frag
- reference/opt/shaders-msl/frag/complex-expression-in-access-chain.frag
- reference/opt/shaders/comp/generate_height.comp
- reference/opt/shaders/frag/complex-expression-in-access-chain.frag
- reference/shaders-hlsl/frag/complex-expression-in-access-chain.frag
- reference/shaders-hlsl/frag/sampler-array.frag
- reference/shaders-msl/frag/complex-expression-in-access-chain.frag
- reference/shaders/frag/complex-expression-in-access-chain.frag
- shaders-hlsl/frag/complex-expression-in-access-chain.frag
- shaders-msl/frag/complex-expression-in-access-chain.frag
- shaders/frag/complex-expression-in-access-chain.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
This is required to avoid relying on complex sub-expression elimination
in compilers, and generates cleaner code.
The problem case is if a complex expression is used in an access chain,
like:
Composite comp = buffer[texture(...)];
vec4 a = comp.a + comp.b + comp.c;
Before, we did not have common subexpression tracking for
OpLoad/OpAccessChain, so we easily ended up with code like:
vec4 a = buffer[texture(...)].a + buffer[texture(...)].b + buffer[texture(...)].c;
A good compiler will optimize this, but we should not rely on it, and
forcing texture(...) to a temporary also looks better.
The solution is to add a vector "implied_expression_reads", which works
similarly to expression_dependencies. We also need an extra mechanism in
to_expression which lets us skip expression read checking and …
> Register implied expression reads in OpLoad/OpAccessChain.

- reference/opt/shaders-hlsl/asm/comp/block-name-alias-global.asm.comp
- reference/opt/shaders-msl/asm/comp/block-name-alias-global.asm.comp
- reference/opt/shaders/asm/comp/block-name-alias-global.asm.comp
- reference/shaders-hlsl/asm/comp/block-name-alias-global.asm.comp
- reference/shaders-msl/asm/comp/block-name-alias-global.asm.comp
- reference/shaders/asm/comp/block-name-alias-global.asm.comp
- shaders-hlsl/asm/comp/block-name-alias-global.asm.comp
- shaders-msl/asm/comp/block-name-alias-global.asm.comp
- shaders/asm/comp/block-name-alias-global.asm.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
A block name cannot alias with any name in its own scope,
and it cannot alias with any other "global" name.
To solve this, we need to complicate the name cache updates a little bit
where we have a "primary" namespace and "secondary" namespace.
Fix #780.
> Use correct block-name / other-name aliasing rules.

- spirv_glsl.cpp
More (legacy) texture stuff from me. We use this to share textures between Metal and OpenGL via an `IOSurfaceRef`, unfortunately that has a hard requirement for rectangle textures.
I wasn't exactly sure what extension requirement to pick, texture rectangle support is available via `GL_ARB_texture_rectangle` and `GL_EXT_gpu_shader4`. I've chosen `GL_ARB_texture_rectangle` for now, but if you prefer `GL_EXT_gpu_shader4` (since that's already used elsewhere for `textureLodOffset`), I'm happy to change it.
> Support for sampler2DRect and legacy texture2DRect() sampling function

- reference/opt/shaders-msl/frag/sampler-compare-cascade-gradient.frag
- reference/opt/shaders-msl/frag/sampler-compare-cascade-gradient.ios.frag
- reference/shaders-msl/frag/sampler-compare-cascade-gradient.frag
- reference/shaders-msl/frag/sampler-compare-cascade-gradient.ios.frag
- shaders-msl/frag/sampler-compare-cascade-gradient.frag
- shaders-msl/frag/sampler-compare-cascade-gradient.ios.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
Promote a compile-time constant gradient2d(float2(0), float2(0)) to level(0) to be compliant with macOS.
Fix #796.
> MSL: Workaround missing gradient2d() on macOS for typical cascaded shadow mapping

- reference/opt/shaders-msl/asm/frag/extract-packed-from-composite.asm.frag
- reference/shaders-msl/asm/frag/extract-packed-from-composite.asm.frag
- shaders-msl/asm/frag/extract-packed-from-composite.asm.frag
- spirv_glsl.cpp
Just like OpAccessChain we need to make use of the meta information
available to use from access_chain_internal as we can extract a packed
vector or transposed vector from a composite, not just memory load.
Fix #788.
> Forward meta information in OpCompositeExtract.

- spirv_common.hpp
- spirv_cross_parsed_ir.cpp
Doesn't do anything, but we can parse it correctly for now.
Fix #786.
> Handle FPRoundingMode decoration.

- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- spirv_msl.cpp
Before, if any component was not identity-mapped, those components that
were still identity-mapped were set to 0. Now we properly leave them
alone.
> MSL: Fix mapping of identity-swizzled components.

- reference/opt/shaders-msl/asm/comp/variable-pointers-2.asm.comp
- reference/opt/shaders-msl/asm/comp/variable-pointers-store-forwarding.asm.comp
- reference/shaders-msl-no-opt/asm/comp/variable-pointers.asm.comp
- reference/shaders-msl/asm/comp/variable-pointers-2.asm.comp
- reference/shaders-msl/asm/comp/variable-pointers-store-forwarding.asm.comp
- shaders-msl-no-opt/asm/comp/variable-pointers.asm.comp
- shaders-msl/asm/comp/variable-pointers-2.asm.comp
- shaders-msl/asm/comp/variable-pointers-store-forwarding.asm.comp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
- spirv_parser.cpp
This allows shaders to declare and use pointer-type variables. Pointers
may be loaded and stored, be the result of an `OpSelect`, be passed to
and returned from functions, and even be passed as inputs to the `OpPhi`
instruction. All types of pointers may be used as variable pointers.
Variable pointers to storage buffers and workgroup memory may even be
loaded from and stored to, as though they were ordinary variables. In
addition, this enables using an interior pointer to an array as though
it were an array pointer itself using the `OpPtrAccessChain`
instruction.
This is a rather large and involved change, mostly because this is
somewhat complicated with a lot of moving parts. It's a wonder
SPIRV-Cross's output is largely unchanged. Indeed, many of these changes
are to accomplish exactly …
> MSL: Support SPV_KHR_variable_pointers.

- reference/opt/shaders-msl/vert/interface-block-block-composites.frag
- reference/opt/shaders-msl/vert/interface-block-block-composites.vert
- reference/shaders-msl/vert/interface-block-block-composites.frag
- reference/shaders-msl/vert/interface-block-block-composites.vert
- shaders-msl/vert/interface-block-block-composites.frag
- shaders-msl/vert/interface-block-block-composites.vert
- spirv_common.hpp
- spirv_msl.cpp
- spirv_msl.hpp
I had to refactor the existing add_interface_block as it was getting extremely large. Now it's all split up into different readable functions.
Fix #797.
> MSL: Add support for emitting structs and arrays within I/O blocks.

- main.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Opt-in, since user need to know about a cbuffer.
Conflicts a bit with the GLSL option for base instance,
since that one is enabled by default, but the HLSL one isn't (because
user needs to know about a magic cbuffer, whereas GLSL can only get
default initialized uniform).
Fix #794.
> HLSL: Support BaseVertex/BaseInstance offsets.

- main.cpp
- reference/opt/shaders-msl/frag/fragment-component-padding.pad-fragment.frag
- reference/shaders-msl/frag/fragment-component-padding.pad-fragment.frag
- shaders-msl/frag/fragment-component-padding.pad-fragment.frag
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
If not enough components are provided in the shader,
the shader MSL compiler throws an error rather than make components
undefined. This hurts portability, so we need to add explicit padding
here.
Fix #819.
> MSL: Add option to pad fragment outputs.

- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- reference/shaders-msl-no-opt/vulkan/frag/texture-access-function.swizzle.vk.frag
- shaders-msl-no-opt/vulkan/frag/texture-access-function.swizzle.vk.frag
- spirv_msl.cpp
- spirv_msl.hpp
In the past, SPIRV-Cross threw an error in this case because it couldn't
work out which swizzle from the auxiliary buffer needs to be passed.
Now, we pass the swizzle around with the texture object, like a combined
image-sampler and its associated sampler.
> MSL: Fix passing a sampled image to a function.

- reference/opt/shaders-msl/asm/comp/buffer-write.asm.comp
- reference/opt/shaders-msl/asm/comp/image-load-store-short-vector.asm.comp
- reference/shaders-msl/asm/comp/buffer-write.asm.comp
- reference/shaders-msl/asm/comp/image-load-store-short-vector.asm.comp
- shaders-msl/asm/comp/image-load-store-short-vector.asm.comp
- spirv_glsl.cpp
- spirv_msl.cpp
Same fixes as for GLSL.
Fix #829.
> MSL: Fix image load/store for short vectors.

- reference/opt/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- shaders-msl/comp/force-recompile-hooks.swizzle.comp
- spirv_msl.cpp
- spirv_msl.hpp
Otherwise, in the event of a forced recompile, we could end up adding
them twice.
> MSL: Hoist fixup hooks in entry_point_args() out of the compile loop.

- reference/opt/shaders-msl/asm/comp/struct-resource-name-aliasing.asm.comp
- reference/shaders-msl/asm/comp/struct-resource-name-aliasing.asm.comp
- shaders-msl/asm/comp/struct-resource-name-aliasing.asm.comp
- spirv_msl.cpp
Apparently we didn't use those yet. MSL seems to be able to alias struct
types and variable types to a degree, so that's why it has escaped
testing until now.
Fix #834.
> MSL: Deal with resource name aliasing.

- reference/opt/shaders-hlsl/frag/sample-cmp-level-zero.frag
- reference/opt/shaders-hlsl/frag/tex-sampling.frag
- reference/opt/shaders-hlsl/frag/texture-proj-shadow.frag
- reference/opt/shaders-msl/frag/texture-proj-shadow.frag
- reference/shaders-hlsl/frag/sample-cmp-level-zero.frag
- reference/shaders-hlsl/frag/tex-sampling.frag
- reference/shaders-hlsl/frag/texture-proj-shadow.frag
- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- reference/shaders-msl-no-opt/vulkan/frag/texture-access-function.swizzle.vk.frag
- reference/shaders-msl/frag/texture-proj-shadow.frag
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
We need to divide the Dref by q.
Fix #840.
> HLSL/MSL: Fix texture projection with Dref.

- reference/opt/shaders-msl/asm/comp/block-name-alias-global.asm.comp
- reference/opt/shaders-msl/asm/frag/vector-shuffle-oom.asm.frag
- reference/opt/shaders-msl/comp/struct-packing.comp
- reference/opt/shaders-msl/vert/packed_matrix.vert
- reference/opt/shaders-msl/vert/ubo.alignment.vert
- reference/shaders-msl/asm/comp/block-name-alias-global.asm.comp
- reference/shaders-msl/asm/frag/vector-shuffle-oom.asm.frag
- reference/shaders-msl/comp/struct-packing.comp
- reference/shaders-msl/vert/packed_matrix.vert
- reference/shaders-msl/vert/ubo.alignment.vert
- spirv_glsl.cpp
- spirv_msl.cpp
Structs in MSL are packed with "normal" rules, i.e. alignment of the struct is max(alignof(members)), not 16 bytes which is the case in std140. Also fix a complex case where an MSL struct is declared with a very low natural alignment due to use of packed_float3.
Also adds a check for arrays of structs where the struct will need to be padded, but we cannot emit correct code yet, just warn about it in the code for now.
Fix #838.
> MSL: Use correct alignment for structs which are members of other structs.

- reference/opt/shaders/asm/comp/recompile-block-naming.asm.comp
- reference/shaders/asm/comp/recompile-block-naming.asm.comp
- shaders/asm/comp/recompile-block-naming.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
When we force recompile, the old var.self name we used as a fallback
name might have been disturbed, so we should recover certain names back
to their original form in case we are forced to take a recompile to make
the naming algorithm more deterministic.
Fix #854.
> GLSL: Fix block name shenanigans in edge cases.

- spirv_cross.hpp
They are internal, so should be protected:
> Move some interfaces out of public.

- reference/opt/shaders-msl/desktop-only/tese/triangle.desktop.sso.tese
- reference/opt/shaders-msl/tese/input-array.tese
- reference/opt/shaders-msl/tese/input-types.tese
- reference/opt/shaders-msl/tese/quad.tese
- reference/opt/shaders-msl/tese/set-from-function.tese
- reference/opt/shaders-msl/tese/triangle.tese
- reference/opt/shaders-msl/tese/water_tess.tese
- reference/shaders-msl/desktop-only/tese/triangle.desktop.sso.tese
- reference/shaders-msl/tese/input-array.tese
- reference/shaders-msl/tese/input-types.tese
- reference/shaders-msl/tese/quad.tese
- reference/shaders-msl/tese/set-from-function.tese
- reference/shaders-msl/tese/triangle.tese
- reference/shaders-msl/tese/water_tess.tese
- shaders-msl/desktop-only/tese/triangle.desktop.sso.tese
- shaders-msl/tese/input-array.tese
- shaders-msl/tese/input-types.tese
- shaders-msl/tese/quad.tese
- shaders-msl/tese/set-from-function.tese
- shaders-msl/tese/triangle.tese
- shaders-msl/tese/water_tess.tese
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
These are mapped to Metal's post-tessellation vertex functions. The
semantic difference is much less here, so this change should be simpler
than the previous one. There are still some hairy parts, though.
In MSL, the array of control point data is represented by a special
type, `patch_control_point<T>`, where `T` is a valid stage-input type.
This object must be embedded inside the patch-level stage input. For
this reason, I've added a new type to the type system to represent this.
On Mac, the number of input control points to the function must be
specified in the `patch()` attribute. This is optional on iOS.
SPIRV-Cross takes this from the `OutputVertices` execution mode; the
intent is that if it's not set in the shader itself, MoltenVK will set
it from the tessellation control shader. If …
> MSL: Add support for tessellation evaluation shaders.

- main.cpp
- reference/opt/shaders-msl/desktop-only/tese/triangle.desktop.sso.domain.tese
- reference/opt/shaders-msl/tese/quad.domain.tese
- reference/shaders-msl/desktop-only/tese/triangle.desktop.sso.domain.tese
- reference/shaders-msl/tese/quad.domain.tese
- shaders-msl/desktop-only/tese/triangle.desktop.sso.domain.tese
- shaders-msl/tese/quad.domain.tese
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
This is intended to be used to support `VK_KHR_maintenance2`'s
tessellation domain origin feature. If `tess_domain_origin_lower_left`
is `true`, the `v` coordinate will be inverted with respect to the
domain. Additionally, in `Triangles` mode, the `v` and `w` coordinates
will be swapped. This is because the winding order is interpreted
differently in lower-left mode.
> MSL: Add an option to set the tessellation domain origin.

- reference/shaders-no-opt/asm/frag/opaque-id-literal-alias.preserve.asm.frag
- reference/shaders-reflection/asm/aliased-entry-point-names.asm.multi.json
- shaders-no-opt/asm/frag/opaque-id-literal-alias.preserve.asm.frag
- shaders-reflection/asm/aliased-entry-point-names.asm.multi
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_reflect.cpp
- test_shaders.py
In the bizarre case where the ID of a loaded opaque type aliased with a
literal which was used as part of another texturing instruction, we
could end up with a case where domination analysis assumed the loaded
opaque type needed to be moved to a different scope.
Fix the issue by never doing dominance analysis for opaque temporaries,
and be more robust when analyzing texturing instructions.
Also make sure reflection output is deterministic.
This patch slightly alterered output for some unknown reason, but it came from an
unordered_map, so it's fine.
Fix #858.
> Fix edge case where opaque types can be declared on stack.

- reference/opt/shaders-hlsl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- reference/opt/shaders-msl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- reference/opt/shaders/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- reference/shaders-hlsl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- reference/shaders-msl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- reference/shaders/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- shaders-hlsl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- shaders-msl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- shaders/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- spirv_glsl.cpp
- spirv_msl.cpp
We were using combined decorations which propagated row-major information all the way from struct members up to the struct itself. The fix is to just check the immediate member when deducing transpose requirements.
Fix #861.
> Fix case where a struct is loaded which contains a row-major matrix.

- reference/opt/shaders-msl/comp/bitcast-16bit-1.invalid.comp
- reference/opt/shaders-msl/frag/16bit-constants.frag
- reference/opt/shaders/comp/bitcast-16bit-1.invalid.comp
- reference/opt/shaders/desktop-only/frag/fp16.invalid.desktop.frag
- reference/opt/shaders/frag/16bit-constants.frag
- reference/shaders-msl/comp/bitcast-16bit-1.invalid.comp
- reference/shaders-msl/frag/16bit-constants.frag
- reference/shaders-msl/frag/fp16.desktop.invalid.frag
- reference/shaders/comp/bitcast-16bit-1.invalid.comp
- reference/shaders/desktop-only/frag/fp16.invalid.desktop.frag
- reference/shaders/frag/16bit-constants.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
GL_NV_gpu_shader5 doesn't support "hf", so to avoid lots of complicated
workarounds, just value-cast the half literals.
Fix #863.
> Always value-cast FP16 constants instead of using literals.

- spirv_common.hpp
In msvc, assigns -1 to uint32_t can cause a warning.
> Fix the signed to unsigned conversion warning

- reference/opt/shaders-hlsl/asm/frag/sample-and-compare.asm.frag
- reference/opt/shaders-msl/asm/frag/sample-and-compare.asm.frag
- reference/opt/shaders/asm/frag/sample-and-compare.asm.frag
- reference/shaders-hlsl/asm/frag/sample-and-compare.asm.frag
- reference/shaders-msl/asm/frag/sample-and-compare.asm.frag
- reference/shaders/asm/frag/sample-and-compare.asm.frag
- shaders-hlsl/asm/frag/sample-and-compare.asm.frag
- shaders-msl/asm/frag/sample-and-compare.asm.frag
- shaders/asm/frag/sample-and-compare.asm.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
depth2d in MSL only returns float, not float4, even for normal sampling.
We need to conditionally remap-swizzle back to float4.
Fix #873.
> MSL: Fix textures which are sampled and compared against.

- reference/opt/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
- reference/opt/shaders-msl/tese/quad.domain.tese
- reference/opt/shaders-msl/tese/quad.tese
- reference/opt/shaders-msl/tese/triangle-tess-level.tese
- reference/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
- reference/shaders-msl/tese/quad.domain.tese
- reference/shaders-msl/tese/quad.tese
- reference/shaders-msl/tese/triangle-tess-level.tese
- shaders-msl/tese/quad.tese
- shaders-msl/tese/triangle-tess-level.tese
- spirv_msl.cpp
- spirv_msl.hpp
The tessellation levels in Metal are stored as a densely-packed array of
half-precision floating point values. But, stage-in attributes in Metal
have to have offsets and strides aligned to a multiple of four, so we
can't add them individually. Luckily for us, the arrays have lengths
less than 4. So, let's use vectors for them!
Triangles get a single attribute with a `float4`, where the outer levels
are in `.xyz` and the inner levels are in `.w`. The arrays are unpacked
as though we had added the elements individually. Quads get two: a
`float4` with the outer levels and a `float2` with the inner levels.
Further, since vectors can be indexed as arrays, there's no need to
unpack them in this case.
This also saves on precious vertex attributes. Before, we were using up
to 6 of them. Now we …
> MSL: Use vectors for the tessellation level builtins in tese shaders.

- spirv_msl.cpp
If a stage takes the position as both an input and an output (i.e. a
tessellation shader or a geometry shader), then we could wind up fixing
up the input position by mistake. Ensure that doesn't happen, by only
setting the `qual_pos_var_name` variable from the output position.
> MSL: Make sure we fix up the output position.

- reference/opt/shaders-msl/asm/tesc/tess-fixed-input-array-builtin-array.invalid.asm.tesc
- reference/opt/shaders-msl/desktop-only/tesc/arrayed-output.desktop.sso.tesc
- reference/opt/shaders-msl/desktop-only/tesc/basic.desktop.sso.tesc
- reference/opt/shaders-msl/desktop-only/tesc/struct-copy.desktop.sso.tesc
- reference/opt/shaders-msl/tesc/water_tess.tesc
- reference/shaders-msl/asm/tesc/tess-fixed-input-array-builtin-array.invalid.asm.tesc
- reference/shaders-msl/desktop-only/tesc/arrayed-output.desktop.sso.tesc
- reference/shaders-msl/desktop-only/tesc/basic.desktop.sso.tesc
- reference/shaders-msl/desktop-only/tesc/struct-copy.desktop.sso.tesc
- reference/shaders-msl/tesc/water_tess.tesc
- spirv_msl.cpp
Return after loading the input control point array if there are more
input points than output points, and this was one of the helper
invocations spun off to load the input points. I was hesitant to do this
initially, since the MSL spec has this to say about barriers:
> The `threadgroup_barrier` (or `simdgroup_barrier`) function must be
> encountered by all threads in a threadgroup (or SIMD-group) executing
> the kernel.
That is, if any thread executes the barrier, then all threads must
execute it, or the barrier'd invocations will hang. But, the key words
here seem to be "executing the kernel;" inactive invocations, those that
have already returned, need not encounter the barrier to prevent hangs.
Indeed, I've encountered no problems from doing this, at least on my
hardware. This also …
> MSL: Return early from helper tesc invocations.

- reference/opt/shaders-msl/asm/frag/descriptor-array-unnamed.asm.frag
- reference/shaders-msl/asm/frag/descriptor-array-unnamed.asm.frag
- shaders-msl/asm/frag/descriptor-array-unnamed.asm.frag
- spirv_msl.cpp
> MSL: Emit proper name for optimized UBO/SSBO arrays.

- spirv_common.hpp
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_reflect.cpp
Setting locales is not thread-safe and is a process-wide operation unless we tap into OS-specific mechanisms. Instead, we just query the locale and do this fix-up ourselves. This is much safer than the alternative.
Fix #880.
> Rewrite how we deal with locales and decimal point

- spirv_glsl.cpp
- spirv_parser.cpp
Can still parse correctly.
Fix #895.
> Move check for structured OpSwitch to CompilerGLSL.

- reference/opt/shaders/asm/geom/unroll-glposition-load.asm.geom
- reference/opt/shaders/asm/tese/unroll-input-array-load.asm.tese
- reference/shaders/asm/geom/unroll-glposition-load.asm.geom
- reference/shaders/asm/tese/unroll-input-array-load.asm.tese
- shaders/asm/geom/unroll-glposition-load.asm.geom
- shaders/asm/tese/unroll-input-array-load.asm.tese
- spirv_glsl.cpp
- spirv_glsl.hpp
Loading an array of gl_Position in geometry/tess needs to unroll via gl_in[i]. Loading an input array in tessellation also needs unrolling because GLSL declares the array as unsized, even if the SPIR-V has a concrete array size.
Fix #897.
> GLSL: Fix some complex cases for loading arrays

- reference/shaders-hlsl-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- reference/shaders-msl-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- reference/shaders-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- shaders-hlsl-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- shaders-msl-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- shaders-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- spirv_glsl.cpp
-1 (0xffffffff) literal means the component should be undefined.
Since we cannot express undefined directly, just use a 0 literal in the
appropriate type.
Fix #901.
> Support -1 index in OpVectorShuffle.

- reference/shaders-hlsl-no-opt/asm/comp/constant-composite-undef.asm.comp
- reference/shaders-msl-no-opt/asm/comp/constant-composite-undef.asm.comp
- reference/shaders-no-opt/asm/comp/constant-composite-undef.asm.comp
- shaders-hlsl-no-opt/asm/comp/constant-composite-undef.asm.comp
- shaders-msl-no-opt/asm/comp/constant-composite-undef.asm.comp
- shaders-no-opt/asm/comp/constant-composite-undef.asm.comp
- spirv_parser.cpp
Just treat any undefined argument as 0. It is risky to use the undefined
variable as it might not lower to a true constant.
Fix #910.
> Parser: Fix OpCompositeConstruct with OpUndef.

- reference/shaders-hlsl-no-opt/asm/comp/glsl-signed-operations.asm.comp
- reference/shaders-hlsl-no-opt/comp/bitfield.comp
- reference/shaders-msl-no-opt/asm/comp/glsl-signed-operations.asm.comp
- reference/shaders-msl-no-opt/comp/bitfield.comp
- reference/shaders-no-opt/asm/comp/glsl-signed-operations.asm.comp
- shaders-hlsl-no-opt/asm/comp/glsl-signed-operations.asm.comp
- shaders-msl-no-opt/asm/comp/glsl-signed-operations.asm.comp
- shaders-no-opt/asm/comp/glsl-signed-operations.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
The GLSLstd450 spec is very lax about input signs, so we need to do the
bitcasting dance to implement it correctly.
Fix #908.
> Properly deal with sign-dependent GLSL opcodes.

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
Allow user to disable individual backends.
Disallow this for CLI builds for now, but should be useful for
library-only builds, and particularly for C API.
Fix #909.
> Make build system more modular.

- reference/shaders-msl-no-opt/asm/comp/storage-buffer-pointer-argument.asm.comp
- shaders-msl-no-opt/asm/comp/storage-buffer-pointer-argument.asm.comp
- spirv_msl.cpp
Only deal with readonly decoration for actual block types.
Fix #916.
> MSL: Fix crash where variable storage buffer pointers are passed down.

- reference/opt/shaders-msl/asm/comp/specialization-constant-workgroup.asm.comp
- reference/opt/shaders-msl/asm/comp/storage-buffer-basic.invalid.asm.comp
- reference/opt/shaders-msl/asm/comp/vector-builtin-type-cast-func.asm.comp
- reference/opt/shaders-msl/asm/comp/vector-builtin-type-cast.asm.comp
- reference/opt/shaders-msl/comp/barriers.comp
- reference/opt/shaders-msl/comp/builtins.comp
- reference/opt/shaders-msl/comp/composite-array-initialization.comp
- reference/opt/shaders-msl/comp/culling.comp
- reference/opt/shaders-msl/comp/packing-test-1.comp
- reference/opt/shaders-msl/comp/packing-test-2.comp
- reference/opt/shaders-msl/comp/shared-array-of-arrays.comp
- reference/opt/shaders-msl/comp/shared.comp
- reference/opt/shaders-msl/comp/spec-constant-work-group-size.comp
- reference/shaders-msl/asm/comp/specialization-constant-workgroup.asm.comp
- reference/shaders-msl/asm/comp/storage-buffer-basic.invalid.asm.comp
- reference/shaders-msl/asm/comp/vector-builtin-type-cast-func.asm.comp
- reference/shaders-msl/asm/comp/vector-builtin-type-cast.asm.comp
- reference/shaders-msl/comp/barriers.comp
- reference/shaders-msl/comp/builtins.comp
- reference/shaders-msl/comp/composite-array-initialization.comp
- reference/shaders-msl/comp/culling.comp
- reference/shaders-msl/comp/packing-test-1.comp
- reference/shaders-msl/comp/packing-test-2.comp
- reference/shaders-msl/comp/shared-array-of-arrays.comp
- reference/shaders-msl/comp/shared.comp
- reference/shaders-msl/comp/spec-constant-work-group-size.comp
- spirv_msl.cpp
Avoids ugly warnings on nearly every compute shader.
We could do analysis to detect whether we need to emit this constant,
but it's a bit tedious to figure out if an OpConstantComponent is
actually used by opcodes, so just make it simple.
Fix #915.
> MSL: Declare gl_WorkGroupSize constant with [[maybe_unused]].

- spirv_glsl.cpp
- spirv_msl.cpp
The design of backend.int16_t_literal_suffix and backend.uint16_t_literal_suffix
allows them to be set to null, but that was not always tested for.
I have removed the expectation that they can be null and set
backend.int16_t_literal_suffix to "" when no suffix is needed.
That has the same effect, and seemed to be a more usable and defensive approach.
> Fix crash when backend.int16_t_literal_suffix set to null.

- CMakeLists.txt
- main.cpp
- spirv_cfg.cpp
- spirv_cfg.hpp
- spirv_common.hpp
- spirv_cpp.cpp
- spirv_cpp.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_c.cpp
- spirv_cross_parsed_ir.cpp
- spirv_cross_parsed_ir.hpp
- spirv_cross_util.cpp
- spirv_cross_util.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- spirv_parser.cpp
- spirv_parser.hpp
- spirv_reflect.cpp
- spirv_reflect.hpp
This is a pragmatic trick to avoid symbol collision where a project
links against SPIRV-Cross statically, while linking to other projects
which also use SPIRV-Cross statically. We can end up with very awkward
symbol collisions which can resolve themselves silently because
SPIRV-Cross is pulled in as necessary. To fix this, we must use
different symbols and embed two copies of SPIRV-Cross in this scenario,
now with different namespaces, which in turn leads to different symbols.
Fix #902.
> Add an option to override the namespace used for spirv_cross.

- reference/shaders-msl-no-opt/asm/frag/image-type-normal-comparison-usage.asm.frag
- shaders-msl-no-opt/asm/frag/image-type-normal-comparison-usage.asm.frag
- spirv_glsl.cpp
Need to look at the backing image for the image. We might have found
diverging use at the image variable level, not just expression level.
> MSL: Fix depth2d 4-component fixup.

- reference/shaders-hlsl-no-opt/asm/frag/image-fetch-uint-coord.asm.frag
- reference/shaders-msl-no-opt/asm/frag/image-fetch-uint-coord.asm.frag
- reference/shaders-no-opt/asm/frag/image-fetch-uint-coord.asm.frag
- shaders-hlsl-no-opt/asm/frag/image-fetch-uint-coord.asm.frag
- shaders-msl-no-opt/asm/frag/image-fetch-uint-coord.asm.frag
- shaders-no-opt/asm/frag/image-fetch-uint-coord.asm.frag
- spirv_glsl.cpp
- spirv_hlsl.cpp
Also fix some minor issues with too many coordinate dimensions in HLSL and GLSL.
Fix #925.
> GLSL: Fix OpImageFetch with uint coordinates and LOD.

- reference/opt/shaders/asm/frag/do-while-statement-fallback.asm.frag
- reference/shaders/asm/frag/do-while-statement-fallback.asm.frag
- shaders/asm/frag/do-while-statement-fallback.asm.frag
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
We had a bug where error conditions in DoWhileLoop emit path would not
detect that statements were being emitted due to the masking behavior
which happens when force_recompile is true. Fix this.
Also, refactor force_recompile into member functions so we can properly
break on any situation where this is set, without having to rely on
watchpoints in debuggers.
Fix #929.
> Detect invalid DoWhileLoop early.

- reference/opt/shaders-msl/comp/atomic.comp
- reference/shaders-msl/comp/atomic.comp
- spirv_msl.cpp
The CAS loop on atomic_compare_exchange_weak_explicit() became infinite if the atomic comparison was not equal. See further notes in the in-code comments.
> MSL: Fix infinite CAS loop on atomic_compare_exchange_weak_explicit().

- spirv_cross_error_handling.hpp
Clang defines _MSC_VER and supports [[noreturn]].
> Fix guard around [[noreturn]].

- reference/shaders-msl-no-opt/asm/comp/variable-pointers.asm.comp
- reference/shaders-no-opt/asm/comp/access-chain-dominator-in-loop-body-2.asm.comp
- reference/shaders-no-opt/asm/comp/access-chain-dominator-in-loop-body.asm.comp
- shaders-no-opt/asm/comp/access-chain-dominator-in-loop-body-2.asm.comp
- shaders-no-opt/asm/comp/access-chain-dominator-in-loop-body.asm.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
If we generate an access chain in a loop body, and it is consumed in the
loop continue block, we have a problem because we cannot emit a
temporary here holding the access chain reference. Force a complex loop
body to workaround this exceptionally rare case.
Fix #941.
> Force complex loop in certain rare access chain scenarios.

- spirv_hlsl.cpp
- spirv_hlsl.hpp
HLSLVertexAttributeRemap appears intended to remap Vertex Attributes to new names, however currently it applies to all interface blocks. This leads to HLSL code like:
Vertex Shader:
```
struct SPIRV_Cross_Input
{
float3 VertexCoord : VertexCoord;  // Position 0
float3 VertexNorm : VertexNorm;   // Position 1
float4 VertexColour : VertexColour;   // Position 2
};
struct SPIRV_Cross_Output
{
float4 FragColour : VertexCoord;  // Position 0. Thus also tagged as VertexCoord
float4 gl_Position : SV_Position;
};
```
This is in itself not a dealbreaker, only weird. Where it becomes an issue is when the fragment shader is converted independently of the vertex shader, and thus loses the vertex attributes:
Fragment Shader:
```
struct SPIRV_Cross_Input
{
float4 FragColour : TEXCOORD0;
};
```
This …
> Don't apply vertex attribute remapping to other interface blocks

- README.md
- build_glslang_spirv_tools.sh
- checkout_glslang_spirv_tools.sh
- test_shaders.py
- test_shaders.sh
- update_test_shaders.sh
Make path to spirv-cross configurable so we can be a bit more flexible
with build systems used to update tests.
Fix #948.
> Support running {,update_}test_shader.sh with CMake builds.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/frag/buffer-read-write.frag
- reference/opt/shaders-msl/frag/buffer-read-write.texture-buffer-native.msl21.frag
- reference/opt/shaders-msl/vert/texture_buffer.texture-buffer-native.msl21.vert
- reference/shaders-msl/frag/buffer-read-write.frag
- reference/shaders-msl/frag/buffer-read-write.texture-buffer-native.msl21.frag
- reference/shaders-msl/vert/texture_buffer.texture-buffer-native.msl21.vert
- shaders-msl/frag/buffer-read-write.frag
- shaders-msl/frag/buffer-read-write.texture-buffer-native.msl21.frag
- shaders-msl/vert/texture_buffer.texture-buffer-native.msl21.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
MSL 2.1 adds support for native texture_buffer types so we can avoid shenanigans with texture_2d workarounds. To not break anything, we need to opt-in to this. Also adds error checking for OpImageTexelPointer which marks that we are trying to use atomic operations on images or texel buffers, which are not supported in MSL.
Fix #950.
> MSL: Add native texture buffer support.

- reference/shaders-hlsl-no-opt/asm/comp/atomic-result-temporary.asm.comp
- reference/shaders-msl-no-opt/asm/comp/atomic-result-temporary.asm.comp
- reference/shaders-no-opt/asm/comp/atomic-result-temporary.asm.comp
- shaders-hlsl-no-opt/asm/comp/atomic-result-temporary.asm.comp
- shaders-msl-no-opt/asm/comp/atomic-result-temporary.asm.comp
- shaders-no-opt/asm/comp/atomic-result-temporary.asm.comp
- spirv_glsl.cpp
- spirv_hlsl.cpp
We made the mistake of registering a dependency on the atomic variable
even if the atomic result was forced to a temporary. There is no need to
register reads from atomic variables like this as we always force atomic
results to a temporary and argument read/writes do not need to be
tracked.
Fix #953
> Fix infinite loop when OpAtomic* temporaries are used in other blocks.

- reference/opt/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
- shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp
- shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp
- shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp
- shaders/vulkan/comp/buffer-reference.nocompat.vk.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_parsed_ir.cpp
- spirv_cross_parsed_ir.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_parser.cpp
Buffer objects can contain pointers to arbitrary data, essentially full pointer support. This might be possible to implement for MSL as well if MSL supports placing pointers in buffers.
Fix #924.
> GLSL: Implement GL_EXT_buffer_reference.

- reference/opt/shaders-hlsl/comp/ssbo-array-length.comp
- reference/opt/shaders/comp/ssbo-array-length.comp
- reference/shaders-hlsl/comp/ssbo-array-length.comp
- reference/shaders/comp/ssbo-array-length.comp
- shaders-hlsl/comp/ssbo-array-length.comp
- shaders/comp/ssbo-array-length.comp
- spirv_glsl.cpp
- spirv_hlsl.cpp
On HLSL we can query the byte size of any (RW)ByteAddressBuffer with GetDimensions, and then we compute the result.
> HLSL: Support OpArrayLength.

- reference/opt/shaders-hlsl/frag/nonuniform-qualifier.nonuniformresource.sm51.frag
- reference/opt/shaders-msl/frag/nonuniform-qualifier.msl2.frag
- reference/shaders-hlsl/frag/nonuniform-qualifier.nonuniformresource.sm51.frag
- reference/shaders-msl/frag/nonuniform-qualifier.msl2.frag
- shaders-hlsl/frag/nonuniform-qualifier.nonuniformresource.sm51.frag
- shaders-msl/frag/nonuniform-qualifier.msl2.frag
- spirv_cpp.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- test_shaders.py
MSL does not seem to have a qualifier for this, but HLSL SM 5.1 does.
glslangValidator for HLSL does not support this, so skip any validation,
but it passes in FXC.
Fix #974.
> HLSL/MSL: Deal correctly with nonuniformEXT qualifier.

- CMakeLists.txt
- main.cpp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_glsl.cpp
- spirv_glsl.hpp
Introduce a way to force treating all GLSL versions as "legacy" with regards to buffer blocks. This can be very useful for renderers that must work with multiple GLSL versions in their OpenGL backend due to having to support operating both in core and compatibility (or 2.x) contexts, the choice being outside of the renderer's control.  This is typically achieved by having (generating) two or more versions of the GLSL source (for example, 120 for compatibility/2.1 and 150 for core), but it would then be ideal if all the GLSL variants could use the same (legacy) approach for uniform blocks, instead of forcing the renderer to support both plain old uniforms and uniform buffers.
> GLSL: Add option to disable buffer blocks regardless of version

- reference/opt/shaders-msl/comp/barriers.comp
- reference/opt/shaders-msl/vulkan/comp/subgroups.nocompat.invalid.vk.msl21.comp
- reference/opt/shaders-msl/vulkan/comp/subgroups.nocompat.invalid.vk.msl21.ios.comp
- reference/shaders-msl/comp/barriers.comp
- reference/shaders-msl/vulkan/comp/subgroups.nocompat.invalid.vk.msl21.comp
- reference/shaders-msl/vulkan/comp/subgroups.nocompat.invalid.vk.msl21.ios.comp
- shaders-msl/comp/barriers.comp
- shaders-msl/vulkan/comp/subgroups.nocompat.invalid.vk.msl21.comp
- shaders-msl/vulkan/comp/subgroups.nocompat.invalid.vk.msl21.ios.comp
- spirv_msl.cpp
- spirv_msl.hpp
Some support for subgroups is present starting in Metal 2.0 on both iOS
and macOS. macOS gains more complete support in 10.14 (Metal 2.1).
Some restrictions are present. On iOS and on macOS 10.13, the
implementation of `OpGroupNonUniformElect` is incorrect: if thread 0 has
already terminated or is not executing a conditional branch, the first
thread that *is* will falsely believe itself not to be. Unfortunately,
this operation is part of the "basic" feature set; without it, subgroups
cannot be supported at all.
The `SubgroupSize` and `SubgroupLocalInvocationId` builtins are only
available in compute shaders (and, by extension, tessellation control
shaders), despite SPIR-V making them available in all stages. This
limits the usefulness of some of the subgroup operations in fragment …
> MSL: Add support for subgroup operations.

- CMakeLists.txt
- reference/opt/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/opt/shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- reference/opt/shaders-msl/frag/array-of-texture-swizzle.msl2.swizzle.frag
- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- reference/shaders-msl-no-opt/vulkan/frag/texture-access-function.swizzle.vk.frag
- reference/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
There is no good reason to expand the aux buffer, so name it
appropriately.
Make the code cleaner by emitting a straight pointer to uint rather than
a dummy struct which only contains a single unsized array member anyways.
Implement support for argument buffers when using image swizzle workaround.
Fix #972.
> MSL: Support image swizzle workaround with argument buffers

- reference/opt/shaders-msl/comp/complex-type-alias.comp
- reference/opt/shaders-msl/comp/composite-array-initialization.comp
- reference/shaders-msl/asm/frag/extract-packed-from-composite.asm.frag
- reference/shaders-msl/asm/vert/extract-transposed-matrix-from-struct.asm.vert
- reference/shaders-msl/comp/complex-type-alias.comp
- reference/shaders-msl/comp/composite-array-initialization.comp
- reference/shaders-msl/comp/packing-test-1.comp
- reference/shaders-msl/comp/storage-buffer-std140-vector-array.comp
- reference/shaders-msl/comp/struct-nested.comp
- reference/shaders-msl/comp/type-alias.comp
- reference/shaders-msl/frag/packing-test-3.frag
- shaders-msl/comp/complex-type-alias.comp
- spirv_cpp.cpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_reflect.cpp
MSL generally emits the aliases, which means we cannot always place the
master type first, unlike GLSL and HLSL. The logic fix is just to
reorder after we have tagged types with packing information, rather than
doing it in the parser fixup.
Fix #987.
> MSL: Fix complex type alias declaration order

- CMakeLists.txt
- reference/opt/shaders-msl/comp/array-length.comp
- reference/opt/shaders-msl/comp/array-length.msl2.argument.discrete.comp
- reference/opt/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/opt/shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- reference/opt/shaders-msl/frag/array-of-texture-swizzle.msl2.swizzle.frag
- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- reference/shaders-msl-no-opt/vulkan/frag/texture-access-function.swizzle.vk.frag
- reference/shaders-msl/comp/array-length.comp
- reference/shaders-msl/comp/array-length.msl2.argument.discrete.comp
- reference/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- reference/shaders-msl/frag/array-of-texture-swizzle.msl2.swizzle.frag
- shaders-msl/comp/array-length.comp
- shaders-msl/comp/array-length.msl2.argument.discrete.comp
- spirv_cross.cpp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
This gets rather complicated because MSL does not support OpArrayLength
natively. We need to pass down a buffer which contains buffer sizes, and
we compute the array length on-demand.
Support both discrete descriptors as well as argument buffers.
Fix #965.
> MSL: Implement OpArrayLength.

- reference/opt/shaders/vulkan/frag/scalar-block-layout-ubo-std430.vk.nocompat.invalid.frag.vk
- reference/shaders/vulkan/frag/scalar-block-layout-ubo-std430.vk.nocompat.invalid.frag.vk
- shaders/vulkan/frag/scalar-block-layout-ubo-std430.vk.nocompat.invalid.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
> GLSL: Support std430 in UBOs with scalar layout.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-hlsl/asm/frag/line-directive.line.asm.frag
- reference/opt/shaders-msl/asm/frag/line-directive.line.asm.frag
- reference/opt/shaders/asm/frag/line-directive.line.asm.frag
- reference/shaders-hlsl/asm/frag/line-directive.line.asm.frag
- reference/shaders-msl/asm/frag/line-directive.line.asm.frag
- reference/shaders/asm/frag/line-directive.line.asm.frag
- shaders-hlsl/asm/frag/line-directive.line.asm.frag
- shaders-msl/asm/frag/line-directive.line.asm.frag
- shaders/asm/frag/line-directive.line.asm.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_cross_parsed_ir.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_parser.cpp
- test_shaders.py
Facilitates easier mapping from source language to cross-compiled output
in tooling.
Fix #989.
> Support emitting OpLine directive.

- reference/opt/shaders-msl/asm/comp/global-parameter-name-alias.asm.comp
- reference/opt/shaders-msl/asm/vert/fake-builtin-input.asm.vert
- reference/opt/shaders-msl/comp/access-private-workgroup-in-function.comp
- reference/opt/shaders-msl/comp/builtins.comp
- reference/opt/shaders-msl/frag/packing-test-3.frag
- reference/shaders-msl-no-opt/asm/comp/variable-pointers.asm.comp
- reference/shaders-msl/asm/vert/fake-builtin-input.asm.vert
- shaders-msl/asm/vert/fake-builtin-input.asm.vert
- spirv_msl.cpp
- spirv_msl.hpp
In multiple-entry-point modules, we declared builtin inputs which were
not supposed to be used for that entry point.
Fix this, by being more strict when checking which builtins to emit.
Fix #998.
> MSL: Fix declaration of unused input variables.

- reference/shaders/vulkan/rgen/execute_callable.nocompat.vk.rgen.vk
- reference/shaders/vulkan/rgen/shader_record_buffer.nocompat.vk.rgen.vk
- shaders/vulkan/rgen/execute_callable.nocompat.vk.rgen
- shaders/vulkan/rgen/shader_record_buffer.nocompat.vk.rgen
- spirv_glsl.cpp
This should fix #999 and add all the remaining features from GLSL_NV_ray_tracing, with the exception of ray flags (which are just printed as integer constants, rather than as a combination of named flags).
> Add some missing features for NV_ray_tracing

- spirv_glsl.cpp
We seem to have to deal with a case where a block is used multiple times
without any "proper" structured control flow, so we risk losing deferred
declaration state.
Fix #1003.
> Deal with case where a block is somehow emitted in a duplicated fashion.

- reference/opt/shaders/frag/inside-loop-dominated-variable-preservation.frag
- reference/opt/shaders/vulkan/rgen/execute_callable.nocompat.vk.rgen.vk
- reference/opt/shaders/vulkan/rgen/shader_record_buffer.nocompat.vk.rgen.vk
- reference/shaders-msl-no-opt/vert/functions_nested.vert
- reference/shaders-msl/vert/copy.flatten.vert
- reference/shaders/asm/geom/unroll-glposition-load.asm.geom
- reference/shaders/flatten/copy.flatten.vert
- reference/shaders/frag/inside-loop-dominated-variable-preservation.frag
- shaders/frag/inside-loop-dominated-variable-preservation.frag
- spirv_cfg.cpp
- spirv_cfg.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
There is a risk that we try to preserve a loop variable through multiple
iterations, even though the dominating block is inside a loop.
Fix this by analyzing if a block starts off by writing to a variable. In
that case, there cannot be any preservation going on. If we don't, pretend the
loop header is reading the variable, which moves the variable to an
appropriate scope.
Rewrite how loop dominators are propagated.
Do this analysis in the CFG stage rather than last minute with the
ad-hoc algorithm we had in place before CFG was introduced.
Some un-submitted RT shaders snuck in as well.
Fix #1007. 
Fix #423.
> Deal with case where a variable is dominated by inner part of a loop.

- reference/shaders-reflection/asm/op-source-glsl-ssbo-1.asm.comp.json
- reference/shaders-reflection/asm/op-source-glsl-ssbo-2.asm.comp.json
- reference/shaders-reflection/asm/op-source-hlsl-uav-1.asm.comp.json
- reference/shaders-reflection/asm/op-source-hlsl-uav-2.asm.comp.json
- reference/shaders-reflection/asm/op-source-none-ssbo-1.asm.comp.json
- reference/shaders-reflection/asm/op-source-none-ssbo-2.asm.comp.json
- reference/shaders-reflection/asm/op-source-none-uav-1.asm.comp.json
- reference/shaders-reflection/asm/op-source-none-uav-2.asm.comp.json
- shaders-reflection/asm/op-source-glsl-ssbo-1.asm.comp
- shaders-reflection/asm/op-source-glsl-ssbo-2.asm.comp
- shaders-reflection/asm/op-source-hlsl-uav-1.asm.comp
- shaders-reflection/asm/op-source-hlsl-uav-2.asm.comp
- shaders-reflection/asm/op-source-none-ssbo-1.asm.comp
- shaders-reflection/asm/op-source-none-ssbo-2.asm.comp
- shaders-reflection/asm/op-source-none-uav-1.asm.comp
- shaders-reflection/asm/op-source-none-uav-2.asm.comp
- spirv_cross.cpp
- spirv_cross.hpp
This is rather shaky, but we don't have many choices here except add a
lot of awkward and unintuitive options. Try to deduce this from OpSource
and fallback to heuristic.
Fix #1018.
> Employ heuristics to figure out how to emit SSBO/UAV reflection names.

- reference/opt/shaders-msl/frag/private-variable-prototype-declaration.frag
- reference/shaders-msl/frag/private-variable-prototype-declaration.frag
- shaders-msl/frag/private-variable-prototype-declaration.frag
- spirv_glsl.cpp
If we compile multiple times due to forced_recompile, we had
deferred_declaration = true while emitting function prototypes which
broke an assumption. Fix this by clearing out stale state before leaving
a function.
Fix #1026.
> MSL: Fix regression with Private parameter declaration.

- reference/opt/shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- reference/shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- test_shaders.py
- Fix a new issue from latest beta SDK.
- Make it so test_shaders.py conditionally validates MSL 2.2 depending on SDK support. Travis CI images don't have MSL 2.2 support yet, but we can test locally at least in the meantime.
> Prepare for MSL 2.2 testing

- test_shaders.py
Also adds a way to skip validation per-shader (needed for an upcoming PR).
> MSL: Fix path check in test_shaders.py.

- test_shaders.py
Works locally, but apparently not on Travis?
> Make sure args.msl22 is set in test_shaders.py.

- reference/opt/shaders-msl/frag/image-query-lod.msl22.frag
- reference/shaders-msl/frag/image-query-lod.msl22.frag
- shaders-msl/frag/image-query-lod.msl22.frag
- spirv_msl.cpp
Correctness is a bit unclear at the moment. The spec document for 2.2 is
not updated for query-lod, but this is the best we can do anyways.
Fix #1013.
> MSL: Support OpImageQueryLod.

- reference/opt/shaders-msl/frag/barycentric-nv-nopersp.msl22.frag
- reference/opt/shaders-msl/frag/barycentric-nv.msl22.frag
- reference/opt/shaders/frag/barycentric-nv.frag
- reference/shaders-msl/frag/barycentric-nv-nopersp.msl22.frag
- reference/shaders-msl/frag/barycentric-nv.msl22.frag
- reference/shaders/frag/barycentric-nv.frag
- shaders-msl/frag/barycentric-nv-nopersp.msl22.frag
- shaders-msl/frag/barycentric-nv.msl22.frag
- shaders/frag/barycentric-nv.frag
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Was also trivial to add GLSL support for GL_NV_fragment_shader_barycentric.
Fix #1010.
> MSL: Support barycentrics and PrimitiveID in fragment shaders

- reference/opt/shaders-msl/comp/int64.invalid.msl22.comp
- reference/shaders-msl/comp/int64.invalid.msl22.comp
- shaders-msl/comp/int64.invalid.msl22.comp
- spirv_msl.cpp
MSL compiler is complaining about that you cannot place long/ulong in buffers, which does seem like a bug.
> MSL: Support 64-bit integers.

- reference/opt/shaders/asm/frag/switch-label-shared-block.asm.frag
- reference/shaders-hlsl-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- reference/shaders-msl-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- reference/shaders-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- reference/shaders/asm/frag/switch-label-shared-block.asm.frag
- shaders-hlsl-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- shaders-msl-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- shaders-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_containers.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
This is rather complicated to deal with in any sensible fashion, it's kind of a restricted form of goto, and it will also impact CFG variable scope analysis a fair bit. If one case label dominates variable declarations in another case label, we need to do the good old variable hoisting outside the switch block.
Fix #1033.
> Deal with OpSwitch case fallthrough

- reference/opt/shaders/asm/comp/phi-temporary-copy-loop-variable.asm.comp
- reference/shaders/asm/comp/phi-temporary-copy-loop-variable.asm.comp
- shaders/asm/comp/phi-temporary-copy-loop-variable.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
Certain Phi variables need to maintain a temporary copy, but we forgot
to declare them when the master variable is a loop variable itself.
Fix #1042.
> Fix declaration of loop variables with a Phi helper copy.

- reference/opt/shaders-hlsl/asm/frag/texture-sampling-fp16.asm.frag
- reference/opt/shaders-msl/asm/frag/texture-sampling-fp16.asm.frag
- reference/opt/shaders/asm/frag/texture-sampling-fp16.asm.vk.frag
- reference/opt/shaders/asm/frag/texture-sampling-fp16.asm.vk.frag.vk
- reference/shaders-hlsl-no-opt/asm/frag/switch-block-case-fallthrough.asm.frag
- reference/shaders-hlsl/asm/frag/texture-sampling-fp16.asm.frag
- reference/shaders-msl/asm/frag/texture-sampling-fp16.asm.frag
- reference/shaders/asm/frag/texture-sampling-fp16.asm.vk.frag
- reference/shaders/asm/frag/texture-sampling-fp16.asm.vk.frag.vk
- shaders-hlsl/asm/frag/texture-sampling-fp16.asm.frag
- shaders-msl/asm/frag/texture-sampling-fp16.asm.frag
- shaders/asm/frag/texture-sampling-fp16.asm.vk.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
MSL fails to resolve overloads if you don't pass in FP32 coordinates exactly.
Also fixes an unrelated FXC failure with HLSL.
Fix #1044.
> MSL: Fix sampling with FP16 coordinates.

- reference/opt/shaders-hlsl/comp/scalar-std450-distance-length-normalize.comp
- reference/opt/shaders-msl/comp/scalar-std450-distance-length-normalize.comp
- reference/opt/shaders/comp/scalar-std450-distance-length-normalize.comp
- reference/shaders-hlsl/comp/scalar-std450-distance-length-normalize.comp
- reference/shaders-msl/comp/scalar-std450-distance-length-normalize.comp
- reference/shaders/comp/scalar-std450-distance-length-normalize.comp
- shaders-hlsl/comp/scalar-std450-distance-length-normalize.comp
- shaders-msl/comp/scalar-std450-distance-length-normalize.comp
- shaders/comp/scalar-std450-distance-length-normalize.comp
- spirv_hlsl.cpp
- spirv_msl.cpp
HLSL and MSL don't support it, so fall back to simpler intrinsics.
Fix #1047.
> Deal with scalar input values for distance/length/normalize.

- main.cpp
- reference/opt/shaders-msl/vulkan/frag/basic.multiview.nocompat.vk.frag
- reference/opt/shaders-msl/vulkan/vert/multiview.multiview.nocompat.vk.vert
- reference/opt/shaders-msl/vulkan/vert/multiview.nocompat.vk.vert
- reference/shaders-msl/vulkan/frag/basic.multiview.nocompat.vk.frag
- reference/shaders-msl/vulkan/vert/multiview.multiview.nocompat.vk.vert
- reference/shaders-msl/vulkan/vert/multiview.nocompat.vk.vert
- shaders-msl/vulkan/frag/basic.multiview.nocompat.vk.frag
- shaders-msl/vulkan/vert/multiview.multiview.nocompat.vk.vert
- shaders-msl/vulkan/vert/multiview.nocompat.vk.vert
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
This is needed to support `VK_KHR_multiview`, which is in turn needed
for Vulkan 1.1 support. Unfortunately, Metal provides no native support
for this, and Apple is once again less than forthcoming, so we have to
implement it all ourselves.
Tessellation and geometry shaders are deliberately unsupported for now.
The problem is that the current implementation encodes the `ViewIndex`
as part of the `InstanceIndex`, which in the SPIR-V environment at least
only exists in the vertex shader. So we need to work out a way to pass
the view index along to the later stages.
This implementation runs vertex shaders for all views up to the highest
bit set in the view mask, even those whose bits are clear. The fragments
for the inactive views are then discarded. Avoiding this is difficult:
calculating …
> MSL: Support SPV_KHR_multiview.

- reference/opt/shaders-msl/vulkan/frag/subgroups.nocompat.invalid.vk.msl21.frag
- reference/shaders-msl/vulkan/frag/subgroups.nocompat.invalid.vk.msl21.frag
- shaders-msl/vulkan/frag/subgroups.nocompat.invalid.vk.msl21.frag
- spirv_msl.cpp
MSL prior to 2.2 doesn't support these natively in any stage but
compute. But, we can (assuming no threads were terminated prematurely)
get their values with some creative uses of the
`simd_prefix_exclusive_sum()` and `simd_sum()` functions.
Also, fix a missing `to_expression()` with `BuiltInSubgroupEqMask`.
For KhronosGroup/MoltenVK#629.
> MSL: Support SubgroupLocalInvocationId and SubgroupSize in all stages.

- spirv_common.hpp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_parser.cpp
No impact on result shader string.
> Parse SPIR-V debug information extended instructions, as well as OpNoLine

- reference/opt/shaders-hlsl/frag/for-loop-continue-control-flow.frag
- reference/opt/shaders-msl/frag/for-loop-continue-control-flow.frag
- reference/opt/shaders/frag/for-loop-continue-control-flow.frag
- reference/shaders-hlsl/frag/for-loop-continue-control-flow.frag
- reference/shaders-msl/frag/for-loop-continue-control-flow.frag
- reference/shaders/frag/for-loop-continue-control-flow.frag
- shaders-hlsl/frag/for-loop-continue-control-flow.frag
- shaders-msl/frag/for-loop-continue-control-flow.frag
- shaders/frag/for-loop-continue-control-flow.frag
- spirv_glsl.cpp
There is a case where we can deduce a for/while loop, but the continue
block is actually very painful to deal with, so handle that case as
well. Removes an exceptional case.
Fix #1062.
> Fall back to complex loop if non-trivial continue block is found.

- reference/shaders-hlsl-no-opt/asm/frag/nonuniform-qualifier-propagation.nonuniformresource.sm51.asm.frag
- reference/shaders-no-opt/asm/frag/nonuniform-qualifier-propagation.vk.nocompat.asm.frag.vk
- shaders-hlsl-no-opt/asm/frag/nonuniform-qualifier-propagation.nonuniformresource.sm51.asm.frag
- shaders-no-opt/asm/frag/nonuniform-qualifier-propagation.vk.nocompat.asm.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
This decoration might only be present for the very last ID which is
consumed by a sampling or Load/Store instruction. To make sure our
access chains are emitted correctly, we have to back-propagate this
decoration.
Fix #1061.
> Propagate NonUniformEXT to dependent expressions

- reference/opt/shaders-msl/comp/struct-packing.comp
- reference/opt/shaders-msl/vert/packed_matrix.vert
- reference/opt/shaders-msl/vulkan/comp/struct-packing-scalar.nocompat.invalid.vk.comp
- reference/opt/shaders-msl/vulkan/frag/scalar-block-layout-ubo-std430.vk.nocompat.invalid.frag
- reference/shaders-msl/comp/struct-packing.comp
- reference/shaders-msl/vert/packed_matrix.vert
- reference/shaders-msl/vulkan/comp/struct-packing-scalar.nocompat.invalid.vk.comp
- reference/shaders-msl/vulkan/frag/scalar-block-layout-ubo-std430.vk.nocompat.invalid.frag
- shaders-msl/vulkan/comp/struct-packing-scalar.nocompat.invalid.vk.comp
- shaders-msl/vulkan/frag/scalar-block-layout-ubo-std430.vk.nocompat.invalid.frag
- spirv_msl.cpp
- spirv_msl.hpp
Relaxed block layout relaxed the restrictions on vector alignment,
allowing them to be aligned on scalar boundaries. Scalar block layout
relaxes this further, allowing *any* member to be aligned on a scalar
boundary. The requirement that a vector not improperly straddle a
16-byte boundary is also relaxed.
I've also added a test showing that `std430` layout works with UBOs.
I'm troubled by the dual meaning of the `Packed` extended decoration. In
some instances (struct, `float[]`, and `vec2[]` members), it actually
means the exact opposite, that the member needs extra padding. This is
especially problematic for `vec2[]`, because now we need to distinguish
the two cases by checking the array stride. I wonder if this should
actually be split into two decorations.
I also don't like that there …
> MSL: Support scalar block layout.

- spirv_parser.cpp
**OpTypeImage** Sampled parameter must be one of the following values:
0 indicates this is only known at run time, not at compile time
1 indicates will be used with sampler
2 indicates will be used without a sampler (a storage image)
> Remove unreasonable assertion for OpTypeImage Sampled parameter.

- reference/shaders-msl/frag/fp16.desktop.invalid.frag
- reference/shaders-msl/frag/mix.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
This significantly improves codegen for vector `OpSelect` in MSL.
> MSL: Use the select() function for OpSelect.

- reference/opt/shaders-msl/frag/post-depth-coverage.ios.msl2.frag
- reference/opt/shaders/frag/post-depth-coverage.frag
- reference/shaders-msl/frag/post-depth-coverage.ios.msl2.frag
- reference/shaders/frag/post-depth-coverage.frag
- shaders-msl/frag/post-depth-coverage.ios.msl2.frag
- shaders/frag/post-depth-coverage.frag
- spirv_glsl.cpp
- spirv_msl.cpp
Using the `PostDepthCoverage` mode specifies that the `gl_SampleMaskIn`
variable is to contain the computed coverage mask following the early
fragment tests, which this mode requires and implicitly enables.
Note that unlike Vulkan and OpenGL, Metal places this on the sample mask
input itself, and furthermore does *not* implicitly enable early
fragment testing. If it isn't enabled explicitly with an
`[[early_fragment_tests]]` attribute, the compiler will error out. So we
have to enable that mode explicitly if `PostDepthCoverage` is enabled
but `EarlyFragmentTests` isn't.
For Metal, only iOS supports this; for some reason, Apple has yet to
implement it on macOS, even though many desktop cards support it.
> Support the SPV_KHR_post_depth_coverage extension.

- reference/opt/shaders-msl/asm/comp/atomic-decrement.asm.comp
- reference/opt/shaders-msl/asm/comp/atomic-increment.asm.comp
- reference/opt/shaders-msl/asm/comp/bitcast_iadd.asm.comp
- reference/opt/shaders-msl/asm/comp/multiple-entry.asm.comp
- reference/opt/shaders-msl/comp/atomic.comp
- reference/opt/shaders-msl/comp/basic.comp
- reference/opt/shaders-msl/comp/coherent-block.comp
- reference/opt/shaders-msl/comp/coherent-image.comp
- reference/opt/shaders-msl/comp/culling.comp
- reference/opt/shaders-msl/vert/no_stage_out.write_buff_atomic.vert
- reference/shaders-msl-no-opt/asm/comp/atomic-result-temporary.asm.comp
- reference/shaders-msl/asm/comp/atomic-decrement.asm.comp
- reference/shaders-msl/asm/comp/atomic-increment.asm.comp
- reference/shaders-msl/asm/comp/bitcast_iadd.asm.comp
- reference/shaders-msl/asm/comp/multiple-entry.asm.comp
- reference/shaders-msl/comp/atomic.comp
- reference/shaders-msl/comp/basic.comp
- reference/shaders-msl/comp/coherent-block.comp
- reference/shaders-msl/comp/coherent-image.comp
- reference/shaders-msl/comp/culling.comp
- reference/shaders-msl/vert/no_stage_out.write_buff_atomic.vert
- spirv_msl.cpp
- spirv_msl.hpp
This maps them to their MSL equivalents. I've mapped `Coherent` to
`volatile` since MSL doesn't have anything weaker than `volatile` but
stronger than nothing.
As part of this, I had to remove the implicit `volatile` added for
atomic operation casts. If the buffer is already `coherent` or
`volatile`, then we would add a second `volatile`, which would be
redundant. I think this is OK even when the buffer *doesn't* have
`coherent`: `T *` is implicitly convertible to `volatile T *`, but not
vice-versa. It seems to compile OK at any rate. (Note that the
non-`volatile` overloads of the atomic functions documented in the spec
aren't present in the MSL 2.2 stdlib headers.)
`restrict` is tricky, because in MSL, as in C++, it needs to go *after*
the asterisk or ampersand for the pointer type it's …
> MSL: Handle coherent, volatile, and restrict.

- CMakeLists.txt
- spirv_cross_c.cpp
Implicit casts to bool -> warning. Also works around some implicit casts to boolean.
Fix #1068.
> MSVC: Fix some warnings in C wrapper.

- reference/opt/shaders-msl/amd/shader_trinary_minmax.msl21.comp
- reference/shaders-msl/amd/shader_trinary_minmax.msl21.comp
- shaders-msl/amd/shader_trinary_minmax.msl21.comp
- spirv_msl.cpp
- spirv_msl.hpp
> MSL: Support the SPV_AMD_shader_trinary_minmax extension.

- main.cpp
- reference/opt/shaders-msl/vulkan/vert/device-group.multiview.viewfromdev.nocompat.vk.vert
- reference/opt/shaders-msl/vulkan/vert/device-group.nocompat.vk.vert
- reference/opt/shaders/vulkan/vert/device-group.nocompat.vk.vert.vk
- reference/shaders-msl/vulkan/vert/device-group.multiview.viewfromdev.nocompat.vk.vert
- reference/shaders-msl/vulkan/vert/device-group.nocompat.vk.vert
- reference/shaders/vulkan/vert/device-group.nocompat.vk.vert.vk
- shaders-msl/vulkan/vert/device-group.multiview.viewfromdev.nocompat.vk.vert
- shaders-msl/vulkan/vert/device-group.nocompat.vk.vert
- shaders/vulkan/vert/device-group.nocompat.vk.vert
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
The only piece added by this extension is the `DeviceIndex` builtin,
which tells the shader which device in a grouped logical device it is
running on.
Metal's pipeline state objects are owned by the `MTLDevice` that created
them. Since Metal doesn't support logical grouping of devices the way
Vulkan does, we'll thus have to create a pipeline state for each device
in a grouped logical device. The upcoming peer group support in Metal 3
will not change this. For this reason, for Metal, the device index is
supplied as a constant at pipeline compile time.
There's an interaction between `VK_KHR_device_group` and
`VK_KHR_multiview` in the
`VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT`, which defines the
view index to be the same as the device index. The new
`view_index_from_device_index` …
> Support the SPV_KHR_device_group extension.

- reference/opt/shaders-msl/intel/shader-integer-functions2.asm.comp
- reference/shaders-msl/intel/shader-integer-functions2.asm.comp
- shaders-msl/intel/shader-integer-functions2.asm.comp
- spirv_msl.cpp
This provides a few functions normally available in OpenCL to the SPIR-V
shader environment. These functions happen to be available in Metal as
well.
No GLSL, unfortunately. Intel has yet to publish a
`GL_INTEL_shader_integer_functions2` spec.
> MSL: Support the SPV_INTEL_shader_integer_functions2 extension.

- reference/opt/shaders-hlsl/frag/demote-to-helper.frag
- reference/opt/shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl21.invalid.frag
- reference/opt/shaders/vulkan/frag/demote-to-helper-forwarding.asm.vk.nocompat.frag.vk
- reference/opt/shaders/vulkan/frag/demote-to-helper.vk.nocompat.frag.vk
- reference/shaders-hlsl/frag/demote-to-helper.frag
- reference/shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl21.invalid.frag
- reference/shaders/vulkan/frag/demote-to-helper-forwarding.asm.vk.nocompat.frag.vk
- reference/shaders/vulkan/frag/demote-to-helper.vk.nocompat.frag.vk
- shaders-hlsl/frag/demote-to-helper.frag
- shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl21.invalid.frag
- shaders/vulkan/frag/demote-to-helper-forwarding.asm.vk.nocompat.frag
- shaders/vulkan/frag/demote-to-helper.vk.nocompat.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
This extension provides a new operation which causes a fragment to be
discarded without terminating the fragment shader invocation. The
invocation for the discarded fragment becomes a helper invocation, so
that derivatives will remain defined. The old `HelperInvocation` builtin
becomes undefined when this occurs, so a second new instruction queries
the current helper invocation status.
This is only fully supported for GLSL. HLSL doesn't support the
`IsHelperInvocation` operation and MSL doesn't support the
`DemoteToHelperInvocation` op.
Fixes #1052.
> Support the SPV_EXT_demote_to_helper_invocation extension.

- main.cpp
- reference/opt/shaders-msl/comp/basic.dispatchbase.comp
- reference/opt/shaders-msl/comp/basic.dispatchbase.msl11.comp
- reference/shaders-msl/comp/basic.dispatchbase.comp
- reference/shaders-msl/comp/basic.dispatchbase.msl11.comp
- shaders-msl/comp/basic.dispatchbase.comp
- shaders-msl/comp/basic.dispatchbase.msl11.comp
- spirv_common.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
This command allows the caller to set the base value of
`BuiltInWorkgroupId`, and thus of `BuiltInGlobalInvocationId`. Metal
provides no direct support for this... but it does provide a builtin,
`[[grid_origin]]`, normally used to pass the base values for the stage
input region, which we will now abuse to pass the dispatch base and
avoid burning a buffer binding.
`[[grid_origin]]`, as part of Metal's support for compute stage input,
requires MSL 1.2. For 1.0 and 1.1, we're forced to provide a buffer.
(Curiously, this builtin was undocumented until the MSL 2.2 release. Go
figure.)
> MSL: Adjust BuiltInWorkgroupId for vkCmdDispatchBase().

- main.cpp
- reference/opt/shaders/asm/frag/image-fetch-no-sampler.no-samplerless.asm.vk.frag
- reference/opt/shaders/asm/frag/image-fetch-no-sampler.no-samplerless.asm.vk.frag.vk
- reference/opt/shaders/asm/frag/image-query-no-sampler.no-samplerless.vk.asm.frag
- reference/opt/shaders/asm/frag/image-query-no-sampler.no-samplerless.vk.asm.frag.vk
- reference/shaders/asm/frag/image-fetch-no-sampler.no-samplerless.asm.vk.frag
- reference/shaders/asm/frag/image-fetch-no-sampler.no-samplerless.asm.vk.frag.vk
- reference/shaders/asm/frag/image-query-no-sampler.no-samplerless.vk.asm.frag
- reference/shaders/asm/frag/image-query-no-sampler.no-samplerless.vk.asm.frag.vk
- shaders/asm/frag/image-fetch-no-sampler.no-samplerless.asm.vk.frag
- shaders/asm/frag/image-query-no-sampler.no-samplerless.vk.asm.frag
- spirv_glsl.cpp
- test_shaders.py
Some platforms support Vulkan GLSL, but not this extension apparently
...
Fix #1090.
> Vulkan GLSL: Support disabling samplerless texture function EXT.

- reference/opt/shaders-hlsl/asm/frag/line-directive.line.asm.frag
- reference/opt/shaders-msl/asm/frag/line-directive.line.asm.frag
- reference/opt/shaders/asm/frag/line-directive.line.asm.frag
- spirv_cross.cpp
We would force temporaries in unexpected places, causing assertions to
throw if access chains were consumed in such loops.
Fix #1095.
> Do not force temporary unless continue-only for loop dominates.

- reference/shaders-msl-no-opt/asm/frag/modf-frexp-scalar-access-chain-output.asm.frag
- shaders-msl-no-opt/asm/frag/modf-frexp-scalar-access-chain-output.asm.frag
- spirv_msl.cpp
This is not allowed as we cannot take mutable reference to a
vec.{x,y,z,w}. We only care about scalar since entire vectors are fine.
Fix #1096.
> MSL: Deal with Modf/Frexp where output is access chain to scalar.

- spirv_glsl.cpp
- spirv_msl.cpp
> MSL: Cleanup temporary use with emit_uninitialized_temporary.

- spirv_msl.cpp
- spirv_msl.hpp
These methods have largely the same logic, with minor differences. That
I felt compelled to duplicate the logic into another method was one of
the things that bothered me about the variable pointers change. This
cleans that part of the code up; now we don't have two places to change.
> MSL: Unify the get_*_address_space() methods.

- main.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
We were going down a tree of expressions multiple times and this caused
an exponential explosion in time, which was not caught until recently.
Fix this by blocking any traversal going through an ID more than one
time.
This fix overall improves performance by almost an order of magnitude on a
particular test shader rather than slowing it down by ~75x.
Fix #1108.
> Fix severe performance issue with invariant expression invalidation.

- reference/shaders-no-opt/asm/frag/switch-single-case-multiple-exit-cfg.asm.frag
- shaders-no-opt/asm/frag/switch-single-case-multiple-exit-cfg.asm.frag
- spirv_cfg.cpp
Inner scope can still dominate here, so we need to be conservative when
we observe switch blocks specifically. Normal selection merges cannot
merge from multiple paths.
Fix #1110.
> Fix variable scope when switch block exits multiple times.

- reference/shaders-no-opt/asm/frag/combined-image-sampler-dxc-min16float.asm.frag
- shaders-no-opt/asm/frag/combined-image-sampler-dxc-min16float.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
When merging combined image samplers, we only looked at sampler, but DXC
emits RelaxedPrecision only for texture. Does not hurt to check for more
things.
Fix #1132.
> GLSL: Assume image and sampler can be RelaxedPrecision.

- reference/opt/shaders/frag/post-depth-coverage-es.frag
- reference/opt/shaders/frag/post-depth-coverage.frag
- reference/shaders/frag/post-depth-coverage-es.frag
- shaders/frag/post-depth-coverage-es.frag
- spirv_glsl.cpp
ESSL does not support `GL_ARB_post_depth_coverage`. There, we must use
`GL_EXT_post_depth_coverage`. I've added this as a fallback for desktop
as well.
Note that `GL_EXT_post_depth_coverage` also requires the fragment shader
to set `early_fragment_tests` explicitly, while
`GL_ARB_post_depth_coverage` does not. It doesn't really matter either
way, since `SPV_KHR_post_depth_coverage` *also* requires both execution
modes to be explicitly set.
> GLSL: Fix post-depth coverage for ESSL.

- reference/opt/shaders-msl/desktop-only/vert/shader-draw-parameters.desktop.vert
- reference/opt/shaders-msl/vert/no_stage_out.vert
- reference/opt/shaders-msl/vulkan/vert/vulkan-vertex.vk.vert
- reference/shaders-msl-no-opt/vert/functions_nested.vert
- reference/shaders-msl/desktop-only/vert/shader-draw-parameters.desktop.vert
- reference/shaders-msl/vert/no_stage_out.vert
- reference/shaders-msl/vulkan/vert/vulkan-vertex.vk.vert
- spirv_msl.cpp
Totally missed these, so float(index) would not work correctly for
negative numbers.
Fix #1139.
> MSL: Add {Base,}{Vertex,Instance}Index to bitcast_from_builtin_load.

- reference/opt/shaders-hlsl/frag/pixel-interlock-ordered.sm51.fxconly.frag
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- reference/opt/shaders/frag/pixel-interlock-ordered.frag
- reference/opt/shaders/frag/pixel-interlock-unordered.frag
- reference/opt/shaders/frag/sample-interlock-ordered.frag
- reference/opt/shaders/frag/sample-interlock-unordered.frag
- reference/shaders-hlsl/frag/pixel-interlock-ordered.sm51.fxconly.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- reference/shaders/frag/pixel-interlock-ordered.frag
- reference/shaders/frag/pixel-interlock-unordered.frag
- reference/shaders/frag/sample-interlock-ordered.frag
- reference/shaders/frag/sample-interlock-unordered.frag
- shaders-hlsl/frag/pixel-interlock-ordered.sm51.fxconly.frag
- shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- shaders/frag/pixel-interlock-ordered.frag
- shaders/frag/pixel-interlock-unordered.frag
- shaders/frag/sample-interlock-ordered.frag
- shaders/frag/sample-interlock-unordered.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
This was straightforward to implement in GLSL. The
`ShadingRateInterlockOrderedEXT` and `ShadingRateInterlockUnorderedEXT`
modes aren't implemented yet, because we don't support
`SPV_NV_shading_rate` or `SPV_EXT_fragment_invocation_density` yet.
HLSL and MSL were more interesting. They don't support this directly,
but they do support marking resources as "rasterizer ordered," which
does roughly the same thing. So this implementation scans all accesses
inside the critical section and marks all storage resources found
therein as rasterizer ordered. They also don't support the fine-grained
controls on pixel- vs. sample-level interlock and disabling ordering
guarantees that GLSL and SPIR-V do, but that's OK. "Unordered" here
merely means the order is undefined; that it just so happens to be …
> Support the SPV_EXT_fragment_shader_interlock extension.

- spirv_cross_parsed_ir.cpp
Need take care of arguments specially for OpCompositeExtract and OpCompositeInsert.
[OpGroupNonUniformElect.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3576775/OpGroupNonUniformElect.spv.zip)
> Fix ParsedIR::mark_used_as_array_length(uint32_t id)

- reference/opt/shaders-msl/comp/argument-buffers-image-load-store.ios.msl2.argument.comp
- reference/shaders-msl/comp/argument-buffers-image-load-store.ios.msl2.argument.comp
- shaders-msl/comp/argument-buffers-image-load-store.ios.msl2.argument.comp
- spirv_msl.cpp
- spirv_msl.hpp
Writable textures cannot use argument buffers on iOS. They must be
passed as arguments directly to the shader function. Since we won't know
if a given storage image will have the `NonWritable` decoration at the
time we encode the argument buffer, we must therefore pass all storage
images as discrete arguments. Previously, we were throwing an error if
we encountered an argument buffer with a writable texture in it on iOS.
> MSL: Force storage images on iOS to use discrete descriptors.

- main.cpp
- reference/opt/shaders-msl/comp/basic.dynamic-buffer.msl2.comp
- reference/shaders-msl/comp/basic.dynamic-buffer.msl2.comp
- shaders-msl/comp/basic.dynamic-buffer.msl2.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Vulkan has two types of buffer descriptors,
`VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC` and
`VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC`, which allow the client to
offset the buffers by an amount given when the descriptor set is bound
to a pipeline. Metal provides no direct support for this when the buffer
in question is in an argument buffer, so once again we're on our own.
These offsets cannot be stored or associated in any way with the
argument buffer itself, because they are set at bind time.  Different
pipelines may have different offsets set. Therefore, we must use a
separate buffer, not in any argument buffer, to hold these offsets. Then
the shader must manually offset the buffer pointer.
This change fully supports arrays, including arrays of arrays, even
though Vulkan forbids them. …
> MSL: Support dynamic offsets for buffers in argument buffers.

- CMakeLists.txt
- main.cpp
- spirv_cfg.cpp
- spirv_cfg.hpp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_c.cpp
- spirv_cross_parsed_ir.cpp
- spirv_cross_parsed_ir.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- spirv_parser.cpp
- spirv_reflect.cpp
- tests-other/typed_id_test.cpp
The C++ interface has been completely un-typed in its ID-based interfaces. This attempts to introduce some level of type safety into the API by adding a `TypedID<Types>` wrapper class. These types can freely convert to and from uint32_t and a special `ID` type, but not between each other, so a `TypeID` cannot be confused with a `VariableID` for example. Full type safety is not practical as SPIR-V will often allow any kind of ID, especially with decorations.
Free conversion to and from uint32_t is important not to break too many clients. This type safety can mostly be ignored for API users who don't really care about it.
Fix #1093.
Fix #441.
> Introduce stronger types for the SPIR-V ID in C++ API

- CMakeLists.txt
> CMake: Add option to skip installation targets.

- .travis.yml
- CMakeLists.txt
- spirv_cfg.cpp
- spirv_glsl.cpp
> Disable -Werror by default in CMake, fix -Wshorten-64-to-32 warnings.

- CMakeLists.txt
Used by projects who might embed SPIRV-Cross as part of a shared
library, but not exported.
Fix #1157.
> CMake: Add option to force -fPIC.

- reference/opt/shaders/frag/struct-type-unrelated-alias.frag
- reference/shaders-hlsl-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- reference/shaders-msl-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- reference/shaders-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- reference/shaders/frag/struct-type-unrelated-alias.frag
- shaders-hlsl-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- shaders-msl-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- shaders-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- shaders/frag/struct-type-unrelated-alias.frag
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_reflect.cpp
It is possible for a shader to declare two plain struct types which simply share the same OpName without there being an implicit value/buffer alias relationship.
For to_member_name(), make sure to use the type alias master when resolving member names. The member name may be different in a type alias master if the SPIR-V is being intentionally difficult.
Fix #1167.
> Do not consider aliased struct types if the master is not a block

- reference/shaders-msl-no-opt/comp/std140-array-load-composite-construct.comp
- shaders-msl-no-opt/comp/std140-array-load-composite-construct.comp
- spirv_glsl.cpp
Simple fix, just need to use to_unpacked_expression rather than to_expression here to
deal with this.
Fix #1172.
> MSL: Fix regression with OpCompositeConstruct from std140 float[].

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/frag/huge-argument-buffer.device-argument-buffer.argument.msl2.frag
- reference/shaders-msl/frag/huge-argument-buffer.device-argument-buffer.argument.msl2.frag
- shaders-msl/frag/huge-argument-buffer.device-argument-buffer.argument.msl2.frag
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
If there are enough members in an IAB, we cannot use the constant
address space as MSL compiler complains about there being too many
members. Support emitting the device address space instead.
Fix #1170.
> MSL: Add opt-in support for huge IABs.

- reference/opt/shaders-hlsl/asm/comp/bitcast_icmp.asm.comp
- reference/opt/shaders-msl/asm/comp/bitcast_icmp.asm.comp
- reference/opt/shaders/asm/comp/bitcast_icmp.asm.comp
- reference/shaders-hlsl-no-opt/asm/frag/unordered-compare.asm.frag
- reference/shaders-hlsl/asm/comp/bitcast_icmp.asm.comp
- reference/shaders-msl/asm/comp/bitcast_icmp.asm.comp
- reference/shaders-no-opt/asm/frag/unordered-compare.asm.frag
- reference/shaders/asm/comp/bitcast_icmp.asm.comp
- shaders-hlsl-no-opt/asm/frag/unordered-compare.asm.frag
- shaders-hlsl/asm/comp/bitcast_icmp.asm.comp
- shaders-msl/asm/comp/bitcast_icmp.asm.comp
- shaders-no-opt/asm/frag/unordered-compare.asm.frag
- shaders/asm/comp/bitcast_icmp.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
HLSL implementation is partially incomplete for Equal/NotEqual, as there is no way to implement it properly without adding lots of "isnan()" hacks, which would be pretty bad. Punt on this issue for now.
Also fix sign issues for unrolled comparison instructions on HLSL.
Fix #1164.
> Implement unordered compare on GLSL/HLSL.

- .travis.yml
Version was updated to 3.8, so need to change the custom PATH.
> Travis: Update PATH for Python3 on Windows.

- reference/shaders-no-opt/asm/frag/vector-extract-dynamic-spec-constant.asm.frag
- shaders-no-opt/asm/frag/vector-extract-dynamic-spec-constant.asm.frag
- spirv_glsl.cpp
We cannot lower this to a swizzle, keep it dynamically indexed.
Fix #1178.
> Fix OpVectorExtractDynamic with spec constant op index.

- spirv_cfg.cpp
This wasn't really a visible bug, since the DominatorBuilder would resolve this
issue, but it is still a bug.
> CFG: Compute actual immediate dominators.

- spirv_msl.cpp
- spirv_msl.hpp
Add `CompilerMSL::Options::texture_1D_as_2D`.
Metal imposes significant restrictions on 1D textures, including not being
renderable, clearable, or permitting mipmaps. This option allows SPIR-V 1D
textures to be treated as 2D textures to permit this additional behaviour.
App must of course supply the textures to Metal as 2D textures.
> MSL: Support option for treating 1D textures as 2D textures of height 1.

- reference/shaders-no-opt/asm/comp/access-tracking-function-call-result.asm.comp
- shaders-no-opt/asm/comp/access-tracking-function-call-result.asm.comp
- spirv_cross.cpp
We were looking at args[1] after incrementing args array, not before,
which means we tracked garbage.
This is also an out-of-bounds hazard.
Fix #1186.
> Fix broken access tracking for OpFunctionCall results.

- reference/opt/shaders/tese/load-array-of-array.tese
- reference/shaders/tese/load-array-of-array.tese
- shaders/tese/load-array-of-array.tese
- spirv_glsl.cpp
Only one dimension can be unsized and wrong dimension was used for
unrolling purposes.
Fix #1182.
> GLSL: Fix issue with array-of-array inputs in tess.

- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
Report which buffer failed validation as well as which member triggered the error.
Fix #1199.
> HLSL: Improve error reporting for cbuffer layout mismatch

- reference/shaders-msl-no-opt/packing/load-store-col-rows.comp
- shaders-msl-no-opt/packing/load-store-col-rows.comp
- spirv_msl.cpp
Missed a case where we need to swizzle a column to extract the correct type.
Fix #1200.
> MSL: Fix unpacking of column from padded matrix.

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Sometimes it's useful to get automatic binding assignment from the D3D
compiler instead.
Fix #1206.
> HLSL: Add support to remove register() bindings.

- spirv_cross.hpp
MoltenVK tessellation needs to be able to identify when a shader has declared
an output built-in, but does not populate it, in order to keep the expectations
about how intermediary buffers are populated aligned between tessellation stages.
> Expose as public Compiler::update_active_builtins() and has_active_builtin().

- spirv_glsl.cpp
We had a case where loops were marked complex in a cascading fashion
where each loop iteration would discover one new complex loop. This was
a problem with three nested loops.
Fix #1215.
> Mark loop headers as complex as early as possible.

- reference/opt/shaders-msl/comp/image-atomic-automatic-bindings.comp
- reference/opt/shaders-ue4/asm/frag/texture-atomics.asm.frag
- reference/opt/shaders-ue4/asm/frag/texture-atomics.asm.graphics-robust-access.frag
- reference/shaders-msl/comp/image-atomic-automatic-bindings.comp
- reference/shaders-ue4/asm/frag/texture-atomics.asm.frag
- reference/shaders-ue4/asm/frag/texture-atomics.asm.graphics-robust-access.frag
- shaders-msl/comp/image-atomic-automatic-bindings.comp
- spirv_msl.cpp
The Primary decoration was used by the atomic buffer, causing the
texture binding to be potentially overlapping with other resources.
Fix #1219.
> MSL: Fix automatic binding allocation for image atomic buffers.

- reference/opt/shaders-msl/asm/vert/clip-distance-plain-variable.asm.vert
- reference/opt/shaders-msl/desktop-only/vert/clip-cull-distance.desktop.vert
- reference/opt/shaders-msl/frag/clip-distance-varying.frag
- reference/opt/shaders-msl/vert/clip-distance-block.vert
- reference/opt/shaders-ue4/asm/tese/ds-patch-input-fixes.asm.tese
- reference/shaders-msl/asm/vert/clip-distance-plain-variable.asm.vert
- reference/shaders-msl/frag/clip-distance-varying.frag
- reference/shaders-msl/vert/clip-distance-block.vert
- reference/shaders-ue4/asm/tese/ds-patch-input-fixes.asm.tese
- shaders-msl/asm/vert/clip-distance-plain-variable.asm.vert
- shaders-msl/frag/clip-distance-varying.frag
- shaders-msl/vert/clip-distance-block.vert
- spirv_msl.cpp
MSL does not support this, so we have to emulate it by passing it around
as a varying between stages. We use a special "user(clipN)" attribute
for this rather than locN which is used for user varyings.
Fix #1223.
> MSL: Support ClipDistance as an input stage variable.

- spirv_cross_error_handling.hpp
Mark report_and_abort as noreturn.
Fix #1225.
> Fix MSVC warnings when building without exceptions.

- test_shaders.sh
- update_test_shaders.sh
This CL adds the ability to pass options to test_shader.sh. The
update_test_shaders.sh script is then changed to call test_shaders.sh
with the --update flag.
This removes the duplication of code between test_shaders.sh and
update_test_shaders.sh.
> Share test shader script

- reference/opt/shaders/comp/barriers.comp
- reference/opt/shaders/comp/shared.comp
- reference/shaders/comp/barriers.comp
- reference/shaders/comp/shared.comp
- spirv_glsl.cpp
- spirv_msl.cpp
This is implied in both GL and GLES. Emitting memoryBarrierShared() was
based on earlier confusion in the spec which has since been fixed and
clarified.
> Don't emit memoryBarrierShared() in workgroup control barriers.

- reference/opt/shaders/desktop-only/tesc/basic.desktop.sso.tesc
- reference/opt/shaders/desktop-only/tese/triangle.desktop.sso.tese
- reference/opt/shaders/tese/patch-input-array.tese
- reference/shaders/desktop-only/tesc/basic.desktop.sso.tesc
- reference/shaders/desktop-only/tese/triangle.desktop.sso.tese
- reference/shaders/tese/patch-input-array.tese
- shaders/tese/patch-input-array.tese
- spirv_glsl.cpp
Hoist out the hack to make array sizes unsized to a place where we can
differentiate patch variables from control point variables.
> GLSL: Fix array of input patch variables.

- spirv_cross_parsed_ir.cpp
Avoids locale issues and avoids unexpected assertions for non-ASCII
values.
Fix #1244.
> Roll custom versions of isalpha/isalnum.

- reference/shaders-msl-no-opt/asm/comp/copy-logical-2.spv14.asm.comp
- reference/shaders-msl-no-opt/asm/comp/copy-logical.spv14.asm.comp
- reference/shaders-no-opt/asm/comp/copy-logical.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/copy-logical-2.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/copy-logical.spv14.asm.comp
- shaders-no-opt/asm/comp/copy-logical.spv14.asm.comp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
To support this opcode, we need to unroll loads of all member and array indices.
Fix #1247.
> Implement SPIR-V 1.4 OpCopyLogical

- reference/opt/shaders-msl/frag/fragment-component-padding.pad-fragment.frag
- reference/shaders-msl-no-opt/components/fragment-input-component.frag
- reference/shaders-msl-no-opt/components/fragment-output-component.frag
- reference/shaders-msl-no-opt/components/fragment-output-component.pad-fragment.frag
- reference/shaders-msl-no-opt/components/vertex-input-component.vert
- reference/shaders-msl-no-opt/components/vertex-output-component.vert
- reference/shaders-msl/frag/fragment-component-padding.pad-fragment.frag
- shaders-msl-no-opt/components/fragment-input-component.frag
- shaders-msl-no-opt/components/fragment-output-component.frag
- shaders-msl-no-opt/components/fragment-output-component.pad-fragment.frag
- shaders-msl-no-opt/components/vertex-input-component.vert
- shaders-msl-no-opt/components/vertex-output-component.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Vertex inputs and fragment outputs in particular can take Component decorations, and we cannot split out user attributes to deal with this case.
Tessellation is unimplemented, this seems extremely painful to deal with, and not sure what approach to take here.
Fix #1249.
> MSL: Partially implement support for Component decoration in complex scenarios

- reference/shaders-hlsl-no-opt/comp/illegal-struct-name.asm.comp
- reference/shaders-msl-no-opt/comp/illegal-struct-name.asm.comp
- reference/shaders-no-opt/comp/illegal-struct-name.asm.comp
- shaders-hlsl-no-opt/comp/illegal-struct-name.asm.comp
- shaders-msl-no-opt/comp/illegal-struct-name.asm.comp
- shaders-no-opt/comp/illegal-struct-name.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- Fixes issue with clip_distance flattening in MSL where member to
flatten from would come from to_member_name, where it should have used
the builtin name directly. This member name was modified by this patch
and broke clip distance test shaders.
- Some cleanups with ir.meta, use ir.find_meta instead to not create
unnecessary hashmap nodes.
Fix #1232
> Deal with illegal names in types as well.

- CMakeLists.txt
- spirv_cross_containers.hpp
Fixes a linting error from cppcheck where reserve() calls can throw, but
caller is marked noexcept to allow proper move semantics.
Only real place to throw would be if allocations fail, but these
allocations tend to be small, and if allocation actually fails here,
we're basically OOM anyways, so just terminate. Constructors and assignment
could also fail, but the only way that could happen is memory related in
SPIRV-Cross' case, so just terminate if that happens as well.
Also, for good measure, add missing -fno-exceptions to EXCEPTIONS_TO_ASSERTIONS
path in CMake.
Fix #1267.
> Make SmallVector noexcept.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/comp/basic.inline-block.msl2.comp
- reference/shaders-msl/comp/basic.inline-block.msl2.comp
- shaders-msl/comp/basic.inline-block.msl2.comp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Here, the inline uniform block is explicit: we instantiate the buffer
block itself in the argument buffer, instead of a pointer to the buffer.
I just hope this will work with the `MTLArgumentDescriptor` API...
Note that Metal recursively assigns individual members of embedded
structs IDs. This means for automatic assignment that we have to
calculate the binding stride for a given buffer block. For MoltenVK,
we'll simply increment the ID by the size of the inline uniform block.
Then the later IDs will never conflict with the inline uniform block. We
can get away with this because Metal doesn't require that IDs be
contiguous, only monotonically increasing.
> MSL: Support inline uniform blocks in argument buffers.

- CMakeLists.txt
- pkg-config/spirv-cross-c-shared.pc.in
This PR has two semi-related commits.
The first one implements `GNUInstallDirs` like other projects in the KhronosGroup (i.e. `Vulkan-ValidationLayers`).
Reference: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
The second commit removes the hardcoded variables in the pkg-config file and installs it the correct directory. Since it is not an architecture independent pkg-config file it does not belong in `/usr/share/`, but rather the appropriate `CMAKE_INSTALL_LIBDIR` which is added in the previous commit. On Slackware this is `/usr/lib64/` and `/usr/lib/` on 64-bit and 32-bit installs respectively.
I took the liberty of removing `SPIRV_CROSS_INSTALL_LIB_DIR` and `SPIRV_CROSS_INSTALL_INC_DIR` since they are not used or needed after this PR.
Example pkg-config.in file: …
> Add GNUInstallDirs + fixes for the pkg-config file

- CMakeLists.txt
> CMake: Avoid warning when parent project uses VERSION in project().

- spirv_msl.cpp
I cannot find any reference to this flag ever having existed in older
MSL spec documents, and it breaks compilation on any recent SDK for any
iOS/macOS Metal version. Just remove it.
Fix #1274.
> Remove old memory_scope flag from iOS barriers.

- reference/opt/shaders-hlsl/frag/bvec-operations.frag
- reference/shaders-hlsl-no-opt/asm/comp/constant-composite-undef.asm.comp
- reference/shaders-hlsl-no-opt/asm/frag/vector-shuffle-undef-index.asm.frag
- reference/shaders-hlsl/asm/frag/unreachable.asm.frag
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Undef variables would somehow become cbuffer variables without any
warning ...
Fix #1276.
> HLSL: Declare undef variables as static.

- spirv_cross_containers.hpp
- spirv_parser.cpp
SPIR-V spec has a limit of ~4 million, and Vulkan spec does not increase
this bound, so be a bit defensive and fail early.
Fix #1278.
> Reject SPIR-V modules with garbage ID bound.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-hlsl/comp/access-chains.force-uav.comp
- reference/opt/shaders/desktop-only/frag/image-size.frag
- reference/opt/shaders/desktop-only/frag/image-size.no-qualifier-deduction.frag
- reference/shaders-hlsl/comp/access-chains.force-uav.comp
- reference/shaders/desktop-only/frag/image-size.frag
- reference/shaders/desktop-only/frag/image-size.no-qualifier-deduction.frag
- shaders-hlsl/comp/access-chains.force-uav.comp
- shaders/desktop-only/frag/image-size.frag
- shaders/desktop-only/frag/image-size.no-qualifier-deduction.frag
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_parser.cpp
- test_shaders.py
- Allow readonly SSBO to be treated as UAV instead of SRV.
- Remove a very old and forgotten hack which forced automatic deduction of image qualifiers.
- Add option to remove automatic storage qualifier deduction for read-write images. Read-write is kind of awkward and it's very hard to know for sure when source comes from HLSL.
> Improve handling of readonly/writeonly flags in some cases

- reference/opt/shaders-hlsl/frag/readonly-coherent-ssbo.force-uav.frag
- reference/opt/shaders-hlsl/frag/readonly-coherent-ssbo.frag
- reference/shaders-hlsl/frag/readonly-coherent-ssbo.force-uav.frag
- reference/shaders-hlsl/frag/readonly-coherent-ssbo.frag
- shaders-hlsl/frag/readonly-coherent-ssbo.force-uav.frag
- shaders-hlsl/frag/readonly-coherent-ssbo.frag
- spirv_hlsl.cpp
> HLSL: Do not emit globallycoherent for SRV ByteAddressBuffer.

- spirv_msl.cpp
Without this patch, `gl_FragCoord` is not output for subpass reads in certain cases where `gl_FragCoord` is not used elsewhere in the shader.
I'm not sure why this isn't caught by existing tests (e.g. [input-attachment.frag](shaders-msl/frag/input-attachment.frag)), but I encountered this issue in code generated by DXC and passed through spire-opt.
> MSL: mark BuiltInFragCoord as implicitly used for subpass reads

- reference/shaders-msl-no-opt/asm/frag/input-attachment-unused-frag-coord.asm.frag
- shaders-msl-no-opt/asm/frag/input-attachment-unused-frag-coord.asm.frag
- spirv_msl.cpp
We need to make sure any builtins which are declared and unused are
emitted as active variables.
> MSL: Deal with cases where builtin is implicitly needed, declared, but unused

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-hlsl/comp/image.nonwritable-uav-texture.comp
- reference/shaders-hlsl/comp/image.nonwritable-uav-texture.comp
- shaders-hlsl/comp/image.nonwritable-uav-texture.comp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- test_shaders.py
> HLSL: Add support for treating NonWritable UAV texture as SRV instead.

- reference/shaders-msl-no-opt/asm/vert/composite-extract-physical-type-id.asm.vert
- shaders-msl-no-opt/asm/vert/composite-extract-physical-type-id.asm.vert
- spirv_glsl.cpp
Similar reasoning as packed expressions.
Fix #1313.
> MSL: Do not use base expression with PhysicalTypeID OpCompositeExtract.

- CMakeLists.txt
- main.cpp
- spirv_common.hpp
Closes #1315
Just makes sure that clang-cl receives the same settings for warnings as MSVC and disable the same warnings in code.
> Improve compatibility with clang-cl

- reference/opt/shaders-msl/vert/no-disable-vertex-out.frag-output.vert
- reference/shaders-msl/vert/no-disable-vertex-out.frag-output.vert
- shaders-msl/vert/no-disable-vertex-out.frag-output.vert
- spirv_msl.cpp
Forgot to do this in #1319.
Fixes #1322.
> MSL: Only disable output variables in fragment shaders.

- reference/opt/shaders-msl/asm/frag/disable-renamed-output.frag-output.asm.frag
- reference/shaders-msl/asm/frag/disable-renamed-output.frag-output.asm.frag
- shaders-msl/asm/frag/disable-renamed-output.frag-output.asm.frag
- spirv_msl.cpp
DXVK emits SPIR-V where fragment shader builtins have names derived from
DXBC assembly, e.g. `oDepth` for `FragDepth`. When we declared the
disabled output, we used this name, but when referencing it, we
continued to use the GLSL name. This breaks compilation.
> MSL: Force disabled fragment builtins to have the right name.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/asm/vert/clip-distance-plain-variable.no-user-varying.asm.vert
- reference/opt/shaders-msl/desktop-only/vert/clip-cull-distance..no-user-varying.desktop.vert
- reference/opt/shaders-msl/vert/clip-distance-block.no-user-varying.vert
- reference/shaders-msl/asm/vert/clip-distance-plain-variable.no-user-varying.asm.vert
- reference/shaders-msl/desktop-only/vert/clip-cull-distance..no-user-varying.desktop.vert
- reference/shaders-msl/vert/clip-distance-block.no-user-varying.vert
- shaders-msl/asm/vert/clip-distance-plain-variable.no-user-varying.asm.vert
- shaders-msl/desktop-only/vert/clip-cull-distance..no-user-varying.desktop.vert
- shaders-msl/vert/clip-distance-block.no-user-varying.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Only safe if user knows that subsequent shader stage will not read clip
distance.
Fix #1320.
> MSL: Allow removing clip distance user varyings.

- reference/opt/shaders-msl/comp/struct-packing.comp
- reference/shaders-msl-no-opt/asm/packing/scalar-array-float2.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-array-float3-one-element.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-array-float3.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float2x2-col-major.invalid.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float2x2-row-major.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float2x3-col-major.invalid.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float2x3-row-major.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float3x2-col-major.invalid.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float3x2-row-major.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float3x3-col-major.invalid.asm.frag
- reference/shaders-msl-no-opt/asm/packing/scalar-float3x3-row-major.asm.frag
- reference/shaders-msl-no-opt/comp/struct-packing-scalar.nocompat.invalid.vk.comp
- reference/shaders-msl/comp/struct-packing.comp
- shaders-msl-no-opt/asm/packing/scalar-array-float2.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-array-float3-one-element.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-array-float3.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float2x2-col-major.invalid.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float2x2-row-major.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float2x3-col-major.invalid.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float2x3-row-major.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float3x2-col-major.invalid.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float3x2-row-major.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float3x3-col-major.invalid.asm.frag
- shaders-msl-no-opt/asm/packing/scalar-float3x3-row-major.asm.frag
- spirv_msl.cpp
DX may emit ArrayStride and MatrixStride of 16, but the size of the
object does not align with that and expect to pack other members inside
its last member.
The workaround is to emit array size/col/row one less than we expect and
rely on padding to carve out a "dead zone" for the last member.
Fix #1321.
> MSL: Support edge case with DX layout in scalar block layout.

- reference/shaders-msl-no-opt/asm/comp/storage-buffer-basic.invalid.asm.comp
- reference/shaders-msl-no-opt/asm/frag/private-initializer-direct-store.asm.frag
- shaders-msl-no-opt/asm/frag/private-initializer-direct-store.asm.frag
- spirv_glsl.cpp
Do not attempt to defer declaration. It would happen to work in most
cases, but the edge case is where the first thing that happens to a
variable is being OpStore'd into.
Fix #1332.
> MSL: Deal correctly with initializers on Private variables.

- spirv_glsl.cpp
actually for it to work, I'd have to remove (pass through) any `nonuniformEXT` calls in the generated GLSL shader
> Try and solve issue #1327

- reference/shaders-msl-no-opt/asm/comp/bitcast-fp16-fp32.asm.comp
- reference/shaders-no-opt/asm/comp/bitcast-fp16-fp32.asm.vk.comp
- reference/shaders-no-opt/asm/comp/bitcast-fp16-fp32.asm.vk.comp.vk
- shaders-msl-no-opt/asm/comp/bitcast-fp16-fp32.asm.comp
- shaders-no-opt/asm/comp/bitcast-fp16-fp32.asm.vk.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
There is no native formulation, so introduce a concept of a "complex"
bitcast to handle odd-ball cases which have no native unary operation.
Fix #1338.
> GLSL: Support f16x2 <-> f32 bitcast.

- spirv_cross.cpp
Members in nested structs were not properly iterated on,
and as a result, flags like row major for matrices could be
not propagated properly.
> Fixed recursion in combined_decoration_for_member

- spirv_common.hpp
This is triggered when building projects that depend on SPIRV-Cross with
clang-cl on Windows with `-pedantic`
../../third_party/spirv-cross/spirv_common.hpp(781,3): error: enumerator
value is not representable in the underlying type 'int'
[-Werror,-Wmicrosoft-enum-value]
NoDominator = 0xffffffffu
> Fix -Wmicrosoft-enum-value

- reference/shaders-hlsl-no-opt/frag/ubo-offset-out-of-order.frag
- reference/shaders-msl-no-opt/frag/ubo-offset-out-of-order.frag
- reference/shaders-no-opt/vulkan/frag/ubo-offset-out-of-order.vk.nocompat.frag.vk
- shaders-hlsl-no-opt/frag/ubo-offset-out-of-order.frag
- shaders-msl-no-opt/frag/ubo-offset-out-of-order.frag
- shaders-no-opt/vulkan/frag/ubo-offset-out-of-order.vk.nocompat.frag
- spirv_common.hpp
- spirv_msl.cpp
If a buffer rewrites its Offsets, all member references to that struct
are invalidated, and must be redirected, do so in to_member_reference,
but there might be other places where this is needed. Fix as required.
SPIR-V code relying on this is somewhat questionable, but seems to be
in-spec.
Fix #1354.
> MSL: Redirect member indices when buffer has been sorted by Offset.

- reference/shaders-msl/asm/vert/packed-bool-to-uint.asm.vert
- reference/shaders-msl/asm/vert/packed-bool2-to-packed_uint2.asm.vert
- reference/shaders-msl/vert/packed-bool-to-uint.vert
- reference/shaders-msl/vert/packed-bool2-to-packed_uint2.vert
- shaders-msl/asm/vert/packed-bool-to-uint.asm.vert
- shaders-msl/asm/vert/packed-bool2-to-packed_uint2.asm.vert
- shaders-msl/vert/packed-bool-to-uint.vert
- shaders-msl/vert/packed-bool2-to-packed_uint2.vert
- spirv_msl.cpp
Scalar type is already packed in metal.
> Fix #1359: MSL: If the packed type is scalar, don't emit "pack_" prefix.

- reference/opt/shaders-msl/asm/vert/packed-bool-to-uint.asm.vert
- reference/opt/shaders-msl/asm/vert/packed-bool2-to-packed_uint2.asm.vert
- reference/opt/shaders-msl/comp/struct-packing.comp
- reference/opt/shaders-msl/vert/packed-bool-to-uint.vert
- reference/opt/shaders-msl/vert/packed-bool2-to-packed_uint2.vert
- reference/shaders-msl-no-opt/comp/struct-packing-scalar.nocompat.invalid.vk.comp
- reference/shaders-msl/asm/vert/packed-bool-to-uint.asm.vert
- reference/shaders-msl/asm/vert/packed-bool2-to-packed_uint2.asm.vert
- reference/shaders-msl/comp/struct-packing.comp
- reference/shaders-msl/vert/packed-bool-to-uint.vert
- reference/shaders-msl/vert/packed-bool2-to-packed_uint2.vert
- spirv_msl.cpp
Extend the array stride relaxation to non-packed arrays as well, as
long as the array in question contains a single array element.
> MSL: Avoid packed arrays in more cases.

- spirv_hlsl.cpp
- spirv_hlsl.hpp
This change is the enhancement proposed in #1368. A new "per-binding" option flag can be specified and used when the global "all binding" option flag is unset. @HansKristian-Work PTAL, hopefully, this is sufficient.
> HLSL: Add option to treat certain SSBO bindings as UAV

- CMakeLists.txt
- main.cpp
- reference/shaders-hlsl-no-opt/frag/native-16bit-types.fxconly.nofxc.sm62.native-16bit.frag
- shaders-hlsl-no-opt/frag/native-16bit-types.fxconly.nofxc.sm62.native-16bit.frag
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- test_shaders.py
Adds support for templated load/store in SM 6.2 to deal with small
types.
Fix #1381.
> HLSL: Add native support for 16-bit types.

- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.hpp
These are completely unused. Need to keep the members around for ABI
compatbility however ...
Fix #1380 
Fix #1050
> MSL: Remove obsolete MSLVertexAttr members.

- spirv_msl.cpp
While implementing https://github.com/KhronosGroup/MoltenVK/issues/873 I stumbled across this bug.
> Fix missing switch cases in Y'CbCr conversion

- reference/shaders-no-opt/frag/sparse-texture-clamp.desktop.frag
- shaders-no-opt/frag/sparse-texture-clamp.desktop.frag
- spirv_glsl.cpp
Missed these in initial sparse implementation.
> GLSL: Handle the rest of GL_ARB_sparse_texture_clamp.

- spirv_glsl.cpp
gl_InstanceID was introduced in GLSL 1.40, so when generating for older version, it requires an explicit extension.
GL_ARB_draw_instanced provides both gl_InstanceID and gl_InstanceIDARB, so no rename is necessary.
Note that GL_EXT_gpu_shader4 also offers gl_InstanceID, but that extension is not nearly as widely supported as GL_ARB_draw_instanced, according to several OpenGL extension databases I queried.
Thanks for your consideration!
> GLSL: Require GL_ARB_draw_instanced for gl_InstanceID in GLSL < 1.40

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/frag/vecsize-mismatch.shader-inputs.frag
- reference/opt/shaders-msl/vert/signedness-mismatch.shader-inputs.vert
- reference/shaders-msl/frag/vecsize-mismatch.shader-inputs.frag
- reference/shaders-msl/vert/signedness-mismatch.shader-inputs.vert
- shaders-msl/frag/vecsize-mismatch.shader-inputs.frag
- shaders-msl/vert/signedness-mismatch.shader-inputs.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Metal is picky about interface matching. If the types don't match
exactly, down to the number of vector components, Metal fails pipline
compilation. To support pipelines where the number of components
consumed by the fragment shader is less than that produced by the vertex
shader, we have to fix up the fragment shader to accept all the
components produced.
> MSL: Fix up input variables' vector lengths in all stages.

- reference/opt/shaders-msl/comp/composite-array-initialization.force-native-array.comp
- reference/shaders-msl-no-opt/asm/comp/composite-construct-buffer-struct.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-array-load-temporary.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-array-load-temporary.force-native-array.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-constant-array-load-store.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-constant-array-load-store.force-native-array.asm.comp
- reference/shaders-msl-no-opt/comp/array-copy-threadgroup-memory.comp
- reference/shaders-msl-no-opt/vert/pass-array-by-value.force-native-array.vert
- reference/shaders-msl/comp/copy-array-of-arrays.force-native-array.comp
- reference/shaders-msl/vert/return-array.force-native-array.vert
- shaders-msl-no-opt/asm/comp/composite-construct-buffer-struct.asm.comp
- shaders-msl-no-opt/asm/comp/device-array-load-temporary.asm.comp
- shaders-msl-no-opt/asm/comp/device-array-load-temporary.force-native-array.asm.comp
- shaders-msl-no-opt/asm/comp/device-constant-array-load-store.asm.comp
- shaders-msl-no-opt/asm/comp/device-constant-array-load-store.force-native-array.asm.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
Buffer block structs in MSL also need to consider that they do not use value types similar to temporaries and stack variables. Also, fix OpCompositeConstruct when used with buffer types, we will need to conditionally reroll array expression based on the struct type we use.
Fix #1394.
> MSL: Deal with array load-store in buffer-block structs

- spirv_msl.hpp
The [[deprecated]] attribute is supposed to be in front of a typedef,
not after the typedef keyword.
PTAL @HansKristian-Work
> Fix placement of SPIRV_CROSS_DEPRECATED.

- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
Too many issues with deprecated declarations on various compilers, just
get rid of it.
Fix #1399.
> MSL: Remove the old VertexAttr API.

- reference/opt/shaders-msl/frag/for-loop-init.frag
- reference/opt/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
- reference/opt/shaders/frag/for-loop-init.frag
- reference/opt/shaders/frag/selection-block-dominator.frag
- reference/shaders-no-opt/asm/frag/switch-single-case-multiple-exit-cfg.asm.frag
- spirv_glsl.cpp
When we see a switch block which only contains one default block, emit a
do {} while(false) statement instead, which is far more idiomatic and
readable anyways.
Fix #1402.
> HLSL: Workaround FXC bugs with degenerate switch blocks.

- reference/opt/shaders-ue4/asm/frag/subpass-input.ios.framebuffer-fetch.asm.frag
- reference/shaders-msl-no-opt/frag/subpass-input-attachment-index-fallback.msl20.ios.framebuffer-fetch.frag
- reference/shaders-ue4/asm/frag/subpass-input.ios.framebuffer-fetch.asm.frag
- shaders-msl-no-opt/frag/subpass-input-attachment-index-fallback.msl20.ios.framebuffer-fetch.frag
- spirv_msl.cpp
> MSL: Use input attachment index directly for resource index fallback.

- spirv_msl.cpp
This ensures that globals are correctly passed through to functions when their only other use is as the r-value of an assignment expression.
Example HLSL:
```
float2 ReadElement(StructuredBuffer<float2> buf, uint index) {
return buf[index];
}
[[vk::binding(0, 0)]] StructuredBuffer<float2> testBuffer; // In artwork space
float2 ReadFromBuffer(uint index) {
return ReadElement(testBuffer, index);
}
[shader("pixel")]
float4 SPIRVRValue_Test(float4 input) : SV_TARGET0 {
return float4(ReadFromBuffer(0));
}
```
Generated SPIR-V via DXC:
```
; SPIR-V
; Version: 1.3
; Generator: Google spiregg; 0
; Bound: 54
; Schema: 0
OpCapability Shader
OpExtension "SPV_GOOGLE_hlsl_functionality1"
OpExtension "SPV_GOOGLE_user_type"
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %SPIRVRValue_Test …
```
> MSL: Ensure OpStore source operands are marked for inclusion in function arguments

- spirv_common.hpp
- spirv_glsl.hpp
Anonymous structs with initializers apparently fail to compile in MSVC
2013, so just name the structs.
> MSVC 2013: Fix silently broken builds.

- main.cpp
- reference/opt/shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.frag
- reference/opt/shaders-msl/frag/sample-mask-not-used.fixed-sample-mask.frag
- reference/opt/shaders-msl/frag/sample-mask.fixed-sample-mask.frag
- reference/shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.frag
- reference/shaders-msl/frag/sample-mask-not-used.fixed-sample-mask.frag
- reference/shaders-msl/frag/sample-mask.fixed-sample-mask.frag
- shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.frag
- shaders-msl/frag/sample-mask-not-used.fixed-sample-mask.frag
- shaders-msl/frag/sample-mask.fixed-sample-mask.frag
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
In Metal render pipelines don't have an option to set a sampleMask
parameter, the only way to get that functionality is to set the
sample_mask output of the fragment shader to this value directly.
We also need to take care to combine the fixed sample mask with the
one that the shader might possibly output.
> Enabling setting an additional fixed sampleMask in Metal fragment shaders.

- CMakeLists.txt
- main.cpp
- reference/shaders-no-opt/vert/io-blocks.force-flattened-io.vert
- shaders-no-opt/vert/io-blocks.force-flattened-io.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_glsl.cpp
- spirv_glsl.hpp
- test_shaders.py
It is not always desirable to use actual blocks.
A prime example in the case where EXT_shader_io_blocks is not supported
on the target implementation.
Fix #1427.
> GLSL: Add option to force flattening IO blocks.

- reference/opt/shaders-hlsl/asm/comp/block-name-alias-global.asm.comp
- reference/opt/shaders/asm/comp/block-name-alias-global.asm.comp
- reference/opt/shaders/comp/struct-packing.comp
- reference/opt/shaders/desktop-only/comp/enhanced-layouts.comp
- reference/opt/shaders/frag/ubo_layout.frag
- reference/shaders-hlsl-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- reference/shaders-hlsl-no-opt/asm/vert/complex-link-by-name.asm.vert
- reference/shaders-hlsl/asm/comp/block-name-alias-global.asm.comp
- reference/shaders-no-opt/asm/comp/aliased-struct-divergent-member-name.asm.comp
- reference/shaders-no-opt/asm/vert/complex-link-by-name.asm.vert
- reference/shaders-no-opt/asm/vert/complex-link-by-name.force-flattened-io.legacy.asm.vert
- reference/shaders-no-opt/comp/struct-packing-scalar.nocompat.invalid.vk.comp.vk
- reference/shaders/asm/comp/block-name-alias-global.asm.comp
- reference/shaders/comp/struct-packing.comp
- reference/shaders/desktop-only/comp/enhanced-layouts.comp
- reference/shaders/frag/struct-type-unrelated-alias.frag
- reference/shaders/frag/ubo_layout.frag
- shaders-hlsl-no-opt/asm/vert/complex-link-by-name.asm.vert
- shaders-no-opt/asm/vert/complex-link-by-name.asm.vert
- shaders-no-opt/asm/vert/complex-link-by-name.force-flattened-io.legacy.asm.vert
- spirv_glsl.cpp
- spirv_reflect.cpp
Fixes some issues which now allows the same struct type to be declared as just one struct in all cases, not just buffer block / value type aliasing cases. This makes it far easier to link GLSL shaders by name, since type names and member names need to match up exactly.
Fix #1408.
> GLSL/HLSL: Be more exhaustive with aliasing struct type declarations.

- reference/opt/shaders-msl/tesc/matrix-output.multi-patch.tesc
- reference/opt/shaders-msl/tesc/struct-output.multi-patch.tesc
- reference/shaders-msl/tesc/matrix-output.multi-patch.tesc
- reference/shaders-msl/tesc/struct-output.multi-patch.tesc
- shaders-msl/tesc/matrix-output.multi-patch.tesc
- shaders-msl/tesc/struct-output.multi-patch.tesc
- spirv_msl.cpp
Prior to this point, we were treating them as flattened, as they are in
old-style tessellation control shaders, and still are for structs in
new-style shaders. This is not true for outputs; output composites are
not flattened at all. This semantic mismatch broke a Vulkan CTS test.
It should now pass.
> MSL: Fix handling of matrices and structs in the output control point array.

- reference/opt/shaders-hlsl/asm/frag/single-function-private-lut.asm.frag
- reference/opt/shaders-hlsl/asm/frag/texel-fetch-no-lod.asm.frag
- reference/opt/shaders-hlsl/frag/builtins.frag
- reference/opt/shaders-hlsl/frag/complex-expression-in-access-chain.frag
- reference/opt/shaders-hlsl/frag/input-attachment-ms.frag
- reference/opt/shaders-hlsl/frag/sampler-array.frag
- reference/opt/shaders-hlsl/frag/tex-sampling-ms.frag
- reference/opt/shaders-hlsl/frag/texel-fetch-offset.frag
- reference/shaders-hlsl-no-opt/asm/frag/pixel-interlock-callstack.sm51.fxconly.asm.frag
- reference/shaders-hlsl-no-opt/asm/frag/pixel-interlock-control-flow.sm51.fxconly.asm.frag
- reference/shaders-hlsl-no-opt/asm/frag/pixel-interlock-split-functions.sm51.fxconly.asm.frag
- reference/shaders-hlsl-no-opt/frag/frag-coord.frag
- reference/shaders-hlsl-no-opt/frag/native-16bit-types.fxconly.nofxc.sm62.native-16bit.frag
- reference/shaders-hlsl-no-opt/frag/pixel-interlock-simple-callstack.sm51.fxconly.frag
- reference/shaders-hlsl/asm/frag/single-function-private-lut.asm.frag
- reference/shaders-hlsl/asm/frag/texel-fetch-no-lod.asm.frag
- reference/shaders-hlsl/frag/builtins.frag
- reference/shaders-hlsl/frag/complex-expression-in-access-chain.frag
- reference/shaders-hlsl/frag/input-attachment-ms.frag
- reference/shaders-hlsl/frag/input-attachment.frag
- reference/shaders-hlsl/frag/sampler-array.frag
- reference/shaders-hlsl/frag/tex-sampling-ms.frag
- reference/shaders-hlsl/frag/texel-fetch-offset.frag
- shaders-hlsl-no-opt/frag/frag-coord.frag
- spirv_hlsl.cpp
Need to invert it, SM 4.0+ uses W, not 1/W (like Vulkan/GL).
Fix #1443.
> HLSL: Fix FragCoord.w.

- reference/opt/shaders-msl/vulkan/vert/multiview.multiview.nocompat.vk.vert
- reference/opt/shaders-msl/vulkan/vert/multiview.nocompat.vk.vert
- reference/shaders-msl/vulkan/vert/multiview.multiview.nocompat.vk.vert
- reference/shaders-msl/vulkan/vert/multiview.nocompat.vk.vert
- spirv_msl.cpp
Account for a non-zero base instance when calculating the view index and
the "real" instance index. Before, it was likely broken with a non-zero
base instance, since the calculated instance index could be less than
the base instance.
> MSL: Fix multiview view index calculation with a non-zero base instance.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/vulkan/frag/basic.multiview.no-layered.nocompat.vk.frag
- reference/opt/shaders-msl/vulkan/vert/multiview.multiview.no-layered.nocompat.vk.vert
- reference/shaders-msl/vulkan/frag/basic.multiview.no-layered.nocompat.vk.frag
- reference/shaders-msl/vulkan/vert/multiview.multiview.no-layered.nocompat.vk.vert
- shaders-msl/vulkan/frag/basic.multiview.no-layered.nocompat.vk.frag
- shaders-msl/vulkan/vert/multiview.multiview.no-layered.nocompat.vk.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Some older iOS devices don't support layered rendering. In that case,
don't set `[[render_target_array_index]]`, because the compiler will
reject the shader in that case. The client will then have to unroll the
render pass manually.
> MSL: Don't set the layer for multiview if the device doesn't support it.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/frag/input-attachment-ms.arrayed-subpass.msl21.frag
- reference/opt/shaders-msl/frag/input-attachment-ms.multiview.msl21.frag
- reference/opt/shaders-msl/frag/input-attachment.arrayed-subpass.frag
- reference/opt/shaders-msl/frag/input-attachment.frag
- reference/opt/shaders-msl/frag/input-attachment.multiview.frag
- reference/shaders-msl-no-opt/asm/frag/input-attachment-unused-frag-coord.asm.frag
- reference/shaders-msl/frag/input-attachment-ms.arrayed-subpass.msl21.frag
- reference/shaders-msl/frag/input-attachment-ms.multiview.msl21.frag
- reference/shaders-msl/frag/input-attachment.arrayed-subpass.frag
- reference/shaders-msl/frag/input-attachment.frag
- reference/shaders-msl/frag/input-attachment.multiview.frag
- shaders-msl/frag/input-attachment-ms.arrayed-subpass.msl21.frag
- shaders-msl/frag/input-attachment-ms.multiview.msl21.frag
- shaders-msl/frag/input-attachment.arrayed-subpass.frag
- shaders-msl/frag/input-attachment.multiview.frag
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
These need to use arrayed texture types, or Metal will complain when
binding the resource. The target layer is addressed relative to the
Layer output by the vertex pipeline, or to the ViewIndex if in a
multiview pipeline. Unlike with the s/t coordinates, Vulkan does not
forbid non-zero layer coordinates here, though this cannot be expressed
in Vulkan GLSL. I wonder, then, if non-zero layer coordinates were even
intended to be supported.
Supporting 3D textures will require additional work. Part of the problem
is that Metal does not allow texture views to subset a 3D texture, so we
need some way to pass the base depth to the shader.
> MSL: Support layered input attachments.

- reference/shaders-no-opt/comp/specialization-constant-evaluation.comp
- shaders-no-opt/comp/specialization-constant-evaluation.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
In some cases, we need to get a literal value from a spec constant op.
Mostly relevant when emitting buffers, so implement a 32-bit integer
scalar subset of the evaluator. Can be extended as needed to support
evaluating any specialization constant operation.
Fix #1462.
> Implement a simple evaluator of specialization constants.

- reference/opt/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
- reference/shaders-no-opt/asm/frag/early-conditional-return-switch.asm.frag
- shaders-no-opt/asm/frag/early-conditional-return-switch.asm.frag
- spirv_glsl.cpp
`to_condition` is a bit overloaded and we could end up in a scenario where both branches takes would be considered a "break". This is wrong and lead to subtle bugs when conditionally breaking out of a switch construct.
Fix #1465.
> Clean up and fix awkward conditional branch codegen.

- reference/opt/shaders-msl/vulkan/frag/demote-to-helper-forwarding.asm.vk.nocompat.msl23.frag
- reference/opt/shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl23.frag
- reference/opt/shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl23.ios.frag
- reference/shaders-msl/vulkan/frag/demote-to-helper-forwarding.asm.vk.nocompat.msl23.frag
- reference/shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl23.frag
- reference/shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl23.ios.frag
- shaders-msl/vulkan/frag/demote-to-helper-forwarding.asm.vk.nocompat.msl23.frag
- shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl23.frag
- shaders-msl/vulkan/frag/demote-to-helper.vk.nocompat.msl23.ios.frag
- spirv_msl.cpp
- test_shaders.py
MSL 2.3 has everything needed to support this extension on all
platforms. The existing `discard_fragment()` function was given demote
semantics, similar to Direct3D, and the `simd_is_helper_thread()`
function was finally added to iOS.
I've left the old test alone. Should I remove it in favor of these?
> MSL: Support SPV_EXT_demote_to_helper_invocation for MSL 2.3.

- reference/opt/shaders-msl/comp/image-atomic-automatic-bindings.argument.msl2.comp
- reference/opt/shaders-ue4/asm/frag/texture-atomics.asm.argument.msl2.frag
- reference/shaders-msl/comp/image-atomic-automatic-bindings.argument.msl2.comp
- reference/shaders-ue4/asm/frag/texture-atomics.asm.argument.msl2.frag
- shaders-msl/comp/image-atomic-automatic-bindings.argument.msl2.comp
- shaders-ue4/asm/frag/texture-atomics.asm.argument.msl2.frag
- spirv_msl.cpp
This was not added when Epic contributed atomic image support.
Fixes #1484.
> MSL: Support atomic access to images from argument buffers.

- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- spirv_msl.cpp
Something I noticed working on #1486.
> MSL: Add missing interlock handling to atomic image buffers.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/comp/image-atomic-automatic-bindings.argument.msl2.comp
- reference/opt/shaders-msl/comp/image-atomic-automatic-bindings.comp
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- reference/shaders-msl/comp/image-atomic-automatic-bindings.argument.msl2.comp
- reference/shaders-msl/comp/image-atomic-automatic-bindings.comp
- reference/shaders-msl/frag/pixel-interlock-ordered.msl2.argument.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl2.frag
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
Fix reversed coordinates: `y` should be used to calculate the row
address. Align row address to the row stride.
Honestly, I don't know how this worked at all for Epic. It definitely
didn't work in the CTS prior to this.
> MSL: Fix calculation of atomic image buffer address.

- reference/opt/shaders-msl/tesc/reload-tess-level.multi-patch.tesc
- reference/opt/shaders-msl/tesc/reload-tess-level.tesc
- reference/shaders-msl/tesc/reload-tess-level.multi-patch.tesc
- reference/shaders-msl/tesc/reload-tess-level.tesc
- shaders-msl/tesc/reload-tess-level.multi-patch.tesc
- shaders-msl/tesc/reload-tess-level.tesc
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
`half` cannot be bitcasted to `float`, because the two types are not the
same size. Use an expanding cast instead.
> MSL: Don't use a bitcast for tessellation levels in tesc shaders.

- spirv_glsl.cpp
Be similar to MSL backend here.
> GLSL: Use need_transpose when checking for non-native matrix.

- reference/opt/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
- reference/opt/shaders/frag/ubo-load-row-major-workaround.frag
- reference/opt/shaders/legacy/vert/transpose.legacy.vert
- reference/opt/shaders/vert/read-from-row-major-array.vert
- reference/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
- reference/shaders/frag/ubo-load-row-major-workaround.frag
- reference/shaders/legacy/vert/transpose.legacy.vert
- reference/shaders/vert/read-from-row-major-array.vert
- shaders/frag/ubo-load-row-major-workaround.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
Fix needs to be verified to be effective for this PR to be considered for merging.
Fix #1491.
> GLSL: Support a workaround for loading row-major matrices

- reference/opt/shaders-msl/frag/post-depth-coverage.msl23.frag
- reference/shaders-msl/frag/post-depth-coverage.msl23.frag
- shaders-msl/frag/post-depth-coverage.msl23.frag
- spirv_msl.cpp
It's still only supported on Apple GPUs, but Macs will have those soon.
> MSL: Allow post-depth coverage on Mac in MSL 2.3.

- spirv_common.hpp
C++20 has different overload resolution rules for comparison operators, which breaks some old code.
- [Code compiles ok on c++17 but fails on c++20](https://godbolt.org/z/458eaP)
- [Simply delete those operators seems to make the compiler happy](https://godbolt.org/z/MvKq14)
> fixed compile error with -std=c++20.

- reference/opt/shaders-msl/frag/sampler-compare-bias.msl23.1d-as-2d.frag
- reference/opt/shaders-msl/frag/sampler-compare-cascade-gradient.msl23.frag
- reference/shaders-msl/frag/sampler-compare-bias.msl23.1d-as-2d.frag
- reference/shaders-msl/frag/sampler-compare-cascade-gradient.msl23.frag
- shaders-msl/frag/sampler-compare-bias.msl23.1d-as-2d.frag
- shaders-msl/frag/sampler-compare-cascade-gradient.msl23.frag
- spirv_msl.cpp
I kept the code to replace constant zero arguments, because `Bias`
and `Grad` still have some problems on desktop GPUs.
`Bias` works on AMD GPUs. `Grad` does not. Both work on Intel. Still
needs testing on NV. It will definitely work with Apple GPUs.
Curiously, `texture()` in GLSL has no overload that accepts both
`sampler2DArrayShadow` and a bias argument. But, it does have a
`sampler1DArrayShadow` with bias overload.
> MSL: Allow Bias and Grad arguments with comparison on Mac in MSL 2.3.

- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
MSL: Support run-time sized image and sampler arrays
(GL_EXT_nonuniform_qualifier/SPV_EXT_descriptor_indexing).
MSL does not natively support unsized arrays.
MSLResourceBinding includes array size through API, and substitutes
in that size if the image or sampler array is not explicitly sized.
Also includes fix to support SPIRCombinedImageSampler type in OpCopyObject in MSL.
I couldn't come up with any simple automated tests to add for these changes.
> MSL: Support run-time sized image and sampler arrays

- reference/shaders-reflection/comp/function-pointer.invalid.asm.comp.json
- shaders-reflection/comp/function-pointer.invalid.asm.comp
- spirv_parser.cpp
Possible to receive a function prototype here. Don't try to do anything
smart here, just don't crash during parsing.
Fix #1510.
> Parser: Don't assume OpTypePointer will always take a SPIRType.

- CMakeLists.txt
- main.cpp
- reference/shaders-hlsl-no-opt/vert/flatten-matrix-input.flatten-matrix-vertex-input.vert
- shaders-hlsl-no-opt/vert/flatten-matrix-input.flatten-matrix-vertex-input.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- test_shaders.py
Helps translation layers where we expect inputs to be multiple float
vectors rather than an indexed matrix.
Fix #1512.
> HLSL: Add option to flatten matrix vertex input semantics.

- reference/opt/shaders-hlsl/frag/tex-sampling.sm30.frag
- reference/shaders-hlsl/frag/tex-sampling.sm30.frag
- spirv_hlsl.cpp
In DX9, all samples of a depth texture result in a depth comparison (in fact, disabling this requires use of the special `INTZ` format, only available on DX10+ hardware).  This works with all 4-component texture sample functions (tex2Dlod, tex2Dbias, tex2Dproj).
This PR provides access to this functionality by enabling use of the Dref texture sample instruction and passing in the depth compare value into the appropriate register.  It assumes that there is indeed a depth texture bound to the appropriate register (which is the application's responsibility, and not something we can check).
Even though the regular `texld` instruction does support this as well, HLSL does not (to my knowledge) allow access to this variant since `tex2D` only accepts 2 coordinates.  To work around this, this PR …
> HLSL: Support depth comparison texture sampling in SM 2/3.

- spirv_hlsl.cpp
According to the [HLSL documentation](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-round), `round()` always rounds .5 to the nearest even integer.  This would satisfy the specification of both the GLSL `round()` and `roundEven()` functions (the former not being specific about rounding, and the latter matching the HLSL behaviour).
I have verified experimentally that FXC, targeting SM 4.0 and higher, does indeed emit a [round_ne](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/round-ne--sm4---asm-) instruction for `round()`.  Older shader models do not have this instruction, and FXC instead emits the equivalent of `floor(x + 0.5)`.  Hence I've added a version check accordingly.
I figured this didn't need a special test (I did verify manually that …
> HLSL: Support roundEven() in HLSL SM 4.0 and above

- reference/shaders-msl-no-opt/asm/frag/image-gather.asm.frag
- reference/shaders-msl-no-opt/frag/image-gather.frag
- reference/shaders-no-opt/frag/image-gather.frag
- shaders-msl-no-opt/asm/frag/image-gather.asm.frag
- shaders-msl-no-opt/frag/image-gather.frag
- shaders-no-opt/frag/image-gather.frag
- spirv_msl.cpp
It was not always possible to get backing variable for a late-combined
image sampler.
Supersedes #1526.
> MSL: Fix regression in image gather handling.

- reference/opt/shaders/legacy/fragment/explicit-lod.legacy.vert
- reference/opt/shaders/legacy/vert/implicit-lod.legacy.vert
- reference/shaders/legacy/fragment/explicit-lod.legacy.vert
- reference/shaders/legacy/vert/implicit-lod.legacy.vert
- shaders/legacy/fragment/explicit-lod.legacy.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
The change in #148 was made with the faulty assumption that textureLod was not supported in legacy GLSL vertex shaders.  
However, LOD sampling in the vertex shader has actually been available in both GLSL and ESSL from the beginning.  See section 8.7 of the [GLSL 1.10 spec](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.1.10.pdf) and [ESSL 1.00 spec](https://www.khronos.org/files/opengles_shading_language.pdf).
The [GL_ARB_shader_texture_lod](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_texture_lod.txt) and [GL_EXT_shader_texture_lod](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_shader_texture_lod.txt) extensions extend the use of these existing functions to fragment shaders, and introduce the Grad variants to both vertex and fragment …
> GLSL: Fix support for textureLod in legacy vertex shaders

- reference/opt/shaders/legacy/vert/transpose.legacy.vert
- reference/shaders/legacy/vert/transpose.legacy.vert
- shaders/legacy/vert/transpose.legacy.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
GLSL 1.10 and ESSL 1.00 do not have `transpose()`.  However, it can be easily emulated—in most cases by flipping the `need_transpose` flag (which may just result in flipping multiplication order somewhere), or otherwise using a helper function.  It is made simpler by the fact that these versions only support square matrices, which leaves only three types to support.
I've followed the example of the HLSL inverse implementation for the helper function.
I do wonder if we should just handle OpTranspose this way for the other versions as well, as an optimisation, but that is outside the scope of this PR.  There are also other operations that are unnecessarily resolving the `need_transpose` (such as matrix-scalar multiplication, which could be performed without transposing the matrix).
> GLSL: implement transpose() in GLSL 1.10 / ES 1.00

- reference/opt/shaders/frag/round-even.frag
- reference/opt/shaders/frag/round.frag
- reference/opt/shaders/legacy/fragment/round.legacy.frag
- reference/shaders/frag/round-even.frag
- reference/shaders/frag/round.frag
- reference/shaders/legacy/fragment/round.legacy.frag
- shaders/frag/round-even.frag
- shaders/frag/round.frag
- shaders/legacy/fragment/round.legacy.frag
- spirv_glsl.cpp
Despite some drivers supporting it, `round()` isn't mentioned in any of the legacy GLSL versions' specs.  The SPIR-V spec says that the rounding direction is implementation-defined, so it should be safe to fall back to `floor(x + 0.5)`.
Also, the `round()` function given by [GL_EXT_gpu_shader4](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_gpu_shader4.txt) guarantees round-to-even semantics: 
>     Returns a value equal to the closest integer to x. If the fractional
>     portion of the operand is 0.5, the nearest even integer is returned. For
>     example, round (1.0) returns 1.0.  round(-1.5) returns -2.0. round(3.5)
>     and round (4.5) both return 4.0.
So, in legacy desktop GLSL, I've added a fallback to that extension for roundEven.  (I would've added a test, but the …
> GLSL: Provide round/roundEven for legacy GLSL

- reference/opt/shaders-msl/asm/frag/pull-model-interpolation.asm.msl23.frag
- reference/shaders-msl/asm/frag/pull-model-interpolation.asm.msl23.frag
- shaders-msl/asm/frag/pull-model-interpolation.asm.msl23.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_msl.cpp
- spirv_msl.hpp
New in MSL 2.3 is a template that can be used in the place of a scalar
type in a stage-in struct. This template has methods which interpolate
the varying at the given points. Curiously, you can't set interpolation
attributes on such a varying; perspective-correctness is encoded in the
type, while interpolation must be done using one of the methods. This
makes using this somewhat awkward from SPIRV-Cross, requiring us to jump
through a bunch of hoops to make this all work.
Using varyings from functions in particular is a pain point, requiring
us to pass the stage-in struct itself around. An alternative is to pass
references to the interpolants; except this will fall over badly with
composite types, which naturally must be flattened.  As with
tessellation, dynamic indexing isn't supported …
> MSL: Support pull-model interpolation on MSL 2.3+.

- reference/shaders-msl/frag/subgroup-globals-extract.msl22.frag
- shaders-msl/frag/subgroup-globals-extract.msl22.frag
- spirv_msl.cpp
The test illustrates the issue with hard-coded global arguments for some subgroup operations - they were not inherited by callers.
Fixes #1513.
> MSL: extract global variables from subgroup ballot operations

- spirv_msl.cpp
`min_lod_clamp()` was actually added in MSL 2.2 on iOS 13. The
restriction was based on the beta versions which didn't have it. Since
the beta versions didn't support family 6, this leads me to suspect that
the reason they lacked `min_lod_clamp()` is that it requires family 6.
This does not seem to be documented anywhere.
`simd_is_helper_thread()` was added in MSL 2.3 to iOS. I neglected to
update this when I finished up `SPV_EXT_demote_to_helper_invocation`.
`barycentric_coord` and `primitive_id` were added in MSL 2.3 on iOS 14.
They are only supported on family 7.
> MSL: Expose some more features on iOS.

- spirv_glsl.cpp
This extension require is missing when using double vertex inputs with pre-4.10 versions.
> GLSL: Require GL_ARB_vertex_attrib_64bit for double input in pre-4.10

- CMakeLists.txt
Using CMake 3.19, this deprecation warning appears:
```
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
According to https://cmake.org/cmake/help/latest/release/3.19.html#id16:
> Compatibility with versions of CMake older than 2.8.12 is now deprecated and will be removed from a future version. Calls to cmake_minimum_required() or cmake_policy() that set the policy version to an older value now issue a deprecation diagnostic.
> CMake: Set minimum required version to 3.0

- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.fixed-subgroup.comp
- spirv_msl.cpp
This was based on my misreading the spec. The Vulkan CTS expects the
bits to be set, even if the invocations corresponding to them are
inactive.
> MSL: Don't mask off inactive bits in ballot masks.

- reference/shaders-msl-no-opt/vert/unused-subgroup-builtin.msl22.vert
- shaders-msl-no-opt/vert/unused-subgroup-builtin.msl22.vert
- spirv_msl.cpp
This is necessary to avoid invalid output because of how implicit dependencies on builtins work.
For example, the fixup for `BuiltInSubgroupEqMask` initializes the variable based on `builtin_subgroup_invocation_id_id`, a field storing the ID for a variable with decoration `BuiltInSubgroupLocalInvocationId`.  This could be either a variable that already exists in the input (spirv_msl.cpp:300) or, if necessary, a newly created one (spirv_msl.cpp:621).  In both cases, though, `builtin_subgroup_invocation_id_id` is only set under the condition `need_subgroup_mask || needs_subgroup_invocation_id`.  `need_subgroup_mask` is true if any of the `BuiltInSubgroupXXMask` are set in `active_input_builtins`.
Normally, if the program contains `BuiltInSubgroupEqMask`, `Compiler::ActiveBuiltinHandler` …
> spirv_msl: Don't add fixup hooks for builtin variables if they're unused.

- spirv_msl.cpp
Found used in the wild by Wolfenstein II.
> MSL: Added fmin3 and fmax3 library functions to the illegal name list.

- CMakeLists.txt
- main.cpp
- spirv_cfg.cpp
- spirv_cfg.hpp
- spirv_common.hpp
- spirv_cpp.cpp
- spirv_cpp.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_cross_containers.hpp
- spirv_cross_error_handling.hpp
- spirv_cross_parsed_ir.cpp
- spirv_cross_parsed_ir.hpp
- spirv_cross_util.cpp
- spirv_cross_util.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- spirv_parser.cpp
- spirv_parser.hpp
- spirv_reflect.cpp
- spirv_reflect.hpp
With the Khronos CLA in place since the beginning and approvals from Khronos, this adds Apache 2.0 + MIT dual licensing, which fixes compatibility with LGPLv2.
> Add MIT dual license for the SPIRV-Cross API and CLI.

- spirv_msl.cpp
According to the Metal Shading Language Specification, it's not supported for vertex functions in any Metal version, only fragment and kernel functions.
> msl: Don't try to use [[thread_index_in_simdgroup]] in vertex shaders.

- reference/shaders-hlsl-no-opt/frag/nonuniform-constructor.sm51.fxconly.frag
- reference/shaders-msl-no-opt/frag/nonuniform-constructor.msl2.frag
- reference/shaders-no-opt/asm/frag/nonuniform-qualifier-propagation.vk.nocompat.asm.frag.vk
- reference/shaders-no-opt/frag/nonuniform-constructor.vk.nocompat.frag.vk
- shaders-hlsl-no-opt/frag/nonuniform-constructor.sm51.fxconly.frag
- shaders-msl-no-opt/frag/nonuniform-constructor.msl2.frag
- shaders-no-opt/frag/nonuniform-constructor.vk.nocompat.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
Need to emit nonuniformEXT(sampler2D()) since constructor expressions in
Vulkan GLSL do not propgate the nonuniform qualifier.
Fix #1558.
> GLSL: Emit nonuniformEXT in correct place for late-combined samplers.

- reference/shaders-hlsl-no-opt/asm/frag/reserved-function-identifier.asm.frag
- reference/shaders-msl-no-opt/asm/frag/fixup-entry-point-identifier.nomain.asm.frag
- reference/shaders-msl-no-opt/asm/frag/reserved-function-identifier.asm.frag
- reference/shaders-no-opt/asm/frag/reserved-function-identifier.asm.frag
- shaders-hlsl-no-opt/asm/frag/reserved-function-identifier.asm.frag
- shaders-msl-no-opt/asm/frag/fixup-entry-point-identifier.nomain.asm.frag
- shaders-msl-no-opt/asm/frag/reserved-function-identifier.asm.frag
- shaders-no-opt/asm/frag/reserved-function-identifier.asm.frag
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
We only considered invalid names, and overwrote the alias for the
function. The correct fix is to replace illegal names early, do the
reserved fixup, then copy back alias to entry point name.
Also fixes a minor bug with reserved identifier handling for SPIRFunction.
Fix #1571.
> MSL: Fix broken reserved identifier handling for entry points

- CMakeLists.txt
Compiles fine with just -std=c++11.
Fix #1574.
> CMake: Disable compiler extensions explicitly.

- reference/shaders-hlsl-no-opt/asm/vert/block-struct-initializer.asm.vert
- reference/shaders-hlsl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- reference/shaders-msl-no-opt/asm/vert/block-struct-initializer.asm.vert
- reference/shaders-msl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- reference/shaders-no-opt/asm/vert/block-struct-initializer.asm.vert
- reference/shaders-no-opt/asm/vert/builtin-output-initializer.asm.vert
- shaders-hlsl-no-opt/asm/vert/block-struct-initializer.asm.vert
- shaders-hlsl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- shaders-msl-no-opt/asm/vert/block-struct-initializer.asm.vert
- shaders-msl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- shaders-no-opt/asm/vert/block-struct-initializer.asm.vert
- shaders-no-opt/asm/vert/builtin-output-initializer.asm.vert
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
- spirv_msl.cpp
Fixes many edge cases around initialization of Output variables which are of block or builtin type.
Fix #1568.
> Improve handling of complex variable initialization

- reference/opt/shaders-msl/asm/vert/fake-builtin-input.asm.vert
- reference/opt/shaders/asm/vert/empty-io.asm.vert
- reference/shaders-hlsl-no-opt/asm/frag/only-initializer-frag-depth.asm.frag
- reference/shaders-hlsl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- reference/shaders-msl-no-opt/asm/frag/only-initializer-frag-depth.asm.frag
- reference/shaders-msl-no-opt/asm/tesc/builtin-control-point-initializer.asm.tesc
- reference/shaders-msl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- reference/shaders-msl-no-opt/asm/vert/duplicate-view-index.asm.vert
- reference/shaders-msl-no-opt/vert/uninitialized-vertex-output.vert
- reference/shaders-msl/asm/vert/fake-builtin-input.asm.vert
- reference/shaders-no-opt/asm/frag/only-initializer-frag-depth.asm.frag
- reference/shaders-no-opt/asm/tesc/array-of-block-output-initializer.asm.tesc
- reference/shaders-no-opt/asm/vert/builtin-output-initializer.asm.vert
- reference/shaders/asm/vert/empty-io.asm.vert
- shaders-hlsl-no-opt/asm/frag/only-initializer-frag-depth.asm.frag
- shaders-msl-no-opt/asm/frag/only-initializer-frag-depth.asm.frag
- shaders-msl-no-opt/asm/tesc/builtin-control-point-initializer.asm.tesc
- shaders-msl-no-opt/asm/vert/builtin-output-initializer.asm.vert
- shaders-msl-no-opt/asm/vert/duplicate-view-index.asm.vert
- shaders-msl-no-opt/vert/uninitialized-vertex-output.vert
- shaders-no-opt/asm/frag/only-initializer-frag-depth.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_msl.cpp
- Only consider builtin variables if they are part of IO interface. It was possible for builtins to be registers multiple times as we only looked at active_builtins and not if the variable was active in the entry point.
- Ensure that initialized builtin outputs (but not accessed) were also considered active.
- Always enable outputs from non-fragment stages as fragment stage can read the variable, and this invokes undefined behavior.
Fix #1586.
Fix #1580.
> Refactor active variable consideration

- spirv_cross.hpp
Used with MSL to determine whether to compile with invariance preserved.
> Expose position invariance.

- spirv_hlsl.cpp
> HLSL: Add vector to illegal names list.

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
> c: Add missing IOS_SUPPORT_BASE_VERTEX_INSTANCE option.

- reference/shaders-msl-no-opt/asm/tesc/tess-level-read-write-in-function-tri.asm.tesc
- reference/shaders-msl-no-opt/tesc/tess-level-read-write-in-function-quad.tesc
- shaders-msl-no-opt/asm/tesc/tess-level-read-write-in-function-tri.asm.tesc
- shaders-msl-no-opt/tesc/tess-level-read-write-in-function-quad.tesc
- spirv_msl.cpp
Need to rewrite array size depending on execution mode.
Fix #1608.
> MSL: Fixup type when using tessellation levels in TESC functions.

- gn/BUILD.gn
error:
clang-cl: error: unknown argument ignored in clang-cl: '-fno-exceptions'
> Fix build errors on Windows

- reference/shaders-msl-no-opt/tese/builtin-input-automatic-attribute-assignment.tese
- shaders-msl-no-opt/tese/builtin-input-automatic-attribute-assignment.tese
- spirv_msl.cpp
- spirv_msl.hpp
get_ordered_member_location is broken when we mix and match user locations. User locations *must* be present in SPIR-V.
Fix #1618.
> MSL: Fix automatic assign of builtin attributes in tessellation

- reference/shaders-msl-no-opt/asm/vert/pointer-to-pointer.asm.vert
- shaders-msl-no-opt/asm/vert/pointer-to-pointer.asm.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
There might be more cases to consider, but this should take care of the common cases.
Pointer-to-pointer is very rare and cannot happen for resources, only variable expressions, so the scope to consider should be somewhat limited.
Also makes sure to set pointer_depth properly when we synthesize pointer types, it matters now since type_is_pointer needs to know.
Fix #1628.
> MSL: Deal with pointer-to-pointer qualifier ordering.

- spirv_parser.cpp
> Throw if SPIR-V module has no entry points.

- reference/shaders-no-opt/asm/frag/array-builtin-bitcast-load-store.asm.frag
- shaders-no-opt/asm/frag/array-builtin-bitcast-load-store.asm.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
Need special workarounds to handle array load/store since array size is
unsized in GLSL, and array copy is not possible.
Also, consider bitcast for scalar loads and stores.
Fix #1626.
> GLSL: Handle complex load/store scenarios to gl_SampleMask.

- spirv_msl.cpp
[Metal Shading Language Specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) states that:
> Note: As of Metal 2.3, Metal supports buffers that contain long or ulong data types.
This PR aims to support long and ulong data types in buffers for Metal 2.3+.
> MSL: Support long ulong types in buffers in 2.3+.

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
Add missing C API to update and query active builtins to fix https://github.com/KhronosGroup/SPIRV-Cross/issues/1649
> c: Add missing API to update and query active builtins.

- spirv_msl.cpp
- spirv_msl.hpp
If `CompilerMSL::Options::pad_argument_buffer_resources` enabled, Metal argument buffer
struct members are positionally aligned to their argument indexes by adding synthetic
padding members when needed. The types and sizes of these synthetic members are
identified in the `resource_bindings` vector provided through the API.
Add `CompilerMSL::Options::pad_argument_buffer_resources` to enable padding
Metal argument buffer structs to positionally match members to argument indexes.
Add `MSLResourceBinding::base_type` to identify resource type through API.
> MSL: Support padding Metal argument buffer entries based on argument index.

- reference/opt/shaders-hlsl/frag/nonuniform-qualifier.nonuniformresource.sm51.frag
- reference/opt/shaders-msl/frag/nonuniform-qualifier.msl2.frag
- reference/opt/shaders/vulkan/frag/nonuniform-qualifier.vk.nocompat.frag.vk
- reference/shaders-hlsl-no-opt/asm/frag/nonuniform-qualifier-propagation.nonuniformresource.sm51.asm.frag
- reference/shaders-hlsl-no-opt/asm/frag/nonuniform-ssbo.sm51.nonuniformresource.asm.frag
- reference/shaders-hlsl/frag/nonuniform-qualifier.nonuniformresource.sm51.frag
- reference/shaders-msl/frag/nonuniform-qualifier.msl2.frag
- reference/shaders-no-opt/asm/comp/nonuniform-bracket-handling.vk.nocompat.asm.comp.vk
- reference/shaders-no-opt/asm/frag/nonuniform-ssbo.nocompat.vk.asm.frag.vk
- reference/shaders/vulkan/frag/nonuniform-qualifier.vk.nocompat.frag.vk
- shaders-hlsl-no-opt/asm/frag/nonuniform-ssbo.sm51.nonuniformresource.asm.frag
- shaders-hlsl/frag/nonuniform-qualifier.nonuniformresource.sm51.frag
- shaders-no-opt/asm/comp/nonuniform-bracket-handling.vk.nocompat.asm.comp
- shaders-no-opt/asm/frag/nonuniform-ssbo.nocompat.vk.asm.frag
- shaders/vulkan/frag/nonuniform-qualifier.vk.nocompat.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
Remove all shenanigans with propagation, and only consume nonuniform
qualifiers exactly where needed (last minute).
Fix #1607.
> Rewrite how non-uniform qualifiers are handled.

- reference/shaders-hlsl-no-opt/comp/subgroups.invalid.nofxc.sm60.comp
- shaders-hlsl-no-opt/comp/subgroups.invalid.nofxc.sm60.comp
- spirv_hlsl.cpp
WaveReadLaneAt is no longer restricted to dynamically uniform index,
so can implement the other shuffle ops.
Fix #1659.
> HLSL: Support Shuffle wave ops.

- spirv_msl.cpp
Padding for Metal argument buffers should not double-count `SampledImages`.
This is a minor last minute patch for MoltenVK SDK release tomorrow (Tuesday) that does not impact anything other than MoltenVK's use of padding on Metal argument buffers.
If this is good, can we pull it into SPIRV-Cross Tuesday morning, so that it can propagate through MoltenVK to the Vulkan SDK build this week?
Apologies for the last minute rush. It showed up during final build testing.
> MSL: Minor last minute patch for MoltenVK Vulkan SDK release tomorrow (Tuesday) - RUSH

- README.md
Trivial. Fix C sample code in README.md.
- `spvc_compiler_create_compiler_options` takes `spvc_compiler`, not context
- `compiler` → `compiler_glsl`
> Fix C sample code in README.md

- reference/opt/shaders-hlsl/asm/frag/inf-nan-constant.asm.frag
- reference/opt/shaders-msl/asm/frag/inf-nan-constant.asm.frag
- reference/opt/shaders/asm/frag/inf-nan-constant-double.asm.frag
- reference/opt/shaders/asm/frag/inf-nan-constant.asm.frag
- reference/shaders-hlsl/asm/frag/inf-nan-constant.asm.frag
- reference/shaders-msl/asm/frag/inf-nan-constant.asm.frag
- reference/shaders/asm/frag/inf-nan-constant-double.asm.frag
- reference/shaders/asm/frag/inf-nan-constant.asm.frag
- spirv_glsl.cpp
Outputs like:
glsl: `float v = uintBitsToFloat(0xff800000u /* -inf */);`
msl: `float v = as_type<float>(0x7f800000u /* inf */);`
> Add comment after inf/nan float number for clarifying.

- spirv_common.hpp
Since C++11 the generation of implicit copy constructor is deprecated if
the type has a user-defined constructor or destructor (even if defaulted).
Fix this by adding a defaulted copy-constructor for IVariant that remove
the implicit default constructor, so add it too.
> Fix IVariant -Wdeprecated-copy-with-dtor

- reference/opt/shaders-hlsl/asm/comp/bitcast_icmp.asm.comp
- reference/opt/shaders-msl/asm/comp/bitcast_icmp.asm.comp
- reference/opt/shaders-ue4/asm/frag/sample-mask-not-array.asm.frag
- reference/opt/shaders-ue4/asm/tesc/hs-incorrect-base-type.asm.tesc
- reference/opt/shaders-ue4/asm/tesc/hs-input-array-access.asm.tesc
- reference/opt/shaders-ue4/asm/tesc/hs-texcoord-array.asm.tesc
- reference/opt/shaders/asm/comp/bitcast_icmp.asm.comp
- reference/opt/shaders/asm/comp/bitcast_iequal.asm.comp
- reference/opt/shaders/comp/casts.comp
- reference/shaders-hlsl-no-opt/asm/frag/scalar-select.spv14.asm.frag
- reference/shaders-hlsl-no-opt/asm/frag/unordered-compare.asm.frag
- reference/shaders-hlsl-no-opt/comp/subgroups-boolean.invalid.nofxc.sm60.comp
- reference/shaders-hlsl/asm/comp/bitcast_icmp.asm.comp
- reference/shaders-msl-no-opt/asm/frag/scalar-select.spv14.asm.frag
- reference/shaders-msl/asm/comp/bitcast_icmp.asm.comp
- reference/shaders-no-opt/asm/frag/scalar-select.spv14.asm.frag
- reference/shaders-no-opt/asm/frag/unordered-compare.asm.frag
- reference/shaders-ue4/asm/frag/sample-mask-not-array.asm.frag
- reference/shaders-ue4/asm/tesc/hs-incorrect-base-type.asm.tesc
- reference/shaders-ue4/asm/tesc/hs-input-array-access.asm.tesc
- reference/shaders-ue4/asm/tesc/hs-texcoord-array.asm.tesc
- reference/shaders/asm/comp/bitcast_icmp.asm.comp
- reference/shaders/asm/comp/bitcast_iequal.asm.comp
- reference/shaders/comp/casts.comp
- shaders-hlsl-no-opt/asm/frag/scalar-select.spv14.asm.frag
- shaders-msl-no-opt/asm/frag/scalar-select.spv14.asm.frag
- shaders-no-opt/asm/frag/scalar-select.spv14.asm.frag
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Fix bug in to_trivial_mix_op, where we made a pre-1.4 assumption that
component count of selector is equal to value component count.
Fix #1694.
> Handle SPIR-V 1.4 selection constructs.

- reference/opt/shaders-hlsl/frag/io-block.frag
- reference/opt/shaders-hlsl/vert/locations.vert
- reference/opt/shaders-hlsl/vert/qualifiers.vert
- reference/shaders-hlsl-no-opt/asm/vert/block-struct-initializer.asm.vert
- reference/shaders-hlsl-no-opt/asm/vert/complex-link-by-name.asm.vert
- reference/shaders-hlsl-no-opt/vert/block-io-auto-location-assignment.vert
- reference/shaders-hlsl/frag/io-block.frag
- reference/shaders-hlsl/vert/locations.vert
- reference/shaders-hlsl/vert/qualifiers.vert
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Emit block members directly in the IO structs and sort them.
Ensures we can get some kind of stable order between stages.
To complete the story, we'll need to be able to inject unused inputs /
builtins, or eliminate unused outputs (probably easiest solution).
Fix #1691.
> HLSL: Rewrite how block IO is emitted.

- spirv_msl.cpp
When setting `SPIRVCrossDecorationInterpolantComponentExpr` decoration, take into consideration a possible array of vectors in an access chain, and don't apply the decoration until we traverse through the array into the vector itself.
> MSL: Fix setting SPIRVCrossDecorationInterpolantComponentExpr decoration.

- CMakeLists.txt
Probably not conventional hosts of SPIRV-Cross, but this PR fixes CMake configuration with recent CMake versions when host is iOS/tvOS/watchOS.
see https://cmake.org/cmake/help/latest/policy/CMP0006.html
> CMake: fix cross-build to iOS/tvOS/watchOS

- reference/opt/shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.force-sample.frag
- reference/opt/shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.frag
- reference/opt/shaders-msl/frag/sample-mask-not-used.fixed-sample-mask.frag
- reference/opt/shaders-msl/frag/sample-mask.fixed-sample-mask.frag
- reference/shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.force-sample.frag
- reference/shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.frag
- reference/shaders-msl/frag/sample-mask-not-used.fixed-sample-mask.frag
- shaders-msl/frag/sample-mask-in-and-out.fixed-sample-mask.force-sample.frag
- spirv_msl.cpp
- spirv_msl.hpp
Vulkan specifies that the Sample Mask Test occurs before fragment shading.
This means `gl_SampleMaskIn` should be influenced by both sample-shading and
`VkPipelineMultisampleStateCreateInfo::pSampleMask`.
CTS tests `dEQP-VK.pipeline.multisample_shader_builtin.*` bear this out.
For sample-shading, `gl_SampleMaskIn` should only have a single bit set,
Since Metal does not filter for this, apply a bitmask based on gl_SampleID.
For a fixed sample mask, since Metal is unaware of
`VkPipelineMultisampleStateCreateInfo::pSampleMask`, we need to ensure that
we apply it to both `gl_SampleMaskIn` and `gl_SampleMask`. This has the side
effect of a redundant application of `pSampleMask` if the shader already
includes `gl_SampleMaskIn` when setting `gl_SampleMask`, but I don't see an
easy way around …
> MSL: Adjust gl_SampleMaskIn for sample-shading and/or fixed sample mask.

- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.comp
- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.fixed-subgroup.comp
- reference/shaders-msl-no-opt/frag/subgroups.nocompat.invalid.vk.msl22.frag
- spirv_msl.cpp
A bitcast to `uint2` will do just fine. I honestly don't know why I
didn't do it this way earlier.
> MSL: Simplify spvSubgroupBallot().

- reference/opt/shaders-msl/comp/type_casting_i64.msl22.comp
- reference/shaders-msl/comp/type_casting_i64.msl22.comp
- shaders-msl/comp/type_casting_i64.msl22.comp
- spirv_msl.cpp
Previous casting in constant expressions allowed `as_type<>` between
types of different overall sizes.
Add check for overall size (width * vecsize) to ensure `as_type<>` will work,
otherwise use regular cast. Also beef up test of integer values to also check
vecsize, and use regular casts for those.
TBH...I'm not sure why we always go to bitcasting when emitting constant expressions. It seems most constant expressions would not have the need for bitcasting. Here I have just done the minimal surgery required to fix the issue at hand, which was to avoid using `as_type<>` when say casting a 64-bit expression value to a 32-bit result, etc.
> MSL: Fix casting in constant expressions with different sizes.

- reference/opt/shaders-msl/comp/mat3-row-maj-read-write-const.comp
- reference/shaders-msl/comp/mat3-row-maj-read-write-const.comp
- shaders-msl/comp/mat3-row-maj-read-write-const.comp
- spirv_msl.cpp
- Remove test and exception when storing row-major matrix from RHS that is not a `SPIRExpression`.
- Add test shaders.
Fixes #1719, and several hundred CTS tests.
The removed test and exception doesn't seem to have a purpose, since subsequent code allows non-SPIRExpression to succeed. After the removal of the test, no SPIRVCross or CTS tests encounter problems.
However, if there are conditions that require this test and exception, we could replace the test, but accommodate a RHS that permits `OpConstantComposite` in addition to `SPIRExpression`. The failing CTS tests, including in #1719 were a result of attempting to store a `OpConstantComposite` into a row-major matrix.
> MSL: Support row-major transpose when storing matrix from constant RHS matrix.

- reference/opt/shaders-msl/vert/unused-position.vert
- reference/shaders-msl/vert/unused-position.vert
- shaders-msl/vert/unused-position.vert
- spirv_msl.cpp
When `gl_Position` is defined by SPIR-V, but neither used nor initialized, it appeared twice in the MSL output, as `gl_Position` and `glPosition_1`.
The existing tests for whether an output is active check only that it is used by an op, or initialized. Adding the implicit `gl_Position` also marked the existing `gl_Position` as active, duplicating the output variable.
Fix is that when checking for the need to add an implicit `gl_Position` output, also check if the var is already defined in the shader, and just needs to be marked as active.
Add test shader.
> MSL: Fix duplicate gl_Position outputs when gl_Position defined but unused.

- spirv_cross.cpp
The argument is a literal, but result is still a temporary.
Fix #1727.
> Track temporary access for OpArrayLength result.

- reference/shaders-msl-no-opt/asm/frag/copy-memory-block-like-thread-local.asm.frag
- shaders-msl-no-opt/asm/frag/copy-memory-block-like-thread-local.asm.frag
- spirv_msl.cpp
Handles a special case with array copies.
The implementation of this fix is not perfect, but should be good
enough for time being.
Fix #1726.
> MSL: Consider that function/private variables can be block-like.

- reference/opt/shaders-msl/asm/vert/spec-constant-op-composite.asm.vert
- reference/opt/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert
- reference/opt/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert.vk
- reference/shaders-msl/asm/vert/spec-constant-op-composite.asm.vert
- reference/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert
- reference/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert.vk
- shaders-msl/asm/vert/spec-constant-op-composite.asm.vert
- shaders/asm/vert/spec-constant-op-composite.asm.vk.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
MSL: Support op `OpQuantizeToF16` in `OpSpecConstantOp`.
All: Support op `OpSRem` in `OpSpecConstantOp`.
I was not able add new tests, as these would require SPIR-V Assembly shaders, which I'm not familiar with creating.
> Add support for additional ops in OpSpecConstantOp.

- reference/opt/shaders-msl/frag/return-value-after-discard-terminator.frag
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
- reference/shaders-msl/frag/return-value-after-discard-terminator.frag
- shaders-msl/frag/return-value-after-discard-terminator.frag
- spirv_glsl.cpp
- spirv_msl.cpp
The terminator Op in a fragment function can be an `OpKill`. In GLSL, where the function returns `void`, this can simply finish the function, but in MSL, this can happen even when the fragment function expects to return a value. So for MSL, if needed, return the value on an `OpKill` that terminates the final entry function block.
Add test shader for new functionality.
Add legacy test reference shader for unrelated buffer-bitcast test, that doesn't seem to have been added previously.
> MSL: Return fragment function value even when last SPIR-V Op is discard (OpKill).

- spirv_msl.cpp
- spirv_msl.hpp
Consolidate derivation of Metal `user(locnL_C)` output/input location
and component attribute qualifier, to establish SVOT across stages.
The `comp != 0` test was not performed uniformly between inputs and outputs, resulting in linkage breakage between attribute qualifiers `user(locn0_0)` for outputs and `user(locn0)` for inputs when component is zero.
I've consolidated to `user(locn0)` for the zero component to make it visibly simpler for the common case where no component is provided, or is assumed to be zero.
Since this was a consolidation, I did not include any new test cases as this was a simple change, and both inputs and outputs now perform identically and any subsequent changes that alters that will then break current tests.
> MSL: Fix location and component variable matching between shader stages.

- reference/opt/shaders-msl/vert/float-math.invariant-float-math.vert
- reference/opt/shaders-msl/vert/no-contraction.vert
- reference/shaders-msl/vert/float-math.invariant-float-math.vert
- reference/shaders-msl/vert/no-contraction.vert
- spirv_msl.cpp
Add `[[clang::optnone]]` attribute to `spvF*()` functions used for handling floating point operations decorated with `DecorationNoContraction`.
Just using precise::fma() did not work.
Adjust SPIRV-Cross unit test reference shaders to accommodate these changes.
> MSL: Honor DecorationNoContraction when compiling using fast-math.

- reference/opt/shaders-msl/asm/comp/quantize.asm.comp
- reference/shaders-msl/asm/comp/quantize.asm.comp
- spirv_msl.cpp
- spirv_msl.hpp
Add `spvQuantizeToF16()` family of synthetic functions to convert from float to half and back again, and add function attribute `[[clang::optnone]]` to honor infinities during conversions.
Adjust SPIRV-Cross unit test reference shaders to accommodate these changes.
> MSL: Honor infinities in OpQuantizeToF16 when compiling using fast-math.

- spirv_msl.cpp
- spirv_msl.hpp
Matching output/input struct member types between shader stages could fail if
a location is shared between members, each using different components of that
location, because the member vecsize was only stored once for the location.
Add `MSLShaderInput::component` member.
Use `LocationComponentPair` to key `inputs_by_location`, instead of just location.
`ensure_correct_input_type()` pass component value as well as location.
Any tests would require ability to pass location and component info. Not sure how to do that.
@cdavis5e Inviting your review here regarding impact on tessellation stages.
> MSL: Track location component to match vecsize between shader stages.

- spirv_common.hpp
- spirv_cross_containers.hpp
> MSVC: Workaround crtdbg macroing free().

- reference/shaders-hlsl-no-opt/comp/intmin-literal.comp
- reference/shaders-msl-no-opt/comp/int16min-literal.comp
- reference/shaders-msl-no-opt/comp/int64min-literal.msl22.comp
- reference/shaders-msl-no-opt/comp/intmin-literal.comp
- reference/shaders-no-opt/comp/int16min-literal.comp
- reference/shaders-no-opt/comp/int64min-literal.comp
- reference/shaders-no-opt/comp/intmin-literal.comp
- shaders-hlsl-no-opt/comp/intmin-literal.comp
- shaders-msl-no-opt/comp/int16min-literal.comp
- shaders-msl-no-opt/comp/int64min-literal.msl22.comp
- shaders-msl-no-opt/comp/intmin-literal.comp
- shaders-no-opt/comp/int16min-literal.comp
- shaders-no-opt/comp/int64min-literal.comp
- shaders-no-opt/comp/intmin-literal.comp
- spirv_common.hpp
- spirv_glsl.cpp
We cannot naively convert these to decimal literals. C/C++ (and thus
MSL) has extremely awkward literal promotion rules.
Fix #1754.
> Improve handling of INT_MIN/INT64_MIN literals.

- spirv_glsl.cpp
Per spec, instead of throwing exception for out-of-bounds swizzles, engage undefined behavior by defaulting to the `.x` swizzle.
Fixes the specific case that drove issue #1778.
> Per spec, support undefined behavior for out-of-bounds swizzles.

- reference/opt/shaders-msl/vert/uniform-struct-packing-nested.vert
- reference/shaders-msl/vert/uniform-struct-packing-nested.vert
- shaders-msl/vert/uniform-struct-packing-nested.vert
- spirv_msl.cpp
Previous test for `SPIRVCrossDecorationPhysicalTypePacked` on parent struct when unpacking member struct was too restrictive, and not needed as long as padding compensates.
Added unit test.
> MSL: Remove over-zealous check for struct packing compatibility.

- spirv_msl.cpp
Only emit `user(locnN)` for tess builtin input variables, and allow output builtin to emit `user(clip/cullN)`. Previously, output builtin would emit location if input builtin also existed.
Fixes the following CTS tests:
```
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.1_fragmentshader_read
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.2_fragmentshader_read
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.3_fragmentshader_read
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.4_fragmentshader_read
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.5_fragmentshader_read
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.6_fragmentshader_read
dEQP-VK.clipping.user_defined.clip_distance.vert_tess.7_fragmentshader_read …
```
> MSL: Correctly emit user(clip/cullN) for clip/cull builtins in tess output struct.

- reference/shaders-reflection/comp/out-of-order-block-offsets.comp.json
- shaders-reflection/comp/out-of-order-block-offsets.comp
- spirv_cross.cpp
Need to deduce size based on member with highest offset, not highest
index.
Fix #1802.
> Correctly reflect declared buffer size for out of order members.

- reference/shaders-msl-no-opt/asm/comp/modf-storage-class.asm.comp
- reference/shaders-msl-no-opt/vert/modf-storage-class.capture.vert
- shaders-msl-no-opt/asm/comp/modf-storage-class.asm.comp
- shaders-msl-no-opt/vert/modf-storage-class.capture.vert
- spirv_msl.cpp
> MSL: Handle non-thread storage class in Modf/Frexp pointer versions.

- reference/shaders-no-opt/asm/degenerate-selection-constructs.asm.frag
- shaders-no-opt/asm/degenerate-selection-constructs.asm.frag
- spirv_parser.cpp
Apparently, it's legal to use a selection construct where both paths
branch to same location, but a different merge point is used.
This breaks many assumptions the variable scope analyzer makes.
The only logical way to generate code for this scenario is to treat the
selection construct as a trivial switch construct with only a default
case.
Fix #1777.
> CFG: Handle degenerate selection constructs.

- reference/opt/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-decorations.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-aliased-block-name.nocompat.vk.asm.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-pod-in-buffer.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-unused-pod-in-buffer.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-bitcast-uvec2.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-bitcast.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-decorations.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
- shaders-no-opt/asm/comp/buffer-reference-pointer-to-pod-in-buffer.asm.nocompat.vk.comp
- shaders-no-opt/asm/comp/buffer-reference-pointer-to-unused-pod-in-buffer.asm.nocompat.vk.comp
- shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp
- shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp
- shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
This is somewhat awkward to support, but the best effort we can do here
is to analyze various Load/Store opcodes and deduce the ideal overall
alignment based on this. This is not a 100% perfect solution, but should
be correct for any reasonable use case.
Also fix various nitpicks with BDA support while I'm at it.
Fix #1801.
> GLSL: Deal with buffer_reference_align.

- reference/opt/shaders-msl/asm/frag/depth-image-color-format-fetch.asm.frag
- reference/opt/shaders-msl/asm/frag/depth-image-color-format-sampled.asm.frag
- reference/shaders-msl/asm/frag/depth-image-color-format-fetch.asm.frag
- reference/shaders-msl/asm/frag/depth-image-color-format-sampled.asm.frag
- shaders-msl/asm/frag/depth-image-color-format-fetch.asm.frag
- shaders-msl/asm/frag/depth-image-color-format-sampled.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
SPIR-V allows an image to be marked as a depth image, but with a non-depth format. Such images should be read or sampled as vectors instead of scalars, except when they are subject to compare operations.
Don't mark an `OpSampledImage` as using a compare operation just because the image contains a depth marker. Instead, require that a compare operation is actually used on that image.
`Compiler::image_is_comparison()` was really testing whether an image is a depth image, since it incorporates the depth marker. Rename that function to `is_depth_image()`, to clarify what it is really testing.
In `Compiler::is_depth_image()`, do not treat an image  as a depth image if it has been explicitly marked with a color format, unless the image is subject to compare operations.
In …
> Separate (partially) the tracking of depth images from depth compare ops.

- reference/opt/shaders-msl/frag/depth-out-early-frag-tests.frag
- reference/opt/shaders-msl/frag/depth-out-no-early-frag-tests.frag
- reference/shaders-msl/frag/depth-out-early-frag-tests.frag
- reference/shaders-msl/frag/depth-out-no-early-frag-tests.frag
- shaders-msl/frag/depth-out-early-frag-tests.frag
- shaders-msl/frag/depth-out-no-early-frag-tests.frag
- spirv_msl.cpp
- spirv_msl.hpp
Fragment shaders that require explicit early fragment tests are incompatible with specifying depth and stencil values within the shader. If explicit early fragment tests is specified, remove the depth and stencil outputs from the output structure, and replace them with dummy local variables.
Add `CompilerMSL:uses_explicit_early_fragment_test()` function to consolidate testing for whether early fragment tests are required.
Add two unit tests for depth-out with, and without, early fragment tests.
Fixes #1764.
> MSL: Don't output depth and stencil values with explicit early fragment tests.

- spirv_cfg.cpp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_parsed_ir.cpp
- spirv_cross_parsed_ir.hpp
- spirv_glsl.cpp
- spirv_parser.cpp
- spirv_parser.hpp
Hello! this is my first PR.
According to the spec, if the `condition` has a type wider than 32 bits,
the literals to be compared with will be of that size as well.
This caused some misalignments if the `condition` is bigger than 32,
causing a nullptr return without further explanation.
Currently neither GLSL nor MSL supports uint64 as the condition but the
SPIRV allows it anyway. With this fix the error message explicitly
states that a switch with 64 bit sized variables can't be used in both GLSL
and MSL.
I couldn't find any "global" array containing type information at this stage,
so I had to add a map to some IDs in order to check their type.
This also fixes #1768.
> Add 64 bit support for OpSwitch

- spirv_glsl.cpp
Hi, in [OpenGL-ES spec](https://www.khronos.org/registry/OpenGL/specs/es/3.1/GLSL_ES_Specification_3.10.withchanges.pdf), there's a restriction for vertex shader input: 
> It is a compile-time error to declare a vertex shader input with, or that contains, any of the following types:
• A boolean type
• An opaque type
• An array
• A structure
I noticed this because our shader failed to compile both for mali and adreno gpu:
```glsl
// vertex shader
#version 310 es
layout(location = 1) in vec2 in_var_ATTRIBUTE1[3];
```
```bash
// adreno
'attribute 2-component vector of float' : cannot declare arrays of this qualifier
// mali
S0049: Illegal type for input variable 'in_var_ATTRIBUTE1'
```
So i added a check for glsl backend, to report this issue when cross compiling rather than in real devices.
> ESSL: Throw if array input var is found in vs.

- reference/opt/shaders-msl/asm/frag/switch-different-sizes.asm.frag
- reference/opt/shaders-msl/asm/frag/switch-long-case.asm.msl22.frag
- reference/opt/shaders-msl/asm/frag/switch-unsigned-long-case.asm.msl22.frag
- reference/opt/shaders/asm/frag/switch-preserve-sign-extension.asm.frag
- reference/shaders-msl/asm/frag/switch-different-sizes.asm.frag
- reference/shaders-msl/asm/frag/switch-long-case.asm.msl22.frag
- reference/shaders-msl/asm/frag/switch-unsigned-long-case.asm.msl22.frag
- reference/shaders/asm/frag/switch-preserve-sign-extension.asm.frag
- shaders-msl/asm/frag/switch-different-sizes.asm.frag
- shaders-msl/asm/frag/switch-long-case.asm.msl22.frag
- shaders-msl/asm/frag/switch-unsigned-long-case.asm.msl22.frag
- shaders/asm/frag/switch-preserve-sign-extension.asm.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_parser.cpp
This _actually_ adds 64 bit support for MSL (previous PR ended up fixing a segfault). I made sure it also passes the tests posted by @billhollings with VK-GL-CTS:
```
Test case 'dEQP-VK.spirv_assembly.type.scalar.i64.switch_vert'..
Pass (Rendered output matches input)
Test case 'dEQP-VK.spirv_assembly.type.scalar.i64.switch_tessc'..
Pass (Rendered output matches input)
Test case 'dEQP-VK.spirv_assembly.type.scalar.i64.switch_tesse'..
Pass (Rendered output matches input)
Test case 'dEQP-VK.spirv_assembly.type.scalar.i64.switch_frag'..
Pass (Rendered output matches input)
Test case 'dEQP-VK.spirv_assembly.type.scalar.i64.switch_comp'..
Pass (Output match with expected)
Test case 'dEQP-VK.spirv_assembly.type.scalar.u64.switch_vert'..
Pass (Rendered output matches input)
Test case …
```
> MSL: Add 64 bit switch support

- reference/opt/shaders/asm/frag/out-of-bounds-access-opspecconstant.asm.frag
- reference/opt/shaders/asm/frag/out-of-bounds-access.asm.frag
- reference/shaders/asm/frag/out-of-bounds-access-opspecconstant.asm.frag
- reference/shaders/asm/frag/out-of-bounds-access.asm.frag
- shaders/asm/frag/out-of-bounds-access-opspecconstant.asm.frag
- shaders/asm/frag/out-of-bounds-access.asm.frag
- spirv_glsl.cpp
I relied on the things discussed in https://github.com/KhronosGroup/SPIRV-Cross/issues/1778.
Not sure if I should add a special case for negative numbers. I'm also very open
to discuss the implementation to be extra sure this is the way to go.
> Clamp vector element access to vector size.

- test_shaders.py
I personally feel like displaying a `diff` instead of the output is useful in some cases to identify the differences faster.
> test_shaders: Add the option to generate diff instead.

- reference/opt/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
- reference/opt/shaders-msl/tese/input-array.tese
- reference/opt/shaders-msl/tese/quad.domain.tese
- reference/opt/shaders-msl/tese/quad.tese
- reference/opt/shaders-msl/tese/water_tess.tese
- reference/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
- reference/shaders-msl/tese/input-array.tese
- reference/shaders-msl/tese/quad.domain.tese
- reference/shaders-msl/tese/quad.tese
- reference/shaders-msl/tese/water_tess.tese
- spirv_msl.cpp
Fix for this issue #1762.
Adds "In" postfix to the "gl_TessCoord" on entry point arguments decompilation stage if built in type is "BuiltInTessCoord" and execution mode is "ExecutionModeQuads". And declares shadow  variable "gl_TessCoord" on entry point declarations.
I have compiled and tested it with VK-GL-CTS, looks like it now works as expected.
> Fix incorrect MSL gl_TessCoord variable type

- reference/opt/shaders-hlsl/asm/vert/spec-constant-op-composite.asm.vert
- reference/shaders-hlsl-no-opt/asm/comp/local-size-id-override.asm.comp
- reference/shaders-hlsl-no-opt/asm/comp/local-size-id.asm.comp
- reference/shaders-hlsl/asm/vert/spec-constant-op-composite.asm.vert
- reference/shaders-msl-no-opt/asm/comp/local-size-id-override.asm.comp
- reference/shaders-msl-no-opt/asm/comp/local-size-id.asm.comp
- reference/shaders-no-opt/asm/comp/local-size-id-override.vk.asm.comp
- reference/shaders-no-opt/asm/comp/local-size-id-override.vk.asm.comp.vk
- reference/shaders-no-opt/asm/comp/local-size-id.vk.asm.comp
- reference/shaders-no-opt/asm/comp/local-size-id.vk.asm.comp.vk
- shaders-hlsl-no-opt/asm/comp/local-size-id-override.asm.comp
- shaders-hlsl-no-opt/asm/comp/local-size-id.asm.comp
- shaders-msl-no-opt/asm/comp/local-size-id-override.asm.comp
- shaders-msl-no-opt/asm/comp/local-size-id.asm.comp
- shaders-no-opt/asm/comp/local-size-id-override.vk.asm.comp
- shaders-no-opt/asm/comp/local-size-id.vk.asm.comp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_parser.cpp
- test_shaders.py
Support added in maintenance4, and WorkGroupSize builtin is deprecated in SPIR-V 1.6.
Fix #1811.
> Support LocalSizeId

- reference/shaders-msl-no-opt/asm/comp/atomic-min-max-sign.asm.comp
- shaders-msl-no-opt/asm/comp/atomic-min-max-sign.asm.comp
- spirv_msl.cpp
- spirv_msl.hpp
C++ deduces this based on the pointer type, so cast to atomic_uint/int
if we have to.
Fix #1843.
> MSL: Handle signed atomic min/max.

- reference/shaders-msl-no-opt/asm/comp/block-like-array-type-construct-2.asm.comp
- reference/shaders-msl-no-opt/asm/comp/block-like-array-type-construct.asm.comp
- shaders-msl-no-opt/asm/comp/block-like-array-type-construct-2.asm.comp
- shaders-msl-no-opt/asm/comp/block-like-array-type-construct.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
Need this to be context sensitive, since array of block-like struct is
template, but struct of block-like array is C-style.
Also, test a mix and match, so we have constant array of block-like
struct with array inside. :v
Fix #1844.
> MSL: Handle constant construct of block-like array types.

- reference/shaders-hlsl-no-opt/asm/comp/constant-lut-name-aliasing.asm.comp
- reference/shaders-hlsl-no-opt/asm/comp/spec-constant-name-aliasing.asm.comp
- reference/shaders-msl-no-opt/asm/comp/constant-lut-name-aliasing.asm.comp
- reference/shaders-msl-no-opt/asm/comp/spec-constant-name-aliasing.asm.comp
- reference/shaders-no-opt/asm/comp/constant-lut-name-aliasing.asm.comp
- reference/shaders-no-opt/asm/comp/spec-constant-name-aliasing.vk.asm.comp
- reference/shaders-no-opt/asm/comp/spec-constant-name-aliasing.vk.asm.comp.vk
- shaders-hlsl-no-opt/asm/comp/constant-lut-name-aliasing.asm.comp
- shaders-hlsl-no-opt/asm/comp/spec-constant-name-aliasing.asm.comp
- shaders-msl-no-opt/asm/comp/constant-lut-name-aliasing.asm.comp
- shaders-msl-no-opt/asm/comp/spec-constant-name-aliasing.asm.comp
- shaders-no-opt/asm/comp/constant-lut-name-aliasing.asm.comp
- shaders-no-opt/asm/comp/spec-constant-name-aliasing.vk.asm.comp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
Need to register resource name.
Fix #1835.
> Handle aliased names in spec constants.

- spirv_msl.cpp
Msl implementation of the fast and precise namespace is not guarenteed  for half by the specification and will break in some cases.
Calling fast::normalize with a half3 or a half2 as parameters will not compile, because thoses are not implemented (reproducible when targeting mac or ios, last version tested with Xcode-12.5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/metal) .
Peaking at the msl documentation: https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf, support is only explicitly stated for single precision floating point
```
For single precision floating-point, Metal supports two variants of the math functions listed in
Table 6.4: the precise and the fast variants. The ffast-math compiler option (refer to section
1.5.3) selects the …
```
> [Spirv_msl] Fix normalize on half3/half2

- spirv_msl.cpp
example:
```
#version 310 es
precision highp float;
layout(location = 0) out vec4 FragColor;
layout(binding = 0) uniform sampler2D texSampler2D;
layout(binding = 1) uniform ALPHA {
float alpha;
} alpha;
void main()
{
vec4 alpha = vec4(alpha.alpha);
vec4 texColor = texture(texSampler2D, vec2(0.0, 0.0));
texColor.xyz += alpha.xyz;
FragColor = texColor;
}
```
before:
```
#include <metal_stdlib>
#include <simd/simd.h>
using namespace metal;
struct ALPHA
{
float alpha;
};
struct main0_out
{
float4 FragColor [[color(0)]];
};
fragment main0_out main0(constant ALPHA& alpha [[buffer(0)]], texture2d<float> texSampler2D [[texture(0)]], sampler texSampler2DSmplr [[sampler(0)]])
{
main0_out out = {};
float4 alpha = float4(alpha.alpha);
float4 texColor = texSampler2D.sample(texSampler2DSmplr, …
```
> MSL: append entry point args to local variable names to avoid conflicts

- spirv_common.hpp
Seeing downstream errors:
"spirv_common.hpp:692:19: error: unqualified call to std::move"
> Qualify move as std::move

- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl23.ios.simd.comp
- spirv_msl.cpp
- spirv_msl.hpp
> MSL: Refactor and fix use of quadgroup vs simdgroup.

- reference/shaders-hlsl-no-opt/vert/empty-shader.sm30.vert
- shaders-hlsl-no-opt/vert/empty-shader.sm30.vert
- spirv_hlsl.cpp
> HLSL: Do not emit VPOS fixup unless position is active.

- main.cpp
- spirv_cross.cpp
- spirv_cross_c.cpp
- spirv_cross_parsed_ir.cpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_parser.cpp
Clang added -Wunqualified-std-cast-call in
https://reviews.llvm.org/D119670, which warns on unqualified std::move
and std::forward calls. This change qualifies these calls to allow the
project to build on HEAD Clang -Werror.
> Qualify std::move.

- spirv_hlsl.cpp
~If targeting SM >= 6.6, `IsHelperLane()` is used.~
~It targeting SM >= 5.0 and < 6.6, the same emulation that DXC does is done here; namely, casting `SV_Coverage` to `bool`.~
**UPDATE:**
`IsHelperLane()` will be used in any case, as long as the ninimum shader model is being targeted.
Kept the old info below the line for possible future reference.
---
NOTES:
- Since a DXC compiler recent enough version is able to understand `IsHelperLane()`, SPIRV-Cross could just emit that, but I believe it's better to do the emulation right here in case users are using an older version of the compiler.
- Curiously, DXC is able to emulate via `@dx.op.coverage` even in `ps_4_0`, despite `SV_Coverage` allegedly not being supported there. In this case DXC would do a better job of emulating it. Maybe it can …
> HLSL: Add support for gl_HelperInvocation.

- reference/shaders-msl-no-opt/asm/frag/constant-composite-block-no-array-stride-2.asm.frag
- reference/shaders-msl-no-opt/asm/vert/constant-composite-block-no-array-stride.asm.vert
- shaders-msl-no-opt/asm/frag/constant-composite-block-no-array-stride-2.asm.frag
- shaders-msl-no-opt/asm/vert/constant-composite-block-no-array-stride.asm.vert
- spirv_glsl.cpp
In normal buffer blocks, every member must be declared, but for
constants, you can technically mix and match, causing much pain and
suffering ...
Fix #1763.
> MSL: Handle awkward mix and match of Offset / ArrayStride in constants.

- spirv_glsl.cpp
This fixes a regression introduced by 93b0dc7, where all volatile variables were not allowed to be forwarded. This doesn't work well for volatile memory object variables like images or buffer blocks, because it forces local variables
to be defined, which is unnecessary, and sometimes results in wrong types.
This patch restricts volatile builtin variables (eg. `HelperInvocation`) from being forwarded, but allows other volatile variables to be forwarded, as before.
> Allow volatile vars that are not builtins to be forwarded.

- reference/opt/shaders-msl/vert/interface-block-single-element-array.vert
- reference/shaders-msl/vert/interface-block-single-element-array.vert
- shaders-msl/vert/interface-block-single-element-array.vert
- spirv_msl.cpp
Emit interface block members of array length 1 as arrays instead of scalars.
Test for array presence using `is_array()` instead of element count.
Add `shaders-msl/vert/interface-block-single-element-array.vert regression test`.
Fixes a regression error introduced in 3d4daab.
Fixes #1919.
Fixes #1920.
> MSL: Emit interface block members of array length 1 as arrays instead of scalars.

- spirv_hlsl.cpp
This adds a translation of `BuiltInLayer` (aka. `gl_Layer`) into `SV_RenderTargetIndex` to the output in the HLSL backend.
> HLSL: Add missing `BuiltInLayer` to HLSL backend.

- reference/opt/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert.vk
- reference/opt/shaders/comp/bake_gradient.comp
- reference/opt/shaders/frag/constant-array.frag
- reference/opt/shaders/frag/frexp-modf.frag
- reference/opt/shaders/tese/water_tess.tese
- reference/opt/shaders/vert/ground.vert
- reference/opt/shaders/vert/ocean.vert
- reference/opt/shaders/vert/read-from-row-major-array.vert
- reference/opt/shaders/vulkan/frag/separate-sampler-texture-array.vk.frag
- reference/opt/shaders/vulkan/frag/separate-sampler-texture-array.vk.frag.vk
- reference/opt/shaders/vulkan/frag/separate-sampler-texture.vk.frag
- reference/opt/shaders/vulkan/frag/separate-sampler-texture.vk.frag.vk
- reference/shaders-no-opt/asm/comp/local-size-id.vk.asm.comp.vk
- reference/shaders-no-opt/asm/frag/late-expression-invalidation-2.asm.frag
- reference/shaders-no-opt/asm/frag/ldexp-uint-exponent.asm.frag
- reference/shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules-hoisted-temporaries.asm.frag
- reference/shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules-hoisted-temporary.asm.frag
- reference/shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules.asm.frag
- reference/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert.vk
- shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules-hoisted-temporaries.asm.frag
- shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules-hoisted-temporary.asm.frag
- shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules.asm.frag
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
GLSL and SPIR-V work completely differently here.
GLSL inherits precision from its arguments, not its destination. SPIR-V on the other hand declares this on the instruction, where inputs may be truncated. Without RelaxedPrecision on a SPIR-V instruction, we might find that all inputs are mediump and will therefore execute in mediump. To counteract this, force temporaries and bind them to highp variables. We cannot mess with the RelaxedPrecision decoration since that will cascade down to sub-dependencies which we don't want.
GLSL will forward the relaxedprecision decorations from chained expressions, so do that as well by just inheriting RelaxedPrecision as necessary.
Fix #1868.
> Implement more proper semantics for RelaxedPrecision vs mediump

- reference/opt/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert.vk
- reference/opt/shaders/vulkan/frag/spec-constant-ternary.vk.frag.vk
- reference/shaders/asm/vert/spec-constant-op-composite.asm.vk.vert.vk
- reference/shaders/vulkan/frag/spec-constant-ternary.vk.frag.vk
- spirv_glsl.cpp
Undefs won't have a chance to emit aliases, and any expression depending
on Undef will be garbage either way.
Fix #1935.
> GLSL: Do not analyze precision for Undef variables.

- reference/opt/shaders-msl/frag/vecsize-mismatch.shader-inputs.frag
- reference/opt/shaders-msl/vert/signedness-mismatch.shader-inputs.vert
- reference/shaders-msl/frag/vecsize-mismatch.shader-inputs.frag
- reference/shaders-msl/vert/signedness-mismatch.shader-inputs.vert
- spirv_msl.cpp
If the sign is rewritten for an input, we might have to fixup the sign
in OpLoad, similar to builtins.
Fix #1934.
> MSL: Potentially cast loaded Input variables.

- reference/opt/shaders-hlsl/frag/switch-unreachable-break.frag
- reference/opt/shaders-msl/frag/switch-unreachable-break.frag
- reference/opt/shaders/frag/switch-unreachable-break.frag
- reference/opt/shaders/legacy/vert/switch-nested.legacy.vert
- reference/shaders-hlsl/frag/switch-unreachable-break.frag
- reference/shaders-msl/frag/switch-unreachable-break.frag
- reference/shaders/frag/switch-unreachable-break.frag
- shaders-hlsl/frag/switch-unreachable-break.frag
- shaders-msl/frag/switch-unreachable-break.frag
- shaders/frag/switch-unreachable-break.frag
- spirv_glsl.cpp
HLSL is very fussy about fallthrough in switch blocks, so promote
Unreachable blocks to breaks if they are inside a switch construct.
Some false positives are possible in weird multi-break scenarios, but
this is benign.
Fix #1943.
> Promote Unreachable cases into break to avoid fallthrough.

- spirv_hlsl.cpp
When trying to use `gl_Layer` and converting to HLSL, I ran into some difficulty.  I think the previous PR had a mistake, as from what I can tell `gl_Layer`'s substitute is `SV_RenderTargetArrayIndex`.
> HLSL: fix BuiltInLayer to emit semantic 'SV_RenderTargetArrayIndex'

- reference/shaders-no-opt/frag/texture1d-emulation.es.frag
- reference/shaders-no-opt/frag/texture1d-emulation.legacy.frag
- shaders-no-opt/frag/texture1d-emulation.es.frag
- shaders-no-opt/frag/texture1d-emulation.legacy.frag
- spirv_glsl.cpp
- test_shaders.py
ES does not support 1D images at all. Fake it by promoting 1D images to
2D.
Fix #1950.
> GLSL: Implement 1D texture emulation for ES.

- reference/opt/shaders/vulkan/comp/fp-atomic.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/fp-atomic.nocompat.vk.comp.vk
- shaders/vulkan/comp/fp-atomic.nocompat.vk.comp
- spirv_glsl.cpp
Fix #1944.
atomicLoad/Store is left out and should be handled when Vulkan memory model support is eventually added.
> GLSL: Add basic support for GL_EXT_shader_atomic_float.

- reference/shaders-no-opt/comp/loop-break-merge-after-inner-continue.comp
- shaders-no-opt/comp/loop-break-merge-after-inner-continue.comp
- spirv_cfg.cpp
Case which caused failure:
if (cond)
{
continue;
}
break;
Only allow tracing from inner selections if the outer header never
merges execution.
Fix #1957.
> Fix control flow bug where we missed continue;

- spirv_hlsl.cpp
I'm trying to get AMD FidelityFX shader through SPIRV-Cross. For some reasons, I have to compile to SPIR-V first. (I know it'd be better to use the HLSL version directly, but for now this flow is more convenient for me.)
The matter is that this function in the generated HLSL gives compile errors:
```
half APrxLoRsqH1(half a)
{
uint16_t param = 22947u;
uint16_t param_1 = 1u;
return (AW1_x(param) - ((a) >> AW1_x(param_1)));
}
```
> `error: int or unsigned int type required`
> `   return (AW1_x(param) - ((a) >> AW1_x(param_1)));`
For reference, this is the corresponding SPIR-V dissasembly of the function:
```
%APrxLoRsqH1_f161_ = OpFunction %half None %32 ; 0x000041a0
%a_7 = OpFunctionParameter %_ptr_Function_half ; 0x000041b4
%90 = OpLabel ; 0x000041c0
%param_9 = OpVariable …
```
> HLSL: Implement bit casts between Half and UShort.

- reference/shaders-no-opt/asm/frag/collapsed-switch-phi-flush.asm.frag
- shaders-no-opt/asm/frag/collapsed-switch-phi-flush.asm.frag
- spirv_glsl.cpp
Collapsed switch constructs only branch directly to the merge block.
Fix #1969.
> Handle PHI in collapsed switch constructs.

- main.cpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
MSL backend supports emitting custom name, and there's no reason for
HLSL to not support that as well, but we have to make it an option to
not break existing users.
Fix #1979.
> HLSL: Add option to emit entry point name 1:1 instead of main().

- reference/shaders-no-opt/asm/comp/fuzz-loop-variable-dominator-with-unreachable-continue-block.asm.comp
- shaders-no-opt/asm/comp/fuzz-loop-variable-dominator-with-unreachable-continue-block.asm.comp
- spirv_cfg.hpp
- spirv_cross.cpp
If the loop variable candidate has a dominating block that lives in an
unrelated loop, we have to reject the loop variable candidate.
Fix #1972.
> Avoid detection of false loop variables.

- reference/shaders-no-opt/asm/comp/fuzz-collapse-degenerate-loop.asm.comp
- shaders-no-opt/asm/comp/fuzz-collapse-degenerate-loop.asm.comp
- spirv_parser.cpp
If we hit the deprecated scenario of selection with identical branches,
we need to collapse loops into direct branches if need be.
Fix #1973.
> Handle collapsed loops similar to collapsed selections.

- reference/shaders-no-opt/asm/comp/multi-break-switch-out-of-loop.asm.comp
- shaders-no-opt/asm/comp/multi-break-switch-out-of-loop.asm.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
Use a switch stack instead.
Fix #1975.
> Handle multiple breaks out of switches.

- reference/shaders-no-opt/asm/frag/composite-insert-hoisted-temporaries-1.asm.frag
- reference/shaders-no-opt/asm/frag/composite-insert-hoisted-temporaries-2.asm.frag
- shaders-no-opt/asm/frag/composite-insert-hoisted-temporaries-1.asm.frag
- shaders-no-opt/asm/frag/composite-insert-hoisted-temporaries-2.asm.frag
- spirv_glsl.cpp
We cannot track uses that happens in subsequent loop iterations, so have
to be very careful.
Fixes regression introduced after this was added.
Fix #1992.
> Do not optimize OpCompositeInsert for hoisted temporaries.

- spirv_cross_parsed_ir.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
The name fixing logic makes shaders with depth fetch broken (`gl_LastFragDepthARM` is renamed to `_RESERVED_IDENTIFIER_FIXUP_gl_LastFragDepthARM`). We should prevent remapped vars from being renamed.
> Don't rename remapped variables like 'gl_LastFragDepthARM'

- main.cpp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
This is analogous to the existing support for fixing up shader inputs. It is intended to be used with tessellation to add implicit builtins that are read from a later stage, despite not being written in an earlier stage. (Believe it or not, this is in fact legal in Vulkan.)
Helps fix 8 CTS tests under `dEQP-VK.pipeline.*.no_position`. (Eight other tests work solely by accident without this change.)
cc @gpx1000
> MSL: Add a mechanism to fix up shader outputs.

- reference/shaders-msl-no-opt/asm/comp/opptrdiff-basic.spv14.asm.comp
- reference/shaders-msl-no-opt/asm/comp/opptrdiff-opptraccesschain-elem-offset.spv14.asm.comp
- reference/shaders-msl-no-opt/asm/comp/opptrequal-basic.spv14.asm.comp
- reference/shaders-msl-no-opt/asm/comp/opptrequal-row-maj-mtx-bypass-transpose.spv14.asm.comp
- reference/shaders-msl-no-opt/asm/comp/opptrnotequal-basic.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/opptrdiff-basic.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/opptrdiff-opptraccesschain-elem-offset.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/opptrequal-basic.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/opptrequal-row-maj-mtx-bypass-transpose.spv14.asm.comp
- shaders-msl-no-opt/asm/comp/opptrnotequal-basic.spv14.asm.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
MSL: Support `OpPtrEqual`, `OpPtrNotEqual`, and `OpPtrDiff`.
- Add `CompilerMSL::emit_binary_ptr_op()` and `to_ptr_expression()` to emit binary pointer op. Compare matrix addresses without automatic `transpose()` conversion, to avoid error taking address of temporary copy.
- Add `Compiler::add_active_interface_variable()` to also track active interface vars in the entry point for SPIR-V 1.4 and above.
- For `OpPtrAccessChain` that ends in array element, use `Element` as offset to existing index, otherwise it will access into array dimension that doesn't exist.
- Dereference pointer function call arguments. Ultimately, this dereferencing is actually backwards, and in future, we should aim to properly support passing pointer variables between functions, but such a refactoring was beyond the …
> MSL: Support OpPtrEqual, OpPtrNotEqual, and OpPtrDiff.

- reference/opt/shaders-ue4/asm/frag/subpass-input.ios.framebuffer-fetch.asm.frag
- reference/opt/shaders-ue4/asm/frag/subpass-input.msl23.framebuffer-fetch.asm.frag
- reference/shaders-ue4/asm/frag/subpass-input.ios.framebuffer-fetch.asm.frag
- reference/shaders-ue4/asm/frag/subpass-input.msl23.framebuffer-fetch.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_msl.cpp
Currently  `gl_FragCoord` will be fixed up to get per-sample semantics when `SubpassInput` or `SubpassInputMS`  is detected:
```
gl_FragCoord.xy += get_sample_position(gl_SampleID) - 0.5;
```
But Old iOS (e.g. iOS 9) does not allow to use `[[sample_id]]` in shader if the pipeline is not multisampled, so the above code may not compile. To solve this issue, we have to check if the fix-up is really needed.
> MSL: only fix up gl_FragCoord if really necessary.

- reference/opt/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.comp
- reference/opt/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.comp
- reference/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.comp
- reference/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.comp
- shaders-msl-no-opt/asm/comp/block-like-array-type-construct-2.asm.comp
- shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.comp
- shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.comp
- spirv_msl.cpp
- spirv_msl.hpp
It is allowed to redeclare descriptors with different types in Vulkan. MSL in general does not allow this, but for raw buffers, we can cast the reference type at the very least.
For typed resources we are kinda hosed. Without descriptor indexing's PARTIALLY_BOUND_BIT, descriptors must be valid if they are statically accessed, so it would not be valid to access differently typed aliases unless that flag is used. There might be a way to reinterpret cast descriptors, but that seems very sketchy.
Implements support for:
- Single discrete descriptor
- Single argument buffer descriptor
- Array of argument buffer descriptors
Other cases are unimplemented for now since they are extremely painful to unroll.
> MSL: Handle descriptor aliasing of raw buffer descriptors.

- reference/opt/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.comp
- reference/opt/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.comp
- reference/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.comp
- reference/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.comp
- shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.comp
- shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.comp
- spirv_msl.cpp
Fixes regression from descriptor aliasing implementation.
> MSL: Do not attempt to alias push constants.

- spirv_msl.cpp
> MSL: Block 64-bit atomics and fix some reserved keywords

- CMakeLists.txt
- main.cpp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_cross_c.cpp
- spirv_cross_c.h
Reflect naming scheme in a context sensitive way that matches the frontend.
GLSL -> use block name
HLSL (DXC) -> use instance name.
Fix #2029.
> Add reflection support for shader record buffers.

- main.cpp
- reference/shaders-hlsl-no-opt/vert/base-instance.vert
- reference/shaders-hlsl-no-opt/vert/base-vertex.vert
- shaders-hlsl-no-opt/vert/base-instance.vert
- shaders-hlsl-no-opt/vert/base-vertex.vert
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Add concept of explicit bindings for aux structs and allows query if these aux structs are required.
Fix #2032.
> HLSL: Improve support for VertexInfo aux struct.

- reference/shaders-msl-no-opt/asm/frag/access-chain-array-ubo-partial.argument.msl2.asm.frag
- reference/shaders-msl-no-opt/asm/frag/access-chain-array-ubo-partial.asm.frag
- shaders-msl-no-opt/asm/frag/access-chain-array-ubo-partial.argument.msl2.asm.frag
- shaders-msl-no-opt/asm/frag/access-chain-array-ubo-partial.asm.frag
- spirv_msl.cpp
Need to consider the backing variable, not just plain SPIRVariable.
Fix #2040.
> MSL: Handle partial access chains with array-of-UBO/SSBO.

- reference/opt/shaders-msl/asm/comp/bitcast_iadd.asm.comp
- reference/opt/shaders-msl/asm/comp/bitcast_icmp.asm.comp
- reference/opt/shaders-msl/asm/comp/multiple-entry.asm.comp
- reference/opt/shaders-msl/comp/buffer_device_address.msl2.comp
- reference/opt/shaders-msl/vert/buffer_device_address.msl2.vert
- reference/shaders-msl-no-opt/comp/bda-restrict-pointer-variable.msl2.comp
- reference/shaders-msl/asm/comp/bitcast_iadd.asm.comp
- reference/shaders-msl/asm/comp/bitcast_icmp.asm.comp
- reference/shaders-msl/asm/comp/multiple-entry.asm.comp
- reference/shaders-msl/comp/buffer_device_address.msl2.comp
- reference/shaders-msl/vert/buffer_device_address.msl2.vert
- shaders-msl-no-opt/comp/bda-restrict-pointer-variable.msl2.comp
- spirv_msl.cpp
- spirv_msl.hpp
restrict was supported, but it broke in MSL 3.0. __restrict works on all versions, so opt for that instead.
Also check for RestrictPointer decoration and refactor to_restrict() to not take optional parameter to make it more obvious when implied space character is added.
Fix #2038.
> MSL: Fix restrict vs __restrict incompatibility.

- reference/shaders-msl-no-opt/comp/implicit-integer-promotion.comp
- reference/shaders-msl-no-opt/comp/int16min-literal.comp
- shaders-msl-no-opt/comp/implicit-integer-promotion.comp
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
MSL inherits the behavior of C where arithmetic on small types are implicitly converted to int. SPIR-V does not have this behavior, so make sure that arithmetic results are handled correctly.
Fix #2046.
> MSL: Handle implicit integer promotion rules.

- reference/opt/shaders-msl/asm/comp/op-spec-constant-op-vector-related.asm.comp
- reference/shaders-msl/asm/comp/op-spec-constant-op-vector-related.asm.comp
- shaders-msl/asm/comp/op-spec-constant-op-vector-related.asm.comp
- spirv_cross_containers.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
This op creates a new composite constant with one element replaced. So, we reconstruct the `SPIRConstant` for the composite constant, but with one of the IDs replaced. Constant initializer lists are memoized for when the result of a `CompositeInsert` is used in another `CompositeInsert`.
(I wanted to add a test case for GLSL as well, but for two things:
1. `glslang` in Vulkan mode chokes on the first constant array, insisting that its initializer needs to be a constant. [Bug in glslang?]
2. The declarations for the buffers used by the shader aren't emitted, regardless of whether Vulkan mode is enabled.)
Fixes five tests under
`dEQP-VK.spirv_assembly.instruction.*.opspecconstantop.vector_related`.
> MSL: Implement `CompositeInsert` `OpSpecConstantOp`.

- CMakeLists.txt
- reference/opt/shaders/legacy/vert/transpose.legacy.vert
- reference/opt/shaders/vert/read-from-row-major-array.vert
- reference/opt/shaders/vert/row-major-workaround.vert
- reference/shaders/legacy/vert/transpose.legacy.vert
- reference/shaders/vert/read-from-row-major-array.vert
- reference/shaders/vert/row-major-workaround.vert
- shaders/vert/row-major-workaround.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_glsl.cpp
- Consider that matrices can be both mediump and highp.
- Add workaround enablement to C API.
Fix #2066.
> Handle row major matrix workaround more gracefully

- reference/shaders-no-opt/asm/frag/complex-opaque-handle-reuse-in-loop.asm.frag
- shaders-no-opt/asm/frag/complex-opaque-handle-reuse-in-loop.asm.frag
- spirv_cross.cpp
- spirv_cross.hpp
Similar concern as access chains. Objects that we cannot lower to temporaries must implicitly access all expression dependencies when they are themselves accessed.
Fix #2068.
> CFG: Handle implied access to opaque loaded values.

- spirv_glsl.cpp
This typo came to my attention when I saw a warning about a `bool != uint32_t` comparison.
> Fixed typo in CompilerGLSL::should_dereference()

- CMakeLists.txt
- main.cpp
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- Add `CompilerMSL::Options::argument_buffers_tier` as an enumeration to allow calling app to specify platform argument buffer tier capabilities.
- Support iOS writable images in Tier2 argument buffers when specified.
Tier capabilities based on recommendations from Apple engineering.
> MSL: Add support for writable images in iOS Tier2 argument buffers.

- spirv_cross.cpp
- spirv_cross.hpp
After https://github.com/KhronosGroup/glslang/commit/7a914ce9261dd591ec793df42b5aba11d6c02848, glslang emits a new `OpLine` in for loops. This can be safely ignored.
Relevant specification docs:
1. https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_miscellaneous_instructions
2. https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_debug_instructions
Addresses https://github.com/KhronosGroup/SPIRV-Cross/issues/2079
> Accept glslang's new loop behavior

- reference/opt/shaders-hlsl/vert/legacy-int-attribute.sm30.vert
- reference/opt/shaders/legacy/vert/int-attribute.legacy.vert
- reference/shaders-hlsl/vert/legacy-int-attribute.sm30.vert
- reference/shaders/legacy/vert/int-attribute.legacy.vert
- shaders-hlsl/vert/legacy-int-attribute.sm30.vert
- shaders/legacy/vert/int-attribute.legacy.vert
- spirv_glsl.cpp
- spirv_hlsl.cpp
Hi, I'm back with more legacy fixes :)
spirv-cross rightly rejects uint vertex attributes, because uints are not supported by legacy GLSL at all.  However it does pass through *signed* integer inputs, even though they are not supported by legacy GLSL (the spec is very explicit that attributes must be float, even if this is popularly accepted, see also KhronosGroup/glslang#3111).
This PR changes these attributes to be declared as float and then automatically generates a typecast to convert them to int/ivec at OpLoad time.  The assumption is that the engine will just use plain old glVertexAttribPointer (since glVertexAttribIPointer is not available in legacy GL anyway) with the normalized flag set to GL_FALSE to supply these attributes.
This change is necessary for our vertex skinning …
> GLSL/HLSL: Add legacy handling for int vertex attributes

- spirv_glsl.cpp
The noperspective qualifier isn't in ESSL, so add a check to throw if it is used.
There is a GL_NV_shader_noperspective_interpolation (available for ES 3+) that adds support for it.
> GLSL: Support GL_NV_shader_noperspective_interpolation in GLES

- reference/opt/shaders-hlsl/vert/point-size.sm30.vert
- reference/shaders-hlsl/vert/point-size.sm30.vert
- shaders-hlsl/vert/point-size.sm30.vert
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Thank you for accepting my other PRs.
This one adds support for the `BuiltInPointSize` output in HLSL SM 3.0, which had a `PSIZE` semantic that matches the behaviour of `gl_PointSize`.
Tested to work with a shader that now shows identical results between DirectX 9 and OpenGL.
The `point_size_compat` option is now ignored if `shader_model <= 30`.
> HLSL: Support PointSize output in vertex shader in SM 3.0

- spirv_glsl.cpp
Compilation was broken for one of our deployment targets -
https://github.com/libretro/RetroArch/actions/runs/3969671032/jobs/6804472772
Fix happened to be quite trivial.
> (spirv_glsl.cpp) Fix error: no matching function for call to 'max(uint32_t&, unsigned int)'

- test_shaders.sh
This has stung me a couple of times now.  I thought it was useful that test_shaders ran the build automatically, so I started relying on it, but it doesn't early-out if compilation fails and the error messages immediately get lost amid the stream of printed paths, leading me think that my changes were OK.
> Add early exit for test_shaders if compilation fails

- reference/opt/shaders/legacy/vert/transpose.legacy.vert
- reference/shaders/legacy/vert/transpose.legacy.vert
- shaders/legacy/vert/transpose.legacy.vert
- spirv_glsl.cpp
Sorry for bombarding you with PRs lately!
This one is simple, it just prevents forcing the transpose when multiplying a matrix times a scalar.  We can just set need_transpose on the result.  It should be rare to actually need a forced transpose.
This comes up in eg. skinning shaders where a matrices might be linearly interpolated based on a set of blend weights, then multiplied with a vector.  No need to force transpose on all those matrices when we can just flip the multiplication order in the end.
> GLSL: Multiplying matrix with scalar shouldn't force transpose

- spirv_glsl.cpp
Briefly:
* `noperspective` on legacy desktop requires `GL_EXT_gpu_shader4`
* `sample` on ES requires 3.20 or (3.00 and `GL_OES_shader_multisample_interpolation`)
* `samplerCubeShadow` on legacy desktop requires `GL_EXT_gpu_shader4`
* `samplerCubeShadow` on legacy ES requires `GL_NV_shadow_samplers_cube` (with `NV` suffix)
* `gl_Clip/CullDistance` on ES requires `GL_EXT_clip_cull_distance`
* `textureQueryLod` on ES requires `GL_EXT_texture_query_lod` (and is called `textureQueryLOD`)
* `texture/imageSamples` requires desktop 4.50 or `GL_ARB_texture_query_samples`
* `uint` on legacy desktop requires `GL_EXT_gpu_shader4`
* `atomic_uint` requires desktop 4.20 or `GL_ARB_shader_atomic_counters`
* `gl_Sample*` on desktop requires 4.00 or `GL_ARB_sample_shading`
Thanks!
> GLSL: Add various missing extension checks

- reference/shaders/frag/shader-clock.frag
- shaders/frag/shader-clock.frag
- spirv_glsl.cpp
This adds support for `OpReadClockKHR` to `CompilerGLSL`.
Relevant docs:
- https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_shader_clock.html
- https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_shader_clock.html
- https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_realtime_clock.txt
- https://registry.khronos.org/OpenGL/extensions/ARB/ARB_shader_clock.txt
> GLSL: Support OpReadClockKHR

- spirv_glsl.cpp
GLSL 110 doesn't have `invariant`.  ESSL 100 does.
I don't personally care enough about GLSL 110 to add a feature check for this in our engine, maybe it's OK to just drop it?  If you prefer to throw then I can do that too.
I don't think emulating it is at all possible, other than in a very specific situation with `ftransform()`, and that requires setting the fixed-function GL modelview/projection matrices, I don't expect anyone will go through that bother either.
> GLSL: Drop invariant keyword in GLSL 110

- reference/opt/shaders/legacy/fragment/isnan-isinf.legacy.frag
- reference/opt/shaders/legacy/fragment/modf.legacy.frag
- reference/shaders/legacy/fragment/isnan-isinf.legacy.frag
- reference/shaders/legacy/fragment/modf.legacy.frag
- shaders/legacy/fragment/isnan-isinf.legacy.frag
- shaders/legacy/fragment/modf.legacy.frag
- spirv_glsl.cpp
- spirv_hlsl.cpp
These functions are missing in legacy GLSL but added in 130 / 300es.  More coming soon (sinh and friends still missing) but wanted to get this out for review first.
I wanted to implement isinf as `v == v && v * 0.0 != v * 0.0` but that doesn't seem to work reliably on the implementations I tested.  The formula `v != 0.0 && 2.0 * v == v` , which is used in Cg, does work.  I didn't want to simply compare to `1.0 / 0.0` since the result of dividing by zero is unspecified in legacy GLSL, so it might produce false positives somewhere.
Unfortunately in GLSL the && operator doesn't work component-wise and it doesn't have an `and()` function, so I have to write out the isinf expression per component.  I'm not really worried about performance in any case, I'm just adding this function for …
> GLSL: Add support for trunc, modf, isnan and isinf in legacy GLSL

- reference/opt/shaders-hlsl/frag/hyperbolic.frag
- reference/opt/shaders/legacy/fragment/hyperbolic.legacy.frag
- reference/shaders-hlsl/frag/hyperbolic.frag
- reference/shaders/legacy/fragment/hyperbolic.legacy.frag
- shaders-hlsl/frag/hyperbolic.frag
- shaders/legacy/fragment/hyperbolic.legacy.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
Hyperbolics were added in GLSL 1.30.  Furthermore, the inverse functions are not supported in any version of HLSL.  This implements them.  The math has been tested.
I would appreciate a review of the GLSLstd450Tanh logic in particular since it creates intermediate temporaries.  I'm not sure I understand the `extra_sub_expressions` logic and whether I need to use it here.
> GLSL/HLSL: Add emulated fallbacks for hyperbolic math functions

- spirv_hlsl.cpp
Shader Model 6.7 introduces integer samplers: https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_7_Advanced_Texture_Ops.html#integer-sampling. However, if one tries to transpile this simple GLSL shader to HLSL, even with setting the shader model to 67, they will get the error message `Sampling non-float textures is not supported in HLSL`. 
```glsl
#version 450
layout(push_constant) uniform UniformBufferObject{
mat4 viewProj;
} ubo;
layout(location = 0) in vec3 inPosition;
layout(location = 1) in vec3 inNormal;
layout(location = 2) in vec2 inUV;
layout(location = 0) out vec3 fragColor;
layout(location = 1) out vec2 outUV;
void main() {
mat4 model = mat4(1);
vec4 worldpos = model * vec4(inPosition,1);
gl_Position = ubo.viewProj * worldpos;
fragColor = vec3(1,1,1);
outUV = inUV;
}
``` …
> Support integer samplers in Shader Model 6.7

- reference/opt/shaders-msl/asm/comp/duplicate-spec-id.asm.comp
- reference/opt/shaders-msl/comp/local-size-duplicate-spec-id.comp
- reference/shaders-msl/asm/comp/duplicate-spec-id.asm.comp
- reference/shaders-msl/comp/local-size-duplicate-spec-id.comp
- shaders-msl/asm/comp/duplicate-spec-id.asm.comp
- shaders-msl/comp/local-size-duplicate-spec-id.comp
- spirv_msl.cpp
It is possible in SPIR-V to declare multiple specialization constants with the same constant ID. The most common cause of this in GLSL is defining a spec constant, then declaring the workgroup size to use that spec constant by its ID. But, MSL forbids defining multiple function constants with the same function constant ID. So, we must only emit one definition of the actual function constant (with the `[[function_constant(id)]]` attribute); but we can point the other variables at this one definition.
Fixes three tests in the Vulkan CTS under
`dEQP-VK.compute.basic.max_local_size_*`.
> MSL: Deduplicate function constants.

- reference/opt/shaders-msl/comp/atomic-float.msl3.comp
- reference/shaders-msl/comp/atomic-float.msl3.comp
- shaders-msl/comp/atomic-float.msl3.comp
- spirv_msl.cpp
- test_shaders.py
These are now available in Metal 3.0, which is only enabled on MacOS 13.x in MoltenVK, where OpAtomicFAddEXT has been tested all the way through, per this discussion: https://github.com/KhronosGroup/MoltenVK/discussions/1616#discussioncomment-4868519
Can also run the metal compiler on code generated using spirv-cross under 12.x and it works fine.
In my testing, it appeared to already have all the necessary logic to require the https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_shader_atomic_float.html and associated SPV extensions to actually enable the use of atomic add on float types, so all that was needed was to put the parsing in the right place.
> add support for OpAtomicFAddEXT atomic add, and also Min, Max

- spirv_glsl.cpp
This fixes a bug that was exposed when targeting GLSL with Vulkan semantics while 'force_temporary' is enabled.
> GLSL: Don't create temporaries for sampled image types in GLSL.

- spirv_cross_containers.hpp
https://reviews.llvm.org/D146097 removed the transitive include for <exception>, which caused the following issue:
In file included from ../../third_party/spirv-cross/spirv_common.hpp:28: ../../third_party/spirv-cross/spirv_cross_containers.hpp:334:9: error: no member named 'terminate' in namespace 'std
This patch adds the missing include to fix the issue.
> Add missing <exception> include

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
This PR adds set_scalar functions for all equivalent get_scalar functions in the specialization constants part of the C API.
I've tested this and it seems to work fine.
> Implement set_scalar functions in the specialization constants C API

- spirv_hlsl.cpp
According to the D3D11 API, `SV_RenderTargetArrayIndex` is not restricted to geometry or mesh shaders if the Direct3D 11.3 feature `D3D11_FEATURE_DATA_D3D11_OPTIONS3::VPAndRTArrayIndexFromAnyShaderFeedingRasterizer` is enabled:
> If [D3D11_FEATURE_DATA_D3D11_OPTIONS3::VPAndRTArrayIndexFromAnyShaderFeedingRasterizer](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_feature_data_d3d11_options3) is true, then SV_RenderTargetArrayIndex is applied to any shader feeding the rasterizer.
> HLSL: Don't restrict SV_RenderTargetArrayIndex to GS and MS.

- spirv_glsl.cpp
The vec4-boundary check for HLSL packing alignment must be done with the actual field offset. Otherwise, optimized SPIR-V (`spirv-opt -Os` in particular) will fail to be validated correctly.
This issue can be reproduced with the following HLSL input:
```hlsl
cbuffer Test {
float3 V0_xyz_; // Offset:   0
float  V0____w; // Offset:  12
float2 V1_xy__; // Offset:  16
float2 V1___zw; // Offset:  24
}
float4 PSMain() : SV_Target {
return float4(V0_xyz_, V1___zw.r);
};
```
Compile with DXC as follows:
```
dxc Input.hlsl -T ps_6_0 -E PSMain -spirv -Fo Output.spv
```
Then optimize using SPIRV-Tools like this:
```
spirv-opt -Os Output.spv -o Optimized.spv
```
This will remove unused field from the struct but maintain the same offsets, i.e. SPIRV-Cross won't be able to track `V0____w` and `V1_xy__` …
> GLSL: Use actual field offset to validate vec4 boundary alignment.

- reference/shaders-no-opt/comp/subgroups_arithmetic_fadd.vk.comp
- reference/shaders-no-opt/comp/subgroups_arithmetic_fadd.vk.comp.vk
- reference/shaders-no-opt/comp/subgroups_arithmetic_fmul.vk.comp
- reference/shaders-no-opt/comp/subgroups_arithmetic_fmul.vk.comp.vk
- reference/shaders-no-opt/comp/subgroups_arithmetic_iadd.vk.comp
- reference/shaders-no-opt/comp/subgroups_arithmetic_iadd.vk.comp.vk
- reference/shaders-no-opt/comp/subgroups_arithmetic_imul.vk.comp
- reference/shaders-no-opt/comp/subgroups_arithmetic_imul.vk.comp.vk
- shaders-no-opt/comp/subgroups_arithmetic_fadd.vk.comp
- shaders-no-opt/comp/subgroups_arithmetic_fmul.vk.comp
- shaders-no-opt/comp/subgroups_arithmetic_iadd.vk.comp
- shaders-no-opt/comp/subgroups_arithmetic_imul.vk.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
Support OpenGL workarounds for subgroup arithmetic group operations.
NVIDIA workarounds are based on  GL_NV_shader_thread_shuffle.
AMD workarounds will be based on GL_AMD_shader_ballot.
Related issue  #1479
> GLSL: Support GL_KHR_shader_subgroup_arithmetic (WIP)

- spirv_msl.cpp
Example broken shader (compile with `--msl --msl-version 20300 --msl-sample-dref-lod-array-as-grad`): [shader-fs-090d3829caba1bbc.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/11457235/shader-fs-090d3829caba1bbc.spv.zip)
> MSL: Fix dref lod workaround on combined texture/samplers

- reference/shaders-hlsl/asm/frag/array-of-structured-buffers.asm.frag
- reference/shaders-hlsl/asm/frag/structured-buffer.asm.frag
- shaders-hlsl/asm/frag/array-of-structured-buffers.frag
- shaders-hlsl/asm/frag/structured-buffer.frag
- spirv_common.hpp
- spirv_cross_parsed_ir.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
This PR adds support to the HLSL backend to preserve `RW`-/`StructuredBuffer` resources when cross-compiling HLSL-to-HLSL. UE5 does this to support modern HLSL2021 features such as templates across all platforms including the D3D11 RHI where DXBC is the only supported shader bytecode but FXC does not support those features. Translating `StructuredBuffer` to `ByteAddressBuffer` breaks the resource binding. These changes make use of the `UserTypeGOOGLE` extension to preserve the original resource type. This feature is disable by default and can be enabled via the `preserve_structured_buffers` option.
> HLSL: Add support to preserve (RW)StructuredBuffer resources.

- spirv_msl.cpp
Previously, if a constant without `DecorationSpecId` occurred before the constant with `DecorationSpecId` 0, it would be inserted into the `unique_func_constants` map with key 0 (the default return value from `get_decoration`). This prevented us from ever emitting the declaration with `[[function_constant(0)]]`, which produced some bizarre MSL compilation errors.
Instead, we now only insert into `unique_func_constants` when we know we're going to emit a `[[function_constant(…)]]` line.
This regressed in 41007cdc7d9c3a1f9b61e307d149f94a68fa3c9c.
> MSL: fix function constant deduplication misfire

- reference/shaders-no-opt/asm/frag/phi-alternative-precision.asm..vk.nocompat.frag.vk
- reference/shaders-no-opt/asm/frag/relaxed-precision-inheritance-rules.asm.frag
- shaders-no-opt/asm/frag/phi-alternative-precision.asm..vk.nocompat.frag
- spirv_glsl.cpp
> GLSL: Fix bug with mixed precision on PHI variables.

- reference/opt/shaders-msl/comp/shader_ballot.msl22.comp
- reference/opt/shaders-msl/comp/shader_group_vote.msl21.comp
- reference/shaders-msl/comp/shader_ballot.msl22.comp
- reference/shaders-msl/comp/shader_group_vote.msl21.comp
- shaders-msl/comp/shader_ballot.msl22.comp
- shaders-msl/comp/shader_group_vote.msl21.comp
- spirv_msl.cpp
Normally, I wouldn't have bothered with this, given that we already support the Vulkan 1.1 subgroup functionality, but a client asked for the legacy extensions.
> MSL: Support `SPV_KHR_shader_ballot` and `SPV_KHR_subgroup_vote`.

- reference/opt/shaders-msl/asm/comp/image-load-store-short-vector.invalid.asm.comp
- reference/opt/shaders-msl/desktop-only/frag/image-ms.desktop.frag
- reference/shaders-msl/asm/comp/image-load-store-short-vector.invalid.asm.comp
- reference/shaders-msl/desktop-only/frag/image-ms.desktop.frag
- spirv_msl.cpp
- spirv_msl.hpp
MSL makes no guarantees on coherency of reads from textures, even if written earlier by the same thread.  This is isn't explicitly stated, but implied by section 6.12.17 of the [MSL spec](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf), since the `fence()` method would be completely useless otherwise:
> The texture `fence()` member function ensures that writes to the texture by a thread become visible to subsequent reads from that texture by the same thread (the thread that is performing the write). Texture types (including texture buffers) that you can declare with the `access::read_write` attribute support the `Fence` function.
On the other hand, [GLSL makes stronger guarantees](https://www.khronos.org/opengl/wiki/Memory_Model#Incoherent_memory_access):
> If …
> [WIP] MSL: Prevent RAW hazards on read_write textures

- reference/opt/shaders/asm/vert/invariant-block.sso.asm.vert
- reference/opt/shaders/asm/vert/invariant.sso.asm.vert
- reference/shaders-no-opt/asm/mesh/invariant-position-dx-style.vk.nocompat.spv14.asm.mesh.vk
- reference/shaders-no-opt/mesh/invariant-position-mesh.spv14.nocompat.vk.mesh.vk
- reference/shaders/asm/vert/invariant-block.sso.asm.vert
- reference/shaders/asm/vert/invariant.sso.asm.vert
- shaders-no-opt/asm/mesh/invariant-position-dx-style.vk.nocompat.spv14.asm.mesh
- shaders-no-opt/mesh/invariant-position-mesh.spv14.nocompat.vk.mesh
- spirv_glsl.cpp
Work around missing feature from GLSL. Normally we can emit a global invariant gl_Position; and call it a day, but it does not work for mesh shaders it seems. Declaring invariance inside an explicit IO block works fine on the other hand ...
> GLSL: Emit inline invariant position for mesh shaders.

- spirv_msl.cpp
There is a code-gen error, If shader uses runtime-array of images + rich descriptors:
No need to emit wrapper for `spvDescriptorArray<spvBufferDescriptor>`, since there is no `spvBufferDescriptor`
> Fixup check for SPVFuncImplVariableSizedDescriptor

- reference/shaders-msl-no-opt/frag/ray-query-mutability.spv14.vk.msl24.frag
- shaders-msl-no-opt/frag/ray-query-mutability.spv14.vk.msl24.frag
- spirv_msl.cpp
This commit fixes wrong code-gen, when rayQuery object is wrongly passed to function with `const` qualifier.
> MSL: fix mutability for rayQueryEXT parameters

- reference/shaders-msl-no-opt/comp/extract-atomics-from-function.comp
- shaders-msl-no-opt/comp/extract-atomics-from-function.comp
- spirv_msl.cpp
Before:
```c++
void testAdd()
{
uint _29 = atomic_fetch_add_explicit((threadgroup atomic_uint*)&var, 1u, memory_order_relaxed);
}
```
After:
```c++
static inline __attribute__((always_inline))
void testAdd(threadgroup uint& var)
{
...
```
> MSL: fix extraction of global variables, in case of atomics

- reference/shaders-hlsl/comp/ssbo-store-array.comp
- shaders-hlsl/comp/ssbo-store-array.comp
- spirv_hlsl.cpp
Original code wasn't accounting for pointers, when unrolling types in `write_access_chain_array`
#fixed #2196
> Fix unroll, when storing to pointer to array

- .github/workflows/main.yml
- Caches externals so they don't get rebuilt every time
- Parallelizes build
macOS build time goes from 30m to 15m (no cache) / 7m (with cache)
In addition, when the cache is available, you should get feedback on compilation errors within a minute or so
> Improve CI build times

- reference/opt/shaders-hlsl/comp/ssbo-store-array.comp
- reference/shaders-no-opt/asm/comp/block-undef.noeliminate.invalid.asm.comp
- reference/shaders-no-opt/asm/comp/empty-ubo-block.noeliminate.asm.comp
- shaders-no-opt/asm/comp/block-undef.noeliminate.invalid.asm.comp
- shaders-no-opt/asm/comp/empty-ubo-block.noeliminate.asm.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
Fix #2210.
- Test 1 declares an empty block type. The simple workaround is to declare dummy member similar to other structs.
- Test 2 is invalid SPIR-V. It declares an OpUndef of a Block type. That block type has OpRuntimeArray, which is illegal and trips `VUID-StandaloneSpirv-OpTypeRuntimeArray-04680`.
- Test 3 is also invalid SPIR-V. It declares a variable pointer to Block type. That block type also has OpRuntimeArray which is illegal. GLSL backend also does not support variable pointers, so it cannot be supported.
This PR fixes 1, adds a workaround for 2 and ignores 3 since it's too broken SPIR-V for us to hack around.
> GLSL: Fix and workaround some awkward code patterns

- main.cpp
- reference/opt/shaders-msl/comp/metal3_1_regression_patch.replace-recursive-inputs.msl3.comp
- reference/shaders-msl/comp/metal3_1_regression_patch.replace-recursive-inputs.msl3.comp
- shaders-msl/comp/metal3_1_regression_patch.replace-recursive-inputs.msl3.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
- test_shaders.sh
Metal 3.1 introduced a Metal regression bug which causes an infinite recursion crash during Metal's analysis of an entry point input structure that itself contains internal recursion. This patch works around this by replacing the recursive input declaration with a alternate variable of type void*, and then casting to the correct type at the top of the entry point function.
- Add `CompilerMSL::Options::replace_recursive_inputs` to enable replacing recursive input.
- Add `Compiler::type_contains_recursion()` to determine if a struct contains internal recursion, and add custom Decorations to mark such structs, to short-cut future similar checks.
- Replace recursive input struct declarations with void*, and emit a recast to correct type at top of entry function.
- Add unit test.
- …
> MSL: Workaround Metal 3.1 regression bug on recursive input structs.

- reference/opt/shaders-hlsl/frag/sample-mask-in-and-out.frag
- reference/opt/shaders-hlsl/frag/sample-mask-in.frag
- reference/opt/shaders-hlsl/frag/sample-mask-out.frag
- reference/shaders-hlsl/frag/sample-mask-in-and-out.frag
- reference/shaders-hlsl/frag/sample-mask-in.frag
- reference/shaders-hlsl/frag/sample-mask-out.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
This might not be the right place, but I wanted to start with a proposal to fix an issue with the cross-compilation of `gl_SampleMask` (GLSL) to `SV_Coverage` (HLSL).
I saw that SPIRV-Cross is already handling the case that `gl_SampleMask` is an array of bits while the corresponding `SV_Coverage` in HLSL is a scalar bitmask. However, the necessary information for that built-in type gets lost in `OpLoad` instructions because that decoration is not propagated to the resulting variable. I am not sure if this solution would break other cases that need the built-in types. A better solution would probably be to mark such variables in how their underlying type has to be interpreted for non-GLSL backends instead of copying the built-in decoration.
The issue can be observed with this simple HLSL …
> Fix declaration of `gl_SampleMaskIn` in HLSL backend.

- reference/shaders-msl-no-opt/frag/ray-query-mutability.spv14.vk.msl24.frag
- spirv_msl.cpp
- spirv_msl.hpp
Argument buffers can contain multiple runtime arrays if they have fixed lengths as specified by the binding API. Regression error had assumed each runtime array is in separate argument buffer with undefined array length.
- Add `CompilerMSL::is_var_runtime_size_array()` to include test for setting of array length via `CompilerMSL::add_msl_resource_binding()`.
- Fixed unrelated test case MSL compile syntax failure when acceleration structure is the first entry point function argument (unrelated).
This has been tested in MoltenVK, but I couldn't think of a way of defining a SPRIV-Cross unit test for this, as it would involve calling `add_msl_resource_binding()` with some complex input.
> MSL: Fix regression error in argument buffer runtime arrays.

- spirv_glsl.cpp
> Workaround for generating bool uniforms in ESSL1

- .gitignore
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
This PR does not change the current behavior. It only works when invoking `set_float_formatter()` with initiative.
I use `std::shared_ptr` to store a `FloatFormatter` virtual base object, because it can use customized deleter (compare to `std::unique_ptr`). Would it be better to just use a raw pointer `FloatFormatter*` and require the user to keep it valid?
Related issues: #2132 #1599
> Allow to customize float literals in output

- spirv_msl.cpp
Fix #2228.
Blind fix, but it's so trivial.
> MSL: Add divide to reserved function names.

- reference/opt/shaders-msl/comp/atomic-image.comp
- reference/opt/shaders-msl/comp/atomic-image.msl31.comp
- reference/opt/shaders-msl/frag/frag-demote-checks.discard-checks.msl31.frag
- reference/opt/shaders-msl/frag/frag-discard-checks-continue-block.discard-checks.msl31.frag
- reference/opt/shaders-msl/frag/frag-discard-checks.discard-checks.msl31.frag
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl31.argument.frag
- reference/opt/shaders-msl/frag/pixel-interlock-ordered.msl31.frag
- reference/shaders-msl-no-opt/comp/image-array-atomic.msl31.comp
- reference/shaders-msl/comp/atomic-image.comp
- reference/shaders-msl/comp/atomic-image.msl31.comp
- reference/shaders-msl/frag/frag-demote-checks.discard-checks.msl31.frag
- reference/shaders-msl/frag/frag-discard-checks-continue-block.discard-checks.msl31.frag
- reference/shaders-msl/frag/frag-discard-checks.discard-checks.msl23.frag
- reference/shaders-msl/frag/frag-discard-checks.discard-checks.msl31.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl31.argument.frag
- reference/shaders-msl/frag/pixel-interlock-ordered.msl31.frag
- shaders-msl-no-opt/comp/image-array-atomic.msl31.comp
- shaders-msl/comp/atomic-image.comp
- shaders-msl/comp/atomic-image.msl31.comp
- shaders-msl/frag/frag-demote-checks.discard-checks.msl31.frag
- shaders-msl/frag/frag-discard-checks-continue-block.discard-checks.msl31.frag
- shaders-msl/frag/frag-discard-checks.discard-checks.msl31.frag
- shaders-msl/frag/pixel-interlock-ordered.msl31.argument.frag
- shaders-msl/frag/pixel-interlock-ordered.msl31.frag
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Current CI does not have Metal 3.1 support, but I added support for testing against the Windows tooling, and it passes with that.
Fix #2212.
> MSL: Implement MSL 3.1 image atomics natively

- reference/opt/shaders-msl/tese/read-patch-vertices-in-func.raw-tess-in.tese
- reference/opt/shaders/tese/read-patch-vertices-in-func.tese
- reference/shaders-msl/tese/read-patch-vertices-in-func.raw-tess-in.tese
- reference/shaders/tese/read-patch-vertices-in-func.tese
- shaders-msl/tese/read-patch-vertices-in-func.raw-tess-in.tese
- shaders/tese/read-patch-vertices-in-func.tese
- spirv_glsl.cpp
- spirv_msl.cpp
We can no longer rely on the `patch_control_point<>` array being present, so the best we can do is use the value given us at compile time.
This was an oversight on my part when I initially implemented the raw-buffer tessellation evaluation input mode. The lack of tests for the `PatchVertices` built-in almost certainly contributed, so I fixed that in this patch.
Fixes the test
`dEQP-VK.tessellation.shader_input_output.patch_vertices_in_tes`. This is the last failing test under `dEQP-VK.tessellation`.
> MSL: Fix patch vertex count with raw buffer tese input.

- reference/opt/shaders-msl/comp/ray-query.spv14.vk.ios.msl24..invalid.comp
- reference/opt/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
- reference/opt/shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
- reference/shaders-msl-no-opt/frag/ray-query-mutability.spv14.vk.msl24.frag
- reference/shaders-msl/comp/ray-query.spv14.vk.ios.msl24..invalid.comp
- reference/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
- reference/shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
- spirv_msl.cpp
Small PR. I think this is the last one for ray-query - now MSL has feature parity with spirv.
> MSL: add ray-cull mask

- .gitignore
- spirv_msl.cpp
- spirv_msl.hpp
An entry-point array of buffers, that is not part of a Metal argument buffer, requires a known length, so it can be emitted as discrete buffers. For runtime arrays of resources, this can be retrieved from the resource binding information added via `add_msl_resource_binding()`.
- Redefine `get_resource_array_size()` to consolidate array sizing using both var type, and runtime array sizing from resource bindings, if not found in type.
- Use `get_resource_array_size()` to fix issue for runtime arrays of buffers.
- Update runtime arrays of images and samplers to use `get_resource_array_size()`.
- Add `.DS_Store` to `.gitignore` (unrelated).
This has been tested in MoltenVK, but I couldn't think of a way of defining a SPRIV-Cross unit test for this, as it would involve calling …
> MSL: Ensure discrete runtime arrays of buffers have known length.

- reference/shaders-hlsl-no-opt/comp/substruct-cbuffer-packing-straddle-top-level.comp
- reference/shaders-hlsl-no-opt/comp/substruct-cbuffer-packing-straddle.comp
- shaders-hlsl-no-opt/comp/substruct-cbuffer-packing-straddle-top-level.comp
- shaders-hlsl-no-opt/comp/substruct-cbuffer-packing-straddle.comp
- spirv_glsl.cpp
> HLSL: Fix issue with vec4 straddle rules in substructs.

- reference/opt/shaders/frag/block-match-sad.frag
- reference/opt/shaders/frag/block-match-ssd.frag
- reference/opt/shaders/frag/box-filter.frag
- reference/opt/shaders/frag/sample-weighted.frag
- reference/opt/shaders/vulkan/frag/block-match-sad.frag
- reference/opt/shaders/vulkan/frag/block-match-ssd.frag
- reference/opt/shaders/vulkan/frag/box-filter.frag
- reference/opt/shaders/vulkan/frag/sample-weighted.frag
- reference/shaders/frag/block-match-sad.frag
- reference/shaders/frag/block-match-ssd.frag
- reference/shaders/frag/box-filter.frag
- reference/shaders/frag/sample-weighted.frag
- reference/shaders/vulkan/frag/block-match-sad.frag
- reference/shaders/vulkan/frag/block-match-ssd.frag
- reference/shaders/vulkan/frag/box-filter.frag
- reference/shaders/vulkan/frag/sample-weighted.frag
- shaders/vulkan/frag/block-match-sad.frag
- shaders/vulkan/frag/block-match-ssd.frag
- shaders/vulkan/frag/box-filter.frag
- shaders/vulkan/frag/sample-weighted.frag
- spirv.h
- spirv.hpp
- spirv_glsl.cpp
- spirv_reflect.cpp
1. Add support for the SPV_QCOM_image_processing extension
2. Add four unit tests
3. Fix minor issues in other unit tests
Please note that 
the following test failed with "The flag --preserve-numeric-ids was specified multiple times."
shaders-no-opt/asm/frag/opaque-id-literal-alias.preserve.asm.frag
the following test failed with "The type of Value must match the Result type"
shaders-no-opt/asm/frag/subgroup-arithmetic-cast.nocompat.vk.asm.frag
shaders-msl-no-opt/asm/frag/subgroup-arithmetic-cast.msl21.asm.frag
%18 = OpGroupNonUniformSMin %uint %uint_3 Reduce %16
the following tests failed with "Selection must be structured"
shaders-no-opt/asm/comp/loop-variable-early-read-with-initializer.asm.comp
OpBranchConditional %69 %12 %13 …
> Add support for the SPV_QCOM_image_processing extension

- CMakeLists.txt
> Bump to CMake 3.6 and handle deprecated Python module check.

- reference/shaders-no-opt/asm/comp/bda-to-array-in-buffer.asm.spv16.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-chained-access.spv16.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-plain-struct.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-pod-in-buffer.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-std140-std430-array.asm.spv16.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-unused-pod-in-buffer.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-to-pointer.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp.vk
- shaders-no-opt/asm/comp/buffer-reference-chained-access.spv16.asm.nocompat.vk.comp
- shaders-no-opt/asm/comp/buffer-reference-pointer-to-plain-struct.asm.nocompat.vk.comp
- shaders-no-opt/asm/comp/buffer-reference-pointer-to-std140-std430-array.asm.spv16.nocompat.vk.comp
- shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-to-pointer.asm.nocompat.vk.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- Handle pointer to non-Block-decorated OpTypeStruct.
- Be more careful about types we forward.
- Handle non-block pointer-to-pointer.
- Handle casts to ptr-to-array types with different ArrayStride.
> GLSL: Improve BDA handling in esoteric situations

- spirv_common.hpp
If windows.h is included before spirv_common.hpp without `NOMINMAX` being defined the windows min and max macros will conflict with the STL `std::numeric_limits` functions.
> Fixed conflict with windows min() and max() macros in spirv_common.hpp

- reference/opt/shaders-msl/comp/coherent-image-atomic.comp
- reference/opt/shaders-msl/comp/coherent-image-atomic.msl2.argument.comp
- reference/opt/shaders-msl/comp/coherent-image-atomic.msl2.comp
- reference/opt/shaders-msl/comp/coherent-image-atomic.msl31.argument.comp
- reference/opt/shaders-msl/comp/coherent-image-atomic.msl31.comp
- reference/shaders-msl/comp/coherent-image-atomic.comp
- reference/shaders-msl/comp/coherent-image-atomic.msl2.argument.comp
- reference/shaders-msl/comp/coherent-image-atomic.msl2.comp
- reference/shaders-msl/comp/coherent-image-atomic.msl31.argument.comp
- reference/shaders-msl/comp/coherent-image-atomic.msl31.comp
- shaders-msl/comp/coherent-image-atomic.comp
- shaders-msl/comp/coherent-image-atomic.msl2.argument.comp
- shaders-msl/comp/coherent-image-atomic.msl2.comp
- shaders-msl/comp/coherent-image-atomic.msl31.argument.comp
- shaders-msl/comp/coherent-image-atomic.msl31.comp
- spirv_msl.cpp
- spirv_msl.hpp
> MSL: Handle volatile properly for emulated image atomics.

- reference/opt/shaders-msl/frag/runtime_array_as_argument_buffer_buf.msl3.argument-tier-1.rich-descriptor.frag
- reference/shaders-msl/frag/runtime_array_as_argument_buffer_buf.msl3.argument-tier-1.rich-descriptor.frag
- shaders-msl/frag/runtime_array_as_argument_buffer_buf.msl3.argument-tier-1.rich-descriptor.frag
- spirv_msl.cpp
forward declaration of 
```c++
template<typename T>
struct spvDescriptorArray;
```
been missing, and without it template specialization is not compilable.
Issue wasn't triggered before, due to bindless ubo/texture/tlas/etc will emit full template and hide the issue.
> Fix codegen for shader with only bindless ssbo

- spirv_cross_error_handling.hpp
No temporary `std::string` is created when `const char*` is passed to `SPIRV_CROSS_THROW` (like this: `SPIRV_CROSS_THROW("Cannot resolve expression type.");`).
This helps to bypass the issue #2273 where using `_HAS_EXCEPTIONS=0` can lead to invalid error messages when compiled with MSVC.
> Add CompilerError constructor that accepts const char* as a parameter (Fixes #2273)

- spirv_msl.cpp
`CompilerMSL:msl_options.texture_1D_as_2D` emulates a Metal 1D texture as a 2D texture in order to expand features available for 1D textures. Support accessing such textures as 2D for `atomic_compare_exchange_weak()`.
> MSL: atomic_compare_exchange_weak() support CompilerMSL:msl_options.texture_1D_as_2D.

- spirv_msl.cpp
MSL: `atomic_compare_exchange_weak()` support `CompilerMSL:msl_options.texture_1D_as_2D`.
- `CompilerMSL:msl_options.texture_1D_as_2D` emulates a Metal 1D texture as a 2D texture in order to expand features available for 1D textures. Support accessing such textures as 2D for `atomic_compare_exchange_weak()`.
This was originally pulled into the SPIRV-Cross `vulkan-sdk-1.3.280-moltenvk` branch in order to have it available for the Vulkan SDK release. This PR is to pull the contributions into `main`.
> MSL: Merge `vulkan-sdk-1.3.280-moltenvk` branch into `main` branch.

- spirv_common.hpp
- spirv_cross.cpp
Prevent cases where arrays that are globally defined constants are redeclared on stack. On Intel macs, declaring a large, statically initialized spvUnsafeArray on stack may cause an internal compiler error.
> Support cases of LUTs which are not function local.

- spirv_glsl.cpp
Somehow this hasn't been caught until now. Impressive.
We'll have to emit side effects in condition block to make this work, which breaks loop conditionals.
Fix #2285.
> Block loop optimization if Phi is used.

- reference/opt/shaders-msl/comp/composite-array-initialization.force-native-array.comp
- reference/shaders-msl-no-opt/asm/comp/device-array-load-temporary.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-array-load-temporary.force-native-array.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-constant-array-load-store.asm.comp
- reference/shaders-msl-no-opt/asm/comp/device-constant-array-load-store.force-native-array.asm.comp
- reference/shaders-msl-no-opt/asm/frag/copy-memory-block-like-thread-local.asm.frag
- reference/shaders-msl-no-opt/vert/pass-array-by-value.force-native-array.vert
- reference/shaders-msl/comp/composite-array-initialization.force-native-array.comp
- reference/shaders-msl/comp/copy-array-of-arrays.force-native-array.comp
- reference/shaders-msl/vert/return-array.force-native-array.vert
- spirv_msl.cpp
- spirv_msl.hpp
I realize it's unlikely to have a >6-deep array, but the limitation was still bothering me
There's a comment on the old code saying you couldn't use recursive templates, but I couldn't get the recursive template to break on anything I tried, including Xcode 8 targeting macOS 10.11, macOS 10.13's online compiler, or Xcode 14 targeting iOS 8.  Do you remember why you originally put in that comment?  If so, maybe we should add where it fails to that comment so it can be removed in the future if support for whatever it fails on is ever dropped.
> Use recursive template for spvArrayCopy

- reference/shaders-msl-no-opt/asm/comp/image-atomic-mismatch-sign.asm.msl31.comp
- shaders-msl-no-opt/asm/comp/image-atomic-mismatch-sign.asm.msl31.comp
- spirv_msl.cpp
- spirv_msl.hpp
Gross reinterpret_cast, but gotta do what you gotta do.
Fix #2303.
> MSL: Handle Atomic{S,U}{Min,Max} with mismatched image sign.

- spirv_msl.cpp
- After padding a resource, retrieve either the next padded slot, or the next resource, in order to correctly offset the slot index.
Fixes issue #2198.
> MSL: Fix argument buffer padding.

- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
Inner function calls can contain flow-control sensitive code. In this case, the function call itself must inherit the control-dependence.
Rarely happens in practice since optimized code with SSA tends to inline.
> Mark function call results as control dependent as necessary.

- reference/opt/shaders-msl/frag/gather-compare-const-offsets.frag
- reference/opt/shaders-msl/frag/gather-const-offsets.frag
- reference/shaders-msl/frag/gather-compare-const-offsets.frag
- reference/shaders-msl/frag/gather-const-offsets.frag
- shaders-msl/frag/gather-compare-const-offsets.frag
- shaders-msl/frag/gather-const-offsets.frag
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
- Add `TextureFunctionArguments::has_array_offsets`.
- Add support functions `spvGatherConstOffsets()` & `spvGatherCompareConstOffsets()`.
- Add `SPVFuncImpl::SPVFuncImplGatherConstOffsets` & `SPVFuncImplGatherCompareConstOffsets`.
- Add unit tests.
@cdavis5e Please review too.
> MSL: Support ConstOffsets on image gather.

- spirv_cpp.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_hlsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Fix some issues with aliasing, and also ensures that declared array sizes always match the layout.
Fix #2318.
> MSL: Improve handling of padded descriptors with argument buffers

- main.cpp
- reference/opt/shaders-msl/frag/force-depth-write-early-tests.input-attachment-is-ds-attachment.frag
- reference/opt/shaders-msl/frag/force-depth-write-false.input-attachment-is-ds-attachment.frag
- reference/opt/shaders-msl/frag/force-depth-write.input-attachment-is-ds-attachment.frag
- reference/shaders-msl/frag/force-depth-write-early-tests.input-attachment-is-ds-attachment.frag
- reference/shaders-msl/frag/force-depth-write-false.input-attachment-is-ds-attachment.frag
- reference/shaders-msl/frag/force-depth-write.input-attachment-is-ds-attachment.frag
- shaders-msl/frag/force-depth-write-early-tests.input-attachment-is-ds-attachment.frag
- shaders-msl/frag/force-depth-write-false.input-attachment-is-ds-attachment.frag
- shaders-msl/frag/force-depth-write.input-attachment-is-ds-attachment.frag
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
Metal writes to the depth/stencil attachment before fragment shader execution if the execution does not modify the depth value. However, Vulkan expects the write to happen after fragment shader execution. To circumvent the issue we add a simple depth passthrough if the user opts in. Only required when the depth/stencil attachment is used as input attachment at the same time. It seems Metal does not correctly detect the dependency.
Required for https://github.com/KhronosGroup/MoltenVK/issues/2232
> MSL: Add option to force depth write in fragment shaders

- spirv_msl.cpp
Constexpr samplers are defined as local variables, but were treated as held within an argument buffer.
- `CompilerMSL::to_sampler_expression()` support constexpr samplers when using argument buffers, plus refactor to minimize generating expression text that may not be used.
- Handle padding around multi-plane images that require multiple textures. Only check for padding on the first plane, but include plane count in total argument buffer slots consumed. 
I experimented with a unit test, but couldn't figure out how to add the ability to define a constexpr sampler into the API in a straightforward manner.
> MSL: Fixes for constexpr sampler use with argument buffers.

- reference/opt/shaders-msl/comp/metal3_1_regression_patch.replace-recursive-inputs.msl3.argument.comp
- reference/shaders-msl/comp/metal3_1_regression_patch.replace-recursive-inputs.msl3.argument.comp
- shaders-msl/comp/metal3_1_regression_patch.replace-recursive-inputs.msl3.argument.comp
- spirv_msl.cpp
When using argument buffers, handle descriptor set entry points with recursive content, similar to discrete entry points with recursive content.
- For descriptor sets entry points with recursive content, add descriptor set to recursive_inputs, and create a local var for it.
- For recursive entry points that are contained in a descriptor set argument buffer, don't add entry point to recursive_inputs, or create a local var for that content entry point.
- Add test shader.
> MSL: Support descriptor sets with recursive content when using argument buffers.

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
Adds missing count variable for bindless.
Fix #2337.
> MSL/C: Add _2 variant for the resource binding API.

- reference/opt/shaders-msl/frag/gather-compare-const-offsets.frag
- reference/opt/shaders-msl/frag/gather-const-offsets.frag
- reference/shaders-msl/frag/gather-compare-const-offsets.frag
- reference/shaders-msl/frag/gather-const-offsets.frag
- spirv_msl.cpp
Required when using descriptor set argument buffers.
- Output overloaded functions for each address space.
- Update test shaders.
> MSL: Image gather ConstOffsets supports multiple address spaces.

- reference/shaders-msl-no-opt/asm/comp/ptr-access-chain-custom-array-stride.asm.msl23.comp
- shaders-msl-no-opt/asm/comp/ptr-access-chain-custom-array-stride.asm.msl23.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Case here is pointer to float3 with array stride of 12. Plain dereference will not work. To be more general, we can do pointer arith instead. For alignment, we have to cast the result to a packed_float3. All of this is rather awkward, but there aren't many great alternatives.
We're missing handling of Aligned mask for Load/Store, where we might have to cast a pointer to scalar types at last minute, which would make this reinterpret_cast chain even more ridiculous.
Fixes #2336.
> MSL: Handle OpPtrAccessChain with ArrayStride

- spirv_msl.cpp
- Modify `get_resource_array_size()` to retrieve size of descriptors in an argument buffer from resource_bindings (reversing change made in b236352).
- Retrieve size of runtime array from `get_resource_array_size()`.
@HansKristian-Work This PR reverses the b236352 commit from PR #2329. It was not clear why the restriction from that commit is required (what is the ABI referenced there?), and it means that variables held within an argument buffer descriptor set cannot have their sizes established by the app. This is particularly troublesome for SPIR-V runtime arrays, whose size must be set by the app.
Several hundred CTS tests use a runtime array in SPIR-V to read from a fixed-size array defined in a Vulkan descriptor set.
If the restriction in b236352 is still required, perhaps this PR …
> MSL: Support a runtime array with dynamic offset in an argument buffer.

- spirv_msl.cpp
- `spvBufferSizeConstants` tracks MSL indexes of buffers, not images.
- Previous code did not allow array index beyond zero.
> MSL: Minor fix to resource type of spvBufferSizeConstants array indexes.

- reference/opt/shaders-msl/asm/frag/image-query-lod-vec4.msl22.asm.frag
- reference/shaders-msl/asm/frag/image-query-lod-vec4.msl22.asm.frag
- shaders-msl/asm/frag/image-query-lod-vec4.msl22.asm.frag
- spirv_msl.cpp
MSL doesn't like it if you pass a float4 to calculate_[un]clamped_lod
> Fix MSL for OpImageQueryLod on a vector larger than needed

- spirv_msl.cpp
- `spvBufferSizeConstants` tracks MSL indexes of buffers, not images.
- Previous code did not allow array index beyond zero.
Pushed from SPIRV-Cross `mvk-vulkan-skd-1.3.289` branch.
> MSL: Minor fix to resource type of spvBufferSizeConstants array indexes

- spirv_cross_parsed_ir.cpp
Discovered through the `spvc_compiler_get_member_decoration()` C interface, it was returning 1 instead of the correct value. The JSON backend is unaffected, it seems to obtain the data some other way.
> Fix incorrect return value for ParsedIR::get_member_decoration(SpvDecorationMatrixStride)

- reference/shaders-msl-no-opt/frag/volatile-helper-invocation.msl23.spv16.frag
- shaders-msl-no-opt/frag/volatile-helper-invocation.msl23.spv16.frag
- spirv_msl.cpp
One of our tests only passed because it operated out of the entry point and would fail if you tried to do the same thing from any other function.  This makes it work no matter where it is.
~~Note: I couldn't think of any better names for the new variable than just adding an underscore.  If anyone else has a better name, please use it.~~
> Fix volatile helper invocation in non-main functions

- CMakeLists.txt
I'm not well versed with the project so I'm not sure how to describe this any further, but we've encountered this error in one of our [tools](https://github.com/ppy/veldrid-spirv/pull) which relies on this repo:
```
CMake Warning (dev) at C:/Android/android-sdk/ndk/27.0.12077973/build/cmake/flags.cmake:46 (if):
Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
--help-policy CMP0057" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
IN_LIST will be interpreted as an operator when the policy is set to NEW.
Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.30/Modules/Platform/Android-Clang.cmake:23 (include)
C:/Program …
```
> Fix CMake failing with Android NDK 27+

- spirv_cross_c.cpp
`spvc_compiler_set_entry_point` should be wrapped in `SPVC_BEGIN_SAFE_SCOPE` / `SPVC_END_SAFE_SCOPE`  to avoid unwind over FFI when the entry point is not found.
> c: wrap spvc_compiler_set_entry_point in error scope

- CMakeLists.txt
- spirv_cross_c.cpp
- spirv_cross_c.h
expose `preserve_structured_buffers` HLSL option to C API as `SPVC_COMPILER_OPTION_HLSL_PRESERVE_STRUCTURED_BUFFERS`
> c: Add HLSL option preserve_structured_buffers

- spirv_cross_parsed_ir.cpp
The assert in `ParsedIR::get_buffer_block_flags` is exposed to user code if `Compiler::get_buffer_block_flags` or `spvc_compiler_get_buffer_block_decorations` is called with a non-buffer variable (handle).
Particularly since the C API has no way of getting a `SPIRType` given only a `spvc_variable_id` this should not cause an assertion fail or be ignored but throw an exception.
> Replace assert of buffer block SPIRType with exception in `get_buffer_block_flags`

- spirv_glsl.cpp
Legacy versions of GLSL do not support switch statements, but the compiler did not take this into account and produced switch statements in versions before 1.30. Since the compiler already supported converting switch statements to ifs for the legacy ES versions, I just replaced the `is_legacy_es()` checks with `is_legacy()` checks.
> GLSL: Convert switch blocks to if statements in legacy desktop versions

- spirv_msl.cpp
Fix https://github.com/KhronosGroup/SPIRV-Cross/issues/2381
Found the similar ticket as I was writing up the bug report, the fix is so trivial I might as well just do it.
> MSL: add fmod to reserved function names

- spirv_hlsl.cpp
There's no good reason to write out a dummy member in an empty struct in legacy HLSL, and doing so can use up an extra constant register.
It may not be necessary in non-legacy HLSL either, but I am unable to test that extensively at this time.
> Allow empty structs in legacy HLSL

- reference/shaders-msl-no-opt/comp/simple-bindless-ssbo.msl2.argument.argument-tier-1.device-argument-buffer.comp
- shaders-msl-no-opt/comp/simple-bindless-ssbo.msl2.argument.argument-tier-1.device-argument-buffer.comp
- spirv_msl.cpp
> MSL: Fix emission of bindless helper template for bindless SSBO.

- reference/opt/shaders-msl/asm/comp/uint_smulextended.asm.comp
- reference/opt/shaders-msl/asm/comp/ulong_smulextended.asm.msl23.comp
- reference/opt/shaders-msl/desktop-only/comp/extended-arithmetic.desktop.comp
- reference/shaders-msl/asm/comp/uint_smulextended.asm.comp
- reference/shaders-msl/asm/comp/ulong_smulextended.asm.msl23.comp
- reference/shaders-msl/desktop-only/comp/extended-arithmetic.desktop.comp
- spirv_msl.cpp
- spirv_msl.hpp
Proposed fix for https://github.com/KhronosGroup/SPIRV-Cross/issues/2385
This introduces a helper function to perform `Op*MulExtended` instructions. The helper takes the following template parameters:
* The type of the result container.
* The type of the operands and result container fields. This is needed because `OpSMulExtended` can be used with unsigned types but will perform signed multiplication. The inputs are cast to signed to perform correct multiplication, and the results need to be cast back to unsigned afterwards in order to satisfy Metal/C++ rules for initializer list types.
* The type the function will use to multiply arguments, based on the instruction.
Updated the tests for these changes, and the shader in the linked issue now compiles without error.
> MSL: Work around internal compiler error from mulhi.

- reference/shaders-msl-no-opt/asm/frag/barycentric-centroid-noperspective.msl22.asm.frag
- reference/shaders-msl-no-opt/asm/frag/barycentric-centroid-perspective.msl22.asm.frag
- reference/shaders-msl-no-opt/asm/frag/barycentric-sample-noperspective.msl22.asm.frag
- reference/shaders-msl-no-opt/asm/frag/barycentric-sample-perspective.msl22.asm.frag
- shaders-msl-no-opt/asm/frag/barycentric-centroid-noperspective.msl22.asm.frag
- shaders-msl-no-opt/asm/frag/barycentric-centroid-perspective.msl22.asm.frag
- shaders-msl-no-opt/asm/frag/barycentric-sample-noperspective.msl22.asm.frag
- shaders-msl-no-opt/asm/frag/barycentric-sample-perspective.msl22.asm.frag
- spirv_msl.cpp
glslang doesn't seem to support this, so need asm shaders.
> MSL: Allow Centroid and Sample decorations on bary coord.

- reference/shaders-hlsl-no-opt/asm/frag/srem.asm.frag
- reference/shaders-msl-no-opt/asm/frag/srem.asm.frag
- reference/shaders-no-opt/asm/frag/srem.asm.frag
- shaders-hlsl-no-opt/asm/frag/srem.asm.frag
- shaders-msl-no-opt/asm/frag/srem.asm.frag
- shaders-no-opt/asm/frag/srem.asm.frag
- spirv_glsl.cpp
> Make SRem sign aware like all the other arithmetic ops.

- reference/opt/shaders-msl/mesh/mesh-shader-basic-lines.msl3.spv14.vk.nocompat.mesh
- reference/opt/shaders-msl/mesh/mesh-shader-basic-triangle.msl3.spv14.vk.nocompat.mesh
- reference/shaders-msl/mesh/mesh-shader-basic-lines.msl3.spv14.vk.nocompat.mesh
- reference/shaders-msl/mesh/mesh-shader-basic-triangle.msl3.spv14.vk.nocompat.mesh
- shaders-msl/mesh/mesh-shader-basic-lines.msl3.spv14.vk.nocompat.mesh
- shaders-msl/mesh/mesh-shader-basic-triangle.msl3.spv14.vk.nocompat.mesh
- spirv_common.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Rework of old https://github.com/KhronosGroup/SPIRV-Cross/pull/2074
Also made some changes to make diff smaller and also introduced `SetMeshOutputsEXT`  wrapper, for sake of code-gen clarity.
Only mesh stage, for the sake of code-review. Task will be separated PR.
In tests `taskPayloadSharedEXT` is replaced to `const`; other than that test-cases are copied from HLSL
~Note: shader-playground is down today - wasn't able to fully test output.~
Tested shaders via shader-playground
> MSL: added mesh-shader support

- .github/workflows/main.yml
Unsure how much interest there is in this, but since we'll be using SPIRV-Cross on several Apple platforms, I've updated the CI/CD to build for Apple's other various platforms locally, and have successfully used the results on an iPhone.
> Add CI/CD for Apple mobile platforms

- reference/opt/shaders-msl/mesh/mesh-shader-basic-lines.msl3.spv14.vk.nocompat.mesh
- reference/opt/shaders-msl/mesh/mesh-shader-basic-triangle.msl3.spv14.vk.nocompat.mesh
- reference/opt/shaders-msl/task/task-basic.msl3.spv14.vk.nocompat.task
- reference/opt/shaders-msl/task/task-func.msl3.spv14.vk.nocompat.task
- reference/shaders-msl/mesh/mesh-shader-basic-lines.msl3.spv14.vk.nocompat.mesh
- reference/shaders-msl/mesh/mesh-shader-basic-triangle.msl3.spv14.vk.nocompat.mesh
- reference/shaders-msl/task/task-basic.msl3.spv14.vk.nocompat.task
- reference/shaders-msl/task/task-func.msl3.spv14.vk.nocompat.task
- shaders-msl/mesh/mesh-shader-basic-lines.msl3.spv14.vk.nocompat.mesh
- shaders-msl/mesh/mesh-shader-basic-triangle.msl3.spv14.vk.nocompat.mesh
- shaders-msl/task/task-basic.msl3.spv14.vk.nocompat.task
- shaders-msl/task/task-func.msl3.spv14.vk.nocompat.task
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Followup to https://github.com/KhronosGroup/SPIRV-Cross/pull/2074
Add task(aka `[[object]]`) shader.
Added `taskPayloadSharedEXT` to mesh shader side.
Updated test-cases for mesh shader to use `taskPayloadSharedEXT`.
Tested shaders via shader-playground
> MSL: added task shader support

- .github/workflows/main.yml
Recently we have found productivty slow down in other KhronosGroups repos because it can take hours for CI to run due to running out of Github Actions minutes. We have found that MacOS/iOS are charged as 10x the minute cost which really starts to add up. The goal is to not have those expensive CI actions run unless we know other things work first.
(There is an internal issue on this, but for short term, I have just been apply these types of YAML chanegs aroudn the repos https://gitlab.khronos.org/khronos-general/khronos-issues/-/issues/127)
> ci: Build dependency for Github Actions

- spirv_glsl.cpp
Fixes a compile error due to constants not having proper suffix and legacy GLSL having no implicit conversion.
I tried to create a unit test but the test_shaders.py script doesn't have a way to build for desktop legacy GLSL.
> GLSL: Use u literal suffix in legacy GLSL if GL_EXT_gpu_shader4 is available

- spirv_glsl.cpp
Texture buffers were introduced in GLSL 140 on desktop. There is no GLSL 300 on desktop.
> glsl: Correct version number check for texture buffers

- spirv_msl.cpp
A shader may declare and access the first element of a descriptor array as a scalar, which throws off the remaining structure of a Metal Argument Buffer. Add a padding member to the shader Metal argument buffer struct to consume the descriptor elements beyond the first.
- `CompilerMSL::analyze_argument_buffers()`: Track when a descriptor array is declared as a scalar in shader, and add a subsequent member to the Metal argument buffer struct to consume the elements beyond the first.
- `CompilerMSL::get_resource_array_size()`: Ensure variable id is valid.
> MSL: Pad array elements in Metal argument buffer when shader declares scalar.

- reference/shaders-msl-no-opt/frag/explicit-lod-unpack-arguments.frag
- shaders-msl-no-opt/frag/explicit-lod-unpack-arguments.frag
- spirv_msl.cpp
If sourcing arguments directly from std140 UBO arrays or something, we generated broken code.
Fix #2416.
> MSL: Use unpacked arguments in texture arguments.

- reference/opt/shaders-hlsl/mesh/mesh-shader-basic-lines.spv14.vk.nocompat.mesh
- reference/opt/shaders-hlsl/mesh/mesh-shader-basic-triangle.spv14.vk.nocompat.mesh
- reference/shaders-hlsl-no-opt/mesh/clip-cull-array-load-store.sm65.nofxc.fxconly.spv16.mesh
- reference/shaders-hlsl-no-opt/mesh/mesh-shader-basic-triangle.spv14.vk.nocompat.nofxc.flip-vert-y.mesh
- reference/shaders-hlsl/mesh/mesh-shader-basic-lines.spv14.vk.nocompat.mesh
- reference/shaders-hlsl/mesh/mesh-shader-basic-triangle.spv14.vk.nocompat.mesh
- shaders-hlsl-no-opt/mesh/clip-cull-array-load-store.sm65.nofxc.fxconly.spv16.mesh
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_hlsl.cpp
- spirv_hlsl.hpp
Fix #2411.
Super cursed, but it is what it is.
> HLSL: Fix lowering of arrayed clip/cull distance in mesh shaders.

- CMakeLists.txt
Fix the following deprecation warning when using CMake 3.31:
> CMake Deprecation Warning at external/SPIRV-Cross/CMakeLists.txt:22 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
>
>  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
From https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features:
> Compatibility with versions of CMake older than 3.10 is now deprecated and will be removed from a future version. Calls to [cmake_minimum_required()](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required) or …
> Bump to CMake 3.10

- spirv_msl.cpp
The generated MSL can fail when compiling when the entry points are Metal reserved keywords, this adds some extra as required by Bevy game engine as it uses these keywords quite often. 
We should probably have to add some more keywords that are accepted by SPIRV but are Metal reserved keywords.
> [MSL] Added some more reserved keywords

- reference/shaders-msl/asm/frag/unreachable-return.msl23.spv14.asm.frag
- shaders-msl/asm/frag/unreachable-return.msl23.spv14.asm.frag
- spirv_glsl.cpp
- spirv_msl.cpp
Fix for https://github.com/KhronosGroup/SPIRV-Cross/issues/2435.
If a function with return value ends in unreachable, insert a return statement to avoid MSL compile errors. This condition already exists for blocks ending in Kill, it just needs to be extended to cover Unreachable as well.
> MSL: Terminate function with return value using return if ending in unreachable.

- CMakeLists.txt
- main.cpp
- reference/opt/shaders-msl/asm/frag/unreachable-return.msl23.spv14.asm.frag
- reference/shaders-msl-no-opt/vert/no-position-write.auto-disable-rasterization.msl21.vert
- reference/shaders-msl-no-opt/vert/no-position-write.disable-rasterization.msl21.vert
- shaders-msl-no-opt/vert/no-position-write.auto-disable-rasterization.msl21.vert
- shaders-msl-no-opt/vert/no-position-write.disable-rasterization.msl21.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
I don't think it's safe to do this as a default since position only needs to be defined if VS is the last pre-raster stage, but fine to make it opt-in.
Fix #2261.
> MSL: Add option to auto-disable rasterization based on Position usage

- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
Specialization constant may be translated into either function constant or macro in MSL. MoltenVK requires different processing for the two cases. We expose the list of constant ids and their corresponding macro names so that MoltenVK can use them properly support specialization on those macros.
References:
https://github.com/KhronosGroup/MoltenVK/pull/2434
https://github.com/KhronosGroup/MoltenVK/issues/2423#issuecomment-2601916375
> MSL: Expose information about specialization constants - macro mapping

- reference/opt/shaders-msl/comp/shared-zero-init-simple.comp
- reference/opt/shaders-msl/comp/shared-zero-init.comp
- reference/opt/shaders/comp/spec-const-arraydim-init.comp
- reference/shaders-msl/comp/shared-zero-init-simple.comp
- reference/shaders-msl/comp/shared-zero-init.comp
- reference/shaders/comp/spec-const-arraydim-init.comp
- shaders-msl/comp/shared-zero-init-simple.comp
- shaders-msl/comp/shared-zero-init.comp
- shaders/comp/spec-const-arraydim-init.comp
- spirv_common.hpp
- spirv_cross.cpp
- spirv_cross_parsed_ir.cpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
The extension allows initializing workgroup memory with OpConstantNull, and is a part of Vulkan 1.3.
In GLSL, the support is realized via GL_EXT_null_initializer. While in MSL, we have to generate code snippets to let the threads initialize the memory. Currently I don't have a corresponding implementation for HLSL due to my lack of knowledge.
When connected with MoltenVK, the implementation can pass all Vulkan CTS compute tests enabled by the extension when an independent fix for specialization constants (https://github.com/KhronosGroup/MoltenVK/pull/2434) is applied. The MoltenVK code (with downstream fix) is available at: https://github.com/dboyan/MoltenVK/tree/zero_init_wg_mem-specfix (need to manually specify SPIRV-Cross tree with this PR branch when using `fetchDependencies` while …
> GLSL/MSL: Support VK_KHR_zero_initialize_workgroup_memory

- reference/shaders-no-opt/asm/comp/atomic-on-bda-pod.asm.nocompat.vk.comp.vk
- reference/shaders-no-opt/comp/atomics-64bit.comp
- reference/shaders-no-opt/vulkan/comp/image-64bit.vk.nocompat.comp.vk
- shaders-no-opt/asm/comp/atomic-on-bda-pod.asm.nocompat.vk.comp
- shaders-no-opt/comp/atomics-64bit.comp
- spirv_glsl.cpp
- spirv_glsl.hpp
- 64-bit SSBO atomics didn't add the extension
- Fix .value dereference for plain POD BDA atomics.
> GLSL: Fix some issues with atomics

- reference/opt/shaders-msl/asm/frag/bitcast-ptr-vec.argument-tier-1.msl23.asm.frag
- reference/shaders-msl/asm/frag/bitcast-ptr-vec.argument-tier-1.msl23.asm.frag
- shaders-msl/asm/frag/bitcast-ptr-vec.argument-tier-1.msl23.asm.frag
- spirv_msl.cpp
Otherwise, they will be misregarded as vectors and can be used in as_type, which does not support pointer type as destination.
Fixes #2451
> MSL: Treat pointer to vector as scalar type when bitcasting

- reference/opt/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/opt/shaders-msl/frag/array-of-texture-swizzle-nonconstant-uniform.msl2.argument.discrete.swizzle.frag
- reference/opt/shaders-msl/frag/array-of-texture-swizzle-nonconstant-uniform.msl2.swizzle.frag
- reference/opt/shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- reference/opt/shaders-msl/frag/array-of-texture-swizzle.msl2.swizzle.frag
- reference/opt/shaders-msl/frag/gather-compare-const-offsets.frag
- reference/opt/shaders-msl/frag/gather-const-offsets.frag
- reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
- reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
- reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
- reference/shaders-msl-no-opt/vulkan/frag/texture-access-function.swizzle.vk.frag
- reference/shaders-msl/comp/force-recompile-hooks.swizzle.comp
- reference/shaders-msl/frag/array-of-texture-swizzle-nonconstant-uniform.msl2.argument.discrete.swizzle.frag
- reference/shaders-msl/frag/array-of-texture-swizzle-nonconstant-uniform.msl2.swizzle.frag
- reference/shaders-msl/frag/array-of-texture-swizzle.msl2.argument.discrete.swizzle.frag
- reference/shaders-msl/frag/array-of-texture-swizzle.msl2.swizzle.frag
- reference/shaders-msl/frag/gather-compare-const-offsets.frag
- reference/shaders-msl/frag/gather-const-offsets.frag
- spirv_msl.cpp
- spirv_msl.hpp
Sequoia's texture2d has a new template parameter (`template <typename T, access a, memory_coherence c, typename _Enable> struct texture2d : _texture2d<T, a, c>`), making the old template matching fail to match.  Switch to using decltype on the method we plan to call.
I also removed `spvForward`, as nothing really has custom copy/move constructors in MSL (and you can't easily use forwarding references due to the explicit address space qualifier requirement).
> MSL: Fix gather functions on Sequoia

- reference/opt/shaders-msl/comp/expect-assume.comp
- reference/shaders-msl/comp/expect-assume.comp
- shaders-msl/comp/expect-assume.comp
- spirv_msl.cpp
- spirv_msl.hpp
Not sure about using the func impl thingy for defining macros, but this seems to work & compile fine. Couldn't think of a good test that actually had any codegen/performance improvements, but the LLVM IR does show that the Metal compiler is using the builtins at least to some degree.
Essentially, this just defines macros around the `__builtin_assume` and `__builtin_expect` builtins to be used for the two SPIR-V instructions, which are both builtins supported by Clang.
Relevant for KhronosGroup/MoltenVK#2490
> MSL: Add support for SPV_KHR_expect_assume

- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.comp
- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.fixed-subgroup.comp
- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl22.ios.comp
- reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl23.ios.simd.comp
- reference/shaders-no-opt/comp/subgroups.nocompat.invalid.vk.comp.vk
- shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.comp
- shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.fixed-subgroup.comp
- shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl22.ios.comp
- shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl23.ios.simd.comp
- shaders-no-opt/comp/subgroups.nocompat.invalid.vk.comp
- spirv_cross.cpp
- spirv_glsl.cpp
- spirv_msl.cpp
- spirv_msl.hpp
Adds GLSL and MSL support for `SPV_KHR_subgroup_rotate`.
* For GLSL both clustered and non-clustered variants are supported.
* For MSL, clustered is not supported as I could not find an option available for this, but it is behind a separate Vulkan feature flag anyway.
> GLSL/MSL: Implement SPV_KHR_subgroup_rotate

- reference/opt/shaders-msl/comp/expect-assume.comp
- reference/shaders-msl/comp/expect-assume.comp
- spirv_msl.cpp
I noticed that `SPV_EXPECT` wasn't defined properly when the builtin wasn't available, and the guards for defining the macros weren't quite right.
> Properly define SPV_EXPECT when builtin not available

- .github/workflows/main.yml
- reference/shaders-msl-no-opt/asm/vert/debug-printf.asm.msl32.vert
- shaders-msl-no-opt/asm/vert/debug-printf.asm.msl32.vert
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- test_shaders.py
Translates `DebugPrintf` to `os_log_default.log`, provided in MSL 3.2.
I don't think this is needed for MoltenVK as the Vulkan Validation Layer is responsible for instrumenting debug prints into buffer writes, but may be useful for users translating SPIR-V for use with Metal directly.
> MSL: Add support for DebugPrintf.

- CMakeLists.txt
- main.cpp
- reference/shaders-msl/vert/no_pointsize.default-point-size.vert
- reference/shaders-msl/vert/pointsize.default-point-size.vert
- shaders-msl/vert/no_pointsize.default-point-size.vert
- shaders-msl/vert/pointsize.default-point-size.vert
- spirv_cross_c.cpp
- spirv_cross_c.h
- spirv_msl.cpp
- spirv_msl.hpp
- test_shaders.py
`VK_KHR_maintenance5` requires that `PointSize` default to `1.0` when not written in a shader. In order to support this requirement, this PR adds an option for MSL to emit a default `PointSize` value when it was not written, as according to Metal documentation the point size must be specified within the vertex shader.
I considered using the existing `enable_point_size_builtin` flag for this but it currently defaults to true. Changing this could negatively impact users relying on the default conversion behavior respecting `PointSize`, and leaving it means every shader emits a default value unless explicitly disabled. Thus I added a new flag to control emitting the default, and a new float option to set what that default is.
Have also added tests with this option where the point size is …
> MSL: Add option to provide a default point size.

- reference/opt/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-bitcast.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference-decorations.nocompat.vk.comp.vk
- reference/opt/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-bitcast-uvec2.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-bitcast.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference-decorations.nocompat.vk.comp.vk
- reference/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
- spirv_glsl.cpp
Buffer reference blocks are always emitted after structs, even when forward declared. This causes invalid GLSL to be generated if a buffer reference block is used as a struct member.
This patch fixes the problem by emitting buffer reference block forward declarations before emitting structs.
> Fix using buffer reference blocks as struct members in glsl

- reference/shaders-msl-no-opt/comp/bda-nonwritable-glslang-workaround.comp
- reference/shaders-msl/vert/buffer_device_address.msl2.vert
- shaders-msl-no-opt/comp/bda-nonwritable-glslang-workaround.comp
- spirv_msl.cpp
glslang has a bug here and emitting const pointers isn't super useful, since it's mostly just a programmer aid in C++, it doesn't have same semantic meaning as NonWritable in SPIR-V.
Closes #2476.
> MSL: Don't emit const for BDA pointers.

- reference/shaders-msl-no-opt/comp/bda-load-std140-arrayed-pointer.msl.msl23.comp
- shaders-msl-no-opt/comp/bda-load-std140-arrayed-pointer.msl.msl23.comp
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_msl.cpp
- spirv_msl.hpp
> MSL: Clear out physical type remapping once we've cast to BDA.

- reference/opt/shaders-hlsl/asm/comp/replicated-composites.spv16.vk.asm.comp
- reference/opt/shaders-msl/asm/comp/replicated-composites.spv16.asm.comp
- reference/opt/shaders/vulkan/comp/replicated-composites.nocompat.spv16.asm.vk.comp.vk
- reference/opt/shaders/vulkan/comp/replicated-composites.spv16.vk.nocompat.comp.vk
- reference/shaders-hlsl/asm/comp/replicated-composites.spv16.vk.asm.comp
- reference/shaders-msl/asm/comp/replicated-composites.spv16.asm.comp
- reference/shaders/vulkan/comp/replicated-composites.nocompat.spv16.asm.vk.comp.vk
- reference/shaders/vulkan/comp/replicated-composites.spv16.vk.nocompat.comp.vk
- shaders-hlsl/asm/comp/replicated-composites.spv16.vk.asm.comp
- shaders-msl/asm/comp/replicated-composites.spv16.asm.comp
- shaders/vulkan/comp/replicated-composites.nocompat.spv16.asm.vk.comp
- shaders/vulkan/comp/replicated-composites.spv16.vk.nocompat.comp
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_parser.cpp
https://github.khronos.org/SPIRV-Registry/extensions/EXT/SPV_EXT_replicated_composites.html offers a streamlined way to initialize composites like vectors and matrices. Also, from extensions like `SPV_KHR_cooperative_matrix` or `SPV_NV_cooperative_vector`.
For constants, we piggyback on the existing logic for constant composites adding an additional bool to indicate whether our composites consists of multiple subconstants or a single replicated one.
In GLSL, most types support replication using their constructor. A notable exception to that are matrices like `mat4` which support `mat4(0.0)` but not `mat4(vec4(0.0))` how they are represented in SPIRV.
One motivation for this PR is to support construction from scalars for https://github.khronos.org/SPIRV-Registry/extensions/NV/SPV_NV_coopera …
> glsl: Implement `SPV_EXT_replicated_composites`

- spirv_reflect.cpp
Couple reflection touch ups related to mesh shaders.
1. It seems that `execution_model_to_str` lucks mesh shading execution models, so when reflecting spirv, it outputs:
```
✦ ❯ ./spirv-cross --reflect --msl triangle_ms.spv
{
"entryPoints" : [
{
"name" : "main_ms",
"mode" : "???"
}
],
```
After this change:
```
✦ ❯ ./spirv-cross --reflect --msl triangle_ms.spv
{
"entryPoints" : [
{
"name" : "main_ms",
"mode" : "mesh"
}
],
```
2. Output `workgroup_size` for mesh/task shaders:
```bash
✦ ❯ /Users/mpavlenko/Github/SPIRV-Cross/spirv-cross --reflect --msl triangle_as.spv
{
"entryPoints" : [
{
"name" : "main_as",
"mode" : "task",
"workgroup_size" : [
1,
1,
1
],
"workgroup_size_is_spec_constant_id" : [
false,
false,
false
]
}
],
```
> Add mesh shaders to reflection

- reference/opt/shaders-hlsl/frag/shader-debug-info-line-directives.line.gV.frag
- reference/opt/shaders-msl/frag/shader-debug-info-line-directives.line.gV.frag
- reference/opt/shaders/frag/shader-debug-info-line-directives.line.gV.frag
- reference/shaders-hlsl/frag/shader-debug-info-line-directives.line.gV.frag
- reference/shaders-msl/frag/shader-debug-info-line-directives.line.gV.frag
- reference/shaders/frag/shader-debug-info-line-directives.line.gV.frag
- shaders-hlsl/frag/shader-debug-info-line-directives.line.gV.frag
- shaders-msl/frag/shader-debug-info-line-directives.line.gV.frag
- shaders/frag/shader-debug-info-line-directives.line.gV.frag
- spirv_common.hpp
- spirv_glsl.cpp
- spirv_glsl.hpp
- spirv_parser.cpp
- test_shaders.py
> Implement line directive from ShaderDebugInfo.100.

- README.md
> README: Add a note clarifying which kinds of GLSL can be cross compiled.

- reference/opt/shaders/comp/cooperative-vec-nv.spv16.vk.nocompat.comp.vk
- reference/shaders/comp/cooperative-vec-nv.spv16.vk.nocompat.comp.vk
- shaders/comp/cooperative-vec-nv.spv16.vk.nocompat.comp
- spirv_glsl.cpp
I realized that #2489 omitted OpAccessChain on OpTypeCooperativeVectorNV. I'm not familiar enough with the code base how to best handle this, but semantically cooperative vectors are pretty much fancy arrays with additional math operations on them. The code path for arrays seems to have the right logic to handle this. There is also a code path for OpTypeCooperativeMatrixNV and normal vectors, but it would require too much distinctions to be used with OpTypeCooperativeVectorNV
> glsl: support OpAccessChain on OpTypeCooperativeVectorNV

- shaders-msl/asm/frag/spec-constant-bool-mixed.asm.frag
- spirv_msl.cpp
RenderDoc generates SPIR-V that may reuse boolean specialization constants, resulting in invalid MSL being generated.
- Updated `emit_specialization_constants_and_structs` to deduplicate function constants and handle boolean types correctly, avoiding illegal bitcasting in Metal.
- Modified `bitcast_glsl_op` to prevent bitcasting to/from boolean types, ensuring compliance with Metal's restrictions.
- Added a new test shader `spec-constant-bool-mixed.asm.frag` to validate the behavior of mixed specialization constants with the same SpecId for boolean and uint types.
> MSL: Fix boolean spec const as_type<> invalid output

- reference/shaders-msl-no-opt/vert/block-io-array-copy.vert
- shaders-msl-no-opt/vert/block-io-array-copy.vert
- spirv_cross.cpp
- spirv_cross.hpp
- spirv_msl.cpp
Need to consider if the type is actually using explicit layout (in which case we drop array wrapper), not if it's just block-like, which also covers stage IO.
Fix #2527.
> MSL: Fix array copy to array inside stage IO Blocks.

- spirv_hlsl.cpp
I found up that in e.g. [Diligent Engine](https://github.com/DiligentGraphics/DiligentEngine) defines it's own namespace 'diligent_spirv_cross' instead of default 'spirv_cross' which brokes compilation at [spirv_hlsl.cpp:3032](https://github.com/KhronosGroup/SPIRV-Cross/blob/072444287f4e139c178d6d8fe32e04a0d2c34e8b/spirv_hlsl.cpp#L3032)
> Fix: change default namespace spirv_cross to configurable SPIRV_CROSS_NAMESPACE in spirv_hlsl.cpp
