reference/shaders/desktop-only/comp/fp64.comp
reference/shaders/desktop-only/comp/int64.comp
shaders/desktop-only/comp/fp64.comp
shaders/desktop-only/comp/int64.comp
spirv_common.hpp
spirv_cpp.cpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp

This adds support for desktop features, GL_ARB_gpu_shader_{fp64,int64}.

Add support for FP64/INT64/UINT64

---

spirv_glsl.cpp

If the source GLSL file accessed gl_FragData, we got double up
with array access, giving invalid GLSL.

Fix legacy GLSL output with gl_FragData.

---

spirv_glsl.cpp
spirv_glsl.hpp

Added GL_EXT_draw_buffers, GL_OES_standard_derivatives and GL_EXT_shader_texture_lod extensions for legacy GLES. Let me know if I can improve further.

Legacy GLES extensions.

---

spirv_cross.cpp
spirv_glsl.cpp

I would completely understand if you reject the PR, this is for Goobuntu's ancient GCC stdlib.

Fix compilation on some old C++11 standard libraries.

---

spirv_cross.hpp
spirv_glsl.cpp
spirv_msl.cpp
spirv_msl.hpp

Several enhancements to CompilerMSL for MSL output.

MSL enhancements

---

spirv_cross.cpp

When a member of a struct is a struct, get_declared_struct_member_size
instead returned the size of the entire outer struct because it added
the offset of the last field to the size of the last field.
Restructure the function so that it handles all arrays in the same way
(by using array stride) and for the rest reuses get_declared_struct_size
if possible - this simplifies the function and fixes the issue.
This is a prerequisite for merging #82.

Fix get_declared_struct_member_size for struct members

---

.travis.yml
reference/shaders-msl/frag/mix.frag
reference/shaders/comp/generate_height.comp
reference/shaders/frag/ground.frag
reference/shaders/frag/mix.frag
reference/shaders/vert/ground.vert
reference/shaders/vert/ocean.vert
reference/shaders/vulkan/frag/spec-constant.vk.frag.vk
spirv_glsl.cpp

Fix a lingering bug with OpSelect and boolean mix().

Update glslang to latest on Travis.

---

spirv_cross.cpp

Needed for some shaders which are generated from HLSL.

Ensure struct members have valid identifiers.

---

reference/shaders/legacy/fragment/explicit-lod.legacy.frag
reference/shaders/legacy/vert/implicit-lod.legacy.vert
shaders/legacy/fragment/explicit-lod.legacy.frag
shaders/legacy/vert/implicit-lod.legacy.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp
spirv_msl.hpp

Prefer plain texture2D in legacy es vertex shaders

---

reference/shaders-hlsl/frag/bit-conversions.frag
reference/shaders-hlsl/frag/builtins.frag
reference/shaders-hlsl/frag/bvec-operations.frag
reference/shaders-hlsl/frag/various-glsl-ops.frag
reference/shaders-hlsl/vert/basic.vert
reference/shaders-hlsl/vert/locations.vert
reference/shaders-hlsl/vert/qualifiers.vert
shaders-hlsl/frag/bit-conversions.frag
shaders-hlsl/frag/bvec-operations.frag
shaders-hlsl/frag/various-glsl-ops.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_hlsl.hpp

This adds everything requested in #128 and all of the remaining "various functions" from https://anteru.net/blog/2016/mapping-between-hlsl-and-glsl/

Transform more functions for HLSL

---

reference/shaders/asm/frag/sampler-buffer-without-sampler.asm.frag
shaders/asm/frag/sampler-buffer-without-sampler.asm.frag
spirv_cross.cpp
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Handles new Buffer<> output from HLSL in glslang.

Fix case where samplerBuffer is emitted without combined sampler.

---

main.cpp
spirv.hpp
spirv_common.hpp
spirv_cross.cpp
spirv_cross.hpp
spirv_hlsl.cpp

Merging this is pending that glslang settles for this identifier format.

Add interface for reflecting "magic" HLSL counter buffers.

---

main.cpp
reference/shaders-hlsl/frag/unary-enclose.frag
reference/shaders-msl/frag/unary-enclose.frag
reference/shaders/asm/frag/hlsl-sample-cmp-level-zero-cube.asm.frag
reference/shaders/frag/sample-parameter.frag
reference/shaders/frag/unary-enclose.frag
reference/shaders/vert/ground.vert
reference/shaders/vert/ocean.vert
reference/shaders/vulkan/frag/input-attachment-ms.vk.frag
reference/shaders/vulkan/frag/input-attachment-ms.vk.frag.vk
shaders-hlsl/frag/unary-enclose.frag
shaders-msl/frag/unary-enclose.frag
shaders/asm/frag/hlsl-sample-cmp-level-zero-cube.asm.frag
shaders/frag/sample-parameter.frag
shaders/frag/unary-enclose.frag
shaders/vulkan/frag/input-attachment-ms.vk.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp
spirv_msl.hpp

Fixes:
- https://github.com/KhronosGroup/SPIRV-Cross/issues/223
- https://github.com/KhronosGroup/SPIRV-Cross/issues/219
- https://github.com/KhronosGroup/SPIRV-Cross/issues/225

Various bug fixes

---

reference/shaders-hlsl/frag/spec-constant.frag
shaders-hlsl/frag/spec-constant.frag
spirv_hlsl.cpp
spirv_hlsl.hpp

Fixes https://github.com/KhronosGroup/SPIRV-Cross/issues/232.

Declare specialization constants in HLSL.

---

spirv_cross.cpp

Should not consider aliasing when names are stripped.
This affects reflection because declared type might be different from reported type.
Fixes #236

Fix spurious struct type aliasing in stripped binaries.

---

reference/shaders/asm/frag/op-constant-null.asm.frag
shaders/asm/frag/op-constant-null.asm.frag
spirv_common.hpp
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp

Support OpConstantNull.

---

reference/shaders-hlsl/frag/partial-write-preserve.frag
reference/shaders/comp/inout-struct.invalid.comp
reference/shaders/frag/flush_params.frag
reference/shaders/frag/partial-write-preserve.frag
shaders-hlsl/frag/partial-write-preserve.frag
shaders/frag/partial-write-preserve.frag
spirv_cross.cpp
spirv_cross.hpp

Preserve arguments with inout unless complete writes are made.

---

main.cpp
spirv_cross.cpp
spirv_cross.hpp

Add support for querying SPIR-V Capabilities and Extensions.

---

spirv_cross.cpp

Fix variable scoping when dest block only uses OpPhi to read variable.

---

reference/shaders-hlsl/vert/sampler-buffers.vert
shaders-hlsl/vert/sampler-buffers.vert
spirv_hlsl.cpp

Add sampler buffer support to HLSL.

---

reference/shaders/comp/bake_gradient.comp
reference/shaders/comp/coherent-image.comp
reference/shaders/comp/image.comp
reference/shaders/vert/texture_buffer.vert
shaders/comp/coherent-image.comp
spirv_glsl.cpp

Fix coherent and restrict image qualifiers for images.

---

reference/shaders-hlsl/frag/constant-buffer-array.frag
reference/shaders-hlsl/frag/partial-write-preserve.frag
reference/shaders-hlsl/frag/resources.frag
spirv_hlsl.cpp

Travis didn't kick in on the PR, so I'll just do it manually this time ...

Merge PR #274 with Travis fixes

---

main.cpp
spirv_common.hpp

Ensure that exceptions are logged.

---

main.cpp
spirv_glsl.cpp
spirv_glsl.hpp

Add option to disable use of 420pack extension.

---

spirv_cross.cpp

Remove some dead code.

---

reference/shaders-hlsl/frag/image-query-selective.frag
reference/shaders-hlsl/frag/image-query.frag
reference/shaders/desktop-only/frag/image-query.desktop.frag
shaders-hlsl/frag/image-query-selective.frag
shaders-hlsl/frag/image-query.frag
shaders/desktop-only/frag/image-query.desktop.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_hlsl.hpp

Implement texture query APIs in HLSL

---

reference/shaders-hlsl/frag/mod.frag
shaders-hlsl/frag/mod.frag
spirv_hlsl.cpp

Stamp out all variants for mod().

---

spirv_glsl.cpp
spirv_glsl.hpp

Do not emit layout(location) for fragment output pre-330.

---

reference/shaders-hlsl/comp/atomic.comp
reference/shaders-hlsl/comp/image.comp
reference/shaders-hlsl/comp/shared.comp
reference/shaders-hlsl/vert/texture_buffer.vert
shaders-hlsl/comp/atomic.comp
shaders-hlsl/comp/image.comp
shaders-hlsl/comp/shared.comp
shaders-hlsl/vert/texture_buffer.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_hlsl.hpp

Fills in some gaps in the compute support of HLSL.
Fixes #303.

HLSL image load/store, atomics, shared memory, barriers

---

spirv_cross.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Fix some warnings on older GCC.

---

main.cpp
spirv_cpp.cpp
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Compliments new interface to query remapped entry point names.
Prepares for multiple entry point support.

Add support for renaming entry points.

---

reference/shaders/asm/vert/global-builtin.sso.asm.vert
shaders/asm/vert/global-builtin.sso.asm.vert
spirv_cpp.cpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

HLSL doesn't seem to put its builtins in blocks and SSO path missed that possibility.

Fix SSO for HLSL vertex shaders

---

reference/opt/shaders-hlsl/frag/fp16-packing.frag
reference/opt/shaders-hlsl/frag/unorm-snorm-packing.frag
reference/shaders-hlsl/frag/fp16-packing.frag
reference/shaders-hlsl/frag/unorm-snorm-packing.frag
shaders-hlsl/frag/fp16-packing.frag
shaders-hlsl/frag/unorm-snorm-packing.frag
spirv_hlsl.cpp
spirv_hlsl.hpp

Fixes #340.
Apart from f32tof16 and back, HLSL does not seem to have any useful intrinsics for this, so have to roll my own.

Add packing support to HLSL

---

reference/opt/shaders-hlsl/comp/bitfield.noopt.comp
reference/opt/shaders-hlsl/comp/image.comp
reference/opt/shaders-hlsl/frag/sample-cmp-level-zero.frag
reference/shaders-hlsl/comp/bitfield.noopt.comp
reference/shaders-hlsl/comp/image.comp
reference/shaders-hlsl/frag/sample-cmp-level-zero.frag
shaders-hlsl/comp/bitfield.noopt.comp
shaders-hlsl/comp/image.comp
shaders-hlsl/frag/sample-cmp-level-zero.frag
spirv_hlsl.cpp
spirv_hlsl.hpp

Fixes #341.
Fixes #342.
Fixes #343.

Fix various HLSL bugs.

---

reference/opt/shaders-hlsl/frag/query-lod.desktop.frag
reference/shaders-hlsl/frag/query-lod.desktop.frag
shaders-hlsl/frag/query-lod.desktop.frag
spirv_hlsl.cpp

Support textureQueryLod in HLSL.

---

reference/opt/shaders/frag/image-load-store-uint-coord.asm.frag
reference/shaders/frag/image-load-store-uint-coord.asm.frag
shaders/frag/image-load-store-uint-coord.asm.frag
spirv_glsl.cpp

HLSL can emit uint here.
Fixes #352.

Make sure image integer coords are int, not uint.

---

reference/opt/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
reference/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp

Lift dominator to loop header when continue block accesses variable

---

reference/opt/shaders-hlsl/asm/vert/vertex-id-instance-id.asm.vert
reference/shaders-hlsl/asm/vert/vertex-id-instance-id.asm.vert
shaders-hlsl/asm/vert/vertex-id-instance-id.asm.vert
spirv_hlsl.cpp
spirv_hlsl.hpp

Support VertexID/InstanceID in HLSL.

---

checkout_glslang_spirv_tools.sh
reference/opt/shaders-hlsl/comp/access-chains.comp
reference/opt/shaders-hlsl/comp/address-buffers.comp
reference/opt/shaders-hlsl/comp/shared.comp
reference/shaders-hlsl/comp/access-chains.comp
reference/shaders-hlsl/comp/address-buffers.comp
reference/shaders-hlsl/comp/shared.comp
spirv_hlsl.cpp
test_shaders.sh

Need to consider some FXC validation ...

Use t-namespace for ByteAddressBuffer.

---

spirv_common.hpp
spirv_cross.cpp
spirv_msl.cpp

- pack/unpack nested constant buffer structs
- support for write-only textures (only global ones for now)
- better rt index support for msl generator

msl generator enhancements/fixes

---

reference/opt/shaders-hlsl/frag/sampler-array.frag
reference/shaders-hlsl/frag/sampler-array.frag
shaders-hlsl/frag/sampler-array.frag
spirv_hlsl.cpp

Support arrays of images in HLSL

---

reference/opt/shaders/desktop-only/geom/viewport-index.desktop.geom
reference/shaders/desktop-only/geom/viewport-index.desktop.geom
shaders/desktop-only/geom/viewport-index.desktop.geom
spirv_glsl.cpp

Add support for gl_ViewportIndex.

---

spirv_glsl.cpp
spirv_msl.cpp

This is an implementation of the suggested fix in issue #387.

Use initializer list for composite initializations

---

reference/opt/shaders-hlsl/asm/frag/unreachable.asm.frag
reference/opt/shaders-msl/asm/frag/unreachable.asm.frag
reference/opt/shaders/asm/frag/unreachable.asm.frag
reference/shaders-hlsl/asm/frag/unreachable.asm.frag
reference/shaders-msl/asm/frag/unreachable.asm.frag
reference/shaders/asm/frag/unreachable.asm.frag
shaders-hlsl/asm/frag/unreachable.asm.frag
shaders-msl/asm/frag/unreachable.asm.frag
shaders/asm/frag/unreachable.asm.frag
spirv_glsl.cpp

Forgot to add it to emit_block_chain. It should just be a noop.
Fixes #391.

Handle OpUnreachable in code-gen.

---

main.cpp
spirv_glsl.cpp
spirv_glsl.hpp

Not using this is broken, and won't work anymore.

Remove cfg_analysis option.

---

reference/opt/shaders/asm/frag/multi-for-loop-init.asm.frag
reference/shaders/asm/frag/multi-for-loop-init.asm.frag
shaders/asm/frag/multi-for-loop-init.asm.frag
spirv_glsl.cpp
spirv_glsl.hpp

Do not use inline for-loop initializers with different types.

---

reference/opt/shaders/asm/frag/composite-construct-struct-no-swizzle.asm.frag
reference/shaders/asm/frag/composite-construct-struct-no-swizzle.asm.frag
shaders/asm/frag/composite-construct-struct-no-swizzle.asm.frag
spirv_glsl.cpp
spirv_glsl.hpp

Do not merge swizzles for anything other than vectors.

---

reference/opt/shaders-hlsl/vert/struct-composite-decl.vert
reference/shaders-hlsl/vert/struct-composite-decl.vert
shaders-hlsl/vert/struct-composite-decl.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

It actually worked surprisingly. Fix it properly.
Fix #405.

Fix HLSL regression with struct declaration.

---

reference/opt/shaders-msl/comp/shared-array-of-arrays.comp
reference/shaders-msl/comp/functions.comp
reference/shaders-msl/comp/shared-array-of-arrays.comp
shaders-msl/comp/shared-array-of-arrays.comp
spirv_msl.cpp

Fix passing arrays of arrays to functions in MSL.

---

reference/opt/shaders-hlsl/frag/texture-size-combined-image-sampler.frag
reference/shaders-hlsl/frag/texture-size-combined-image-sampler.frag
shaders-hlsl/frag/texture-size-combined-image-sampler.frag
spirv_hlsl.cpp

Fix OpImage on OpSampledImages in HLSL.

---

reference/opt/shaders/asm/frag/loop-header-to-continue.asm.frag
reference/shaders/asm/frag/loop-header-to-continue.asm.frag
shaders/asm/frag/loop-header-to-continue.asm.frag
spirv_glsl.cpp

Fix #419.
Should be improved by https://github.com/KhronosGroup/SPIRV-Cross/issues/423

Fix case where loop header branches into continue block.

---

main.cpp
reference/opt/shaders-hlsl/comp/num-workgroups-alone.comp
reference/opt/shaders-hlsl/comp/num-workgroups-with-builtins.comp
reference/shaders-hlsl/comp/num-workgroups-alone.comp
reference/shaders-hlsl/comp/num-workgroups-with-builtins.comp
shaders-hlsl/comp/num-workgroups-alone.comp
shaders-hlsl/comp/num-workgroups-with-builtins.comp
spirv_hlsl.cpp
spirv_hlsl.hpp

Support gl_NumWorkgroups in HLSL.

---

reference/opt/shaders-msl/comp/struct-packing.comp
reference/opt/shaders-msl/vert/packed_matrix.vert
reference/shaders-msl/comp/struct-packing.comp
reference/shaders-msl/vert/packed_matrix.vert
shaders-msl/comp/struct-packing.comp
shaders-msl/vert/packed_matrix.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

MSL support for smaller offsets for 3-row row-major matrices (fix issue #436).

MSL support for smaller offsets for 3-row row-major matrices (fix issue #436).

---

reference/opt/shaders/frag/hoisted-temporary-use-continue-block-as-value.frag
reference/shaders/frag/hoisted-temporary-use-continue-block-as-value.frag
shaders/frag/hoisted-temporary-use-continue-block-as-value.frag
spirv_glsl.cpp

Fix case where hoisted temporaries were used before being declared.

---

reference/opt/shaders-hlsl/frag/front-facing.frag
reference/opt/shaders-msl/frag/front-facing.frag
reference/opt/shaders/frag/front-facing.frag
reference/shaders-hlsl/frag/front-facing.frag
reference/shaders-msl/frag/front-facing.frag
reference/shaders/frag/front-facing.frag
shaders-hlsl/frag/front-facing.frag
shaders-msl/frag/front-facing.frag
shaders/frag/front-facing.frag
spirv_hlsl.cpp

Add IsFrontFace support to HLSL.

---

reference/opt/shaders-hlsl/asm/frag/frem.asm.frag
reference/opt/shaders-msl/asm/frag/frem.asm.frag
reference/opt/shaders/asm/frag/frem.asm.frag
reference/shaders-hlsl/asm/frag/frem.asm.frag
reference/shaders-msl/asm/frag/frem.asm.frag
reference/shaders/asm/frag/frem.asm.frag
shaders-hlsl/asm/frag/frem.asm.frag
shaders-msl/asm/frag/frem.asm.frag
shaders/asm/frag/frem.asm.frag
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Implement OpFRem.

---

main.cpp
reference/opt/shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag
reference/opt/shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag.vk
reference/shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag
reference/shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag.vk
shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp

Implement texelFetch(texture2D) workaround on GLSL.

---

reference/opt/shaders-hlsl/frag/inf-nan-constant.frag
reference/opt/shaders-msl/frag/inf-nan-constant.frag
reference/opt/shaders/desktop-only/frag/inf-nan-constant-double.desktop.frag
reference/opt/shaders/frag/inf-nan-constant.frag
reference/shaders-hlsl/frag/inf-nan-constant.frag
reference/shaders-msl/frag/inf-nan-constant.frag
reference/shaders/desktop-only/frag/inf-nan-constant-double.desktop.frag
reference/shaders/frag/inf-nan-constant.frag
shaders-hlsl/frag/inf-nan-constant.frag
shaders-msl/frag/inf-nan-constant.frag
shaders/desktop-only/frag/inf-nan-constant-double.desktop.frag
shaders/frag/inf-nan-constant.frag
spirv_common.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp

Support special float constants (NaN/Inf).

---

main.cpp
reference/opt/shaders-hlsl/frag/point-coord-compat.frag
reference/opt/shaders-hlsl/vert/point-size-compat.vert
reference/shaders-hlsl/frag/point-coord-compat.frag
reference/shaders-hlsl/vert/point-size-compat.vert
shaders-hlsl/frag/point-coord-compat.frag
shaders-hlsl/vert/point-size-compat.vert
spirv_hlsl.cpp
spirv_hlsl.hpp

Add workaround for PointCoord builtin on HLSL.

---

reference/opt/shaders/asm/vert/invariant-block.asm.vert
reference/opt/shaders/asm/vert/invariant-block.sso.asm.vert
reference/opt/shaders/asm/vert/invariant.asm.vert
reference/opt/shaders/asm/vert/invariant.sso.asm.vert
reference/shaders/asm/vert/invariant-block.asm.vert
reference/shaders/asm/vert/invariant-block.sso.asm.vert
reference/shaders/asm/vert/invariant.asm.vert
reference/shaders/asm/vert/invariant.sso.asm.vert
shaders/asm/vert/invariant-block.asm.vert
shaders/asm/vert/invariant-block.sso.asm.vert
shaders/asm/vert/invariant.asm.vert
shaders/asm/vert/invariant.sso.asm.vert
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp

Support Invariant for BuiltInPosition.

---

reference/opt/shaders-hlsl/frag/fp16.desktop.frag
reference/opt/shaders-msl/frag/fp16.desktop.frag
reference/opt/shaders-msl/vert/functions.vert
reference/opt/shaders/desktop-only/frag/fp16.desktop.frag
reference/shaders-hlsl/frag/fp16.desktop.frag
reference/shaders-msl/frag/fp16.desktop.frag
reference/shaders-msl/vert/functions.vert
reference/shaders/desktop-only/frag/fp16.desktop.frag
shaders-hlsl/frag/fp16.desktop.frag
shaders-msl/frag/fp16.desktop.frag
shaders/desktop-only/frag/fp16.desktop.frag
spirv_common.hpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_hlsl.hpp
spirv_msl.cpp

Add true FP16 support.

---

reference/opt/shaders-msl/frag/constant-composites.frag
reference/opt/shaders-msl/frag/illegal-name-test-0.frag
reference/shaders-msl/frag/constant-composites.frag
reference/shaders-msl/frag/illegal-name-test-0.frag
shaders-msl/frag/illegal-name-test-0.frag
spirv_glsl.cpp
spirv_msl.cpp

Add more illegal name replacement in MSL.

---

reference/opt/shaders-msl/frag/dual-source-blending.frag
reference/opt/shaders/desktop-only/frag/dual-source-blending.desktop.frag
reference/shaders-msl/frag/dual-source-blending.frag
reference/shaders/desktop-only/frag/dual-source-blending.desktop.frag
shaders-msl/frag/dual-source-blending.frag
shaders/desktop-only/frag/dual-source-blending.desktop.frag
spirv_common.hpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_msl.cpp

Support dual-source blending on GLSL and MSL.

---

spirv_glsl.cpp

Emit classic uniform for UBO in GLSL 1.30.

---

reference/opt/shaders-hlsl/asm/frag/empty-struct.asm.frag
reference/opt/shaders-msl/asm/frag/empty-struct.asm.frag
reference/opt/shaders/asm/frag/empty-struct.asm.frag
reference/opt/shaders/asm/vert/empty-io.asm.vert
reference/shaders-hlsl-no-opt/asm/vert/empty-struct-composite.asm.vert
reference/shaders-hlsl/asm/frag/empty-struct.asm.frag
reference/shaders-msl-no-opt/asm/vert/empty-struct-composite.asm.vert
reference/shaders-msl/asm/frag/empty-struct.asm.frag
reference/shaders-no-opt/asm/vert/empty-struct-composite.asm.vert
reference/shaders/asm/frag/empty-struct.asm.frag
reference/shaders/asm/vert/empty-io.asm.vert
shaders-hlsl/asm/frag/empty-struct.asm.frag
shaders-msl/asm/frag/empty-struct.asm.frag
shaders/asm/frag/empty-struct.asm.frag
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp

Support empty structs better, fix register_extension regression

---

spirv_glsl.cpp
spirv_glsl.hpp

Block locations are 440, but non-block are 410 ...

Distinguish between enhanced_layouts and SSO requirements.

---

CMakeLists.txt
appveyor.yml
test_shaders.py

Need to make sure MSVC builds continue working ...

Add AppVeyor.

---

reference/opt/shaders/vulkan/frag/separate-sampler-texture-array.vk.frag
reference/opt/shaders/vulkan/frag/separate-sampler-texture-array.vk.frag.vk
reference/shaders/vulkan/frag/separate-sampler-texture-array.vk.frag
reference/shaders/vulkan/frag/separate-sampler-texture-array.vk.frag.vk
shaders/asm/frag/sampler-buffer-array-without-sampler.asm.frag
shaders/vulkan/frag/separate-sampler-texture-array.vk.frag
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp

Support combined image-sampler workaround for arrays as well.

---

reference/opt/shaders-hlsl/asm/frag/texel-fetch-no-lod.asm.frag
reference/opt/shaders-hlsl/frag/tex-sampling-ms.frag
reference/opt/shaders-msl/asm/frag/texel-fetch-no-lod.asm.frag
reference/opt/shaders/asm/frag/image-query-no-sampler.vk.asm.frag
reference/opt/shaders/asm/frag/image-query-no-sampler.vk.asm.frag.vk
reference/opt/shaders/asm/frag/texel-fetch-no-lod.asm.frag
reference/shaders-hlsl/asm/frag/texel-fetch-no-lod.asm.frag
reference/shaders-hlsl/frag/tex-sampling-ms.frag
reference/shaders-msl/asm/frag/texel-fetch-no-lod.asm.frag
reference/shaders/asm/frag/image-query-no-sampler.vk.asm.frag
reference/shaders/asm/frag/image-query-no-sampler.vk.asm.frag.vk
reference/shaders/asm/frag/texel-fetch-no-lod.asm.frag
shaders-hlsl/asm/frag/texel-fetch-no-lod.asm.frag
shaders-hlsl/frag/tex-sampling-ms.frag
shaders-msl/asm/frag/texel-fetch-no-lod.asm.frag
shaders/asm/frag/image-query-no-sampler.vk.asm.frag
shaders/asm/frag/texel-fetch-no-lod.asm.frag
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

Fix OpImageFetch without explicit LOD and query functions without combined sampler.

---

reference/opt/shaders-msl/frag/gather-dref.frag
reference/opt/shaders/frag/gather-dref.frag
reference/shaders-msl/frag/gather-dref.frag
reference/shaders/frag/gather-dref.frag
shaders-msl/frag/gather-dref.frag
shaders/frag/gather-dref.frag
spirv_glsl.cpp

Fix GatherDref on GLSL.

---

reference/opt/shaders-msl/comp/composite-construct.comp
reference/shaders-msl/comp/composite-construct.comp
shaders-msl/comp/composite-construct.comp
spirv_glsl.cpp

Fix OpCompositeConstruct with arrays in MSL.

---

reference/opt/shaders-hlsl/vert/read-from-row-major-array.vert
reference/opt/shaders-msl/vert/read-from-row-major-array.vert
reference/opt/shaders/vert/read-from-row-major-array.vert
reference/shaders-hlsl/vert/read-from-row-major-array.vert
reference/shaders-msl/vert/read-from-row-major-array.vert
reference/shaders/vert/read-from-row-major-array.vert
shaders-hlsl/vert/read-from-row-major-array.vert
shaders-msl/vert/read-from-row-major-array.vert
shaders/vert/read-from-row-major-array.vert
spirv_msl.cpp

Will fail when recompiles are necessary.
Pending a regression test first.
Fix #561.

Do not clear spv_function_implementations on MSL.

---

reference/opt/shaders-hlsl/comp/rmw-matrix.comp
reference/opt/shaders-msl/comp/rmw-matrix.comp
reference/opt/shaders/comp/rmw-matrix.comp
reference/shaders-hlsl/comp/rmw-matrix.comp
reference/shaders-msl/comp/rmw-matrix.comp
reference/shaders/comp/rmw-matrix.comp
shaders-hlsl/comp/rmw-matrix.comp
shaders-msl/comp/rmw-matrix.comp
shaders/comp/rmw-matrix.comp
spirv_glsl.cpp
spirv_glsl.hpp

Does not work on MSL.
Fix #563.

Do not use RMW rewrite for matrices.

---

build_glslang_spirv_tools.sh
spirv_common.hpp

Fix GCC 8.1 build.

---

reference/opt/shaders/asm/geom/split-access-chain-input.asm.geom
reference/shaders/asm/geom/split-access-chain-input.asm.geom
shaders/asm/geom/split-access-chain-input.asm.geom
spirv_glsl.cpp

Fix split access chains for builtin arrays.

---

reference/opt/shaders-msl/comp/struct-packing.comp
reference/opt/shaders/asm/geom/inout-split-access-chain-handle.asm.geom
reference/opt/shaders/comp/struct-packing.comp
reference/shaders-msl/comp/struct-packing.comp
reference/shaders/asm/geom/inout-split-access-chain-handle.asm.geom
reference/shaders/comp/struct-packing.comp
shaders/asm/geom/inout-split-access-chain-handle.asm.geom
shaders/comp/struct-packing.comp
spirv_common.hpp
spirv_cross.cpp
spirv_glsl.cpp

Found some other issues. Had some bugs with variable writes not properly
invalidating if writes came from split access chains.
Fix #570.

Handle inout properly with split access chains.

---

reference/opt/shaders-msl/asm/comp/storage-buffer-basic.invalid.asm.comp
reference/opt/shaders-msl/comp/access-private-workgroup-in-function.comp
reference/opt/shaders-msl/comp/atomic.comp
reference/opt/shaders-msl/comp/basic.comp
reference/opt/shaders-msl/comp/culling.comp
reference/shaders-msl/asm/comp/storage-buffer-basic.invalid.asm.comp
reference/shaders-msl/comp/access-private-workgroup-in-function.comp
reference/shaders-msl/comp/atomic.comp
reference/shaders-msl/comp/basic.comp
reference/shaders-msl/comp/culling.comp
reference/shaders-msl/comp/shared.comp
reference/shaders-msl/vert/packed_matrix.vert
shaders-msl/comp/access-private-workgroup-in-function.comp
shaders-msl/comp/atomic.comp
spirv_glsl.cpp
spirv_msl.cpp

Need to emit a CAS loop.
Fix shared memory declaration.
Declare atomic ops with correct memory scope.
Fix some scoping issues for Private variables.
Fix #575.

Fix atomic_compare_exchange_weak_explicit.

---

reference/opt/shaders-hlsl/asm/frag/srem.asm.frag
reference/opt/shaders-msl/asm/frag/srem.asm.frag
reference/opt/shaders/asm/frag/srem.asm.frag
reference/shaders-hlsl/asm/frag/srem.asm.frag
reference/shaders-msl/asm/frag/srem.asm.frag
reference/shaders/asm/frag/srem.asm.frag
shaders-hlsl/asm/frag/srem.asm.frag
shaders-msl/asm/frag/srem.asm.frag
shaders/asm/frag/srem.asm.frag
spirv_glsl.cpp

Commit tests for PR #583

---

reference/opt/shaders-msl/comp/image-cube-array-load-store.comp
reference/shaders-msl/comp/image-cube-array-load-store.comp
shaders-msl/comp/image-cube-array-load-store.comp
spirv_msl.cpp

Unpack the packed Z component into face and layer manually.
Fix #578.

Fix image load/store on cube arrays in MSL.

---

main.cpp
spirv_glsl.cpp
spirv_glsl.hpp

Add support to remove SPIRV_Cross_BaseInstance uniform.

---

reference/opt/shaders-hlsl/asm/vert/uint-vertex-id-instance-id.asm.vert
reference/opt/shaders-msl/asm/vert/uint-vertex-id-instance-id.asm.vert
reference/opt/shaders/asm/geom/store-uint-layer.invalid.asm.geom
reference/opt/shaders/asm/vert/uint-vertex-id-instance-id.asm.vert
reference/shaders-hlsl/asm/vert/uint-vertex-id-instance-id.asm.vert
reference/shaders-msl/asm/vert/uint-vertex-id-instance-id.asm.vert
reference/shaders/asm/geom/store-uint-layer.invalid.asm.geom
reference/shaders/asm/vert/uint-vertex-id-instance-id.asm.vert
shaders-hlsl/asm/vert/uint-vertex-id-instance-id.asm.vert
shaders-msl/asm/vert/uint-vertex-id-instance-id.asm.vert
shaders/asm/geom/store-uint-layer.invalid.asm.geom
shaders/asm/vert/uint-vertex-id-instance-id.asm.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

Fix #612.
Automatically bitcast when reading/writing to certain builtins.

Deal with some builtins being declared with wrong signedness.

---

reference/opt/shaders-hlsl/frag/spec-constant-ternary.frag
reference/opt/shaders-msl/frag/spec-constant-ternary.frag
reference/opt/shaders/vulkan/frag/spec-constant-ternary.vk.frag
reference/opt/shaders/vulkan/frag/spec-constant-ternary.vk.frag.vk
reference/shaders-hlsl/frag/spec-constant-ternary.frag
reference/shaders-msl/frag/spec-constant-ternary.frag
reference/shaders/vulkan/frag/spec-constant-ternary.vk.frag
reference/shaders/vulkan/frag/spec-constant-ternary.vk.frag.vk
shaders-hlsl/frag/spec-constant-ternary.frag
shaders-msl/frag/spec-constant-ternary.frag
shaders/vulkan/frag/spec-constant-ternary.vk.frag
spirv_glsl.cpp
spirv_glsl.hpp

Support ternary expressions in OpSpecConstantOp.

---

reference/opt/shaders-hlsl/comp/globallycoherent.comp
reference/shaders-hlsl/comp/globallycoherent.comp
shaders-hlsl/comp/globallycoherent.comp
spirv_hlsl.cpp

Support globallycoherent in HLSL.

---

reference/opt/shaders-hlsl/asm/comp/control-flow-hints.asm.comp
reference/shaders-hlsl/asm/comp/control-flow-hints.asm.comp
shaders-hlsl/asm/comp/control-flow-hints.asm.comp
spirv_common.hpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_hlsl.hpp

Support branch/loop hints in HLSL.

---

spirv_glsl.cpp

Fail more gracefully with some unsupported opcodes.

---

reference/opt/shaders/flatten/copy.flatten.vert
reference/opt/shaders/flatten/matrix-conversion.flatten.frag
reference/opt/shaders/flatten/struct.rowmajor.flatten.vert
reference/shaders/flatten/copy.flatten.vert
reference/shaders/flatten/matrix-conversion.flatten.frag
reference/shaders/flatten/struct.rowmajor.flatten.vert
shaders/flatten/matrix-conversion.flatten.frag
spirv_glsl.cpp

Lower to a temporary if complex loads are used multiple times.

Fix a lot of redundant code when loading flattened composites.

---

reference/opt/shaders-hlsl/asm/comp/access-chain-invalidate.asm.comp
reference/shaders-hlsl/asm/comp/access-chain-invalidate.asm.comp
shaders-hlsl/asm/comp/access-chain-invalidate.asm.comp
spirv_glsl.cpp
spirv_hlsl.cpp

Properly track read dependencies for UAV access chain.

---

reference/opt/shaders-hlsl/frag/texel-fetch-offset.frag
reference/opt/shaders-msl/frag/texel-fetch-offset.frag
reference/opt/shaders/frag/texel-fetch-offset.frag
reference/shaders-hlsl/frag/texel-fetch-offset.frag
reference/shaders-msl/frag/texel-fetch-offset.frag
reference/shaders/frag/texel-fetch-offset.frag
shaders-hlsl/frag/texel-fetch-offset.frag
shaders-msl/frag/texel-fetch-offset.frag
shaders/frag/texel-fetch-offset.frag
spirv_msl.cpp

Just apply the offset directly, MSL has no immediate offset parameter.
Fix #656.

MSL: Fix support for texelFetchOffset.

---

reference/opt/shaders/asm/geom/block-name-namespace.asm.geom
reference/shaders/asm/geom/block-name-namespace.asm.geom
shaders/asm/geom/block-name-namespace.asm.geom
spirv_glsl.cpp
spirv_glsl.hpp

GLSL: Allow blocks to have their own namespace.

---

.travis.yml
reference/opt/shaders-msl/desktop-only/frag/sampler-ms-query.desktop.frag
reference/opt/shaders-msl/frag/texture-multisample-array.msl21.frag
reference/shaders-msl/desktop-only/frag/sampler-ms-query.desktop.frag
reference/shaders-msl/frag/texture-multisample-array.msl21.frag
shaders-msl/desktop-only/frag/sampler-ms-query.desktop.frag
shaders-msl/frag/texture-multisample-array.msl21.frag
spirv_msl.cpp
test_shaders.py

MSL: Implement multisampled array textures.

---

main.cpp
spirv_cross.cpp
spirv_cross.hpp

Add a helper function to improve reflection on runtime sized arrays.

---

reference/opt/shaders/asm/frag/locations-components.asm.frag
reference/opt/shaders/desktop-only/frag/layout-component.desktop.frag
reference/shaders/asm/frag/locations-components.asm.frag
reference/shaders/desktop-only/frag/layout-component.desktop.frag
shaders/asm/frag/locations-components.asm.frag
shaders/desktop-only/frag/layout-component.desktop.frag
spirv_glsl.cpp

Support Component decoration in GLSL.

---

reference/opt/shaders-msl/asm/frag/lut-promotion-initializer.asm.frag
reference/opt/shaders-msl/comp/composite-array-initialization.comp
reference/opt/shaders-msl/comp/composite-construct.comp
reference/opt/shaders-msl/comp/copy-array-of-arrays.comp
reference/opt/shaders-msl/frag/constant-array.frag
reference/opt/shaders-msl/frag/constant-composites.frag
reference/opt/shaders-msl/frag/lut-promotion.frag
reference/shaders-msl/asm/frag/lut-promotion-initializer.asm.frag
reference/shaders-msl/comp/composite-array-initialization.comp
reference/shaders-msl/comp/composite-construct.comp
reference/shaders-msl/comp/copy-array-of-arrays.comp
reference/shaders-msl/frag/constant-array.frag
reference/shaders-msl/frag/constant-composites.frag
reference/shaders-msl/frag/lut-promotion.frag
reference/shaders-msl/vert/return-array.vert
shaders-msl/comp/copy-array-of-arrays.comp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

MSL: Support copying array of arrays.

---

main.cpp
reference/opt/shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag.vk
reference/shaders/asm/frag/image-fetch-no-sampler.asm.vk.frag.vk
reference/shaders/asm/frag/image-query-no-sampler.vk.asm.frag.vk
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp

Use GL_EXT_samplerless_texture_functions in Vulkan GLSL.

---

reference/shaders-msl-no-opt/asm/frag/texture-access.swizzle.asm.frag
reference/shaders-msl-no-opt/frag/texture-access-int.swizzle.frag
reference/shaders-msl-no-opt/frag/texture-access-leaf.swizzle.frag
reference/shaders-msl-no-opt/frag/texture-access-uint.swizzle.frag
reference/shaders-msl-no-opt/frag/texture-access.swizzle.frag
spirv_msl.cpp

MSL: Swizzle gathers on depth textures as well.

---

.travis.yml

Speeds up testing process by 2x on Windows.

Try release build for Travis.

---

spirv_glsl.cpp

Setting force_temporary to true produces invalid GLSL because sampler
variables are copied:
highp sampler2D _377 = DiffuseMapTexture;
This change fixes the problem by always forwarding forwardable
variables. I also took an opportunity to restructure the code to make
it easier to read and add extra conditions to in the future.

Fix Options::force_temporary to work with OpenGL GLSL

---

reference/opt/shaders-msl/frag/depth-greater-than.frag
reference/opt/shaders-msl/frag/depth-less-than.frag
reference/opt/shaders-msl/frag/early-fragment-tests.frag
reference/shaders-msl/frag/depth-less-than.frag
reference/shaders-msl/frag/early-fragment-tests.frag
shaders-msl/frag/depth-greater-than.frag
shaders-msl/frag/depth-less-than.frag
shaders-msl/frag/early-fragment-tests.frag

Was causing compilation failures, jumped the merge a bit too soon.

MSL: Split out early_fragment_tests.

---

reference/opt/shaders/asm/comp/decoration-group.asm.comp
reference/shaders/asm/comp/decoration-group.asm.comp
shaders/asm/comp/decoration-group.asm.comp
spirv_parser.cpp

Parser: Handle group decorations.

---

README.md

Deeply sorry for missing one snippet that should be taken into last pull request patch.

Adding C++ syntax coloring for missed snippet

---

reference/opt/shaders-hlsl/frag/switch-unsigned-case.frag
reference/opt/shaders-msl/frag/switch-unsigned-case.frag
reference/opt/shaders/frag/switch-unsigned-case.frag
reference/shaders-hlsl/frag/switch-unsigned-case.frag
reference/shaders-msl/frag/switch-unsigned-case.frag
reference/shaders/frag/switch-unsigned-case.frag
shaders-hlsl/frag/switch-unsigned-case.frag
shaders-msl/frag/switch-unsigned-case.frag
shaders/frag/switch-unsigned-case.frag
spirv_glsl.cpp

Fix unsigned switch case selectors.

---

spirv_cpp.cpp

CPP: declare constants.

---

reference/opt/shaders-msl/frag/helper-invocation.msl21.frag
reference/opt/shaders/frag/helper-invocation.frag
reference/shaders-msl/frag/helper-invocation.msl21.frag
reference/shaders/frag/helper-invocation.frag
shaders-msl/frag/helper-invocation.msl21.frag
shaders/frag/helper-invocation.frag
spirv_glsl.cpp
spirv_msl.cpp

There is no obvious builtin for this on HLSL.
Fix #777.

Support gl_HelperInvocation on GLSL and MSL.

---

reference/opt/shaders/asm/comp/op-phi-swap.asm.comp
reference/opt/shaders/asm/frag/op-phi-swap-continue-block.asm.frag
reference/shaders/asm/comp/op-phi-swap.asm.comp
reference/shaders/asm/frag/op-phi-swap-continue-block.asm.frag
shaders/asm/comp/op-phi-swap.asm.comp
shaders/asm/frag/op-phi-swap-continue-block.asm.frag
spirv_common.hpp
spirv_glsl.cpp

Fix case where OpPhi is used to swap values.

---

reference/opt/shaders-hlsl/frag/dual-source-blending.frag
reference/shaders-hlsl/frag/dual-source-blending.frag
shaders-hlsl/frag/dual-source-blending.frag
spirv_hlsl.cpp

HLSL: Support dual-source blending.

---

reference/opt/shaders-hlsl/asm/frag/storage-class-output-initializer.asm.frag
reference/opt/shaders-msl/asm/frag/storage-class-output-initializer.asm.frag
reference/opt/shaders/asm/frag/storage-class-output-initializer.asm.frag
reference/shaders-hlsl/asm/frag/storage-class-output-initializer.asm.frag
reference/shaders-msl/asm/frag/storage-class-output-initializer.asm.frag
reference/shaders/asm/frag/storage-class-output-initializer.asm.frag
shaders-hlsl/asm/frag/storage-class-output-initializer.asm.frag
shaders-msl/asm/frag/storage-class-output-initializer.asm.frag
shaders/asm/frag/storage-class-output-initializer.asm.frag
spirv_cross.cpp
spirv_glsl.cpp
spirv_msl.cpp

Support initializers on StorageClassOutput.

---

reference/opt/shaders-hlsl/asm/frag/single-function-private-lut.asm.frag
reference/opt/shaders-msl/asm/frag/single-function-private-lut.asm.frag
reference/opt/shaders/asm/frag/single-function-private-lut.asm.frag
reference/shaders-hlsl/asm/frag/single-function-private-lut.asm.frag
reference/shaders-hlsl/frag/constant-composites.frag
reference/shaders-msl/asm/frag/single-function-private-lut.asm.frag
reference/shaders-msl/frag/constant-composites.frag
reference/shaders/asm/frag/single-function-private-lut.asm.frag
reference/shaders/frag/constant-composites.frag
shaders-hlsl/asm/frag/single-function-private-lut.asm.frag
shaders-msl/asm/frag/single-function-private-lut.asm.frag
shaders/asm/frag/single-function-private-lut.asm.frag
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

Fairly common pattern in unoptimized SPIR-V. Support this case as well.
Fix #846.

Support LUTs in single-function CFGs on Private storage class.

---

reference/opt/shaders-msl/asm/tesc/tess-level-overrun.asm.tesc
reference/opt/shaders-msl/tese/water_tess.tese
reference/shaders-msl/asm/tesc/tess-level-overrun.asm.tesc
reference/shaders-msl/tese/water_tess.tese
shaders-msl/asm/tesc/tess-level-overrun.asm.tesc
spirv_msl.cpp
spirv_msl.hpp

All of these were from running the CTS.

MSL: Some fixes for tessellation shaders.

---

reference/opt/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
reference/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
spirv_msl.cpp
spirv_msl.hpp

Some more issues I found running the CTS.

MSL: More tessellation shader fixes

---

.travis.yml
CMakeLists.txt
spirv.h
test_shaders.py
tests-other/c_api_test.c

Gracefully fall back in test suite if we haven't built external dependencies

---

spirv_glsl.cpp

Fix build on Android API < 26.

---

CMakeLists.txt
main.cpp
reference/opt/shaders/vulkan/frag/push-constant-as-ubo.push-ubo.vk.frag
reference/opt/shaders/vulkan/frag/push-constant-as-ubo.push-ubo.vk.frag.vk
reference/shaders/vulkan/frag/push-constant-as-ubo.push-ubo.vk.frag
reference/shaders/vulkan/frag/push-constant-as-ubo.push-ubo.vk.frag.vk
shaders/vulkan/frag/push-constant-as-ubo.push-ubo.vk.frag
spirv_cross_c.cpp
spirv_cross_c.h
spirv_glsl.cpp
spirv_glsl.hpp
test_shaders.py

GLSL: Support emitting push constant block as a plain UBO.

---

reference/opt/shaders-hlsl/asm/comp/nmin-max-clamp.asm.comp
reference/opt/shaders/asm/comp/nmin-max-clamp.asm.comp
reference/shaders-hlsl/asm/comp/nmin-max-clamp.asm.comp
reference/shaders/asm/comp/nmin-max-clamp.asm.comp
shaders-hlsl/asm/comp/nmin-max-clamp.asm.comp
shaders/asm/comp/nmin-max-clamp.asm.comp
spirv_glsl.cpp
spirv_glsl.hpp

Need to emulate these calls for correctness.
Fix #899.

GLSL/HLSL: Implement NMin/NMax/NClamp.

---

reference/opt/shaders/legacy/fragment/fma.legacy.frag
reference/shaders/legacy/fragment/fma.legacy.frag
shaders/legacy/fragment/fma.legacy.frag
spirv_glsl.cpp

Support fma() in older GLSL targets.

---

reference/shaders-msl-no-opt/asm/vert/op-load-forced-temporary-array.asm.frag
shaders-msl-no-opt/asm/vert/op-load-forced-temporary-array.asm.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

MSL: Fix OpLoad of array which is forced to a temporary.

---

reference/shaders-msl-no-opt/asm/comp/arithmetic-conversion-signs.asm.comp
reference/shaders-no-opt/asm/comp/arithmetic-conversion-signs.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/spec-constant-op-convert-sign.asm.comp
shaders-msl-no-opt/asm/comp/arithmetic-conversion-signs.asm.comp
shaders-no-opt/asm/comp/arithmetic-conversion-signs.asm.nocompat.vk.comp
shaders-no-opt/asm/comp/spec-constant-op-convert-sign.asm.comp
spirv_glsl.cpp
test_shaders.py

Deal with mismatched signs in S/U/F conversion opcodes.

---

spirv_cross_containers.hpp

Work around false positive warning on GCC 8.3.

---

reference/opt/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/struct-packing-scalar.nocompat.invalid.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/struct-packing-scalar.nocompat.invalid.vk.comp.vk
shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp
shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp
shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp
shaders/vulkan/comp/buffer-reference.nocompat.vk.comp
shaders/vulkan/comp/struct-packing-scalar.nocompat.invalid.vk.comp
spirv_cross.cpp
spirv_cross.hpp
spirv_cross_parsed_ir.cpp
spirv_cross_parsed_ir.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp
spirv_parser.cpp

GLSL: Implement GL_EXT_scalar_block_layout

---

reference/opt/shaders-msl/asm/vert/copy-memory-interface.asm.vert
reference/shaders-msl/asm/vert/copy-memory-interface.asm.vert
shaders-msl/asm/vert/copy-memory-interface.asm.vert
spirv_cross.cpp

(I don't know why those two variable pointer tests suddenly need
updating...)

Fix a copy-pasto.

---

reference/opt/shaders/vulkan/frag/nonuniform-qualifier.vk.nocompat.frag.vk
reference/shaders/vulkan/frag/nonuniform-qualifier.vk.nocompat.frag.vk
shaders/vulkan/frag/nonuniform-qualifier.vk.nocompat.frag
spirv_glsl.cpp
spirv_glsl.hpp

GLSL: Support GL_EXT_nonuniform_qualifier.

---

test_shaders.py

Set env to vulkan1.1 for spirv-as in test_shaders.py

---

spirv_cross_c.cpp

Fix spvc_type_get_vector_size C function.

Fix spvc_type_get_vector_size C function.

---

spirv_cross_c.cpp
spirv_cross_c.h

This PR adds additional APIs to the C interface

Add get_member_name and active_buffer_ranges to C APIs

---

CMakeLists.txt
cmake/gitversion.in.h
main.cpp
spirv_cross_c.cpp
spirv_cross_c.h
tests-other/c_api_test.c

Only supported in CMake build.
Fix #986.

Add Git/timestamp --revision support.

---

reference/opt/shaders-msl/asm/vert/invariant.msl21.asm.vert
reference/opt/shaders-msl/vert/invariant.msl21.vert
reference/shaders-msl/asm/vert/invariant.msl21.asm.vert
reference/shaders-msl/vert/invariant.msl21.vert
shaders-msl/asm/vert/invariant.msl21.asm.vert
shaders-msl/vert/invariant.msl21.vert
spirv_msl.cpp

MSL: Support Invariant qualifier on position.

---

reference/opt/shaders-msl/frag/stencil-export.msl21.frag
reference/opt/shaders/desktop-only/frag/stencil-export.desktop.frag
reference/shaders-msl/frag/stencil-export.msl21.frag
reference/shaders/desktop-only/frag/stencil-export.desktop.frag
shaders-msl/frag/stencil-export.msl21.frag
shaders/desktop-only/frag/stencil-export.desktop.frag
spirv_glsl.cpp
spirv_msl.cpp

GLSL/MSL: Support stencil export

---

reference/opt/shaders-msl/asm/frag/min-lod.msl22.asm.frag
reference/shaders-msl/asm/frag/min-lod.msl22.asm.frag
shaders-msl/asm/frag/min-lod.msl22.asm.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp
spirv_msl.hpp

MSL: Support MinLod operand.

---

spirv_glsl.cpp

Workaround GCC 9 bug.

---

reference/opt/shaders-msl/frag/subgroup-builtins.msl22.frag
reference/shaders-msl/frag/subgroup-builtins.msl22.frag
shaders-msl/frag/subgroup-builtins.msl22.frag
spirv_msl.cpp

MSL: Add support for SubgroupSize / SubgroupInvocationID in fragment.

---

CMakeLists.txt
spirv_cross.hpp
spirv_cross_c.cpp
spirv_cross_c.h
spirv_msl.cpp
spirv_msl.hpp

Also fixes some weirdness where this call was virtual for some reason.

Add C API support for get_declared_struct_member_size

---

reference/opt/shaders-hlsl/comp/outer-product.comp
reference/opt/shaders-msl/comp/outer-product.comp
reference/opt/shaders/comp/outer-product.comp
reference/shaders-hlsl/comp/outer-product.comp
reference/shaders-msl/comp/outer-product.comp
reference/shaders/comp/outer-product.comp
shaders-hlsl/comp/outer-product.comp
shaders-msl/comp/outer-product.comp
shaders/comp/outer-product.comp
spirv_hlsl.cpp
spirv_msl.cpp

MSL/HLSL: Support OpOuterProduct.

---

reference/opt/shaders-hlsl/frag/scalar-refract-reflect.frag
reference/opt/shaders-msl/frag/scalar-refract-reflect.frag
reference/opt/shaders/frag/scalar-refract-reflect.frag
reference/shaders-hlsl/frag/scalar-refract-reflect.frag
reference/shaders-msl/frag/scalar-refract-reflect.frag
reference/shaders/frag/scalar-refract-reflect.frag
shaders-hlsl/frag/scalar-refract-reflect.frag
shaders-msl/frag/scalar-refract-reflect.frag
shaders/frag/scalar-refract-reflect.frag
spirv_hlsl.cpp
spirv_hlsl.hpp
spirv_msl.cpp
spirv_msl.hpp

MSL/HLSL: Support scalar reflect and refract.

---

spirv_glsl.cpp

Forget loop variable enables after emitting block chain.

---

reference/opt/shaders-msl/vert/functions.vert
reference/shaders-hlsl-no-opt/asm/comp/bitscan.asm.comp
reference/shaders-msl-no-opt/asm/comp/bitscan.asm.comp
reference/shaders-msl-no-opt/asm/comp/glsl-signed-operations.asm.comp
reference/shaders-msl/vert/functions.vert
reference/shaders-no-opt/asm/comp/bitscan.asm.comp
shaders-hlsl-no-opt/asm/comp/bitscan.asm.comp
shaders-msl-no-opt/asm/comp/bitscan.asm.comp
shaders-no-opt/asm/comp/bitscan.asm.comp
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Deal correctly with return sign of bitscan operations.

---

reference/shaders-hlsl-no-opt/asm/comp/glsl.std450.frexp-modf-struct.fxconly.asm.comp
reference/shaders-hlsl-no-opt/comp/glsl.std450.fxconly.comp
reference/shaders-msl-no-opt/asm/comp/glsl.std450.frexp-modf-struct.asm.comp
reference/shaders-msl-no-opt/comp/glsl.std450.comp
reference/shaders-no-opt/asm/comp/glsl.std450.frexp-modf-struct.asm.comp
reference/shaders-no-opt/comp/glsl.std450.comp
shaders-hlsl-no-opt/asm/comp/glsl.std450.frexp-modf-struct.fxconly.asm.comp
shaders-hlsl-no-opt/comp/glsl.std450.fxconly.comp
shaders-msl-no-opt/asm/comp/glsl.std450.frexp-modf-struct.asm.comp
shaders-msl-no-opt/comp/glsl.std450.comp
shaders-no-opt/asm/comp/glsl.std450.frexp-modf-struct.asm.comp
shaders-no-opt/comp/glsl.std450.comp
spirv_hlsl.cpp
spirv_hlsl.hpp
spirv_msl.cpp
spirv_msl.hpp
test_shaders.py

Make sure to test everything with scalar as well to catch any weird edge
cases.
Not all opcodes are covered here, just the arithmetic ones. FP64 packing
is also ignored.
Fix #1085.

Test glsl.std450 more exhaustively.

---

reference/opt/shaders/asm/comp/phi-temporary-copy-loop-variable.asm.comp
reference/opt/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
reference/shaders-msl-no-opt/asm/frag/inliner-dominator-inside-loop.asm.frag
reference/shaders-no-opt/asm/frag/do-while-continue-phi.asm.frag
reference/shaders-no-opt/asm/frag/inliner-dominator-inside-loop.asm.frag
reference/shaders/asm/comp/phi-temporary-copy-loop-variable.asm.comp
shaders-no-opt/asm/frag/do-while-continue-phi.asm.frag
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_glsl.hpp

Missed case where DoWhile continue block deals with Phi.

---

reference/shaders-hlsl-no-opt/asm/comp/bitfield-signed-operations.asm.comp
reference/shaders-msl-no-opt/asm/comp/bitfield-signed-operations.asm.comp
reference/shaders-msl-no-opt/comp/bitfield.comp
reference/shaders-no-opt/asm/comp/bitfield-signed-operations.asm.comp
shaders-hlsl-no-opt/asm/comp/bitfield-signed-operations.asm.comp
shaders-msl-no-opt/asm/comp/bitfield-signed-operations.asm.comp
shaders-no-opt/asm/comp/bitfield-signed-operations.asm.comp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

Need a lot of special purpose implementation functions for these.
Fix #1112.

Deal correctly with sign on bitfield operations.

---

reference/shaders-no-opt/asm/frag/ldexp-uint-exponent.asm.frag
shaders-no-opt/asm/frag/ldexp-uint-exponent.asm.frag
spirv_glsl.cpp

Need to value cast to int first.
Fix #1115.

Deal with ldexp taking uint input.

---

reference/opt/shaders-msl/asm/frag/lut-promotion-initializer.asm.frag
reference/opt/shaders-msl/asm/tesc/tess-fixed-input-array-builtin-array.invalid.asm.tesc
reference/opt/shaders-msl/comp/composite-array-initialization.comp
reference/opt/shaders-msl/comp/composite-construct.comp
reference/opt/shaders-msl/frag/lut-promotion.frag
reference/shaders-msl-no-opt/comp/array-copy-threadgroup-memory.comp
reference/shaders-msl-no-opt/vert/pass-array-by-value.vert
reference/shaders-msl/asm/frag/lut-promotion-initializer.asm.frag
reference/shaders-msl/asm/tesc/tess-fixed-input-array-builtin-array.invalid.asm.tesc
reference/shaders-msl/comp/composite-array-initialization.comp
reference/shaders-msl/comp/composite-construct.comp
reference/shaders-msl/comp/copy-array-of-arrays.comp
reference/shaders-msl/frag/constant-composites.frag
reference/shaders-msl/frag/lut-promotion.frag
reference/shaders-msl/vert/return-array.vert
shaders-msl-no-opt/comp/array-copy-threadgroup-memory.comp
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

MSL: Deal with array copies from and to threadgroup.

---

reference/shaders-reflection/asm/op-source-glsl-ssbo-1.asm.comp.json
reference/shaders-reflection/asm/op-source-glsl-ssbo-2.asm.comp.json
reference/shaders-reflection/asm/op-source-hlsl-uav-1.asm.comp.json
reference/shaders-reflection/asm/op-source-hlsl-uav-2.asm.comp.json
reference/shaders-reflection/asm/op-source-none-ssbo-1.asm.comp.json
reference/shaders-reflection/asm/op-source-none-ssbo-2.asm.comp.json
reference/shaders-reflection/asm/op-source-none-uav-1.asm.comp.json
reference/shaders-reflection/asm/op-source-none-uav-2.asm.comp.json
reference/shaders-reflection/comp/struct-layout.comp.json
reference/shaders-reflection/comp/struct-packing.comp.json
spirv_reflect.cpp

Emits `workgroup_size` to JSON for compute entry points.

Reflect workgroup size

---

spirv.h
spirv.hpp

Missed this when I did the update to tests and such for 1.5.

Update SPV_VERSION from 1.4 to 1.5

---

gn/BUILD.gn

CC @null77
FYI: I'm an ANGLE project's contributor. I have no affiliation with Google.

Added BUILD.gn file to be used by Chromium's ANGLE project

---

reference/shaders-no-opt/asm/comp/arithmetic-conversion-signs.asm.nocompat.vk.comp.vk
shaders-no-opt/asm/comp/arithmetic-conversion-signs.asm.nocompat.vk.comp
spirv_glsl.cpp

Always deal with input casting when output is floating point here.

Fix sign handling for S/UToF.

---

main.cpp

Added --msl-decoration-binding command line argument to enable binding decoration for Metal.

Added --msl-decoration-binding command line argument

---

reference/opt/shaders/geom/multi-stream.geom
reference/shaders/geom/multi-stream.geom
shaders/geom/multi-stream.geom
spirv_glsl.cpp

GLSL: Fix EmitStreamVertex/Primitive.

---

reference/shaders-hlsl-no-opt/asm/frag/subgroup-arithmetic-cast.invalid.nofxc.sm60.asm.frag
reference/shaders-msl-no-opt/asm/frag/subgroup-arithmetic-cast.msl21.asm.frag
reference/shaders-no-opt/asm/frag/subgroup-arithmetic-cast.nocompat.vk.asm.frag.vk
shaders-hlsl-no-opt/asm/frag/subgroup-arithmetic-cast.invalid.nofxc.sm60.asm.frag
shaders-msl-no-opt/asm/frag/subgroup-arithmetic-cast.msl21.asm.frag
shaders-no-opt/asm/frag/subgroup-arithmetic-cast.nocompat.vk.asm.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

Deal with bitcasting for subgroup Min/Max operations

---

reference/opt/shaders/geom/geometry-passthrough.geom
reference/shaders/geom/geometry-passthrough.geom
shaders/geom/geometry-passthrough.geom
spirv_common.hpp
spirv_glsl.cpp

GLSL: Implement geometry shader passthrough extension.

---

reference/shaders-reflection/asm/aliased-entry-point-names.asm.multi.json
reference/shaders-reflection/asm/op-source-glsl-ssbo-1.asm.comp.json
reference/shaders-reflection/asm/op-source-glsl-ssbo-2.asm.comp.json
reference/shaders-reflection/asm/op-source-hlsl-uav-1.asm.comp.json
reference/shaders-reflection/asm/op-source-hlsl-uav-2.asm.comp.json
reference/shaders-reflection/asm/op-source-none-ssbo-1.asm.comp.json
reference/shaders-reflection/asm/op-source-none-ssbo-2.asm.comp.json
reference/shaders-reflection/asm/op-source-none-uav-1.asm.comp.json
reference/shaders-reflection/asm/op-source-none-uav-2.asm.comp.json
reference/shaders-reflection/comp/struct-layout.comp.json
reference/shaders-reflection/comp/struct-packing.comp.json
reference/shaders-reflection/comp/workgroup-size-spec-constant.comp.json
reference/shaders-reflection/frag/separate-sampler-texture-array.vk.frag.json
reference/shaders-reflection/frag/spec-constant.vk.frag.json
reference/shaders-reflection/vert/array-size-reflection.vert.json
reference/shaders-reflection/vert/read-from-row-major-array.vert.json
reference/shaders-reflection/vert/stride-reflection.vert.json
shaders-reflection/vert/array-size-reflection.vert
shaders-reflection/vert/stride-reflection.vert
spirv_reflect.cpp

- Reflect array stride
- Reflect matrix stride
- Reflect spec constant array sizes.
Fix #1259 
Fix #1260

Reflection: Various improvements

---

CMakeLists.txt
main.cpp
reference/shaders-msl-no-opt/frag/force-active-resources.msl2.argument..force-active.discrete.frag
shaders-msl-no-opt/frag/force-active-resources.msl2.argument..force-active.discrete.frag
spirv_cross_c.cpp
spirv_cross_c.h
spirv_msl.cpp
spirv_msl.hpp
test_shaders.py

Important for ABI compatibility on MSL in certain cases.
Supersedes https://github.com/KhronosGroup/SPIRV-Cross/pull/1240.

MSL: Add support for force-activating IAB resources.

---

reference/opt/shaders/vert/transform-feedback-decorations.vert
reference/shaders/vert/transform-feedback-decorations.vert
shaders/vert/transform-feedback-decorations.vert
spirv_common.hpp
spirv_cross_parsed_ir.cpp
spirv_glsl.cpp
spirv_glsl.hpp

GLSL: Support GL_ARB_enchanced_layouts for XFB.

---

CMakeLists.txt
main.cpp
reference/opt/shaders-msl/comp/composite-array-initialization.force-native-array.comp
reference/opt/shaders-msl/comp/copy-array-of-arrays.force-native-array.comp
reference/opt/shaders-msl/vert/return-array.force-native-array.vert
reference/shaders-msl-no-opt/vert/pass-array-by-value.force-native-array.vert
reference/shaders-msl/comp/composite-array-initialization.force-native-array.comp
reference/shaders-msl/comp/copy-array-of-arrays.force-native-array.comp
reference/shaders-msl/vert/return-array.force-native-array.vert
shaders-msl-no-opt/vert/pass-array-by-value.force-native-array.vert
shaders-msl/comp/composite-array-initialization.force-native-array.comp
shaders-msl/comp/copy-array-of-arrays.force-native-array.comp
shaders-msl/vert/return-array.force-native-array.vert
spirv_common.hpp
spirv_cross_c.cpp
spirv_cross_c.h
spirv_glsl.cpp
spirv_msl.cpp
spirv_msl.hpp
test_shaders.py

MSL: Reintroduce workarounds for arrays not being value types

---

reference/shaders-hlsl-no-opt/asm/comp/buffer-atomic-nonuniform.asm.sm51.nonuniformresource.comp
reference/shaders-hlsl-no-opt/asm/comp/image-atomic-nonuniform.asm.sm51.nonuniformresource.comp
reference/shaders-hlsl-no-opt/asm/frag/nonuniform-qualifier-propagation.nonuniformresource.sm51.asm.frag
reference/shaders-no-opt/asm/comp/buffer-atomic-nonuniform.vk.nocompat.asm.comp.vk
reference/shaders-no-opt/asm/comp/image-atomic-nonuniform.vk.nocompat.asm.comp.vk
shaders-hlsl-no-opt/asm/comp/buffer-atomic-nonuniform.asm.sm51.nonuniformresource.comp
shaders-hlsl-no-opt/asm/comp/image-atomic-nonuniform.asm.sm51.nonuniformresource.comp
shaders-no-opt/asm/comp/buffer-atomic-nonuniform.vk.nocompat.asm.comp
shaders-no-opt/asm/comp/image-atomic-nonuniform.vk.nocompat.asm.comp
spirv_glsl.cpp
spirv_hlsl.cpp

Did not properly propagate nonuniform qualifiers when using atomics.
Fix #1292.

Fix nonuniform qualifier with atomics

---

main.cpp
reference/shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.frag
reference/shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.legacy.frag
shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.frag
shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.legacy.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
test_shaders.py

glslang cannot compile these shaders, so just hoping it works.
Fix #1295.

GLSL: Implement GL_EXT_shader_framebuffer_fetch.

---

reference/shaders-msl-no-opt/frag/ubo-array-multiple-structs-access-chain.argument.msl2.frag
reference/shaders-msl-no-opt/frag/ubo-array-multiple-structs-access-chain.frag
shaders-msl-no-opt/frag/ubo-array-multiple-structs-access-chain.argument.msl2.frag
shaders-msl-no-opt/frag/ubo-array-multiple-structs-access-chain.frag
spirv_msl.cpp

MSL: Fix access chain for deep struct hierarchy on array of buffers.

---

CMakeLists.txt
main.cpp
spirv_cross_c.cpp
spirv_cross_c.h
spirv_glsl.cpp
spirv_glsl.hpp

Expose query if a resource was used as a comparison/depth resource

---

reference/shaders-reflection/comp/workgroup-size-spec-constant.comp.json
reference/shaders-reflection/frag/spec-constant.vk.frag.json
reference/shaders-reflection/vert/array-size-reflection.vert.json
spirv_reflect.cpp

Reflection: Add specialization constant name

---

CMakeLists.txt
spirv.h
spirv.hpp
spirv_common.hpp
spirv_cross.cpp
spirv_cross_c.h
spirv_glsl.cpp
spirv_parser.cpp

Handle RayQueryKHR type.

---

reference/shaders-msl-no-opt/frag/subpass-input-function-argument.framebuffer-fetch.ios.frag
shaders-msl-no-opt/frag/subpass-input-function-argument.framebuffer-fetch.ios.frag
spirv_msl.cpp
spirv_msl.hpp

MSL: Fix case where subpassInput is passed to leaf functions.

---

reference/shaders-hlsl-no-opt/asm/comp/atomic-load-store.asm.comp
reference/shaders-msl-no-opt/asm/comp/atomic-load-store.asm.comp
reference/shaders-no-opt/asm/comp/atomic-load-store.asm.comp
shaders-hlsl-no-opt/asm/comp/atomic-load-store.asm.comp
shaders-msl-no-opt/asm/comp/atomic-load-store.asm.comp
shaders-no-opt/asm/comp/atomic-load-store.asm.comp
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Need some emulation on GLSL/HLSL, fix bug with atomic store on MSL.
Fix #1343.

Implement OpAtomicLoad/OpAtomicStore.

---

test_shaders.py

Not exactly sure what is going on, internet suggests there's a pipe that
fills up. Calling close() before we start waiting for results seems to
do the trick.
Fix #1348.

Work around odd deadlock in test_shaders.py in --parallel mode.

---

reference/opt/shaders-hlsl/frag/image-query-uav.frag
reference/opt/shaders-hlsl/frag/image-query-uav.nonwritable-uav-texture.frag
reference/shaders-hlsl/frag/image-query-uav.frag
reference/shaders-hlsl/frag/image-query-uav.nonwritable-uav-texture.frag
shaders-hlsl/frag/image-query-uav.frag
shaders-hlsl/frag/image-query-uav.nonwritable-uav-texture.frag
spirv_hlsl.cpp
spirv_hlsl.hpp

This was completely unimplemented for some reason.
Fix #1365.

HLSL: Implement image queries for UAV images.

---

reference/shaders-reflection/asm/comp/pointer-to-array-of-physical-pointer.asm.comp.json
reference/shaders-reflection/comp/array-of-physical-pointer.comp.json
reference/shaders-reflection/comp/physical-pointer.comp.json
shaders-reflection/asm/comp/pointer-to-array-of-physical-pointer.asm.comp
shaders-reflection/comp/array-of-physical-pointer.comp
shaders-reflection/comp/physical-pointer.comp
spirv_common.hpp
spirv_cross.cpp
spirv_cross.hpp
spirv_parser.cpp
spirv_parser.hpp
spirv_reflect.cpp
spirv_reflect.hpp

Handle physical pointers in reflection API.

---

main.cpp
spirv_glsl.cpp

Document CLI options.

---

reference/shaders-no-opt/frag/sparse-texture-feedback.desktop.frag
shaders-no-opt/frag/sparse-texture-feedback.desktop.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_hlsl.hpp
spirv_msl.cpp
spirv_msl.hpp

GLSL: Implement sparse feedback.

---

reference/opt/shaders-hlsl/frag/legacy-tex-modifiers.sm30.frag
reference/shaders-hlsl/frag/legacy-tex-modifiers.sm30.frag
shaders-hlsl/frag/legacy-tex-modifiers.sm30.frag
spirv_hlsl.cpp

HLSL: Fix texProj in legacy HLSL.

---

reference/shaders-no-opt/asm/comp/loop-variable-with-initializer.asm.comp
shaders-no-opt/asm/comp/loop-variable-with-initializer.asm.comp
spirv_glsl.cpp

Fix duplicated initialization for loop variables with initializers.

---

reference/opt/shaders/asm/frag/loop-header-to-continue.asm.frag
reference/opt/shaders/frag/avoid-expression-lowering-to-loop.frag
reference/shaders-msl/asm/comp/variable-pointers-2.asm.comp
reference/shaders-no-opt/asm/frag/inliner-dominator-inside-loop.asm.frag
reference/shaders-ue4-no-opt/asm/frag/accesschain-invalid-expression.asm.invalid.frag
reference/shaders-ue4-no-opt/asm/frag/array-copy-error.asm.invalid.frag
reference/shaders-ue4-no-opt/asm/frag/phi-variable-declaration.asm.invalid.frag
reference/shaders-ue4/asm/frag/texture-atomics.asm.frag
reference/shaders-ue4/asm/frag/texture-atomics.asm.graphics-robust-access.frag
reference/shaders/asm/frag/loop-header-to-continue.asm.frag
reference/shaders/frag/avoid-expression-lowering-to-loop.frag
shaders/frag/avoid-expression-lowering-to-loop.frag
spirv_common.hpp
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_glsl.hpp

Improve expression usage tracking

---

reference/opt/shaders/legacy/fragment/switch.legacy.frag
reference/shaders-hlsl-no-opt/asm/frag/switch-block-case-fallthrough.asm.invalid.frag
reference/shaders-no-opt/legacy/frag/switch-single-case-multiple-exit-cfg.legacy.asm.frag
reference/shaders/legacy/fragment/switch.legacy.frag
shaders-no-opt/legacy/frag/switch-single-case-multiple-exit-cfg.legacy.asm.frag
shaders/legacy/fragment/switch.legacy.frag
spirv_glsl.cpp
test_shaders.py

GLSL: Support switch more properly in legacy ESSL

---

reference/opt/shaders/legacy/fragment/switch.legacy.frag
reference/opt/shaders/legacy/vert/switch-nested.legacy.vert
reference/shaders-no-opt/legacy/frag/switch-single-case-multiple-exit-cfg.legacy.asm.frag
reference/shaders/legacy/fragment/switch.legacy.frag
reference/shaders/legacy/vert/switch-nested.legacy.vert
shaders/legacy/vert/switch-nested.legacy.vert
spirv_glsl.cpp

GLSL: Fix nested legacy switch workarounds.

---

reference/opt/shaders/legacy/fragment/multiple-struct-flattening.legacy.frag
reference/opt/shaders/legacy/vert/struct-flatten-inner-array.legacy.vert
reference/opt/shaders/legacy/vert/struct-flatten-stores-multi-dimension.legacy.vert
reference/opt/shaders/legacy/vert/struct-varying.legacy.vert
reference/shaders/legacy/fragment/multiple-struct-flattening.legacy.frag
reference/shaders/legacy/vert/struct-flatten-inner-array.legacy.vert
reference/shaders/legacy/vert/struct-flatten-stores-multi-dimension.legacy.vert
reference/shaders/legacy/vert/struct-varying.legacy.vert
shaders/legacy/fragment/multiple-struct-flattening.legacy.frag
shaders/legacy/vert/struct-flatten-inner-array.legacy.vert
shaders/legacy/vert/struct-flatten-stores-multi-dimension.legacy.vert
spirv_common.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp

GLSL: Support multi-level struct flattening for I/O.

---

spirv_msl.cpp
spirv_msl.hpp

This should help with readability, both of the code itself as well as #1294.

MSL: Refactor some code

---

reference/opt/shaders-hlsl/frag/sample-mask-in-and-out.frag
reference/opt/shaders-hlsl/frag/sample-mask-in.frag
reference/opt/shaders-hlsl/frag/sample-mask-out.frag
reference/shaders-hlsl/frag/sample-mask-in-and-out.frag
reference/shaders-hlsl/frag/sample-mask-in.frag
reference/shaders-hlsl/frag/sample-mask-out.frag
shaders-hlsl/frag/sample-mask-in-and-out.frag
shaders-hlsl/frag/sample-mask-in.frag
shaders-hlsl/frag/sample-mask-out.frag
spirv_hlsl.cpp
spirv_hlsl.hpp

This is a basic support for BuiltInSampleMask in HLSL which seems to work fine on the examples provided, but might still be missing some necessary fixes.

Adding BuiltInSampleMask in HLSL

---

reference/shaders-hlsl-no-opt/asm/frag/struct-packing-last-element-array-matrix-rule.invalid.asm.frag
reference/shaders-hlsl-no-opt/frag/cbuffer-packing-straddle.frag
shaders-hlsl-no-opt/asm/frag/struct-packing-last-element-array-matrix-rule.invalid.asm.frag
shaders-hlsl-no-opt/frag/cbuffer-packing-straddle.frag
spirv_glsl.cpp

HLSL: Fix some subtle bugs in buffer packing handling.

---

reference/shaders-msl-no-opt/asm/frag/component-insert-packed-expression.asm.frag
shaders-msl-no-opt/asm/frag/component-insert-packed-expression.asm.frag
spirv_glsl.cpp

Need to take care of unpacked RHS expressions.
Fix #1455.

MSL: Fix OpCompositeInsert and OpVectorInsertDynamic.

---

spirv_msl.cpp
spirv_msl.hpp
spirv_reflect.cpp

Fix -Wduplicate-enum and -Wrange-for-analysis.

---

spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

Allow flip_vert_y in all relevant stages.

---

spirv_cross.cpp

Work around MSVC warning.

---

reference/opt/shaders/geom/transform-feedback-streams.geom
reference/shaders/geom/transform-feedback-streams.geom
shaders/geom/transform-feedback-streams.geom
spirv_common.hpp
spirv_cross_parsed_ir.cpp
spirv_glsl.cpp

GLSL: Support geometry streams.

---

reference/shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp
reference/shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp.vk
shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp
spirv_cross_containers.hpp
spirv_glsl.cpp
spirv_glsl.hpp

Some minor cleanups from https://github.com/KhronosGroup/SPIRV-Cross/pull/1476

Merge GL subgroup support.

---

reference/shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp
shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp
spirv_cross_containers.hpp
spirv_glsl.cpp
spirv_glsl.hpp

WIP: Partial Subgroup Intrinsics Support

---

CMakeLists.txt
spirv_cross_c.cpp
spirv_cross_c.h
spirv_msl.cpp
spirv_msl.hpp

MSL: Support querying and modifying generated combined sampler suffix.

---

reference/shaders-msl-no-opt/frag/depth-image-gather.asm.frag
shaders-msl-no-opt/frag/depth-image-gather.asm.frag
spirv_msl.cpp

MSL: Do not use component::x gather for depth2d textures.

---

spirv_msl.cpp

Writing to buffers actually works starting in MSL 2.1 (macOS 10.14,
iOS 12). Writing to textures works starting in MSL 2.2 (macOS 10.15, iOS
13).
No tests unfortunately, because the MSL 2.2 compiler and above produce a
warning that cannot be disabled, because it has no associated option.

MSL: For 2.1+, don't disable rasterization for vertex writes.

---

reference/shaders-no-opt/asm/loop-header-self-continue-break.asm.comp
shaders-no-opt/asm/loop-header-self-continue-break.asm.comp
spirv_glsl.cpp

Handle case where block is loop header, continue AND break block.

---

reference/shaders-hlsl-no-opt/asm/frag/nonuniform-bracket-handling-2.nonuniformresource.sm51.asm.frag
reference/shaders-no-opt/asm/comp/nonuniform-bracket-handling.vk.nocompat.asm.comp.vk
reference/shaders-no-opt/asm/frag/nonuniform-bracket-handling-2.vk.nocompat.asm.frag.vk
shaders-hlsl-no-opt/asm/frag/nonuniform-bracket-handling-2.nonuniformresource.sm51.asm.frag
shaders-no-opt/asm/comp/nonuniform-bracket-handling.vk.nocompat.asm.comp
shaders-no-opt/asm/frag/nonuniform-bracket-handling-2.vk.nocompat.asm.frag
spirv_glsl.cpp

Needs to consider that other expressions might be using brackets as well
...

GLSL: Fix nonuniformEXT injection.

---

spirv_glsl.cpp

Adds error checking and fallback to [GL_ARB_texture_gather](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_gather.txt) for use of textureGather().
The version provided by the extension is quite limited, only being able to return the first component and supporting no depth comparison, though it does have the Offset variant.  (More overloads are offered by GL_ARB_gpu_shader5, but no non-GL4 hardware supports that, so there's just no point.)
Note that the extension always uses the new-style syntax, even in legacy GLSL:
>     (2) What naming convention do we use for the new texture built-in
>         functions?
>
>        RESOLVED: Even though this extension is written against OpenGL
>        Shading Language 1.20, we use the new texture function naming
>        convention …

GLSL: Add error checking and extension fallback for textureGather

---

spirv_glsl.cpp

I hope you're not tired of me yet :)
This PR adds a legacy fallback for texelFetch and textureSize, using [GL_EXT_gpu_shader4](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_gpu_shader4.txt), which uses a subtly different naming convention.
It also tags [GL_ARB_shader_image_size](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_image_size.txt) when using imageSize before GLSL 4.30 and errors when using it in legacy ES.
In the longer term it might be interesting to consider a feature whereby extra inputs are generated for the texture size so that these operations can be supported even without these extensions.

GLSL: Legacy / extension fallbacks for textureSize and texelFetch

---

reference/opt/shaders/asm/frag/storage-class-output-initializer.asm.frag
reference/shaders-msl-no-opt/asm/tesc/array-control-point-initializer.asm.tesc
reference/shaders-msl-no-opt/asm/tesc/block-control-point-initializer.asm.tesc
reference/shaders-msl-no-opt/asm/tesc/builtin-control-point-initializer.asm.tesc
reference/shaders-msl-no-opt/asm/tesc/composite-control-point-initializer.asm.tesc
reference/shaders-msl-no-opt/asm/tesc/plain-control-point-initializer.asm.tesc
reference/shaders-msl-no-opt/asm/tesc/tess-level-initializer-quad.asm.tesc
reference/shaders-msl-no-opt/asm/tesc/tess-level-initializer-triangle.asm.tesc
reference/shaders-no-opt/asm/tesc/array-of-block-output-initializer.asm.tesc
reference/shaders-no-opt/asm/tesc/tess-level-initializer.asm.tesc
reference/shaders-no-opt/asm/vert/block-struct-initializer.asm.vert
reference/shaders/asm/frag/storage-class-output-initializer.asm.frag
shaders-msl-no-opt/asm/tesc/array-control-point-initializer.asm.tesc
shaders-msl-no-opt/asm/tesc/block-control-point-initializer.asm.tesc
shaders-msl-no-opt/asm/tesc/builtin-control-point-initializer.asm.tesc
shaders-msl-no-opt/asm/tesc/composite-control-point-initializer.asm.tesc
shaders-msl-no-opt/asm/tesc/plain-control-point-initializer.asm.tesc
shaders-msl-no-opt/asm/tesc/tess-level-initializer-quad.asm.tesc
shaders-msl-no-opt/asm/tesc/tess-level-initializer-triangle.asm.tesc
shaders-no-opt/asm/tesc/array-of-block-output-initializer.asm.tesc
shaders-no-opt/asm/tesc/tess-level-initializer.asm.tesc
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp

GLSL/MSL: Handle more complicated tessellation Output initializers

---

main.cpp

CLI: Add stdin support.

---

spirv.h
spirv.hpp
spirv_glsl.cpp
spirv_parser.cpp

GLSL: Update SPIR-V headers for modified ray tracing opcodes.

---

reference/shaders-msl-no-opt/frag/subpass-input.decoration-binding.framebuffer-fetch.msl23.argument.frag
reference/shaders-msl-no-opt/frag/subpass-input.decoration-binding.framebuffer-fetch.msl23.frag
reference/shaders-msl-no-opt/frag/subpass-input.decoration-binding.ios.framebuffer-fetch.msl2.argument.frag
reference/shaders-msl-no-opt/frag/subpass-input.decoration-binding.ios.framebuffer-fetch.msl2.frag
shaders-msl-no-opt/frag/subpass-input.decoration-binding.framebuffer-fetch.msl23.argument.frag
shaders-msl-no-opt/frag/subpass-input.decoration-binding.framebuffer-fetch.msl23.frag
shaders-msl-no-opt/frag/subpass-input.decoration-binding.ios.framebuffer-fetch.msl2.argument.frag
shaders-msl-no-opt/frag/subpass-input.decoration-binding.ios.framebuffer-fetch.msl2.frag
spirv_msl.cpp
spirv_msl.hpp
test_shaders.py

MSL: Fix some edge cases in input attachment handling.

---

reference/opt/shaders-msl/vert/implicit-position-1.vert
reference/opt/shaders-msl/vert/implicit-position-2.vert
reference/shaders-msl/vert/implicit-position-1.vert
reference/shaders-msl/vert/implicit-position-2.vert
shaders-msl/vert/implicit-position-1.vert
shaders-msl/vert/implicit-position-2.vert
spirv_msl.cpp

MSL: Always return [[position]] when required.

---

reference/shaders-msl-no-opt/asm/tesc/copy-tess-level-tri.asm.tesc
reference/shaders-msl-no-opt/tesc/copy-tess-level.tesc
shaders-msl-no-opt/asm/tesc/copy-tess-level-tri.asm.tesc
shaders-msl-no-opt/tesc/copy-tess-level.tesc
spirv_msl.cpp
spirv_msl.hpp

More edge cases ... :(
Fix #1619.

MSL: Handle load and store to TessLevel array in TESC.

---

reference/shaders-hlsl-no-opt/comp/subgroups-boolean.invalid.nofxc.sm60.comp
reference/shaders-hlsl-no-opt/comp/subgroups.invalid.nofxc.sm60.comp
reference/shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.comp
reference/shaders-no-opt/comp/subgroups.nocompat.invalid.vk.comp.vk
shaders-hlsl-no-opt/comp/subgroups-boolean.invalid.nofxc.sm60.comp
shaders-hlsl-no-opt/comp/subgroups.invalid.nofxc.sm60.comp
shaders-msl-no-opt/comp/subgroups.nocompat.invalid.vk.msl21.comp
shaders-no-opt/comp/subgroups.nocompat.invalid.vk.comp
spirv_glsl.cpp
spirv_hlsl.cpp

Handle logical subgroup arithmetic ops

---

.github/workflows/main.yml
test_shaders.py

PR-ing this from my own fork to avoid cluttering main repo with random commits.
TODO: Export artifacts.

Add GitHub Actions script.

---

reference/shaders-hlsl-no-opt/vert/block-io-auto-location-assignment.vert
shaders-hlsl-no-opt/vert/block-io-auto-location-assignment.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp
spirv_msl.hpp

HLSL: Fix automatic location assignment in block IO.

---

spirv_cross.cpp

CFG analysis needs to know if we need to take address of variable.
Fix #1644.

MSL: Handle variable access in OpSelect.

---

reference/shaders-no-opt/comp/image-load-formatted.comp
shaders-no-opt/comp/image-load-formatted.comp
spirv_glsl.cpp

GLSL: Support GL_EXT_shader_image_load_formatted.

---

reference/shaders-no-opt/frag/frag-fully-covered.frag
shaders-no-opt/frag/frag-fully-covered.frag
spirv_glsl.cpp

GLSL: Implement gl_FragFullyCoveredNV.

---

reference/shaders-no-opt/vulkan/frag/shading-rate.vk.nocompat.frag.vk
reference/shaders-no-opt/vulkan/vert/primitive-shading-rate.vk.nocompat.vert.vk
shaders-no-opt/vulkan/frag/shading-rate.vk.nocompat.frag
shaders-no-opt/vulkan/vert/primitive-shading-rate.vk.nocompat.vert
spirv_glsl.cpp

GLSL: Support shading rate builtins.

---

reference/opt/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
reference/opt/shaders-msl/tese/quad.domain.tese
reference/opt/shaders-msl/tese/quad.tese
reference/opt/shaders-msl/tese/read-tess-level-in-func-quad.msl2.tese
reference/opt/shaders-msl/tese/read-tess-level-in-func.msl2.tese
reference/shaders-msl-no-opt/asm/tese/copy-tess-level.asm.msl2.tese
reference/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
reference/shaders-msl/tese/quad.domain.tese
reference/shaders-msl/tese/quad.tese
reference/shaders-msl/tese/read-tess-level-in-func-quad.msl2.tese
reference/shaders-msl/tese/read-tess-level-in-func.msl2.tese
shaders-msl-no-opt/asm/tese/copy-tess-level.asm.msl2.tese
shaders-msl/tese/read-tess-level-in-func-quad.msl2.tese
spirv_msl.cpp

We need to handle loads from array as well, so the float4 hack doesn't
work.
Fix #1658.

MSL: Use proper array for quad tess levels.

---

reference/opt/shaders-hlsl/vert/invariant.vert
reference/opt/shaders-hlsl/vert/no-contraction.vert
reference/opt/shaders-msl/vert/no-contraction.vert
reference/opt/shaders/vert/no-contraction.vert
reference/shaders-hlsl/vert/invariant.vert
reference/shaders-hlsl/vert/no-contraction.vert
reference/shaders-msl/vert/no-contraction.vert
reference/shaders/vert/no-contraction.vert
shaders-hlsl/vert/invariant.vert
shaders-hlsl/vert/no-contraction.vert
shaders-msl/vert/no-contraction.vert
shaders/vert/no-contraction.vert
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp
spirv_msl.hpp

Implement NoContraction decoration

---

reference/opt/shaders-msl/frag/array-component-io.frag
reference/opt/shaders-msl/vert/array-component-io.for-tess.vert
reference/opt/shaders-msl/vert/array-component-io.vert
reference/shaders-msl-no-opt/components/fragment-output-component.frag
reference/shaders-msl-no-opt/components/fragment-output-component.pad-fragment.frag
reference/shaders-msl-no-opt/components/vertex-input-component.vert
reference/shaders-msl/frag/array-component-io.frag
reference/shaders-msl/vert/array-component-io.for-tess.vert
reference/shaders-msl/vert/array-component-io.vert
shaders-msl/frag/array-component-io.frag
shaders-msl/vert/array-component-io.for-tess.vert
shaders-msl/vert/array-component-io.vert
spirv_msl.cpp
spirv_msl.hpp

MSL: Support array-of-component IO variables in vertex/fragment

---

main.cpp
reference/shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.framebuffer-fetch-noncoherent.frag
reference/shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.legacy.framebuffer-fetch-noncoherent.frag
shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.framebuffer-fetch-noncoherent.frag
shaders-no-opt/frag/subpass-input.framebuffer-fetch.nocompat.legacy.framebuffer-fetch-noncoherent.frag
spirv_glsl.cpp
spirv_glsl.hpp
test_shaders.py

GLSL: Implement noncoherent framebuffer fetch.

---

reference/shaders-msl-no-opt/asm/tese/split-access-chain.asm.tese
shaders-msl-no-opt/asm/tese/split-access-chain.asm.tese
spirv_msl.cpp

MSL: Improve handling of split tessellation access chains.

---

main.cpp

MSL: Add CLI option for sampler suffix.

---

reference/shaders-hlsl-no-opt/frag/texture-gather-uint-component.asm.frag
reference/shaders-msl-no-opt/frag/texture-gather-uint-component.asm.frag
reference/shaders-no-opt/frag/texture-gather-uint-component.asm.frag
shaders-hlsl-no-opt/frag/texture-gather-uint-component.asm.frag
shaders-msl-no-opt/frag/texture-gather-uint-component.asm.frag
shaders-no-opt/frag/texture-gather-uint-component.asm.frag
spirv_glsl.cpp

Handle odd type for textureGather component.

---

reference/opt/shaders/asm/comp/control-flow-hints.asm.comp
reference/opt/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
reference/opt/shaders/asm/frag/vector-shuffle-oom.asm.frag
reference/shaders/asm/comp/control-flow-hints.asm.comp
reference/shaders/asm/frag/loop-body-dominator-continue-access.asm.frag
reference/shaders/asm/frag/vector-shuffle-oom.asm.frag
shaders/asm/comp/control-flow-hints.asm.comp
spirv_glsl.cpp
spirv_msl.cpp
spirv_msl.hpp

GLSL: Support control flow hints

---

CMakeLists.txt
main.cpp
spirv_cross_c.cpp
spirv_cross_c.h
spirv_glsl.cpp
spirv_glsl.hpp

GLSL: Emit num_views for OVR_multiview2.

---

spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp

Fix -Wunreachable-code-aggressive.

---

reference/opt/shaders/vulkan/comp/ray-query.nocompat.spv14.vk.comp.vk
reference/shaders/vulkan/comp/ray-query.nocompat.spv14.vk.comp.vk
shaders/vulkan/comp/ray-query.nocompat.spv14.vk.comp
spirv_cross.cpp
spirv_glsl.cpp

GLSL: Implement GL_EXT_ray_query.

---

reference/shaders-no-opt/asm/comp/temorary-access-terminator.vk.nocompat.asm.comp.vk
shaders-no-opt/asm/comp/temorary-access-terminator.vk.nocompat.asm.comp
spirv_cross.cpp
spirv_cross.hpp

Fixes case where value is created inside loop body and consumed by a
return outside it.

Handle value access in terminators.

---

reference/shaders-no-opt/asm/frag/switch-non-default-fallthrough-no-phi.asm.frag
shaders-no-opt/asm/frag/switch-non-default-fallthrough-no-phi.asm.frag
spirv_glsl.cpp

Fix switch fallthrough case in some cases.

---

main.cpp
reference/opt/shaders-hlsl/comp/num-workgroups-alone.comp
reference/opt/shaders-hlsl/comp/num-workgroups-with-builtins.comp
reference/shaders-hlsl-no-opt/asm/comp/num-workgroups.spv14.asm.comp
reference/shaders-hlsl/comp/num-workgroups-alone.comp
reference/shaders-hlsl/comp/num-workgroups-with-builtins.comp
shaders-hlsl-no-opt/asm/comp/num-workgroups.spv14.asm.comp
spirv_hlsl.cpp

HLSL: Fix NumWorkgroups for SPIR-V 1.4+

---

reference/opt/shaders-msl/frag/modf-access-tracking-function.frag
reference/opt/shaders/frag/modf-pointer-function-analysis.frag
reference/shaders-msl-no-opt/asm/frag/usage-tracking-modf-io-pointer.asm.frag
reference/shaders-msl/frag/modf-access-tracking-function.frag
reference/shaders-no-opt/frag/modf-non-function-purity-analysis.frag
reference/shaders/frag/modf-pointer-function-analysis.frag
shaders-msl-no-opt/asm/frag/usage-tracking-modf-io-pointer.asm.frag
shaders-msl/frag/modf-access-tracking-function.frag
shaders-no-opt/frag/modf-non-function-purity-analysis.frag
shaders/frag/modf-pointer-function-analysis.frag
spirv_cross.cpp
spirv_msl.cpp

Consider it a write to a variable, similar to OpStore.
Fix #1776.

Handle Modf/Frexp in more cases.

---

reference/opt/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
reference/opt/shaders-msl/tese/input-array.tese
reference/opt/shaders-msl/tese/quad.domain.tese
reference/opt/shaders-msl/tese/quad.tese
reference/opt/shaders-msl/tese/water_tess.tese
reference/shaders-msl/asm/tese/unnamed-builtin-array.asm.tese
reference/shaders-msl/tese/input-array.tese
reference/shaders-msl/tese/quad.domain.tese
reference/shaders-msl/tese/quad.tese
reference/shaders-msl/tese/water_tess.tese
spirv_msl.cpp

Fix incorrect TessCoord type in some cases

---

reference/shaders-no-opt/asm/comp/basic.spv16.asm.comp
shaders-no-opt/asm/comp/basic.spv16.asm.comp
spirv_parser.cpp
test_shaders.py

Just verify that we don't blow up on these modules.

Add sanity test for SPIR-V 1.6 modules.

---

reference/opt/shaders/vert/texture_buffer.vert
reference/shaders/vert/texture_buffer.vert
spirv_glsl.cpp

Fixups for PR 1842

---

reference/shaders-no-opt/asm/frag/late-expression-invalidation-2.asm.frag
reference/shaders-no-opt/asm/frag/late-expression-invalidation.asm.frag
shaders-no-opt/asm/frag/late-expression-invalidation-2.asm.frag
shaders-no-opt/asm/frag/late-expression-invalidation.asm.frag
spirv_cpp.cpp
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_hlsl.cpp
spirv_msl.cpp

Introduces an idea of a recompilation making forward progress.
There are some extreme edge cases where we need more than 3 loops, but
only allow this in specific circumstances where we can reason about
forward progress being made.
Fix #1775.
Supersedes #1825.

Rework how loop iteration counts are validated.

---

README.md

Update documentation for descriptor set support in MSL/HLSL.

---

main.cpp
reference/shaders-no-opt/asm/frag/texel-fetch-ms-uint-sample.asm.frag
shaders-no-opt/asm/frag/texel-fetch-ms-uint-sample.asm.frag
spirv_cross.cpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_parser.cpp

Fix various minor bugs I ran into while working on a larger shader set.
Fix #1854.

Various fixes

---

reference/opt/shaders-msl/frag/helper-invocation.msl21.frag
reference/shaders-hlsl-no-opt/frag/helper-invocation.fxconly.nofxc.frag
reference/shaders-hlsl-no-opt/frag/volatile-helper-invocation.fxconly.nofxc.spv16.frag
reference/shaders-msl-no-opt/frag/volatile-helper-invocation.msl23.spv16.frag
reference/shaders-msl/frag/helper-invocation.msl21.frag
reference/shaders-no-opt/vulkan/frag/volatile-helper-invocation.vk.nocompat.spv16.frag.vk
shaders-hlsl-no-opt/frag/helper-invocation.fxconly.nofxc.frag
shaders-hlsl-no-opt/frag/volatile-helper-invocation.fxconly.nofxc.spv16.frag
shaders-msl-no-opt/frag/volatile-helper-invocation.msl23.spv16.frag
shaders-no-opt/vulkan/frag/volatile-helper-invocation.vk.nocompat.spv16.frag
spirv_common.hpp
spirv_glsl.cpp
spirv_hlsl.cpp
spirv_msl.cpp
test_shaders.py

Builds on #1882.
- Handle HelperInvocationEXT in HLSL as well.
- Add tests
- Handle Volatile BuiltInHelperInvocation from SPIR-V 1.6
- Fix BuiltInHelperInvocation on MSL with Volatile

Helper invocation rework

---

spirv_hlsl.cpp

I'm sorry. I just realized this.

HLSL: Fix Helper Invocation wrongly allowed in compute.

---

reference/opt/shaders-msl/comp/ray-query.spv14.vk.ios.msl24.comp
reference/shaders-msl/comp/ray-query.spv14.vk.ios.msl24.comp
spirv_msl.cpp

MSL: Fix goofy bugs in ray query.

---

spirv_hlsl.cpp

For reference: https://github.com/microsoft/DirectXShaderCompiler/wiki/SV_ViewID

HLSL: Implement ViewIndex.

---

reference/opt/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
reference/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
spirv_msl.cpp

MSL: Pass down global RayQuery object to leaf functions.

---

reference/shaders-no-opt/asm/vert/debug-printf.asm.vk.nocompat.vert.vk
shaders-no-opt/asm/vert/debug-printf.asm.vk.nocompat.vert
spirv_common.hpp
spirv_glsl.cpp
spirv_parser.cpp

GLSL: Support GL_EXT_debug_printf.

---

spirv_hlsl.cpp

HLSL: Add more comprehensible reserved identifier list.

---

reference/opt/shaders/amd/gcn_shader.comp
reference/opt/shaders/amd/shader_ballot.comp
reference/opt/shaders/asm/frag/inf-nan-constant-double.asm.frag
reference/opt/shaders/desktop-only/comp/int64.desktop.comp
reference/opt/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/vert/small-storage.vk.vert
reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/spec-constant-op-convert-sign.asm.comp
reference/shaders-no-opt/comp/bitcast-16bit-1.invalid.comp
reference/shaders-no-opt/comp/bitcast-16bit-2.invalid.comp
reference/shaders-no-opt/comp/int16min-literal.comp
reference/shaders-no-opt/comp/int64min-literal.comp
reference/shaders-no-opt/frag/16bit-constants.invalid.frag
reference/shaders/amd/gcn_shader.comp
reference/shaders/amd/shader_ballot.comp
reference/shaders/asm/frag/inf-nan-constant-double.asm.frag
reference/shaders/asm/frag/pack-and-unpack-uint2.asm.frag
reference/shaders/desktop-only/comp/int64.desktop.comp
reference/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
reference/shaders/vulkan/vert/small-storage.vk.vert
spirv_glsl.cpp

Fix #1955 
Fix #1956
@devshgraphicsprogramming Does this work for you?

GLSL: Add more extension ladder fallbacks for unusual integer sizes.

---

reference/shaders-no-opt/asm/comp/ray-query-force-temporary-rtas.spv14.asm.vk.nocompat.comp.vk
shaders-no-opt/asm/comp/ray-query-force-temporary-rtas.spv14.asm.vk.nocompat.comp
spirv_cross.cpp
spirv_glsl.cpp

Need to lower to temporary before casting to RTAS.

GLSL: Handle forced temporary OpConvertUToAccelerationStructureKHR.

---

reference/opt/shaders-msl/comp/shared-matrix-array-of-array.comp
reference/opt/shaders-msl/comp/shared-matrix-cast.comp
reference/opt/shaders-msl/comp/shared-matrix-nested-struct-array.comp
reference/opt/shaders-msl/comp/shared-matrix-nested-struct.comp
reference/opt/shaders-msl/comp/shared-struct-bool-cast.comp
reference/shaders-msl/comp/shared-matrix-array-of-array.comp
reference/shaders-msl/comp/shared-matrix-cast.comp
reference/shaders-msl/comp/shared-matrix-nested-struct-array.comp
reference/shaders-msl/comp/shared-matrix-nested-struct.comp
reference/shaders-msl/comp/shared-struct-bool-cast.comp
shaders-msl/comp/shared-matrix-array-of-array.comp
shaders-msl/comp/shared-matrix-cast.comp
shaders-msl/comp/shared-matrix-nested-struct-array.comp
shaders-msl/comp/shared-matrix-nested-struct.comp
shaders-msl/comp/shared-struct-bool-cast.comp
spirv_common.hpp
spirv_glsl.cpp
spirv_msl.cpp
spirv_msl.hpp

CTS Portability:  @cdavis5e is primary author on these changes.  I have reviewed them and internally LGTM;

CTS shared composite variables

---

reference/opt/shaders-msl/comp/buffer_device_address-packed-vec-and-cast-to-and-from-uvec2.msl23.comp
reference/shaders-msl-no-opt/asm/comp/buffer-device-address-ptr-casting.msl24.asm.comp
reference/shaders-msl/comp/buffer_device_address-packed-vec-and-cast-to-and-from-uvec2.msl23.comp
reference/shaders-no-opt/asm/comp/buffer-device-address-ptr-casting.vk.nocompat.asm.comp.vk
shaders-msl-no-opt/asm/comp/buffer-device-address-ptr-casting.msl24.asm.comp
shaders-no-opt/asm/comp/buffer-device-address-ptr-casting.vk.nocompat.asm.comp
spirv_msl.cpp

MSL: Fix various bugs with Ptr/U bitcasts.

---

spirv_glsl.cpp

OpImageQuerySizeLod translation was not accounting for the case when sampler1D images where being promoted to sampler2D for OpenGL ES.
Input Vulkan GLSL:
```
#version 450
layout(binding = 1) uniform sampler1D uInput;
layout(location = 0) in vec2 fTexCoord;
layout(location = 0) out vec4 outPixel;
void main()
{
int size = textureSize(uInput, 0);
outPixel = vec4(0.0);
}
```
Current generated GLSL after compiling to SPIRV
```
#version 300 es
precision mediump float;
precision highp int;
uniform highp sampler2D uInput;
layout(location = 0) out highp vec4 outPixel;
in highp vec2 fTexCoord;
void main()
{
int size = textureSize(uInput, 0);
outPixel = vec4(0.0);
}
```
Generated GLSL after compiling to SPIRV with this change.
```
#version 300 es
precision mediump float;
precision highp int;
uniform …
```

GLSL: Account for ES sampler1D to sampler2D promotion in textureSize.

---

spirv_msl.cpp
spirv_msl.hpp

MSL: Expose way to query if a buffer needs array length.

---

main.cpp

Fix #2037.
Solve this on CLI, no need to add new APIs for it.

HLSL: Add option to bind vertex input smemantics by name.

---

spirv_common.hpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_parser.cpp

Handle ShaderDebugInfo non-semantic extension.

---

reference/shaders-msl-no-opt/comp/buffer-device-address-from-pointer-complex-chain.msl23.comp
shaders-msl-no-opt/comp/buffer-device-address-from-pointer-complex-chain.msl23.comp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

Merge #2061

---

spirv_cross_containers.hpp
spirv_glsl.cpp

Fix GCC5 build.

---

spirv_glsl.cpp

If a builtin block was not already declared, we would miss some scenarios.
Fix #2069.

GLSL: Declare gl_in/gl_out as array more robustly.

---

reference/shaders-no-opt/frag/texture-gather-offsets.frag
shaders-no-opt/frag/texture-gather-offsets.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp

We forgot to pass down the offset ID, clean up coffset vs offset jank while we're at it.
Fix #2075.

GLSL: Handle textureGatherOffsets properly.

---

reference/opt/shaders/frag/shader-clock.frag
spirv_glsl.cpp

GLSL: Minor fixes for shader clock implementation.

---

reference/opt/shaders/legacy/vert/inverse.legacy.vert
reference/shaders/legacy/vert/inverse.legacy.vert
spirv_glsl.cpp

Whoops, missed this.  Sorry about that.

GLSL: Fix missing precision qualifier in spvDeterminant return value

---

reference/shaders-msl-no-opt/asm/comp/bda-to-array-in-buffer.asm.spv16.msl24.comp
reference/shaders-no-opt/asm/comp/bda-to-array-in-buffer.asm.spv16.nocompat.vk.comp.vk
shaders-msl-no-opt/asm/comp/bda-to-array-in-buffer.asm.spv16.msl24.comp
shaders-no-opt/asm/comp/bda-to-array-in-buffer.asm.spv16.nocompat.vk.comp
spirv_cross.cpp
spirv_cross.hpp
spirv_glsl.cpp
spirv_msl.cpp
spirv_reflect.cpp

Fix misc bugs with mixed pointer/array types in buffers

---

reference/opt/shaders-msl/comp/ray-query.spv14.vk.ios.msl24..invalid.comp
reference/opt/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
reference/shaders-msl/comp/ray-query.spv14.vk.ios.msl24..invalid.comp
reference/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
spirv_msl.cpp
spirv_msl.hpp

MSL: ray-query intersection params

---

spirv_msl.cpp

When determining need for arg buffer padding, use the descriptor count provided by the app, rather than the shader, to determine the number of slots consumed, as the shader may only be accessing part, or even one element, of the array.

Fix argument buffer padding when content includes arrays.

---

main.cpp
reference/opt/shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
reference/shaders-msl/frag/ray-query-object-in-function.spv14.vk.msl24.frag
reference/shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
spirv_cross.cpp
spirv_cross.hpp
spirv_msl.cpp
spirv_msl.hpp
test_shaders.py

Squashes https://github.com/KhronosGroup/SPIRV-Cross/pull/2179 and fixes some small nits on top.

Land PR 2179

---

spirv_msl.cpp

MSL: Workaround bizarre crash on macOS.

---

reference/opt/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference-bitcast-uvec2.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference-bitcast.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference-decorations.nocompat.vk.comp.vk
reference/opt/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/bda-to-array-in-buffer.asm.spv16.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-device-address-ptr-casting.vk.nocompat.asm.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-aliased-block-name.nocompat.vk.asm.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-pod-in-buffer.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-pointer-to-unused-pod-in-buffer.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer-2.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/buffer-reference-synthesized-pointer.asm.nocompat.vk.comp.vk
reference/shaders-no-opt/asm/comp/nonuniform-bracket-handling.vk.nocompat.asm.comp.vk
reference/shaders/vulkan/comp/array-of-buffer-reference.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference-atomic.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference-base-alignment-promote.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference-bitcast-uvec2-2.nocompat.invalid.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference-bitcast-uvec2.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference-bitcast.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference-decorations.nocompat.vk.comp.vk
reference/shaders/vulkan/comp/buffer-reference.nocompat.vk.comp.vk
spirv_glsl.cpp

GLSL: Use buffer_reference2 instead of 1.

---

reference/shaders-msl-no-opt/asm/comp/variable-pointers-2.asm.comp
reference/shaders-msl-no-opt/asm/comp/variable-pointers-vector-to-scalar.asm.comp
reference/shaders-msl-no-opt/asm/comp/workgroup-uint-to-uchar-alias-ptr-access-chain.asm.comp
shaders-msl-no-opt/asm/comp/variable-pointers-2.asm.comp
shaders-msl-no-opt/asm/comp/variable-pointers-vector-to-scalar.asm.comp
shaders-msl-no-opt/asm/comp/workgroup-uint-to-uchar-alias-ptr-access-chain.asm.comp
spirv_glsl.cpp
spirv_msl.cpp

MSL: Improve PtrAccessChain handling.

---

reference/opt/shaders-msl/comp/argument-buffers-runtime-array-buffer.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/opt/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/opt/shaders-msl/comp/argument-buffers-runtime-array.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/shaders-msl/comp/argument-buffers-runtime-array-buffer.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/shaders-msl/comp/argument-buffers-runtime-array.argument.device-argument-buffer.argument-tier-1.msl2.comp
shaders-msl/comp/argument-buffers-runtime-array-buffer.argument.device-argument-buffer.argument-tier-1.msl2.comp
shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp
shaders-msl/comp/argument-buffers-runtime-array.argument.device-argument-buffer.argument-tier-1.msl2.comp
spirv_common.hpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

MSL: Support variable sized descriptor arrays in argument buffers directly.

---

CMakeLists.txt

Use more descriptive versioning in gitversion.h.

---

spirv_cross.cpp

Fixes MSL issue where temp variable was declared as pointer var, and `OpCopyObject` attempted to copy a base type var into the pointer var.
Fixes crash in CTS test `dEQP-VK.graphicsfuzz.spv-copy-object`.

OpCopyObject declare a temp var of base type, not pointer type.

---

reference/opt/shaders-msl/comp/atomic-image.msl31.comp
reference/shaders-msl/comp/atomic-image.msl31.comp
shaders-msl/comp/atomic-image.msl31.comp
spirv_msl.cpp

Supersedes https://github.com/KhronosGroup/SPIRV-Cross/pull/2281.

Land PR 2281

---

reference/shaders-msl-no-opt/comp/bda-atomics.msl23.comp
shaders-msl-no-opt/comp/bda-atomics.msl23.comp
spirv_msl.cpp

MSL: Improve handling of BDA + atomics.

---

spirv_cross.cpp

Fix crash when traversing PtrAccessChain to OpTypeStruct.

---

reference/opt/shaders/asm/comp/private-storage-lut.asm.comp
reference/shaders/asm/comp/private-storage-lut.asm.comp
shaders/asm/comp/private-storage-lut.asm.comp
spirv_common.hpp
spirv_cross.cpp

Land PR 2297

---

reference/opt/shaders-msl/asm/comp/uint_smulextended.asm.comp
reference/opt/shaders-msl/asm/comp/ulong_smulextended.asm.msl23.comp
reference/shaders-msl/asm/comp/uint_smulextended.asm.comp
reference/shaders-msl/asm/comp/ulong_smulextended.asm.msl23.comp
shaders-msl/asm/comp/ulong_smulextended.asm.msl23.comp
spirv_glsl.cpp
spirv_msl.cpp

MSL: Fix SUMulExtended for 64-bit inputs.

---

reference/opt/shaders-msl/frag/fp16-trancendentals.frag
reference/shaders-msl-no-opt/frag/fp16.desktop.invalid.frag
reference/shaders-msl/frag/fp16-trancendentals.frag
shaders-msl/frag/fp16-trancendentals.frag
spirv_msl.cpp

MSL: Handle missing FP16 trancendental overloads.

---

reference/opt/shaders-msl/frag/gather-compare-const-offsets.frag
reference/opt/shaders-msl/frag/gather-const-offsets.frag
reference/shaders-msl/frag/gather-compare-const-offsets.frag
reference/shaders-msl/frag/gather-const-offsets.frag
shaders-msl/frag/gather-compare-const-offsets.frag
shaders-msl/frag/gather-const-offsets.frag
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp
spirv_msl.hpp

Land PR 2325.

---

reference/shaders-hlsl-no-opt/vert/base-instance-index.sm68.nofxc.fxconly.vert
reference/shaders-hlsl-no-opt/vert/base-vertex-index.sm68.nofxc.fxconly.vert
reference/shaders-hlsl-no-opt/vert/instance-index.sm68.nofxc.fxconly.vert
reference/shaders-hlsl-no-opt/vert/vertex-index.sm68.nofxc.fxconly.vert
shaders-hlsl-no-opt/vert/base-instance-index.sm68.nofxc.fxconly.vert
shaders-hlsl-no-opt/vert/base-vertex-index.sm68.nofxc.fxconly.vert
shaders-hlsl-no-opt/vert/instance-index.sm68.nofxc.fxconly.vert
shaders-hlsl-no-opt/vert/vertex-index.sm68.nofxc.fxconly.vert
spirv_hlsl.cpp
test_shaders.py

HLSL: Implement SM 6.8 BaseVertex/BaseInstance.

---

CMakeLists.txt
spirv_cross_c.cpp
spirv_cross_c.h

c: Add HLSL option use_entry_point_name.

---

reference/opt/shaders/frag/barycentric-khr-io-block.frag
reference/shaders-hlsl-no-opt/frag/barycentric-khr-nopersp.sm61.fxconly.nofxc.frag
reference/shaders-hlsl-no-opt/frag/barycentric-khr-persp.sm61.fxconly.nofxc.frag
reference/shaders-hlsl-no-opt/frag/barycentric-khr.sm61.fxconly.nofxc.frag
reference/shaders/frag/barycentric-khr-io-block.frag
shaders-hlsl-no-opt/frag/barycentric-khr-nopersp.sm61.fxconly.nofxc.frag
shaders-hlsl-no-opt/frag/barycentric-khr-persp.sm61.fxconly.nofxc.frag
shaders-hlsl-no-opt/frag/barycentric-khr.sm61.fxconly.nofxc.frag
shaders/frag/barycentric-khr-io-block.frag
spirv_glsl.cpp
spirv_hlsl.cpp
test_shaders.py

Also fix perVertex on GLSL IO blocks.

HLSL: Implement SV_Barycentrics.

---

spirv_cross_parsed_ir.cpp

Add out-of-bounds assertions

---

reference/shaders-no-opt/comp/ext-inst-with-forward-refs.gV.vk.nocompat.comp.vk
shaders-no-opt/comp/ext-inst-with-forward-refs.gV.vk.nocompat.comp
spirv.h
spirv.hpp
spirv_glsl.cpp
spirv_parser.cpp

Recognize ExtInstWithForwardRefsKHR

---

reference/opt/shaders/comp/cooperative-matrix.vk.nocompat.comp.vk
reference/shaders-no-opt/asm/comp/cooperative-matrix-insert-extract.vk.nocompat.asm.comp.vk
reference/shaders/comp/cooperative-matrix.vk.nocompat.comp.vk
shaders-no-opt/asm/comp/cooperative-matrix-insert-extract.vk.nocompat.asm.comp
shaders/comp/cooperative-matrix.vk.nocompat.comp
spirv_common.hpp
spirv_cross.cpp
spirv_glsl.cpp
spirv_parser.cpp

GLSL: Implement SPV_KHR_cooperative_matrix.

---

reference/opt/shaders-msl/comp/barriers.msl32.comp
reference/opt/shaders-msl/comp/coherent.msl32.argument.comp
reference/opt/shaders-msl/comp/coherent.msl32.comp
reference/shaders-msl/comp/barriers.msl32.comp
reference/shaders-msl/comp/coherent.msl32.argument.comp
reference/shaders-msl/comp/coherent.msl32.comp
shaders-msl/comp/barriers.msl32.comp
shaders-msl/comp/coherent.msl32.argument.comp
shaders-msl/comp/coherent.msl32.comp
spirv_msl.cpp
spirv_msl.hpp

Hopefully caught all cases where it's relevant.
Closes #2473.

Implement MSL 3.2 coherent/atomic_thread_fence

---

reference/shaders-msl-no-opt/comp/read-only-coherent-image.msl32.comp
shaders-msl-no-opt/comp/read-only-coherent-image.msl32.comp
spirv_msl.cpp

MSL: Always emit access qualifier when emitting coherency.

---

reference/opt/shaders-msl/frag/fp16-trancendentals.frag
reference/shaders-msl-no-opt/frag/fp16.desktop.invalid.frag
reference/shaders-msl/frag/fp16-trancendentals.frag
shaders-msl/frag/fp16-trancendentals.frag
spirv_msl.cpp

MSL: Fix issues with fp16 trancendentals.

---

reference/shaders-hlsl-no-opt/comp/workgroup-size-spec-constant-array.comp
reference/shaders-hlsl-no-opt/comp/workgroup-size-spec-constant-array.spv16.comp
reference/shaders-msl-no-opt/comp/workgroup-size-spec-constant-array.comp
reference/shaders-msl-no-opt/comp/workgroup-size-spec-constant-array.spv16.comp
reference/shaders-no-opt/comp/workgroup-size-spec-constant-array.comp
reference/shaders-no-opt/comp/workgroup-size-spec-constant-array.spv16.comp
reference/shaders-no-opt/comp/workgroup-size-spec-constant-array.vk.comp
reference/shaders-no-opt/comp/workgroup-size-spec-constant-array.vk.comp.vk
shaders-hlsl-no-opt/comp/workgroup-size-spec-constant-array.comp
shaders-hlsl-no-opt/comp/workgroup-size-spec-constant-array.spv16.comp
shaders-msl-no-opt/comp/workgroup-size-spec-constant-array.comp
shaders-msl-no-opt/comp/workgroup-size-spec-constant-array.spv16.comp
shaders-no-opt/comp/workgroup-size-spec-constant-array.comp
shaders-no-opt/comp/workgroup-size-spec-constant-array.spv16.comp
shaders-no-opt/comp/workgroup-size-spec-constant-array.vk.comp
spirv_cross_parsed_ir.cpp
spirv_glsl.cpp
spirv_glsl.hpp
spirv_msl.cpp

MSL: Deal with WorkGroupSize spec constant being used as array size.

---

reference/opt/shaders-msl/asm/frag/bitcast-ptr-vec.argument-tier-1.msl23.asm.frag
reference/opt/shaders-msl/comp/argument-buffers-runtime-array-buffer.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/opt/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/opt/shaders-msl/comp/argument-buffers-runtime-array.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/opt/shaders-msl/comp/buffers-unsized-discrete-aliasing.msl2.argument-tier-1.comp
reference/opt/shaders-msl/comp/buffers-unsized-discrete-aliasing.msl2.argument-tier-1.rich-descriptor.comp
reference/opt/shaders-msl/comp/buffers-unsized-discrete.msl2.argument-tier-1.comp
reference/opt/shaders-msl/comp/overlapping-bindings.msl31.argument.argument-tier-1.decoration-binding.device-argument-buffer.texture-buffer-native.comp
reference/opt/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.decoration-binding.comp
reference/opt/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.descriptor-binding.comp
reference/opt/shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
reference/opt/shaders-msl/frag/runtime_array_as_argument_buffer_buf.msl3.argument-tier-1.rich-descriptor.frag
reference/shaders-msl-no-opt/comp/argument-buffer-readonly-writeonly-alias.msl2.argument.argument-tier-1.device-argument-buffer.comp
reference/shaders-msl-no-opt/comp/integer-dot-product.comp
reference/shaders-msl/asm/frag/bitcast-ptr-vec.argument-tier-1.msl23.asm.frag
reference/shaders-msl/comp/argument-buffers-runtime-array-buffer.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/shaders-msl/comp/argument-buffers-runtime-array-buffer.rich-descriptor.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/shaders-msl/comp/argument-buffers-runtime-array.argument.device-argument-buffer.argument-tier-1.msl2.comp
reference/shaders-msl/comp/buffers-unsized-discrete-aliasing.msl2.argument-tier-1.comp
reference/shaders-msl/comp/buffers-unsized-discrete-aliasing.msl2.argument-tier-1.rich-descriptor.comp
reference/shaders-msl/comp/buffers-unsized-discrete.msl2.argument-tier-1.comp
reference/shaders-msl/comp/overlapping-bindings.msl31.argument.argument-tier-1.decoration-binding.device-argument-buffer.texture-buffer-native.comp
reference/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.device-argument-buffer.msl2.decoration-binding.comp
reference/shaders-msl/comp/raw-buffer-descriptor-aliasing.argument.discrete.msl2.descriptor-binding.comp
reference/shaders-msl/frag/runtime_array_as_argument_buffer.msl3.argument-tier-1.rich-descriptor.frag
shaders-msl/comp/buffers-unsized-discrete-aliasing.msl2.argument-tier-1.comp
shaders-msl/comp/buffers-unsized-discrete-aliasing.msl2.argument-tier-1.rich-descriptor.comp
shaders-msl/comp/buffers-unsized-discrete.msl2.argument-tier-1.comp
spirv_msl.cpp

MSL: Rethink how discrete variable count descriptor arrays are emitted.
